"use strict";
Object.defineProperty(exports, "__esModule", { value: !0 }),
  (exports.getAkiExcelPath =
    exports.getAkiExcelExportJsonFileName =
    exports.getAkiExcelPairConfig =
    exports.akiExcelToKeyValuePairConfigs =
    exports.EAkiExcelType =
      void 0);
const File_1 = require("../Misc/File"),
  Util_1 = require("../Misc/Util");
var EAkiExcelType;
function getAkiExcelPairConfig(e) {
  return exports.akiExcelToKeyValuePairConfigs[e];
}
function getAkiExcelExportJsonFileName(e) {
  var e = getAkiExcelPairConfig(e),
    t = e.SheetName.split("|");
  if (t.length < 1)
    throw new Error(
      `配置表${e.ExcelRelativePath}的Sheet名${e.SheetName}不合法`,
    );
  return t[1];
}
function getAkiExcelPath(e) {
  e = exports.akiExcelToKeyValuePairConfigs[e];
  return "AkiBase" === e.SheetWorkspace
    ? (0, File_1.getAbsolutePath)(
        `${(0, Util_1.getAkiBaseLocalPath)()}/Source/Config/Raw/BaseTables/${e.ExcelRelativePath}.xlsx`,
      )
    : (0, File_1.getAbsolutePath)(
        `${(0, File_1.getProjectPath)("")}/../Config/Raw/Tables/${e.ExcelRelativePath}.xlsx`,
      );
}
!(function (e) {
  (e.ItemInfo = "ItemInfo"),
    (e.WeaponBaseInfo = "WeaponBaseInfo"),
    (e.FunctionCondition = "FunctionCondition"),
    (e.GmAddRoleConfig = "GmAddRoleConfig"),
    (e.TeleporterForGM = "TeleporterForGM"),
    (e.Teleporter = "Teleporter"),
    (e.PhantomItemSkillId = "VisionSkillId"),
    (e.MapMark = "MapMark"),
    (e.MapMarkDetail = "MapMarkDetail"),
    (e.Weather = "Weather"),
    (e.TrialRoleInfo = "TrialRoleInfo"),
    (e.TrialRoleGroupInfo = "TrialRoleGroupInfo"),
    (e.PhantomFormation = "PhantomFormation"),
    (e.Role = "Role"),
    (e.ScanType = "ScanType"),
    (e.DungeonEntrance = "DungeonEntrance"),
    (e.ExploreTools = "ExploreTools"),
    (e.Damage = "Damage"),
    (e.TimePeriod = "TimePeriod"),
    (e.DropPackage = "DropPackage"),
    (e.AreaLevel = "AreaLevel"),
    (e.PhotoMemoryCollect = "PhotoMemoryCollect"),
    (e.QuestTag = "QuestTag"),
    (e.VisionCapture = "VisionCapture"),
    (e.Attribute = "Attribute"),
    (e.MonsterAttributeRate = "MonsterAttributeRate"),
    (e.WorldLevelBonusForMonster = "WorldLevelBonusForMonster"),
    (e.HardnessMode = "HardnessMode"),
    (e.CookProcessMsg = "CookProcessMsg"),
    (e.GeographyHandBook = "GeographyHandBook"),
    (e.PhotographHandBook = "PhotographHandBook"),
    (e.InfoDisplay = "InfoDisplay"),
    (e.ReviveRegion = "ReviveRegion"),
    (e.FunctionOpen = "FunctionOpen"),
    (e.RiskHarvestEffect = "RiskHarvestEffect"),
    (e.NounHandBook = "NounHandBook"),
    (e.ComboTeaching = "ComboTeaching"),
    (e.GuideGroup = "GuideGroup"),
    (e.MapFog = "MapFog");
})((EAkiExcelType = exports.EAkiExcelType || (exports.EAkiExcelType = {}))),
  (exports.akiExcelToKeyValuePairConfigs = {
    [EAkiExcelType.ItemInfo]: {
      KeyName: "Id",
      ExcelRelativePath: "d.道具",
      SheetName: "道具|ItemInfo",
      PromptKeyList: ["Id", "Desc"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.WeaponBaseInfo]: {
      KeyName: "ItemId",
      ExcelRelativePath: "w.武器基础配置",
      SheetName: "武器基础配置|WeaponConf",
      PromptKeyList: ["ItemId", "NameDesc"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.FunctionCondition]: {
      KeyName: "FunctionId",
      ExcelRelativePath: "g.功能开启",
      SheetName: "功能条件|FunctionCondition",
      PromptKeyList: ["FunctionId", "Name"],
      SeparatorInPrompt: " - ",
      ExtraValidValue: [
        { StartBranch: "branch_1.0", Key: 0, Prompt: "开启全部" },
      ],
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.GmAddRoleConfig]: {
      KeyName: "Id",
      ExcelRelativePath: "g.GM添加配置角色",
      SheetName: "GM指令|GmAddRoleConfig",
      PromptKeyList: ["Id", "字段名", "RoleLevel"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.TeleporterForGM]: {
      KeyName: "Id",
      ExcelRelativePath: "c.传送",
      SheetName: "传送|Teleporter",
      PromptKeyList: ["Id", "Desc"],
      SeparatorInPrompt: " - ",
      ExtraValidValue: [
        { StartBranch: "branch_1.0", Key: 0, Prompt: "开启全部" },
      ],
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.Teleporter]: {
      KeyName: "Id",
      ExcelRelativePath: "c.传送",
      SheetName: "传送|Teleporter",
      PromptKeyList: ["Id", "Desc"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.PhantomItemSkillId]: {
      KeyName: "SkillId",
      ExcelRelativePath: "h.幻象",
      SheetName: "幻象道具|PhantomItem",
      PromptKeyList: ["SkillId", "字段名"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.MapMark]: {
      KeyName: "MarkId",
      ExcelRelativePath: "d.地图标记",
      SheetName: "地图标记|MapMark",
      PromptKeyList: ["MarkId", "Desc"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.MapMarkDetail]: {
      KeyName: "MarkId",
      ExcelRelativePath: "d.地图标记",
      SheetName: "地图标记|MapMark",
      PromptKeyList: ["MarkId", "Desc", "MarkVector", "MapId", "MarkTitle"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.Weather]: {
      KeyName: "Id",
      ExcelRelativePath: "t.天气系统",
      SheetName: "天气|Weather",
      PromptKeyList: ["Id", "Desc"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.TrialRoleInfo]: {
      KeyName: "Id",
      ExcelRelativePath: "s.试用角色",
      SheetName: "试用角色信息|TrialRoleInfo",
      PromptKeyList: ["Id", "字段名"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.TrialRoleGroupInfo]: {
      KeyName: "GroupId",
      ExcelRelativePath: "s.试用角色",
      SheetName: "试用角色信息|TrialRoleInfo",
      PromptKeyList: ["GroupId", "字段名"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.PhantomFormation]: {
      KeyName: "Id",
      ExcelRelativePath: "b.编队",
      SheetName: "声骸编队|PhantomFormation",
      PromptKeyList: ["Id", "字段名"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.Role]: {
      KeyName: "Id",
      ExcelRelativePath: "j.角色",
      SheetName: "角色总表|RoleInfo",
      PromptKeyList: ["Id", "字段名"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.ScanType]: {
      KeyName: "UId",
      ExcelRelativePath: "g.关卡玩法数据",
      SheetName: "扫描组合|GamePlayScanComposite",
      PromptKeyList: ["UId", "字段名"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.DungeonEntrance]: {
      KeyName: "Id",
      ExcelRelativePath: "f.副本",
      SheetName: "副本入口|InstanceDungeonEntrance",
      PromptKeyList: ["Id", "字段名"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.ExploreTools]: {
      KeyName: "PhantomSkillId",
      ExcelRelativePath: "t.探索工具",
      SheetName: "探索工具|ExploreTools",
      PromptKeyList: ["字段名"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.Damage]: {
      KeyName: "Id",
      ExcelRelativePath: "j.结算",
      SheetName: "结算表|Damage",
      PromptKeyList: ["Id", "字段名"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.TimePeriod]: {
      KeyName: "TimeId",
      ExcelRelativePath: "s.时间表/q.区间时间",
      SheetName: "区间时间|TimeQuantum",
      PromptKeyList: ["TimeId", "BeginTime", "EndTime"],
      SeparatorInPrompt: " ~ ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.DropPackage]: {
      KeyName: "Id",
      ExcelRelativePath: "d.掉落",
      SheetName: "掉落包|DropPackage",
      PromptKeyList: ["Id", "Desc"],
      SeparatorInPrompt: " - ",
      ExtraValidValue: [{ StartBranch: "branch_1.0", Key: 0, Prompt: "0" }],
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.AreaLevel]: {
      KeyName: "AreaId",
      ExcelRelativePath: "q.区域",
      SheetName: "区域|Area",
      PromptKeyList: ["Title", "Level"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.PhotoMemoryCollect]: {
      KeyName: "Id",
      ExcelRelativePath: "j.记忆手册",
      SheetName: "记忆收集|PhotoMemoryCollect",
      PromptKeyList: ["Id", "Title"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.QuestTag]: {
      KeyName: "Id",
      ExcelRelativePath: "r.任务标签",
      SheetName: "任务标签表|QuestTag",
      PromptKeyList: ["Id", "Name"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.VisionCapture]: {
      KeyName: "Id",
      ExcelRelativePath: "g.怪物",
      SheetName: "怪物|MonsterConf",
      PromptKeyList: ["Id", "Name"],
      SeparatorInPrompt: " - ",
      ExtraValidValue: [{ StartBranch: "branch_1.0", Key: 0, Prompt: "0" }],
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.Attribute]: {
      KeyName: "Id",
      ExcelRelativePath: "s.属性",
      SheetName: "基础属性|BaseProperty",
      PromptKeyList: ["Id", "Desc"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.MonsterAttributeRate]: {
      KeyName: "Id",
      ExcelRelativePath: "s.属性",
      SheetName: "怪物属性倍率|MonsterPropExtraRate",
      PromptKeyList: ["Id", "字段名"],
      SeparatorInPrompt: " - ",
      ExtraValidValue: [{ StartBranch: "branch_1.0", Key: 0, Prompt: "0" }],
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.WorldLevelBonusForMonster]: {
      KeyName: "Id",
      ExcelRelativePath: "s.世界等级",
      SheetName: "世界等级对怪物等级|WorldLevelMonster",
      PromptKeyList: ["Id", "Desc"],
      SeparatorInPrompt: " - ",
      ExtraValidValue: [{ StartBranch: "branch_1.0", Key: 0, Prompt: "0" }],
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.HardnessMode]: {
      KeyName: "Id",
      ExcelRelativePath: "z.战斗/b.白条/b.白条_common",
      SheetName: "白条|HardnessMode",
      PromptKeyList: ["Id", "Desc"],
      SeparatorInPrompt: " - ",
      ExtraValidValue: [{ StartBranch: "branch_1.0", Key: 0, Prompt: "0" }],
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.CookProcessMsg]: {
      KeyName: "Id",
      ExcelRelativePath: "p.烹饪",
      SheetName: "食材加工文本|CookProcessMsg",
      PromptKeyList: ["Id"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.GeographyHandBook]: {
      KeyName: "Id",
      ExcelRelativePath: "t.图鉴系统",
      SheetName: "地理图鉴|GeographyHandBook",
      PromptKeyList: ["Id", "Desc"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.PhotographHandBook]: {
      KeyName: "Id",
      ExcelRelativePath: "t.图鉴系统",
      SheetName: "留影图鉴|PhotographHandBook",
      PromptKeyList: ["Id", "Desc"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.NounHandBook]: {
      KeyName: "Id",
      ExcelRelativePath: "t.图鉴系统",
      SheetName: "名词图鉴|NounHandBook",
      PromptKeyList: ["Id"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.InfoDisplay]: {
      KeyName: "Id",
      ExcelRelativePath: "x.信息展示",
      SheetName: "信息展示|InfoDisplay",
      PromptKeyList: ["Id", "字段名"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.ReviveRegion]: {
      KeyName: "Id",
      ExcelRelativePath: "f.复活范围",
      SheetName: "范围触发|ReviveRegion",
      PromptKeyList: ["Id", "Position"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.FunctionOpen]: {
      KeyName: "FunctionId",
      ExcelRelativePath: "g.功能开启",
      SheetName: "功能条件|FunctionCondition",
      PromptKeyList: ["FunctionId", "Name"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.RiskHarvestEffect]: {
      KeyName: "Id",
      ExcelRelativePath: "h.活动/g.割草冒险活动",
      SheetName: "割草buff投放|RiskHarvestBuffDrop",
      PromptKeyList: ["Id", "Desc"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.ComboTeaching]: {
      KeyName: "Id",
      ExcelRelativePath: "j.角色出招教学",
      SheetName: "角色出招总表|ComboTeaching",
      PromptKeyList: ["Id", "字段名"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.GuideGroup]: {
      KeyName: "Id",
      ExcelRelativePath: "y.引导(新)",
      SheetName: "引导组数据|GuideGroup",
      PromptKeyList: ["Id", "字段名"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
    [EAkiExcelType.MapFog]: {
      KeyName: "Fog",
      ExcelRelativePath: "d.地图迷雾",
      SheetName: "地图迷雾配置|MapFog",
      PromptKeyList: ["Fog", "备注"],
      SeparatorInPrompt: " - ",
      IsFilterByWell: !0,
      SheetWorkspace: "AkiBase",
    },
  }),
  (exports.getAkiExcelPairConfig = getAkiExcelPairConfig),
  (exports.getAkiExcelExportJsonFileName = getAkiExcelExportJsonFileName),
  (exports.getAkiExcelPath = getAkiExcelPath);
//# sourceMappingURL=AkiExcelDefine.js.map
