"use strict";
Object.defineProperty(exports, "__esModule", { value: !0 }),
  (exports.RESETSPEED =
    exports.SPEEDUP =
    exports.ENTITY_TIMESCALE_PAUSE_THRESHOLD =
    exports.ENTITY_TIMESCALE_ENABLE_THRESHOLD =
    exports.RTPC_DOLBY_ATMOS =
    exports.RPTC_SKIP_PROGRESS =
    exports.RPTC_COVER_LEVEL_CLOSING =
    exports.RPTC_COVER_LEVEL_OPENING =
    exports.RTPC_COVER_LEVEL_DELTA =
    exports.RTPC_COVER_ALPHA =
    exports.RTPC_COVER_LEVEL =
    exports.RTPCGLOBALWET =
    exports.RTPCSNOWINTENSITY =
    exports.RTPCRAININTENSITY =
    exports.RTPCWINDINTENSITY =
    exports.RTPCTEXTREPLY =
    exports.RTPCSPEEDUP =
    exports.PLOT_NOT_VIDEO =
    exports.PLOT_VIDEO =
    exports.PLOT_VIDEO_GROUP =
    exports.STATEBACKGROUND =
    exports.STATEINCUTSCENE =
    exports.STATENORMAL =
      void 0),
  (exports.STATENORMAL = "normal"),
  (exports.STATEINCUTSCENE = "incutscene"),
  (exports.STATEBACKGROUND = "background"),
  (exports.PLOT_VIDEO_GROUP = "plot_video"),
  (exports.PLOT_VIDEO = "playing"),
  (exports.PLOT_NOT_VIDEO = "none"),
  (exports.RTPCSPEEDUP = "Cutscene_speedup"),
  (exports.RTPCTEXTREPLY = "Set_TextReply"),
  (exports.RTPCWINDINTENSITY = "amb_wind_intensity"),
  (exports.RTPCRAININTENSITY = "amb_rain_intensity"),
  (exports.RTPCSNOWINTENSITY = "amb_snow_intensity"),
  (exports.RTPCGLOBALWET = "global_wet"),
  (exports.RTPC_COVER_LEVEL = "ui_cover_level"),
  (exports.RTPC_COVER_ALPHA = "ui_cover_alpha"),
  (exports.RTPC_COVER_LEVEL_DELTA = "ui_cover_level_delta"),
  (exports.RPTC_COVER_LEVEL_OPENING = "ui_cover_level_opening"),
  (exports.RPTC_COVER_LEVEL_CLOSING = "ui_cover_level_closing"),
  (exports.RPTC_SKIP_PROGRESS = "ui_plot_skip_progress"),
  (exports.RTPC_DOLBY_ATMOS = "dolby_atmos"),
  (exports.ENTITY_TIMESCALE_ENABLE_THRESHOLD = 0.8),
  (exports.ENTITY_TIMESCALE_PAUSE_THRESHOLD = 0.0625),
  (exports.SPEEDUP = 15),
  (exports.RESETSPEED = 0);
//# sourceMappingURL=AudioDefine.js.map
