"use strict";
var ELocalStorageGlobalKey, ELocalStoragePlayerKey, ELocalStorageDeviceKey;
Object.defineProperty(exports, "__esModule", { value: !0 }),
  (exports.ELocalStorageDeviceKey =
    exports.ELocalStoragePlayerKey =
    exports.ELocalStorageGlobalKey =
      void 0),
  (function (e) {
    (e[(e.GameQualitySetting = 0)] = "GameQualitySetting"),
      (e[(e.LoginFailCount = 1)] = "LoginFailCount"),
      (e[(e.NextLoginTime = 2)] = "NextLoginTime"),
      (e[(e.ResetLoginFailCountTime = 3)] = "ResetLoginFailCountTime"),
      (e[(e.SingleMapId = 4)] = "SingleMapId"),
      (e[(e.MultiMapId = 5)] = "MultiMapId"),
      (e[(e.LoginSex = 6)] = "LoginSex"),
      (e[(e.SelectBoxActive = 7)] = "SelectBoxActive"),
      (e[(e.SkipPlot = 8)] = "SkipPlot"),
      (e[(e.FirstOpenShop = 9)] = "FirstOpenShop"),
      (e[(e.LoginDebugServerIp = 10)] = "LoginDebugServerIp"),
      (e[(e.PlayMenuInfo = 11)] = "PlayMenuInfo"),
      (e[(e.MenuData = 12)] = "MenuData"),
      (e[(e.Account = 13)] = "Account"),
      (e[(e.GmHistory = 14)] = "GmHistory"),
      (e[(e.LocalGameTimeData = 15)] = "LocalGameTimeData"),
      (e[(e.PackageAudio = 16)] = "PackageAudio"),
      (e[(e.RecentlyAccountList = 17)] = "RecentlyAccountList"),
      (e[(e.RecentlyLoginUID = 18)] = "RecentlyLoginUID"),
      (e[(e.LastTimeUploadStamp = 19)] = "LastTimeUploadStamp"),
      (e[(e.SdkLastTimeLoginData = 20)] = "SdkLastTimeLoginData"),
      (e[(e.SdkLevelData = 21)] = "SdkLevelData"),
      (e[(e.RequestPhotoPermissionMinTime = 22)] =
        "RequestPhotoPermissionMinTime"),
      (e[(e.PhotoAndShareShowPlayerName = 23)] = "PhotoAndShareShowPlayerName"),
      (e[(e.CombineAction = 24)] = "CombineAction"),
      (e[(e.GameQualityLevel = 25)] = "GameQualityLevel"),
      (e[(e.CustomFrameRate = 26)] = "CustomFrameRate"),
      (e[(e.ShadowQuality = 27)] = "ShadowQuality"),
      (e[(e.NiagaraQuality = 28)] = "NiagaraQuality"),
      (e[(e.ImageDetail = 29)] = "ImageDetail"),
      (e[(e.Brightness = 30)] = "Brightness"),
      (e[(e.AntiAliasing = 31)] = "AntiAliasing"),
      (e[(e.SceneAo = 32)] = "SceneAo"),
      (e[(e.VolumeFog = 33)] = "VolumeFog"),
      (e[(e.VolumeLight = 34)] = "VolumeLight"),
      (e[(e.MotionBlur = 35)] = "MotionBlur"),
      (e[(e.StreamLevel = 36)] = "StreamLevel"),
      (e[(e.PcVsync = 37)] = "PcVsync"),
      (e[(e.MobileResolution = 38)] = "MobileResolution"),
      (e[(e.SuperResolution = 39)] = "SuperResolution"),
      (e[(e.PcResolutionWidth = 40)] = "PcResolutionWidth"),
      (e[(e.PcResolutionHeight = 41)] = "PcResolutionHeight"),
      (e[(e.PcWindowMode = 42)] = "PcWindowMode"),
      (e[(e.NvidiaSuperSamplingEnable = 43)] = "NvidiaSuperSamplingEnable"),
      (e[(e.NvidiaSuperSamplingFrameGenerate = 44)] =
        "NvidiaSuperSamplingFrameGenerate"),
      (e[(e.NvidiaSuperSamplingMode = 45)] = "NvidiaSuperSamplingMode"),
      (e[(e.NvidiaSuperSamplingQuality = 46)] = "NvidiaSuperSamplingQuality"),
      (e[(e.NvidiaSuperSamplingSharpness = 47)] =
        "NvidiaSuperSamplingSharpness"),
      (e[(e.NvidiaReflex = 48)] = "NvidiaReflex"),
      (e[(e.FsrEnable = 49)] = "FsrEnable"),
      (e[(e.HorizontalViewSensitivity = 50)] = "HorizontalViewSensitivity"),
      (e[(e.VerticalViewSensitivity = 51)] = "VerticalViewSensitivity"),
      (e[(e.AimHorizontalViewSensitivity = 52)] =
        "AimHorizontalViewSensitivity"),
      (e[(e.AimVerticalViewSensitivity = 53)] = "AimVerticalViewSensitivity"),
      (e[(e.CameraShakeStrength = 54)] = "CameraShakeStrength"),
      (e[(e.MobileHorizontalViewSensitivity = 55)] =
        "MobileHorizontalViewSensitivity"),
      (e[(e.MobileVerticalViewSensitivity = 56)] =
        "MobileVerticalViewSensitivity"),
      (e[(e.MobileAimHorizontalViewSensitivity = 57)] =
        "MobileAimHorizontalViewSensitivity"),
      (e[(e.MobileAimVerticalViewSensitivity = 58)] =
        "MobileAimVerticalViewSensitivity"),
      (e[(e.MobileCameraShakeStrength = 59)] = "MobileCameraShakeStrength"),
      (e[(e.CommonSpringArmLength = 60)] = "CommonSpringArmLength"),
      (e[(e.FightSpringArmLength = 61)] = "FightSpringArmLength"),
      (e[(e.IsResetFocusEnable = 62)] = "IsResetFocusEnable"),
      (e[(e.IsSidestepCameraEnable = 63)] = "IsSidestepCameraEnable"),
      (e[(e.IsSoftLockCameraEnable = 64)] = "IsSoftLockCameraEnable"),
      (e[(e.JoystickShakeStrength = 65)] = "JoystickShakeStrength"),
      (e[(e.JoystickShakeType = 66)] = "JoystickShakeType"),
      (e[(e.WalkOrRunRate = 67)] = "WalkOrRunRate"),
      (e[(e.JoystickMode = 68)] = "JoystickMode"),
      (e[(e.IsAutoSwitchSkillButtonMode = 69)] = "IsAutoSwitchSkillButtonMode"),
      (e[(e.AimAssistEnable = 70)] = "AimAssistEnable"),
      (e[(e.XessEnable = 71)] = "XessEnable"),
      (e[(e.XessQuality = 72)] = "XessQuality"),
      (e[(e.MetalFxEnable = 73)] = "MetalFxEnable"),
      (e[(e.IrxEnable = 74)] = "IrxEnable"),
      (e[(e.BloomEnable = 75)] = "BloomEnable"),
      (e[(e.NpcDensity = 76)] = "NpcDensity"),
      (e[(e.KeyboardLockEnemyMode = 77)] = "KeyboardLockEnemyMode"),
      (e[(e.HorizontalViewRevert = 78)] = "HorizontalViewRevert"),
      (e[(e.VerticalViewRevert = 79)] = "VerticalViewRevert"),
      (e[(e.SkillLockEnemyMode = 80)] = "SkillLockEnemyMode"),
      (e[(e.GamepadLockEnemyMode = 81)] = "GamepadLockEnemyMode"),
      (e[(e.EnemyHitDisplayMode = 82)] = "EnemyHitDisplayMode"),
      (e[(e.RepairEnemyHitDisplayMode = 83)] = "RepairEnemyHitDisplayMode"),
      (e[(e.GamepadRouletteSelectConfig = 84)] = "GamepadRouletteSelectConfig"),
      (e[(e.IsConvertViewSensitivity = 85)] = "IsConvertViewSensitivity"),
      (e[(e.IsConvertAllViewSensitivity = 86)] = "IsConvertAllViewSensitivity"),
      (e[(e.MasterVolume = 87)] = "MasterVolume"),
      (e[(e.VoiceVolume = 88)] = "VoiceVolume"),
      (e[(e.MusicVolume = 89)] = "MusicVolume"),
      (e[(e.SFXVolume = 90)] = "SFXVolume"),
      (e[(e.AMBVolume = 91)] = "AMBVolume"),
      (e[(e.UIVolume = 92)] = "UIVolume"),
      (e[(e.PcResolutionIndex = 93)] = "PcResolutionIndex"),
      (e[(e.TextLanguage = 94)] = "TextLanguage"),
      (e[(e.VoiceLanguage = 95)] = "VoiceLanguage"),
      (e[(e.AdviceSetting = 96)] = "AdviceSetting"),
      (e[(e.GenderSetting = 97)] = "GenderSetting"),
      (e[(e.ImageQuality = 98)] = "ImageQuality"),
      (e[(e.HasLocalGameSettings = 99)] = "HasLocalGameSettings"),
      (e[(e.IsConvertOldMenuData = 100)] = "IsConvertOldMenuData"),
      (e[(e.LastReviewTime = 101)] = "LastReviewTime"),
      (e[(e.IsConvertInputActionSort = 102)] = "IsConvertInputActionSort"),
      (e[(e.OpenReviewTimeList = 103)] = "OpenReviewTimeList"),
      (e[(e.AutoAdjustImageQuality = 104)] = "AutoAdjustImageQuality"),
      (e[(e.IsConvertInput = 105)] = "IsConvertInput"),
      (e[(e.IsSavedKeyMappings = 106)] = "IsSavedKeyMappings"),
      (e[(e.GamepadOperationPreferences = 107)] =
        "GamepadOperationPreferences"),
      (e[(e.ShowDamage = 108)] = "ShowDamage"),
      (e[(e.DynamicBones = 109)] = "DynamicBones"),
      (e[(e.IsCustomImageQuality = 110)] = "IsCustomImageQuality"),
      (e[(e.DolbyAtmos = 111)] = "DolbyAtmos"),
      (e[(e.IsFinishRecommendQuality = 112)] = "IsFinishRecommendQuality"),
      (e[(e.FlowAdaptation = 113)] = "FlowAdaptation"),
      (e[(e.FlyControlMode = 114)] = "FlyControlMode"),
      (e[(e.IsShowFinishedPlayPointMark = 115)] =
        "IsShowFinishedPlayPointMark"),
      (e[(e.IsShowCustomMark = 116)] = "IsShowCustomMark"),
      (e[(e.AreaStoryProgress = 117)] = "AreaStoryProgress"),
      (e[(e.RayTracing = 118)] = "RayTracing"),
      (e[(e.RayTracedReflection = 119)] = "RayTracedReflection"),
      (e[(e.RayTracedGI = 120)] = "RayTracedGI"),
      (e[(e.RayTracedShadow = 121)] = "RayTracedShadow"),
      (e[(e.TeammateFx = 122)] = "TeammateFx"),
      (e[(e.Saturation = 123)] = "Saturation"),
      (e[(e.Contrast = 124)] = "Contrast"),
      (e[(e.SaturationNew = 125)] = "SaturationNew"),
      (e[(e.ContrastNew = 126)] = "ContrastNew"),
      (e[(e.IconPercentAreaStory = 127)] = "IconPercentAreaStory"),
      (e[(e.IconPercentAreaShow = 128)] = "IconPercentAreaShow"),
      (e[(e.AreaExplorePlayState = 129)] = "AreaExplorePlayState"),
      (e[(e.ShowNoteIdMap = 130)] = "ShowNoteIdMap"),
      (e[(e.SkinDamageMode = 131)] = "SkinDamageMode"),
      (e[(e.HasRefreshNvidiaDlssQuality = 132)] =
        "HasRefreshNvidiaDlssQuality"),
      (e[(e.HasRefreshNvidiaDlssFrameGenerate = 133)] =
        "HasRefreshNvidiaDlssFrameGenerate"),
      (e[(e.AfmeSince2Dot3 = 134)] = "AfmeSince2Dot3"),
      (e[(e.AutoRun = 135)] = "AutoRun"),
      (e[(e.AutoSprint = 136)] = "AutoSprint"),
      (e[(e.Vulkan = 137)] = "Vulkan"),
      (e[(e.PreDownloadVersionRecord = 138)] = "PreDownloadVersionRecord"),
      (e[(e.IsLastGamePadPlayStation = 139)] = "IsLastGamePadPlayStation"),
      (e[(e.LastGamepadEnum = 140)] = "LastGamepadEnum"),
      (e[(e.HasResetBrightness = 141)] = "HasResetBrightness");
  })(
    (ELocalStorageGlobalKey =
      exports.ELocalStorageGlobalKey || (exports.ELocalStorageGlobalKey = {})),
  ),
  (function (e) {
    (e[(e.FirstOpenShop = 0)] = "FirstOpenShop"),
      (e[(e.CookerLevelKey = 1)] = "CookerLevelKey"),
      (e[(e.EditBattleTeam = 2)] = "EditBattleTeam"),
      (e[(e.GachaPoolOpenRecord = 3)] = "GachaPoolOpenRecord"),
      (e[(e.InventoryCommonItem = 4)] = "InventoryCommonItem"),
      (e[(e.InventoryAttributeItem = 5)] = "InventoryAttributeItem"),
      (e[(e.InventoryCommonItemRedDot = 6)] = "InventoryCommonItemRedDot"),
      (e[(e.InventoryAttributeItemRedDot = 7)] =
        "InventoryAttributeItemRedDot"),
      (e[(e.RouletteAssemblyItemRedDot = 8)] = "RouletteAssemblyItemRedDot"),
      (e[(e.GetItemConfigListSaveKey = 9)] = "GetItemConfigListSaveKey"),
      (e[(e.ComposeLevelKey = 10)] = "ComposeLevelKey"),
      (e[(e.ForgingLevelKey = 11)] = "ForgingLevelKey"),
      (e[(e.Chat = 12)] = "Chat"),
      (e[(e.BattlePassPayButton = 13)] = "BattlePassPayButton"),
      (e[(e.MonthCardNextShowRedDotTime = 14)] = "MonthCardNextShowRedDotTime"),
      (e[(e.IsErrorChatReplace = 15)] = "IsErrorChatReplace"),
      (e[(e.LocalFriendApplication = 16)] = "LocalFriendApplication"),
      (e[(e.MarqueeScrollingMap = 17)] = "MarqueeScrollingMap"),
      (e[(e.LoginTime = 18)] = "LoginTime"),
      (e[(e.LastTimeUploadStamp = 19)] = "LastTimeUploadStamp"),
      (e[(e.Activity = 20)] = "Activity"),
      (e[(e.IsTriggerMobileGuide = 21)] = "IsTriggerMobileGuide"),
      (e[(e.IsTriggerDesktopGuide = 22)] = "IsTriggerDesktopGuide"),
      (e[(e.AutoInteractionGuideAppearCount = 23)] =
        "AutoInteractionGuideAppearCount"),
      (e[(e.IsSimpleDetail = 24)] = "IsSimpleDetail"),
      (e[(e.VisionSpecialSkillShowMap = 25)] = "VisionSpecialSkillShowMap"),
      (e[(e.ItemGridDropDown = 26)] = "ItemGridDropDown"),
      (e[(e.HasShowNewMailTipsMap = 27)] = "HasShowNewMailTipsMap"),
      (e[(e.RoguelikeDescModel = 28)] = "RoguelikeDescModel"),
      (e[(e.RoleDataItem = 29)] = "RoleDataItem"),
      (e[(e.PersonalDataItem = 30)] = "PersonalDataItem"),
      (e[(e.CalabashCollect = 31)] = "CalabashCollect"),
      (e[(e.CalabashCollectIsSimpleDetail = 32)] =
        "CalabashCollectIsSimpleDetail"),
      (e[(e.RoguelikeShopRecord = 33)] = "RoguelikeShopRecord"),
      (e[(e.RoguelikeShopNextTimeStamp = 34)] = "RoguelikeShopNextTimeStamp"),
      (e[(e.VisionSkin = 35)] = "VisionSkin"),
      (e[(e.SilentTips = 36)] = "SilentTips"),
      (e[(e.GachaRoleRecord = 37)] = "GachaRoleRecord"),
      (e[(e.GachaWeaponRecord = 38)] = "GachaWeaponRecord"),
      (e[(e.RouletteAction01OpenConfig = 39)] = "RouletteAction01OpenConfig"),
      (e[(e.RouletteAction02OpenConfig = 40)] = "RouletteAction02OpenConfig"),
      (e[(e.MoonChasingShopItemUnlock = 41)] = "MoonChasingShopItemUnlock"),
      (e[(e.MoonChasingShopItemChecked = 42)] = "MoonChasingShopItemChecked"),
      (e[(e.MoonChasingRoleUnlock = 43)] = "MoonChasingRoleUnlock"),
      (e[(e.MoonChasingQuestUnlock = 44)] = "MoonChasingQuestUnlock"),
      (e[(e.MoonChasingMemoryChecked = 45)] = "MoonChasingMemoryChecked"),
      (e[(e.LoopTowerIsClickSeason = 46)] = "LoopTowerIsClickSeason"),
      (e[(e.LoopTowerIsClickShop = 47)] = "LoopTowerIsClickShop"),
      (e[(e.TowerOverLockArea = 48)] = "TowerOverLockArea"),
      (e[(e.ActivityRecallWatchFirstShow = 49)] =
        "ActivityRecallWatchFirstShow"),
      (e[(e.ActivityRecallWatchFirstShowTime = 50)] =
        "ActivityRecallWatchFirstShowTime"),
      (e[(e.ActivityRegressSignLastDailyFirstShowTimeStamp = 51)] =
        "ActivityRegressSignLastDailyFirstShowTimeStamp"),
      (e[(e.ActivityRegressShopRedDotCheckedInPeriod = 52)] =
        "ActivityRegressShopRedDotCheckedInPeriod"),
      (e[(e.ActivityRegressQuestionnaireRedDotCheckedInPeriod = 53)] =
        "ActivityRegressQuestionnaireRedDotCheckedInPeriod"),
      (e[(e.ActivityRegressSecondQuestionnaireRedDotCheckedInPeriod = 54)] =
        "ActivityRegressSecondQuestionnaireRedDotCheckedInPeriod"),
      (e[(e.ActivityRegressDoubleDropReminderLastShowTime = 55)] =
        "ActivityRegressDoubleDropReminderLastShowTime"),
      (e[(e.ActivityRegressDoubleDropFirstRedDotCheckedInPeriod = 56)] =
        "ActivityRegressDoubleDropFirstRedDotCheckedInPeriod"),
      (e[(e.TowerDefenseEntered = 57)] = "TowerDefenseEntered"),
      (e[(e.VersionPreheatToQuestClicked = 58)] =
        "VersionPreheatToQuestClicked"),
      (e[(e.VersionPreheatBonusClicked = 59)] = "VersionPreheatBonusClicked"),
      (e[(e.VersionPreheatToQuestPlayed = 60)] = "VersionPreheatToQuestPlayed"),
      (e[(e.VersionPreheatBonusPlayed = 61)] = "VersionPreheatBonusPlayed"),
      (e[(e.Spring25FirstTimeTaskAllDone = 62)] =
        "Spring25FirstTimeTaskAllDone"),
      (e[(e.Spring25FirstDoneTaskIndex = 63)] = "Spring25FirstDoneTaskIndex"),
      (e[(e.Spring25FirstLetterClick = 64)] = "Spring25FirstLetterClick"),
      (e[(e.Spring25FirstEnter = 65)] = "Spring25FirstEnter"),
      (e[(e.MoonChasingDelegation = 66)] = "MoonChasingDelegation"),
      (e[(e.ShowPersonalTip = 67)] = "ShowPersonalTip"),
      (e[(e.HasCleanInvalidCustomMark = 68)] = "HasCleanInvalidCustomMark"),
      (e[(e.SortConfig = 69)] = "SortConfig"),
      (e[(e.FragmentMemoryOpened = 70)] = "FragmentMemoryOpened"),
      (e[(e.VisionRecoveryBatchTip = 71)] = "VisionRecoveryBatchTip"),
      (e[(e.VisionRefineTip = 72)] = "VisionRefineTip"),
      (e[(e.AuToTrackQuestTime = 73)] = "AuToTrackQuestTime"),
      (e[(e.GoodsRemindMap = 74)] = "GoodsRemindMap"),
      (e[(e.WeaponSkinRedDot = 75)] = "WeaponSkinRedDot"),
      (e[(e.FlySkinRedDot = 76)] = "FlySkinRedDot"),
      (e[(e.MowingRiskIsInstanceNew = 77)] = "MowingRiskIsInstanceNew"),
      (e[(e.TowerDefenseNewLevel = 78)] = "TowerDefenseNewLevel"),
      (e[(e.MailBindNextShowRedDotTime = 79)] = "MailBindNextShowRedDotTime"),
      (e[(e.ShowSkillResume = 80)] = "ShowSkillResume"),
      (e[(e.EnterGamepadCount = 81)] = "EnterGamepadCount"),
      (e[(e.CumulativeGamepadTime = 82)] = "CumulativeGamepadTime"),
      (e[(e.RedDotAdventureNewSoundAreaTabLastUpdateTime = 83)] =
        "RedDotAdventureNewSoundAreaTabLastUpdateTime"),
      (e[(e.VisionLevelUpMaterialPutInMode = 84)] =
        "VisionLevelUpMaterialPutInMode"),
      (e[(e.VisionLevelUpMaterialUseType = 85)] =
        "VisionLevelUpMaterialUseType"),
      (e[(e.VisionLevelUpSettingRedDot = 86)] = "VisionLevelUpSettingRedDot"),
      (e[(e.DirectTrainGotoRedDotHaveDisplayed = 87)] =
        "DirectTrainGotoRedDotHaveDisplayed"),
      (e[(e.DetectionRedDotRecord = 88)] = "DetectionRedDotRecord"),
      (e[(e.SuitWeaponFirstWearRecord = 89)] = "SuitWeaponFirstWearRecord"),
      (e[(e.RoleSkinRedDot = 90)] = "RoleSkinRedDot"),
      (e[(e.NewLordGymEntranceIdRecord = 91)] = "NewLordGymEntranceIdRecord"),
      (e[(e.SailingIsFix = 92)] = "SailingIsFix"),
      (e[(e.VisionTopTipsState = 93)] = "VisionTopTipsState"),
      (e[(e.FirstOpenVisionGroup = 94)] = "FirstOpenVisionGroup"),
      (e[(e.ShipTowerSeason = 95)] = "ShipTowerSeason"),
      (e[(e.DockyardListItemRead = 96)] = "DockyardListItemRead"),
      (e[(e.FilterRedPoint = 97)] = "FilterRedPoint"),
      (e[(e.SolarSpeedInstanceClicked = 98)] = "SolarSpeedInstanceClicked"),
      (e[(e.PayShopTabItemChecked = 99)] = "PayShopTabItemChecked"),
      (e[(e.FishingHandBookItemRecord = 100)] = "FishingHandBookItemRecord"),
      (e[(e.FishingShipSkinRecord = 101)] = "FishingShipSkinRecord"),
      (e[(e.ShipTowerGetBuffSet = 102)] = "ShipTowerGetBuffSet"),
      (e[(e.ExploreActivityFirstUnlock = 103)] = "ExploreActivityFirstUnlock"),
      (e[(e.PlayerTitleRecord = 104)] = "PlayerTitleRecord"),
      (e[(e.PlayerTitleUnlockRedDot = 105)] = "PlayerTitleUnlockRedDot"),
      (e[(e.BabelTowerNewLevel = 106)] = "BabelTowerNewLevel"),
      (e[(e.BabelTowerNewLevelHasClick = 107)] = "BabelTowerNewLevelHasClick"),
      (e[(e.InviteNewbieEntered = 108)] = "InviteNewbieEntered"),
      (e[(e.AbyssDangoFormationSelect = 109)] = "AbyssDangoFormationSelect"),
      (e[(e.RogueResDungeonNewest = 110)] = "RogueResDungeonNewest"),
      (e[(e.RogueResSkillTreeOpen = 111)] = "RogueResSkillTreeOpen"),
      (e[(e.RogueResEndingOpen = 112)] = "RogueResEndingOpen"),
      (e[(e.RogueResShopOpen = 113)] = "RogueResShopOpen"),
      (e[(e.RogueResTaskOpen = 114)] = "RogueResTaskOpen"),
      (e[(e.RogueResTrialOpen = 115)] = "RogueResTrialOpen"),
      (e[(e.DangoMonopolyActivityId = 116)] = "DangoMonopolyActivityId"),
      (e[(e.DangoMonopolySpeed = 117)] = "DangoMonopolySpeed"),
      (e[(e.DangoMonopolyLastEnterBoard = 118)] =
        "DangoMonopolyLastEnterBoard"),
      (e[(e.DangoMonopolyNewTask = 119)] = "DangoMonopolyNewTask"),
      (e[(e.RacingBetsMatchViewRecord = 120)] = "RacingBetsMatchViewRecord"),
      (e[(e.RacingBetsRankViewRecord = 121)] = "RacingBetsRankViewRecord"),
      (e[(e.RacingBetsReplayGameRecord = 122)] = "RacingBetsReplayGameRecord"),
      (e[(e.RacingBetsWatchGameRecord = 123)] = "RacingBetsWatchGameRecord"),
      (e[(e.RacingBetsBulletScreenAlphaRecord = 124)] =
        "RacingBetsBulletScreenAlphaRecord"),
      (e[(e.RacingBetsBulletScreenShowTypeRecord = 125)] =
        "RacingBetsBulletScreenShowTypeRecord"),
      (e[(e.SdkReportStateMap = 126)] = "SdkReportStateMap"),
      (e[(e.ShowNoteIdMap = 127)] = "ShowNoteIdMap"),
      (e[(e.AbyssSelectRole = 128)] = "AbyssSelectRole"),
      (e[(e.AbyssDangoLevelCheck = 129)] = "AbyssDangoLevelCheck"),
      (e[(e.AbyssDangoRoleNew = 130)] = "AbyssDangoRoleNew"),
      (e[(e.AbyssDangoFormationNew = 131)] = "AbyssDangoFormationNew");
  })(
    (ELocalStoragePlayerKey =
      exports.ELocalStoragePlayerKey || (exports.ELocalStoragePlayerKey = {})),
  ),
  (function (e) {
    (e[(e.CacheP4Version = 0)] = "CacheP4Version"),
      (e[(e.PatchVersion = 1)] = "PatchVersion"),
      (e[(e.LauncherPatchVersion = 2)] = "LauncherPatchVersion");
  })(
    (ELocalStorageDeviceKey =
      exports.ELocalStorageDeviceKey || (exports.ELocalStorageDeviceKey = {})),
  );
//# sourceMappingURL=LocalStorageDefine.js.map
