"use strict";
Object.defineProperty(exports, "__esModule", { value: !0 }),
  (exports.UiTabViewManager = void 0);
const BossRushBuffSelectView_1 = require("../Module/Activity/ActivityContent/BossRush/BossRushBuffSelectView"),
  BossRushLevelDetailView_1 = require("../Module/Activity/ActivityContent/BossRush/BossRushLevelDetailView"),
  BossRushRewardView_1 = require("../Module/Activity/ActivityContent/BossRush/BossRushRewardView"),
  BossRushSelectView_1 = require("../Module/Activity/ActivityContent/BossRush/BossRushSelectView"),
  FishingTimeLimitRewardTabView_1 = require("../Module/Activity/ActivityContent/Fishing/Activity/View/FishingTimeLimitRewardTabView"),
  FishingTimeLimitShopTabView_1 = require("../Module/Activity/ActivityContent/Fishing/Activity/View/FishingTimeLimitShopTabView"),
  DockyardBuyTabView_1 = require("../Module/Activity/ActivityContent/Fishing/Dockyard/Shop/DockyardBuyTabView"),
  DockyardSellTabView_1 = require("../Module/Activity/ActivityContent/Fishing/Dockyard/Shop/DockyardSellTabView"),
  FishingNormalTechView_1 = require("../Module/Activity/ActivityContent/Fishing/FishingTech/FishingNormalTechView"),
  FishingRoleTechView_1 = require("../Module/Activity/ActivityContent/Fishing/FishingTech/FishingRoleTechView"),
  RewardShopTabView_1 = require("../Module/Activity/ActivityContent/MoonChasing/Main/Reward/Shop/RewardShopTabView"),
  RewardTargetTabView_1 = require("../Module/Activity/ActivityContent/MoonChasing/Main/Reward/Target/RewardTargetTabView"),
  AdventureTargetView_1 = require("../Module/AdventureGuide/Views/AdventureTargetView"),
  MonsterDetectView_1 = require("../Module/AdventureGuide/Views/MonsterDetectView"),
  NewSoundAreaView_1 = require("../Module/AdventureGuide/Views/NewSoundAreaView"),
  CalabashCollectTabView_1 = require("../Module/Calabash/New/CalabashCollect/CalabashCollectTabView"),
  CalabashLevelUpTabView_1 = require("../Module/Calabash/New/CalabashLevelUp/CalabashLevelUpTabView"),
  PhantomBattleFettersTabView_1 = require("../Module/Calabash/New/PhantomBattleFetters/PhantomBattleFettersTabView"),
  VisionRecoveryTabView_1 = require("../Module/Calabash/New/VisionRecovery/VisionRecoveryTabView"),
  VisionRefineTabView_1 = require("../Module/Calabash/New/VisionRefine/VisionRefineTabView"),
  DailyActivityView_1 = require("../Module/DailyActivity/View/DailyActivityView"),
  RolePreviewDescribeTabView_1 = require("../Module/Gacha/PreviewView/RolePreviewDescribeTabView"),
  RolePreviewResonanceTabView_1 = require("../Module/Gacha/PreviewView/RolePreviewResonanceTabView"),
  RolePreviewSkillTabView_1 = require("../Module/Gacha/PreviewView/RolePreviewSkillTabView"),
  BattlePassRewardView_1 = require("../Module/PayShop/BattlePass/BattlePassTabView/BattlePassRewardView"),
  BattlePassTaskView_1 = require("../Module/PayShop/BattlePass/BattlePassTabView/BattlePassTaskView"),
  BattlePassWeaponView_1 = require("../Module/PayShop/BattlePass/BattlePassTabView/BattlePassWeaponView"),
  MonthCardView_1 = require("../Module/PayShop/MonthCard/MonthCardView"),
  BabelTowerShopView_1 = require("../Module/PayShop/PayShopTab/BabelTowerShopView"),
  DiscountShopView_1 = require("../Module/PayShop/PayShopTab/DiscountShopView"),
  PayPackageShopView_1 = require("../Module/PayShop/PayShopTab/PayPackageShopView"),
  PayShopRechargeView_1 = require("../Module/PayShop/PayShopTab/PayShopRechargeView"),
  PayShopRecommendView_1 = require("../Module/PayShop/PayShopTab/PayShopRecommendView"),
  PayShopSkinView_1 = require("../Module/PayShop/PayShopTab/PayShopSkinView"),
  RogueShopTabView_1 = require("../Module/PayShop/PayShopTab/RogueShopTabView"),
  RoleSkinTabView_1 = require("../Module/PayShop/PayShopTab/RoleSkinTabView"),
  RogueIllustratedEventTabView_1 = require("../Module/PermanentRogue/View/RogueIllustratedEventTabView"),
  RogueIllustratedTokenTabView_1 = require("../Module/PermanentRogue/View/RogueIllustratedTokenTabView"),
  VisionIdentifyView_1 = require("../Module/Phantom/Vision/View/VisionIdentifyView"),
  VisionLevelUpView_1 = require("../Module/Phantom/Vision/View/VisionLevelUpView"),
  RogueBattleMapSummaryFetterTabView_1 = require("../Module/RogueBattle/View/RogueBattleMapSummaryFetterTabView"),
  RogueBattleMapSummaryGridEffectTabView_1 = require("../Module/RogueBattle/View/RogueBattleMapSummaryGridEffectTabView"),
  RogueBattleMapSummaryTeamTabView_1 = require("../Module/RogueBattle/View/RogueBattleMapSummaryTeamTabView"),
  RogueBattleSummaryTeamTabView_1 = require("../Module/RogueBattle/View/RogueBattleSummaryTeamTabView"),
  RogueBattleSummaryTokenTabView_1 = require("../Module/RogueBattle/View/RogueBattleSummaryTokenTabView"),
  RoleHandBookPreviewView_1 = require("../Module/RoleHandBook/RoleHandBookPreviewView"),
  RoleFavorTabView_1 = require("../Module/RoleUi/RoleFavor/RoleFavorTabView"),
  ResonanceChainView_1 = require("../Module/RoleUi/RoleResonance/ResonanceChainView"),
  RoleSkillTreeView_1 = require("../Module/RoleUi/RoleSkill/RoleSkillTreeView"),
  RoleAttributeTabView_1 = require("../Module/RoleUi/TabView/RoleAttributeTabView"),
  RolePreviewAttributeTabView_1 = require("../Module/RoleUi/TabView/RolePreviewAttributeTabView"),
  RoleVisionTabView_1 = require("../Module/RoleUi/TabView/RoleVisionTabView"),
  RoleWeaponTabView_1 = require("../Module/RoleUi/TabView/RoleWeaponTabView"),
  RoleSkinTabView_2 = require("../Module/Skin/Role/View/RoleSkinTabView"),
  FlySkinTabView_1 = require("../Module/Skin/Tab/Fly/FlySkinTabView"),
  RoleSkinRecommendView_1 = require("../Module/Skin/Tab/Role/RoleSkinRecommendView"),
  WeaponSkinTabView_1 = require("../Module/Skin/Tab/Weapon/WeaponSkinTabView"),
  WeaponBreachView_1 = require("../Module/Weapon/Breach/WeaponBreachView"),
  WeaponLevelUpView_1 = require("../Module/Weapon/LevelUp/WeaponLevelUpView"),
  WeaponResonanceView_1 = require("../Module/Weapon/Reasonance/WeaponResonanceView"),
  UiTabViewStorage_1 = require("../Ui/UiTabViewStorage");
class UiTabViewManager {
  static Init() {
    UiTabViewStorage_1.UiTabViewStorage.AddUiTabViewBase([
      [
        "RoleAttributeTabView",
        RoleAttributeTabView_1.RoleAttributeTabView,
        "UiTabView_RoleAttribute_Prefab",
      ],
      [
        "RoleSkillTabView",
        RoleSkillTreeView_1.RoleSkillTreeView,
        "UiTabView_RoleSkill_Prefab",
      ],
      [
        "RoleWeaponTabView",
        RoleWeaponTabView_1.RoleWeaponTabView,
        "UiTabView_RoleWeapon_Prefab",
      ],
      [
        "RoleFavorTabView",
        RoleFavorTabView_1.RoleFavorTabView,
        "UiView_Tab_RoleDangan_Prefab",
      ],
      [
        "RolePreviewAttributeTabView",
        RolePreviewAttributeTabView_1.RolePreviewAttributeTabView,
        "UiTabView_RoleAttributePreview_Prefab",
      ],
      [
        "WeaponLevelUpView",
        WeaponLevelUpView_1.WeaponLevelUpView,
        "UiTabView_WeaponLevelUp_Prefab",
      ],
      [
        "WeaponBreachView",
        WeaponBreachView_1.WeaponBreachView,
        "UiTabView_WeaponBreach_Prefab",
      ],
      [
        "WeaponResonanceView",
        WeaponResonanceView_1.WeaponResonanceView,
        "UiTabView_WeaponResonance_Prefab",
      ],
      [
        "RolePhantomTabView",
        RoleVisionTabView_1.RoleVisionTabView,
        "UiItem_VisionIMain_New",
      ],
      [
        "PayShopGiftBagView",
        DiscountShopView_1.DiscountShopView,
        "UiItem_Exchange1",
      ],
      [
        "RogueShopTabView",
        RogueShopTabView_1.RogueShopTabView,
        "UiItem_Exchange1",
      ],
      [
        "BabelTowerShopTabView",
        BabelTowerShopView_1.BabelTowerShopTabView,
        "UiItem_Exchange1",
      ],
      [
        "PayItemTabView",
        PayShopRechargeView_1.PayShopRechargeView,
        "UiItem_Exchange1",
      ],
      [
        "PayShopRecommendView",
        PayShopRecommendView_1.PayShopRecommendView,
        "UiItem_Exchange1",
      ],
      [
        "PayShopExchangeEntryView",
        DiscountShopView_1.DiscountShopView,
        "UiItem_Exchange1",
      ],
      [
        "PayPackageShopView",
        PayPackageShopView_1.PayPackageShopView,
        "UiItem_Exchange1",
      ],
      [
        "PayShopSkinView",
        PayShopSkinView_1.PayShopSkinView,
        "UiItem_Exchange1",
      ],
      [
        "RoleShopSkinTabView",
        RoleSkinTabView_1.RoleShopSkinTabView,
        "UiItem_ShopSkinList",
      ],
      [
        "RolePreviewDescribeTabView",
        RolePreviewDescribeTabView_1.RolePreviewDescribeTabView,
        "UiTabView_RoleDescribe_Prefab",
      ],
      [
        "RolePreviewSkillTabView",
        RolePreviewSkillTabView_1.RolePreviewSkillTabView,
        "UiTabView_RoleSkill_Prefab",
      ],
      [
        "RolePreviewResonanceTabView",
        RolePreviewResonanceTabView_1.RolePreviewResonanceTabView,
        "UiTabView_RoleResonance_Prefab",
      ],
      [
        "MonthCardView",
        MonthCardView_1.MonthCardView,
        "UiItem_MonthlyCard_Prefab",
      ],
      [
        "RoleSkinRecommendView",
        RoleSkinRecommendView_1.RoleSkinRecommendView,
        "UiItem_ShopSkin",
      ],
      [
        "RoleResonanceTabNewView",
        ResonanceChainView_1.ResonanceChainView,
        "UiTabView_RoleResonance_New_Prefab",
      ],
      [
        "RoleHandBookPreviewView",
        RoleHandBookPreviewView_1.RoleHandBookPreviewView,
        "UiTabView_RoleDescribe_Prefab",
      ],
      [
        "AdventureTargetView",
        AdventureTargetView_1.AdventureTargetView,
        "UiView_Completion",
      ],
      [
        "MonsterDetectView",
        MonsterDetectView_1.MonsterDetectView,
        "UiView_Survey",
      ],
      [
        "DisposableChallengeView",
        NewSoundAreaView_1.NewSoundAreaView,
        "UiView_NewSoundArea",
      ],
      [
        "NewSoundAreaView",
        NewSoundAreaView_1.NewSoundAreaView,
        "UiView_NewSoundArea",
      ],
      [
        "DailyActivityTabView",
        DailyActivityView_1.DailyActivityView,
        "UiItem_Active",
      ],
      [
        "VisionLevelUpView",
        VisionLevelUpView_1.VisionLevelUpView,
        "UiView_VisionLevelUp",
      ],
      [
        "VisionIdentifyView",
        VisionIdentifyView_1.VisionIdentifyView,
        "UiView_VisionIdentify",
      ],
      [
        "CalabashLevelUpTabView",
        CalabashLevelUpTabView_1.CalabashLevelUpTabView,
        "UiItem_VisionUpgrade",
      ],
      [
        "CalabashCollectTabView",
        CalabashCollectTabView_1.CalabashCollectTabView,
        "UiItem_VisionlMap",
      ],
      [
        "PhantomBattleFettersTabView",
        PhantomBattleFettersTabView_1.PhantomBattleFettersTabView,
        "UiItem_VisionFetter",
      ],
      [
        "VisionRecoveryTabView",
        VisionRecoveryTabView_1.VisionRecoveryTabView,
        "UiView_VisionRecovery",
      ],
      [
        "VisionRefineTabView",
        VisionRefineTabView_1.VisionRefineTabView,
        "UiView_VisionRefining",
      ],
      [
        "WeaponSkinTabView",
        WeaponSkinTabView_1.WeaponSkinTabView,
        "UiItem_RoleWeaponSkin",
      ],
      ["RoleSkinTabView", RoleSkinTabView_2.RoleSkinTabView, "UiItem_RoleSkin"],
      ["FlySkinTabView", FlySkinTabView_1.FlySkinTabView, "UiItem_FlySkin"],
      [
        "BattlePassRewardView",
        BattlePassRewardView_1.BattlePassRewardView,
        "UiItem_BattlePassReward",
      ],
      [
        "BattlePassTaskView",
        BattlePassTaskView_1.BattlePassTaskView,
        "UiItem_BattlePassMission",
      ],
      [
        "BattlePassWeaponView",
        BattlePassWeaponView_1.BattlePassWeaponView,
        "UiItem_WeaponPreview",
      ],
      [
        "BossRushBuffSelectView",
        BossRushBuffSelectView_1.BossRushBuffSelectView,
        "UiItem_BossRushEntryCard",
      ],
      [
        "BossRushLevelDetailView",
        BossRushLevelDetailView_1.BossRushLevelDetailView,
        "UiItem_BossrushLevelInfo",
      ],
      [
        "BossRushSelectView",
        BossRushSelectView_1.BossRushSelectView,
        "UiItem_BossrushSleLevel",
      ],
      [
        "BossRushRewardView",
        BossRushRewardView_1.BossRushRewardView,
        "UiItem_BossrushReward",
      ],
      [
        "RewardTargetTabView",
        RewardTargetTabView_1.RewardTargetTabView,
        "UiItem_ShopMission",
      ],
      [
        "RewardShopTabView",
        RewardShopTabView_1.RewardShopTabView,
        "MoonChasing_UiItem_ShopItem",
      ],
      [
        "DockyardSellTabView",
        DockyardSellTabView_1.DockyardSellTabView,
        "UiItem_ShopSell",
      ],
      [
        "DockyardBuyTabView",
        DockyardBuyTabView_1.DockyardBuyTabView,
        "UiItem_ShopList",
      ],
      [
        "FishingNormalTechView",
        FishingNormalTechView_1.FishingNormalTechView,
        "UiItem_NavigationUpgradeSkill",
      ],
      [
        "FishingRoleTechView",
        FishingRoleTechView_1.FishingRoleTechView,
        "UiItem_RoleUpgrade",
      ],
      [
        "FishingTimeLimitRewardTabView",
        FishingTimeLimitRewardTabView_1.FishingTimeLimitRewardTabView,
        "UiItem_LimitTimeReward",
      ],
      [
        "FishingTimeLimitShopTabView",
        FishingTimeLimitShopTabView_1.FishingTimeLimitShopTabView,
        "UiItem_LimitTimeShop",
      ],
      [
        "RogueIllustratedTokenTabView",
        RogueIllustratedTokenTabView_1.RogueIllustratedTokenTabView,
        "UiItem_IllustratedTokenItem",
      ],
      [
        "RogueIllustratedEventTabView",
        RogueIllustratedEventTabView_1.RogueIllustratedEventTabView,
        "UiItem_RogueHandbook",
      ],
      [
        "RogueBattleMapSummaryTeamTabView",
        RogueBattleMapSummaryTeamTabView_1.RogueBattleMapSummaryTeamTabView,
        "UiItem_RogueTeamView",
      ],
      [
        "RogueBattleMapSummaryFettersTabView",
        RogueBattleMapSummaryFetterTabView_1.RogueBattleMapSummaryFettersTabView,
        "UiItem_RogueFettersBuff",
      ],
      [
        "RogueBattleSummaryTeamTabView",
        RogueBattleSummaryTeamTabView_1.RogueBattleSummaryTeamTabView,
        "UiItem_RogueRoleInfo",
      ],
      [
        "RogueBattleMapSummaryGridEffectTabView",
        RogueBattleMapSummaryGridEffectTabView_1.RogueBattleMapSummaryGridEffectTabView,
        "UiItem_BattleAddtionView",
      ],
      [
        "RogueBattleSummaryTokenTabView",
        RogueBattleSummaryTokenTabView_1.RogueBattleSummaryTokenTabView,
        "UiItem_RogueTokenInfo",
      ],
    ]);
  }
}
exports.UiTabViewManager = UiTabViewManager;
//# sourceMappingURL=UiTabViewManager.js.map
