"use strict";
var ELevelGeneralCondition;
Object.defineProperty(exports, "__esModule", { value: !0 }),
  (exports.ELevelGeneralCondition = void 0),
  (function (e) {
    (e.DistanceLess = "DistanceLess"),
      (e.SelfTagCheck = "SelfTagCheck"),
      (e.ItemCheck = "ItemCheck"),
      (e.CheckItemWithOperator = "CheckItemWithOperator"),
      (e.CheckDis = "CheckDis"),
      (e.TargetTagCheck = "TargetTagCheck"),
      (e.CheckOnTrap = "CheckOnTrap"),
      (e.CheckDirection = "CheckDirection"),
      (e.QuestState = "QuestState"),
      (e.CheckStrikeInfo = "CheckStrikeInfo"),
      (e.CheckLevel = "CheckLevel"),
      (e.CheckLevelOp = "CheckLevelOp"),
      (e.CheckGuideStatus = "CheckGuideStatus"),
      (e.CheckCharacterTag = "CheckCharacterTag"),
      (e.CheckCharacterTagNotByEvent = "CheckCharacterTagNotByEvent"),
      (e.CheckCharacterTagByEvent = "CheckCharacterTagByEvent"),
      (e.DragonPoolState = "DragonPoolState"),
      (e.SceneStepState = "SceneStepState"),
      (e.CheckTeleportStatus = "CheckTeleportStatus"),
      (e.RoleLevel = "RoleLevel"),
      (e.CheckRoleLevel = "CheckRoleLevel"),
      (e.RoleBreach = "RoleBreach"),
      (e.SelfGameplayTagCheck = "SelfGameplayTagCheck"),
      (e.CheckInTodTimeSpan = "CheckInTodTimeSpan"),
      (e.CheckSceneItemTag = "CheckEntityCommonTag"),
      (e.IsPlayer = "IsPlayer"),
      (e.CheckEntityConfigId = "CheckEntityConfigId"),
      (e.CheckSelfEntityCommonTag = "CheckSelfEntityCommonTag"),
      (e.CheckInstanceEntranceUnlockStatus =
        "CheckInstanceEntranceUnlockStatus"),
      (e.CheckOriginWorldLevel = "CheckOriginWorldLevel"),
      (e.CheckCurWorldLevel = "CheckCurWorldLevel"),
      (e.CheckCurWorldLevelOp = "CheckCurWorldLevelOp"),
      (e.StartShootTarget = "StartShootTarget"),
      (e.CheckInstanceState = "CheckInstanceState"),
      (e.CheckInstanceMatchAble = "CheckInstanceMatchAble"),
      (e.MoveStateCheck = "MoveStateCheck"),
      (e.CheckBuff = "LevelConditionCheckBuff"),
      (e.CheckUIState = "CheckUIState"),
      (e.CheckUIOpen = "CheckUIOpen"),
      (e.CheckUIOpenDone = "CheckUIOpenDone"),
      (e.CheckInputAction = "CheckInputAction"),
      (e.CheckClientUseSkill = "CheckClientUseSkill"),
      (e.CheckClientUseVisionSkill = "CheckClientUseVisionSkill"),
      (e.CheckBattleRole = "CheckBattleRole"),
      (e.CheckEquippedPhantom = "CheckEquippedPhantom"),
      (e.CheckEnemyBuff = "CheckEnemyBuff"),
      (e.CheckEnemyTag = "CheckEnemyTag"),
      (e.CheckSkillPoint = "CheckSkillPoint"),
      (e.CheckExploreSkill = "CheckExploreSkill"),
      (e.CheckFightEnergyBar = "CheckFightEnergyBar"),
      (e.CheckFightEnergyBall = "CheckFightEnergyBall"),
      (e.FunctionUnlock = "FunctionUnlock"),
      (e.GetNewItem = "GetNewItem"),
      (e.HarmonyQte = "HarmonyQte"),
      (e.GetWhichRole = "GetWhichRole"),
      (e.HpLowerThan = "HpLowerThan"),
      (e.FightWithMonster = "FightWithMonster"),
      (e.PawnInRange = "PawnInRange"),
      (e.SlotOfCurrentRole = "SlotOfCurrentRole"),
      (e.PhantomTargetLevel = "PhantomTargetLevel"),
      (e.CheckClientQuest = "CheckClientQuest"),
      (e.CheckClientQuestNode = "CheckClientQuestNode"),
      (e.PhantomMaxLevel = "PhantomMaxLevel"),
      (e.RoleTargetLevel = "RoleTargetLevel"),
      (e.RoleSkillTargetLevel = "RoleSkillTargetLevel"),
      (e.BattleRoleIsNot = "BattleRoleIsNot"),
      (e.BattleRoleWeaponType = "BattleRoleWeaponType"),
      (e.FormationAnyRoleDead = "FormationAnyRoleDead"),
      (e.ComboTeachingState = "ComboTeachingState"),
      (e.OnViewClose = "OnViewClose"),
      (e.OnPlayerUseSkill = "OnPlayerUseSkill"),
      (e.OnSkillButtonDataRefresh = "OnSkillButtonDataRefresh"),
      (e.FinishGuideStepByEvent = "FinishGuideStepByEvent"),
      (e.PlayerRevive = "PlayerRevive"),
      (e.CheckTeamRoleCouldLevelUp = "CheckTeamRoleCouldLevelUp"),
      (e.CheckTeamWeaponCouldLevelUp = "CheckTeamWeaponCouldLevelUp"),
      (e.ClientCalabashLevel = "ClientCalabashLevel"),
      (e.TeamRoleLevel = "TeamRoleLevel"),
      (e.TeamWeaponLevel = "TeamWeaponLevel"),
      (e.TeamCouldEquipPhantom = "TeamCouldEquipPhantom"),
      (e.CheckAnyPhantomCouldUpdate = "CheckAnyPhantomCouldUpdate"),
      (e.CheckAnyRoleFullPhantom = "CheckAnyRoleFullPhantom"),
      (e.CheckRolePhantomNum = "CheckRolePhantomNum"),
      (e.CheckItemCountByType = "CheckItemCountByType"),
      (e.CheckRouletteEquipItemId = "CheckRouletteEquipItemId"),
      (e.CheckVisionIntensifyTabOpen = "CheckVisionIntensifyTabOpen"),
      (e.CheckAccountSettingOpen = "CheckAccountSettingOpen"),
      (e.CheckOnTreasureBoxOpen = "CheckOnTreasureBoxOpen"),
      (e.CheckWeaponCount = "CheckWeaponCount"),
      (e.CheckOnCostInsufficient = "CheckOnCostInsufficient"),
      (e.CheckRangeByPbDataId = "CheckRangeByPbDataId"),
      (e.CheckDungeonId = "CheckDungeonId"),
      (e.CheckRogueTerm = "CheckRogueTerm"),
      (e.CheckTeleportTypeUnlock = "CheckTeleportTypeUnlock"),
      (e.CheckTypeItemPickUp = "CheckTypeItemPickUp"),
      (e.CheckDungeonFinished = "CheckDungeonFinished"),
      (e.CheckRogueCanUnlockSkill = "CheckRogueCanUnlockSkill"),
      (e.CheckPositionRolePhantomSkillEquip =
        "CheckPositionRolePhantomSkillEquip"),
      (e.CheckHasFirstPhantomAtPosition = "CheckHasFirstPhantomAtPosition"),
      (e.CheckWorldMapSecondaryUiOpened = "CheckWorldMapSecondaryUiOpened"),
      (e.CheckHasUnlockAffixInBossRush = "CheckHasUnlockAffixInBossRush"),
      (e.OnChangeBossRushBuff = "OnChangeBossRushBuff"),
      (e.RoguelikeHasSelectEntryAndShow = "RoguelikeHasSelectEntryAndShow"),
      (e.CheckActivityOpen = "CheckActivityOpen"),
      (e.CheckHasSkinInRoleSkinSubView = "CheckHasSkinInRoleSkinSubView"),
      (e.OnTakingPhoto = "OnTakingPhoto"),
      (e.HasNotInvitedRoleInSpring25 = "HasNotInvitedRoleInSpring25"),
      (e.CheckMapFocusByQuestId = "CheckMapFocusByQuestId"),
      (e.PickupInTowerDefenceBattle = "PickupInTowerDefenceBattle"),
      (e.CheckOnSelectMenuMainType = "CheckOnSelectMenuMainType"),
      (e.OnShowPhantomInFormation = "OnShowPhantomInFormation"),
      (e.ForMoonChasingCheckTargetBuiltCount =
        "ForMoonChasingCheckTargetBuiltCount"),
      (e.ForMoonChasingCheckHasCanLevelUpBuilding =
        "ForMoonChasingCheckHasCanLevelUpBuilding"),
      (e.ForMoonChasingCheckNeedBranch = "ForMoonChasingCheckNeedBranch"),
      (e.ForMoonChasingCheckHasNotFinishedTask =
        "ForMoonChasingCheckHasNotFinishedTask"),
      (e.ForMoonChasingCheckTaskState = "ForMoonChasingCheckTaskState"),
      (e.ForMoonChasingCheckMainlineTaskDone =
        "ForMoonChasingCheckMainlineTaskDone"),
      (e.ForMoonChasingOpenInteractive = "ForMoonChasingOpenInteractive"),
      (e.CheckPureModeWhenBattleViewActive =
        "CheckPureModeWhenBattleViewActive"),
      (e.OnActivitySubViewDone = "OnActivitySubViewDone"),
      (e.CheckLockEnemyMode = "CheckLockEnemyMode"),
      (e.CheckIsShowProgressBarInMapExploreDetailView =
        "CheckIsShowProgressBarInMapExploreDetailView"),
      (e.CheckIsMulti = "CheckIsMulti"),
      (e.CheckFishingRoleTechViewOpen = "CheckFishingRoleTechViewOpen"),
      (e.CheckFishingDockyardItemTipsShown =
        "CheckFishingDockyardItemTipsShown"),
      (e.CheckShipTowerTeamOpen = "CheckShipTowerTeamOpen"),
      (e.CheckDockyardWareHouseHasItem = "CheckDockyardWareHouseHasItem"),
      (e.CheckFishingQteBtnHitValidArea = "CheckFishingQteBtnHitValidArea"),
      (e.OnFishingQteScoreReachedMaximum = "OnFishingQteScoreReachedMaximum"),
      (e.CheckFishingTechUnlock = "CheckFishingTechUnlock"),
      (e.OnFishingBackpackBtnStateChange = "OnFishingBackpackBtnStateChange"),
      (e.CheckFishingEntrustState = "CheckFishingEntrustState"),
      (e.CheckFishingWareHouseItemListLength =
        "CheckFishingWareHouseItemListLength"),
      (e.CheckCurFishingEntrustAvailablePeriod =
        "CheckCurFishingEntrustAvailablePeriod"),
      (e.OnTreasureCompassUnitShow = "OnTreasureCompassUnitShow"),
      (e.OnFishingBackpackQuickSellToggleShow =
        "OnFishingBackpackQuickSellToggleShow"),
      (e.HideSettingInCloudGame = "HideSettingInCloudGame"),
      (e.OnPlayerTitleUnlock = "OnPlayerTitleUnlock"),
      (e.CheckDangoMonopolyHasFinishedRound =
        "CheckDangoMonopolyHasFinishedRound"),
      (e.OnDangoMonopolyMoveStop = "OnDangoMonopolyMoveStop"),
      (e.OnDangoMonopolyViewShowProcessEnd =
        "OnDangoMonopolyViewShowProcessEnd"),
      (e.OnDangoAbyssPluginRoleSelect = "OnDangoAbyssPluginRoleSelect"),
      (e.CheckDangoMatchState = "CheckDangoMatchState"),
      (e.CheckDangoMatchPlayerNumType = "CheckDangoMatchPlayerNumType"),
      (e.OnEnterDangoMatchView = "OnEnterDangoMatchView"),
      (e.OnDangoMonopolyViewStart = "OnDangoMonopolyViewStart"),
      (e.OnCiacconaAvgInspirationChoiceShow =
        "OnCiacconaAvgInspirationChoiceShow"),
      (e.OnCiacconaChapterFirstStart = "OnCiacconaChapterFirstStart"),
      (e.OnCiacconaChapterRestart = "OnCiacconaChapterRestart"),
      (e.OnMovieRogueInfoRefreshWithMultipleEnds =
        "OnMovieRogueInfoRefreshWithMultipleEnds"),
      (e.CheckMovieRogueFinishedEndingCount =
        "CheckMovieRogueFinishedEndingCount"),
      (e.OnDangoAbyssEnterWithTeamExploreBtn =
        "OnDangoAbyssEnterWithTeamExploreBtn"),
      (e.OnDangoAbyssEquipPluginWithValidChange =
        "OnDangoAbyssEquipPluginWithValidChange"),
      (e.OnDangoAbyssEquipPluginWithInvalid =
        "OnDangoAbyssEquipPluginWithInvalid"),
      (e.OnMovieRogueLinkRefresh = "OnMovieRogueLinkRefresh"),
      (e.OnMovieRogueMapMoveEnd = "OnMovieRogueMapMoveEnd"),
      (e.OnMapRogueEventDetailShow = "OnMapRogueEventDetailShow"),
      (e.CheckMapRogueEventDetailShow = "CheckMapRogueEventDetailShow"),
      (e.OnDangoMonopolyCameraFocusOnMainDango =
        "OnDangoMonopolyCameraFocusOnMainDango"),
      (e.CheckDangoAbyssProgress = "CheckDangoAbyssProgress"),
      (e.CheckDangoAbyssHasItemByType = "CheckDangoAbyssHasItemByType"),
      (e.CheckDangoMatchFinalEnd = "CheckDangoMatchFinalEnd"),
      (e.CheckGridHasExplored = "CheckGridHasExplored"),
      (e.OnUiTabViewShow = "OnUiTabViewShow"),
      (e.AlwaysFalse = "AlwaysFalse");
  })(
    (ELevelGeneralCondition =
      exports.ELevelGeneralCondition || (exports.ELevelGeneralCondition = {})),
  );
//# sourceMappingURL=LevelGeneralDefine.js.map
