"use strict";
var EEventName;
Object.defineProperty(exports, "__esModule", { value: !0 }),
  (exports.EEventName = void 0),
  (function (e) {
    (e[(e.SetEntityCreatureDataRelation = 0)] =
      "SetEntityCreatureDataRelation"),
      (e[(e.KeyClick = 1)] = "KeyClick"),
      (e[(e.UiSceneLoaded = 2)] = "UiSceneLoaded"),
      (e[(e.UiSceneStartLoad = 3)] = "UiSceneStartLoad"),
      (e[(e.OpenView = 4)] = "OpenView"),
      (e[(e.StackPreOpenView = 5)] = "StackPreOpenView"),
      (e[(e.StackOpenView = 6)] = "StackOpenView"),
      (e[(e.StackCloseView = 7)] = "StackCloseView"),
      (e[(e.OpenViewBegined = 8)] = "OpenViewBegined"),
      (e[(e.OpenViewFail = 9)] = "OpenViewFail"),
      (e[(e.CreateViewInstance = 10)] = "CreateViewInstance"),
      (e[(e.OnViewLoadCompleted = 11)] = "OnViewLoadCompleted"),
      (e[(e.OnViewDone = 12)] = "OnViewDone"),
      (e[(e.OnViewHidden = 13)] = "OnViewHidden"),
      (e[(e.CloseView = 14)] = "CloseView"),
      (e[(e.OpenTabView = 15)] = "OpenTabView"),
      (e[(e.TriggerUiTimeDilation = 16)] = "TriggerUiTimeDilation"),
      (e[(e.CloseTabView = 17)] = "CloseTabView"),
      (e[(e.ChangeChildView = 18)] = "ChangeChildView"),
      (e[(e.UiManagerInit = 19)] = "UiManagerInit"),
      (e[(e.UiManagerDestroy = 20)] = "UiManagerDestroy"),
      (e[(e.HotKeyInput = 21)] = "HotKeyInput"),
      (e[(e.ViewHotKeyInputPress = 22)] = "ViewHotKeyInputPress"),
      (e[(e.ViewHotKeyInputRelease = 23)] = "ViewHotKeyInputRelease"),
      (e[(e.ResetNormalAction = 24)] = "ResetNormalAction"),
      (e[(e.UnBlockCharacterAction = 25)] = "UnBlockCharacterAction"),
      (e[(e.ResetSystemAction = 26)] = "ResetSystemAction"),
      (e[(e.OnReduceDamageViewDepth = 27)] = "OnReduceDamageViewDepth"),
      (e[(e.LoginSuccess = 28)] = "LoginSuccess"),
      (e[(e.EnterGameSuccess = 29)] = "EnterGameSuccess"),
      (e[(e.LoginStatusChange = 30)] = "LoginStatusChange"),
      (e[(e.LoginRequestResult = 31)] = "LoginRequestResult"),
      (e[(e.SdkLoginResult = 32)] = "SdkLoginResult"),
      (e[(e.OnGetLoginPlayerInfo = 33)] = "OnGetLoginPlayerInfo"),
      (e[(e.OnSelectServerItem = 34)] = "OnSelectServerItem"),
      (e[(e.OnConfirmServerItem = 35)] = "OnConfirmServerItem"),
      (e[(e.SendHeartbeat = 36)] = "SendHeartbeat"),
      (e[(e.SdkInitDone = 37)] = "SdkInitDone"),
      (e[(e.TimeValidError = 38)] = "TimeValidError"),
      (e[(e.CharQteActive = 39)] = "CharQteActive"),
      (e[(e.CharQteConsume = 40)] = "CharQteConsume"),
      (e[(e.CharInQteChanged = 41)] = "CharInQteChanged"),
      (e[(e.CharExecuteMultiQte = 42)] = "CharExecuteMultiQte"),
      (e[(e.CharHitLocal = 43)] = "CharHitLocal"),
      (e[(e.CharHitRemote = 44)] = "CharHitRemote"),
      (e[(e.CharBeHitLocal = 45)] = "CharBeHitLocal"),
      (e[(e.CharHitIncludingVision = 46)] = "CharHitIncludingVision"),
      (e[(e.CharBeHitRemote = 47)] = "CharBeHitRemote"),
      (e[(e.CharLimitDodge = 48)] = "CharLimitDodge"),
      (e[(e.CharBeHitAnim = 49)] = "CharBeHitAnim"),
      (e[(e.CharBeHitTimeScale = 50)] = "CharBeHitTimeScale"),
      (e[(e.CharShieldChange = 51)] = "CharShieldChange"),
      (e[(e.CharAnimBreakPoint = 52)] = "CharAnimBreakPoint"),
      (e[(e.CharBeforeSkillWithTarget = 53)] = "CharBeforeSkillWithTarget"),
      (e[(e.CharUseSkill = 54)] = "CharUseSkill"),
      (e[(e.OnSkillEnd = 55)] = "OnSkillEnd"),
      (e[(e.OnMultiSkillIdChanged = 56)] = "OnMultiSkillIdChanged"),
      (e[(e.OnMultiSkillEnable = 57)] = "OnMultiSkillEnable"),
      (e[(e.CharSwitchControl = 58)] = "CharSwitchControl"),
      (e[(e.CharInputPress = 59)] = "CharInputPress"),
      (e[(e.CharDeleteSkill = 60)] = "CharDeleteSkill"),
      (e[(e.CharResetSkill = 61)] = "CharResetSkill"),
      (e[(e.CharInterruptSkill = 62)] = "CharInterruptSkill"),
      (e[(e.CharSkillCountChanged = 63)] = "CharSkillCountChanged"),
      (e[(e.CharSkillRemainCdChanged = 64)] = "CharSkillRemainCdChanged"),
      (e[(e.CharSkillCdPauseStateChanged = 65)] =
        "CharSkillCdPauseStateChanged"),
      (e[(e.CharClearSkill = 66)] = "CharClearSkill"),
      (e[(e.CharDamage = 67)] = "CharDamage"),
      (e[(e.CharBeDamage = 68)] = "CharBeDamage"),
      (e[(e.FormationPanelUIShowRoleHeal = 69)] =
        "FormationPanelUIShowRoleHeal"),
      (e[(e.CharPartDamage = 70)] = "CharPartDamage"),
      (e[(e.CharClimbStartExit = 71)] = "CharClimbStartExit"),
      (e[(e.CharActivateClimbInput = 72)] = "CharActivateClimbInput"),
      (e[(e.CharClimbJumpCheck = 73)] = "CharClimbJumpCheck"),
      (e[(e.CustomMoveSwim = 74)] = "CustomMoveSwim"),
      (e[(e.CustomMoveSlide = 75)] = "CustomMoveSlide"),
      (e[(e.CustomMoveSki = 76)] = "CustomMoveSki"),
      (e[(e.CustomMoveWalkOnWater = 77)] = "CustomMoveWalkOnWater"),
      (e[(e.CustomMoveClimb = 78)] = "CustomMoveClimb"),
      (e[(e.CustomMoveGlide = 79)] = "CustomMoveGlide"),
      (e[(e.CustomMovePendulum = 80)] = "CustomMovePendulum"),
      (e[(e.CustomMoveCatapult = 81)] = "CustomMoveCatapult"),
      (e[(e.CustomMoveSoar = 82)] = "CustomMoveSoar"),
      (e[(e.CharTurnBegin = 83)] = "CharTurnBegin"),
      (e[(e.CharTurnEnd = 84)] = "CharTurnEnd"),
      (e[(e.CharMovementModeChanged = 85)] = "CharMovementModeChanged"),
      (e[(e.CharActivate = 86)] = "CharActivate"),
      (e[(e.CharOnAttrChanged = 87)] = "CharOnAttrChanged"),
      (e[(e.CharOnRoleDead = 88)] = "CharOnRoleDead"),
      (e[(e.CharOnRoleDeadTargetSelf = 89)] = "CharOnRoleDeadTargetSelf"),
      (e[(e.CharOnRoleDrown = 90)] = "CharOnRoleDrown"),
      (e[(e.CharOnRoleDrownInjure = 91)] = "CharOnRoleDrownInjure"),
      (e[(e.CharOnEnergyChanged = 92)] = "CharOnEnergyChanged"),
      (e[(e.CharOnHealthChanged = 93)] = "CharOnHealthChanged"),
      (e[(e.CharOnHealthMaxChanged = 94)] = "CharOnHealthMaxChanged"),
      (e[(e.CharOnElementEnergyChanged = 95)] = "CharOnElementEnergyChanged"),
      (e[(e.CharOnUnifiedMoveStateChanged = 96)] =
        "CharOnUnifiedMoveStateChanged"),
      (e[(e.CharOnPositionStateChanged = 97)] = "CharOnPositionStateChanged"),
      (e[(e.CharOnDirectionStateChanged = 98)] = "CharOnDirectionStateChanged"),
      (e[(e.CharOnPositionSubStateChanged = 99)] =
        "CharOnPositionSubStateChanged"),
      (e[(e.CharSwimStrengthChanged = 100)] = "CharSwimStrengthChanged"),
      (e[(e.RoleOnStateInherit = 101)] = "RoleOnStateInherit"),
      (e[(e.CharOnEndPlay = 102)] = "CharOnEndPlay"),
      (e[(e.CharOnBuffAddUITexture = 103)] = "CharOnBuffAddUITexture"),
      (e[(e.CharOnBuffAddUIPrefab = 104)] = "CharOnBuffAddUIPrefab"),
      (e[(e.CharOnBuffAddUIDamage = 105)] = "CharOnBuffAddUIDamage"),
      (e[(e.CharOnAnimNotifyStateDurationChange = 106)] =
        "CharOnAnimNotifyStateDurationChange"),
      (e[(e.CharOnLand = 107)] = "CharOnLand"),
      (e[(e.CharPossessed = 108)] = "CharPossessed"),
      (e[(e.CharUnpossessed = 109)] = "CharUnpossessed"),
      (e[(e.CharChangeMeshAnim = 110)] = "CharChangeMeshAnim"),
      (e[(e.CharRecordOperate = 111)] = "CharRecordOperate"),
      (e[(e.OnPlayerDead = 112)] = "OnPlayerDead"),
      (e[(e.OnOtherPlayerDead = 113)] = "OnOtherPlayerDead"),
      (e[(e.OnCharDeathLogicBegin = 114)] = "OnCharDeathLogicBegin"),
      (e[(e.CharRecordTeamDeath = 115)] = "CharRecordTeamDeath"),
      (e[(e.CharOnSetNewBeHit = 116)] = "CharOnSetNewBeHit"),
      (e[(e.OnBattleStateChanged = 117)] = "OnBattleStateChanged"),
      (e[(e.OnChangeWalkOrRun = 118)] = "OnChangeWalkOrRun"),
      (e[(e.CharOnRevive = 119)] = "CharOnRevive"),
      (e[(e.OnRevive = 120)] = "OnRevive"),
      (e[(e.AllRevive = 121)] = "AllRevive"),
      (e[(e.PlayerRevive = 122)] = "PlayerRevive"),
      (e[(e.CharOnFallInjure = 123)] = "CharOnFallInjure"),
      (e[(e.ChangeAiTeamLevel = 124)] = "ChangeAiTeamLevel"),
      (e[(e.AiHateAddOrRemove = 125)] = "AiHateAddOrRemove"),
      (e[(e.AiInFight = 126)] = "AiInFight"),
      (e[(e.AiHateTargetChanged = 127)] = "AiHateTargetChanged"),
      (e[(e.AiTauntAddOrRemove = 128)] = "AiTauntAddOrRemove"),
      (e[(e.AiTaskWanderForResetEnd = 129)] = "AiTaskWanderForResetEnd"),
      (e[(e.OnRunBehaviorTree = 130)] = "OnRunBehaviorTree"),
      (e[(e.OnAiEnable = 131)] = "OnAiEnable"),
      (e[(e.OnAiDisable = 132)] = "OnAiDisable"),
      (e[(e.CloseItemTips = 133)] = "CloseItemTips"),
      (e[(e.CreateRoleForwardAnimEnd = 134)] = "CreateRoleForwardAnimEnd"),
      (e[(e.CreateRoleShowInputName = 135)] = "CreateRoleShowInputName"),
      (e[(e.GuideFinish = 136)] = "GuideFinish"),
      (e[(e.GuideGroupOpening = 137)] = "GuideGroupOpening"),
      (e[(e.GuideGroupFinished = 138)] = "GuideGroupFinished"),
      (e[(e.GuideGroupBreak = 139)] = "GuideGroupBreak"),
      (e[(e.GuideGroupRest = 140)] = "GuideGroupRest"),
      (e[(e.GuideFocusNeedUiTabView = 141)] = "GuideFocusNeedUiTabView"),
      (e[(e.FinishGuideStepByEvent = 142)] = "FinishGuideStepByEvent"),
      (e[(e.GuideTouchIdInject = 143)] = "GuideTouchIdInject"),
      (e[(e.OnRefreshRoleHp = 144)] = "OnRefreshRoleHp"),
      (e[(e.BeforeLoadMap = 145)] = "BeforeLoadMap"),
      (e[(e.BeforeTravelMap = 146)] = "BeforeTravelMap"),
      (e[(e.EndTravelMap = 147)] = "EndTravelMap"),
      (e[(e.OnEnterTransitionMap = 148)] = "OnEnterTransitionMap"),
      (e[(e.AfterLoadMap = 149)] = "AfterLoadMap"),
      (e[(e.ClearWorld = 150)] = "ClearWorld"),
      (e[(e.WorldDone = 151)] = "WorldDone"),
      (e[(e.WorldDoneAndCloseLoading = 152)] = "WorldDoneAndCloseLoading"),
      (e[(e.ChangeMode = 153)] = "ChangeMode"),
      (e[(e.ChangeModeFinish = 154)] = "ChangeModeFinish"),
      (e[(e.ChangePerformanceLimitMode = 155)] = "ChangePerformanceLimitMode"),
      (e[(e.PauseGame = 156)] = "PauseGame"),
      (e[(e.OnChangeRole = 157)] = "OnChangeRole"),
      (e[(e.OnOtherChangeRole = 158)] = "OnOtherChangeRole"),
      (e[(e.OnChangeRoleCoolDownChanged = 159)] =
        "OnChangeRoleCoolDownChanged"),
      (e[(e.OnRoleGoDown = 160)] = "OnRoleGoDown"),
      (e[(e.OnRoleGoDownFinish = 161)] = "OnRoleGoDownFinish"),
      (e[(e.OnClearFollowData = 162)] = "OnClearFollowData"),
      (e[(e.InitArea = 163)] = "InitArea"),
      (e[(e.ChangeArea = 164)] = "ChangeArea"),
      (e[(e.UpdateAreaView = 165)] = "UpdateAreaView"),
      (e[(e.CreateEntity = 166)] = "CreateEntity"),
      (e[(e.CreateEntityFail = 167)] = "CreateEntityFail"),
      (e[(e.AddEntity = 168)] = "AddEntity"),
      (e[(e.FixBornLocation = 169)] = "FixBornLocation"),
      (e[(e.CharBornFinished = 170)] = "CharBornFinished"),
      (e[(e.PreloadEntityFinished = 171)] = "PreloadEntityFinished"),
      (e[(e.DelayRemoveEntityFinished = 172)] = "DelayRemoveEntityFinished"),
      (e[(e.RemoveEntity = 173)] = "RemoveEntity"),
      (e[(e.EntityOnLandedPush = 174)] = "EntityOnLandedPush"),
      (e[(e.SpawnBoss = 175)] = "SpawnBoss"),
      (e[(e.OnUpdateSceneTeam = 176)] = "OnUpdateSceneTeam"),
      (e[(e.OnRefreshItem = 177)] = "OnRefreshItem"),
      (e[(e.OnRemoveItem = 178)] = "OnRemoveItem"),
      (e[(e.OnItemDecompose = 179)] = "OnItemDecompose"),
      (e[(e.OnItemLock = 180)] = "OnItemLock"),
      (e[(e.OnGetReward = 181)] = "OnGetReward"),
      (e[(e.OnReceivePlayerVar = 182)] = "OnReceivePlayerVar"),
      (e[(e.OpenItemInfo = 183)] = "OpenItemInfo"),
      (e[(e.CloseItemInfo = 184)] = "CloseItemInfo"),
      (e[(e.BoughtItem = 185)] = "BoughtItem"),
      (e[(e.ShopUpdate = 186)] = "ShopUpdate"),
      (e[(e.OnShopInfoResponded = 187)] = "OnShopInfoResponded"),
      (e[(e.OnGoodUnlock = 188)] = "OnGoodUnlock"),
      (e[(e.SelectedMail = 189)] = "SelectedMail"),
      (e[(e.PickingAttachment = 190)] = "PickingAttachment"),
      (e[(e.DeletingMail = 191)] = "DeletingMail"),
      (e[(e.DeletingMailPassively = 192)] = "DeletingMailPassively"),
      (e[(e.AddingNewMail = 193)] = "AddingNewMail"),
      (e[(e.SwitchUnfinishedFlag = 194)] = "SwitchUnfinishedFlag"),
      (e[(e.CloseMailView = 195)] = "CloseMailView"),
      (e[(e.OnlyCloseMailContentView = 196)] = "OnlyCloseMailContentView"),
      (e[(e.BulletCreate = 197)] = "BulletCreate"),
      (e[(e.BulletDestroy = 198)] = "BulletDestroy"),
      (e[(e.BulletHit = 199)] = "BulletHit"),
      (e[(e.BulletRebound = 200)] = "BulletRebound"),
      (e[(e.BulletHitSpecialCharacter = 201)] = "BulletHitSpecialCharacter"),
      (e[(e.ScenePlayerChanged = 202)] = "ScenePlayerChanged"),
      (e[(e.ScenePlayerLocationChanged = 203)] = "ScenePlayerLocationChanged"),
      (e[(e.ScenePlayerLeaveScene = 204)] = "ScenePlayerLeaveScene"),
      (e[(e.ScenePlayerMarkItemStateChange = 205)] =
        "ScenePlayerMarkItemStateChange"),
      (e[(e.MatchTeamFlagChange = 206)] = "MatchTeamFlagChange"),
      (e[(e.LoadingViewProgressSequenceEnd = 207)] =
        "LoadingViewProgressSequenceEnd"),
      (e[(e.DestroyAllUiCameraAnimationHandles = 208)] =
        "DestroyAllUiCameraAnimationHandles"),
      (e[(e.RoleSelectionListUpdate = 209)] = "RoleSelectionListUpdate"),
      (e[(e.SelectRole = 210)] = "SelectRole"),
      (e[(e.SelectSkill = 211)] = "SelectSkill"),
      (e[(e.SelectLevelUpItemCount = 212)] = "SelectLevelUpItemCount"),
      (e[(e.SelectLevelUpItem = 213)] = "SelectLevelUpItem"),
      (e[(e.RoleInfoUpdate = 214)] = "RoleInfoUpdate"),
      (e[(e.RoleRefreshAttribute = 215)] = "RoleRefreshAttribute"),
      (e[(e.RoleSkillLevelUp = 216)] = "RoleSkillLevelUp"),
      (e[(e.RoleLevelUp = 217)] = "RoleLevelUp"),
      (e[(e.RoleLevelUpReceiveItem = 218)] = "RoleLevelUpReceiveItem"),
      (e[(e.RoleBreakUp = 219)] = "RoleBreakUp"),
      (e[(e.ActiveRole = 220)] = "ActiveRole"),
      (e[(e.RoleResonUplevel = 221)] = "RoleResonUplevel"),
      (e[(e.RoleResonActive = 222)] = "RoleResonActive"),
      (e[(e.RoleResonAnimationSuccess = 223)] = "RoleResonAnimationSuccess"),
      (e[(e.RoleResonPlayAnimation = 224)] = "RoleResonPlayAnimation"),
      (e[(e.CloseRoleView = 225)] = "CloseRoleView"),
      (e[(e.SelectedResonanceTab = 226)] = "SelectedResonanceTab"),
      (e[(e.UnSelectedResonanceTab = 227)] = "UnSelectedResonanceTab"),
      (e[(e.SwitchRootTabState = 228)] = "SwitchRootTabState"),
      (e[(e.RoleRefreshName = 229)] = "RoleRefreshName"),
      (e[(e.RoleSystemChangeRole = 230)] = "RoleSystemChangeRole"),
      (e[(e.OnSelectedRoleChanged = 231)] = "OnSelectedRoleChanged"),
      (e[(e.ChangeResonance = 232)] = "ChangeResonance"),
      (e[(e.OnRoleInternalViewEnter = 233)] = "OnRoleInternalViewEnter"),
      (e[(e.OnRoleInternalViewQuit = 234)] = "OnRoleInternalViewQuit"),
      (e[(e.AttributeComponentEvent = 235)] = "AttributeComponentEvent"),
      (e[(e.UpdateRoleLevelUpViewData = 236)] = "UpdateRoleLevelUpViewData"),
      (e[(e.UpdateRoleResonanceDetailView = 237)] =
        "UpdateRoleResonanceDetailView"),
      (e[(e.UpdateRoleSkillView = 238)] = "UpdateRoleSkillView"),
      (e[(e.UpdateRoleSkillLevelUpView = 239)] = "UpdateRoleSkillLevelUpView"),
      (e[(e.RefreshSkillTreeInfoTabView = 240)] =
        "RefreshSkillTreeInfoTabView"),
      (e[(e.SkillTreeRefresh = 241)] = "SkillTreeRefresh"),
      (e[(e.RefreshSkillTreeLeftSkillPoint = 242)] =
        "RefreshSkillTreeLeftSkillPoint"),
      (e[(e.SkillTreeReset = 243)] = "SkillTreeReset"),
      (e[(e.SkillTreeClickEmpty = 244)] = "SkillTreeClickEmpty"),
      (e[(e.SkillTreeNodeActive = 245)] = "SkillTreeNodeActive"),
      (e[(e.SkillTreeNodeLevelUp = 246)] = "SkillTreeNodeLevelUp"),
      (e[(e.UpdateSkillTreeInfoView = 247)] = "UpdateSkillTreeInfoView"),
      (e[(e.OnSkillTreeNodeToggleClick = 248)] = "OnSkillTreeNodeToggleClick"),
      (e[(e.UpdateRoleFavorData = 249)] = "UpdateRoleFavorData"),
      (e[(e.UnLockRoleFavorItem = 250)] = "UnLockRoleFavorItem"),
      (e[(e.RoleFavorExpChange = 251)] = "RoleFavorExpChange"),
      (e[(e.UpdateRoleFavorHintView = 252)] = "UpdateRoleFavorHintView"),
      (e[(e.RefreshFunctionOpenView = 253)] = "RefreshFunctionOpenView"),
      (e[(e.RoleFindFixHook = 254)] = "RoleFindFixHook"),
      (e[(e.UpdateRoleBreachView = 255)] = "UpdateRoleBreachView"),
      (e[(e.OnClickSkillLevelUp = 256)] = "OnClickSkillLevelUp"),
      (e[(e.OnClickSkillActive = 257)] = "OnClickSkillActive"),
      (e[(e.OnEnterOrExitUltraSkill = 258)] = "OnEnterOrExitUltraSkill"),
      (e[(e.WeaponLevelUp = 259)] = "WeaponLevelUp"),
      (e[(e.WeaponLevelUpReceiveItem = 260)] = "WeaponLevelUpReceiveItem"),
      (e[(e.WeaponCanGoBreach = 261)] = "WeaponCanGoBreach"),
      (e[(e.WeaponItemClick = 262)] = "WeaponItemClick"),
      (e[(e.WeaponEmptyClick = 263)] = "WeaponEmptyClick"),
      (e[(e.WeaponSortClick = 264)] = "WeaponSortClick"),
      (e[(e.WeaponMaterialPropClick = 265)] = "WeaponMaterialPropClick"),
      (e[(e.EquipWeapon = 266)] = "EquipWeapon"),
      (e[(e.ContrastWeapon = 267)] = "ContrastWeapon"),
      (e[(e.WeaponResonanceSuccess = 268)] = "WeaponResonanceSuccess"),
      (e[(e.ReConnectBegin = 269)] = "ReConnectBegin"),
      (e[(e.ReConnectFail = 270)] = "ReConnectFail"),
      (e[(e.CanNotReConnect = 271)] = "CanNotReConnect"),
      (e[(e.ReConnectSuccess = 272)] = "ReConnectSuccess"),
      (e[(e.BackLoginView = 273)] = "BackLoginView"),
      (e[(e.LogOut = 274)] = "LogOut"),
      (e[(e.ExitGamePush = 275)] = "ExitGamePush"),
      (e[(e.NetWorkMaskRpcAdd = 276)] = "NetWorkMaskRpcAdd"),
      (e[(e.NetWorkMaskRpcRemove = 277)] = "NetWorkMaskRpcRemove"),
      (e[(e.OnAimStateChanged = 278)] = "OnAimStateChanged"),
      (e[(e.OnPhantomInputDataUpdate = 279)] = "OnPhantomInputDataUpdate"),
      (e[(e.OpenDragonPoolView = 280)] = "OpenDragonPoolView"),
      (e[(e.UpdateDragonPoolView = 281)] = "UpdateDragonPoolView"),
      (e[(e.LoadMapTileFinish = 282)] = "LoadMapTileFinish"),
      (e[(e.MapOpenAreaChange = 283)] = "MapOpenAreaChange"),
      (e[(e.MapOpenAreaFullUpdate = 284)] = "MapOpenAreaFullUpdate"),
      (e[(e.WorldMapSecondaryUiClosed = 285)] = "WorldMapSecondaryUiClosed"),
      (e[(e.WorldMapSecondaryUiOpened = 286)] = "WorldMapSecondaryUiOpened"),
      (e[(e.BlackScreenFadeOnPlotToWorldMap = 287)] =
        "BlackScreenFadeOnPlotToWorldMap"),
      (e[(e.MarkMenuClickItem = 288)] = "MarkMenuClickItem"),
      (e[(e.RefreshMenuSetting = 289)] = "RefreshMenuSetting"),
      (e[(e.ModelReady = 290)] = "ModelReady"),
      (e[(e.MapReplaceMarkResponse = 291)] = "MapReplaceMarkResponse"),
      (e[(e.CreateMapMark = 292)] = "CreateMapMark"),
      (e[(e.RemoveMapMark = 293)] = "RemoveMapMark"),
      (e[(e.TrackMapMark = 294)] = "TrackMapMark"),
      (e[(e.UnlockTeleport = 295)] = "UnlockTeleport"),
      (e[(e.TrackMark = 296)] = "TrackMark"),
      (e[(e.UnTrackMark = 297)] = "UnTrackMark"),
      (e[(e.ClearTrackMark = 298)] = "ClearTrackMark"),
      (e[(e.MarkForceVisibleChanged = 299)] = "MarkForceVisibleChanged"),
      (e[(e.UpdateTrackTarget = 300)] = "UpdateTrackTarget"),
      (e[(e.SetTrackMarkOccupied = 301)] = "SetTrackMarkOccupied"),
      (e[(e.TeleportComplete = 302)] = "TeleportComplete"),
      (e[(e.TeleportStart = 303)] = "TeleportStart"),
      (e[(e.TeleportStartEntity = 304)] = "TeleportStartEntity"),
      (e[(e.OnEnterDailyQuestNotifyRange = 305)] =
        "OnEnterDailyQuestNotifyRange"),
      (e[(e.OnEnterNearbyTrackRange = 306)] = "OnEnterNearbyTrackRange"),
      (e[(e.OnLeaveNearbyTrackRange = 307)] = "OnLeaveNearbyTrackRange"),
      (e[(e.RemoveNearbyTrack = 308)] = "RemoveNearbyTrack"),
      (e[(e.UpdateNearbyTrackTag = 309)] = "UpdateNearbyTrackTag"),
      (e[(e.OnUpdateNearbyEnable = 310)] = "OnUpdateNearbyEnable"),
      (e[(e.WorldMapViewOpened = 311)] = "WorldMapViewOpened"),
      (e[(e.WorldMapPointerDown = 312)] = "WorldMapPointerDown"),
      (e[(e.WorldMapPointerDrag = 313)] = "WorldMapPointerDrag"),
      (e[(e.WorldMapJoystickMoveForward = 314)] =
        "WorldMapJoystickMoveForward"),
      (e[(e.WorldMapJoystickMoveRight = 315)] = "WorldMapJoystickMoveRight"),
      (e[(e.WorldMapJoystickFocusPlayer = 316)] =
        "WorldMapJoystickFocusPlayer"),
      (e[(e.WorldMapDragInertia = 317)] = "WorldMapDragInertia"),
      (e[(e.WorldMapPointerUp = 318)] = "WorldMapPointerUp"),
      (e[(e.WorldMapFingerExpandClose = 319)] = "WorldMapFingerExpandClose"),
      (e[(e.WorldMapWheelAxisInput = 320)] = "WorldMapWheelAxisInput"),
      (e[(e.WorldMapHandleTriggerAxisInput = 321)] =
        "WorldMapHandleTriggerAxisInput"),
      (e[(e.WorldMapScaleChanged = 322)] = "WorldMapScaleChanged"),
      (e[(e.WorldMapPositionChanged = 323)] = "WorldMapPositionChanged"),
      (e[(e.TaskRangeTrackStateChange = 324)] = "TaskRangeTrackStateChange"),
      (e[(e.RangeTrackStateChanged = 325)] = "RangeTrackStateChanged"),
      (e[(e.GetAreaProgress = 326)] = "GetAreaProgress"),
      (e[(e.PlaySoundTrackEffect = 327)] = "PlaySoundTrackEffect"),
      (e[(e.UpdatePlotSubtitle = 328)] = "UpdatePlotSubtitle"),
      (e[(e.ShowPlotSubtitleOptions = 329)] = "ShowPlotSubtitleOptions"),
      (e[(e.UpdatePlotCenterText = 330)] = "UpdatePlotCenterText"),
      (e[(e.UpdatePortraitVisible = 331)] = "UpdatePortraitVisible"),
      (e[(e.OnStartFlow = 332)] = "OnStartFlow"),
      (e[(e.PlotNetworkStart = 333)] = "PlotNetworkStart"),
      (e[(e.PlotNetworkEnd = 334)] = "PlotNetworkEnd"),
      (e[(e.PlotConfigChanged = 335)] = "PlotConfigChanged"),
      (e[(e.PlotDoingTextShow = 336)] = "PlotDoingTextShow"),
      (e[(e.ClearPlotSubtitle = 337)] = "ClearPlotSubtitle"),
      (e[(e.HidePlotUi = 338)] = "HidePlotUi"),
      (e[(e.PlotInteractViewOpen = 339)] = "PlotInteractViewOpen"),
      (e[(e.TriggerPlotInteraction = 340)] = "TriggerPlotInteraction"),
      (e[(e.TriggerBlackSequence = 341)] = "TriggerBlackSequence"),
      (e[(e.OnBlackFadeScreenStart = 342)] = "OnBlackFadeScreenStart"),
      (e[(e.OnBlackFadeScreenFinish = 343)] = "OnBlackFadeScreenFinish"),
      (e[(e.EnableSkipPlot = 344)] = "EnableSkipPlot"),
      (e[(e.PlotSequencePlay = 345)] = "PlotSequencePlay"),
      (e[(e.HangPlotViewHud = 346)] = "HangPlotViewHud"),
      (e[(e.UpdatePlotUiParam = 347)] = "UpdatePlotUiParam"),
      (e[(e.PlotViewChange = 348)] = "PlotViewChange"),
      (e[(e.PlotViewBgFadePhoto = 349)] = "PlotViewBgFadePhoto"),
      (e[(e.PlotViewBgFadeBlackScreen = 350)] = "PlotViewBgFadeBlackScreen"),
      (e[(e.PlotStartShowTalk = 351)] = "PlotStartShowTalk"),
      (e[(e.PlotEndShowTalk = 352)] = "PlotEndShowTalk"),
      (e[(e.PrewarFormationChanged = 353)] = "PrewarFormationChanged"),
      (e[(e.PrewarReadyChanged = 354)] = "PrewarReadyChanged"),
      (e[(e.DissolvePrewar = 355)] = "DissolvePrewar"),
      (e[(e.SceneStepGroupChanged = 356)] = "SceneStepGroupChanged"),
      (e[(e.InstanceStepChanged = 357)] = "InstanceStepChanged"),
      (e[(e.InstanceEnterCountChanged = 358)] = "InstanceEnterCountChanged"),
      (e[(e.InstanceEntranceUnlock = 359)] = "InstanceEntranceUnlock"),
      (e[(e.EnterInstanceDungeon = 360)] = "EnterInstanceDungeon"),
      (e[(e.LeaveInstanceDungeon = 361)] = "LeaveInstanceDungeon"),
      (e[(e.DungeonGuideChange = 362)] = "DungeonGuideChange"),
      (e[(e.LeaveInstanceDungeonConfirm = 363)] =
        "LeaveInstanceDungeonConfirm"),
      (e[(e.OpenOnlineInstanceDeath = 364)] = "OpenOnlineInstanceDeath"),
      (e[(e.OnDungeonFinish = 365)] = "OnDungeonFinish"),
      (e[(e.OnRefreshEditBattleRoleSlotData = 366)] =
        "OnRefreshEditBattleRoleSlotData"),
      (e[(e.OnRefreshEditBattleRoleReady = 367)] =
        "OnRefreshEditBattleRoleReady"),
      (e[(e.EntityVisionSkillChanged = 368)] = "EntityVisionSkillChanged"),
      (e[(e.GetAllVisionSkill = 369)] = "GetAllVisionSkill"),
      (e[(e.VisionSkillUp = 370)] = "VisionSkillUp"),
      (e[(e.ExploreVisionSkill = 371)] = "ExploreVisionSkill"),
      (e[(e.VisionMorphBegin = 372)] = "VisionMorphBegin"),
      (e[(e.AddExploreVisionSkill = 373)] = "AddExploreVisionSkill"),
      (e[(e.ChangeVisionSkillByTab = 374)] = "ChangeVisionSkillByTab"),
      (e[(e.ChangeVisionSimplyState = 375)] = "ChangeVisionSimplyState"),
      (e[(e.VisionSkinViewClose = 376)] = "VisionSkinViewClose"),
      (e[(e.ChangeCalabashCollectSimplyState = 377)] =
        "ChangeCalabashCollectSimplyState"),
      (e[(e.SelectedPhantom = 378)] = "SelectedPhantom"),
      (e[(e.CheckNewUnlock = 379)] = "CheckNewUnlock"),
      (e[(e.PhantomEquip = 380)] = "PhantomEquip"),
      (e[(e.PhantomEquipError = 381)] = "PhantomEquipError"),
      (e[(e.VisionFilterMonster = 382)] = "VisionFilterMonster"),
      (e[(e.OnRolePropUpdate = 383)] = "OnRolePropUpdate"),
      (e[(e.RefreshVisionIntensifyViewBackBtnState = 384)] =
        "RefreshVisionIntensifyViewBackBtnState"),
      (e[(e.OnClickVisionIntensifyItemJump = 385)] =
        "OnClickVisionIntensifyItemJump"),
      (e[(e.VisionIntensifyTabOpen = 386)] = "VisionIntensifyTabOpen"),
      (e[(e.PhantomPersonalSkillActive = 387)] = "PhantomPersonalSkillActive"),
      (e[(e.PhantomEquipWithSourceAndTargetPos = 388)] =
        "PhantomEquipWithSourceAndTargetPos"),
      (e[(e.PhantomCostInsufficient = 389)] = "PhantomCostInsufficient"),
      (e[(e.PhantomExpPreviewChange = 390)] = "PhantomExpPreviewChange"),
      (e[(e.PhantomLevelUp = 391)] = "PhantomLevelUp"),
      (e[(e.PhantomLevelUpWithId = 392)] = "PhantomLevelUpWithId"),
      (e[(e.PhantomLevelUpReceiveItem = 393)] = "PhantomLevelUpReceiveItem"),
      (e[(e.CloseSubPhantomView = 394)] = "CloseSubPhantomView"),
      (e[(e.PhantomBreach = 395)] = "PhantomBreach"),
      (e[(e.PhantomBreachPreview = 396)] = "PhantomBreachPreview"),
      (e[(e.PhantomDecomposePreview = 397)] = "PhantomDecomposePreview"),
      (e[(e.PhantomDecompose = 398)] = "PhantomDecompose"),
      (e[(e.PhantomMaxLevelSkip = 399)] = "PhantomMaxLevelSkip"),
      (e[(e.HideDelFettersText = 400)] = "HideDelFettersText"),
      (e[(e.PhantomRecommendResponse = 401)] = "PhantomRecommendResponse"),
      (e[(e.ClosePhantomSkillTips = 402)] = "ClosePhantomSkillTips"),
      (e[(e.OnPhantomItemUpdate = 403)] = "OnPhantomItemUpdate"),
      (e[(e.OnPhantomSlotUpdate = 404)] = "OnPhantomSlotUpdate"),
      (e[(e.OnVisionIdentify = 405)] = "OnVisionIdentify"),
      (e[(e.OnVisionIdentifyWithId = 406)] = "OnVisionIdentifyWithId"),
      (e[(e.OnVisionIdentifyDoAnimation = 407)] =
        "OnVisionIdentifyDoAnimation"),
      (e[(e.RefreshVisionIdentifyRedPoint = 408)] =
        "RefreshVisionIdentifyRedPoint"),
      (e[(e.RefreshVisionEquipRedPoint = 409)] = "RefreshVisionEquipRedPoint"),
      (e[(e.JumpToCalabashCollect = 410)] = "JumpToCalabashCollect"),
      (e[(e.JumpToPhantomBattleFettersTabView = 411)] =
        "JumpToPhantomBattleFettersTabView"),
      (e[(e.OnVisionSkinEquip = 412)] = "OnVisionSkinEquip"),
      (e[(e.RedDotRefreshCalabash = 413)] = "RedDotRefreshCalabash"),
      (e[(e.HasCalabashExp = 414)] = "HasCalabashExp"),
      (e[(e.CloseUpgradeCalabashView = 415)] = "CloseUpgradeCalabashView"),
      (e[(e.CloseCalabashExpAddView = 416)] = "CloseCalabashExpAddView"),
      (e[(e.ShowCalabashControllerView = 417)] = "ShowCalabashControllerView"),
      (e[(e.GetCalabashRewardSuccess = 418)] = "GetCalabashRewardSuccess"),
      (e[(e.ShowCalabashUnlockItemTips = 419)] = "ShowCalabashUnlockItemTips"),
      (e[(e.GetCalabashReward = 420)] = "GetCalabashReward"),
      (e[(e.CalabashLevelUpdate = 421)] = "CalabashLevelUpdate"),
      (e[(e.CalabashEnterInternalView = 422)] = "CalabashEnterInternalView"),
      (e[(e.CalabashQuitInternalView = 423)] = "CalabashQuitInternalView"),
      (e[(e.OnVisionRecoveryResult = 424)] = "OnVisionRecoveryResult"),
      (e[(e.OnRefreshCalabashTabShowState = 425)] =
        "OnRefreshCalabashTabShowState"),
      (e[(e.OnSetPartStateVisible = 426)] = "OnSetPartStateVisible"),
      (e[(e.OnPlatformChanged = 427)] = "OnPlatformChanged"),
      (e[(e.ShowHUD = 428)] = "ShowHUD"),
      (e[(e.HideHUD = 429)] = "HideHUD"),
      (e[(e.OnGetPlayerBasicInfo = 430)] = "OnGetPlayerBasicInfo"),
      (e[(e.OnPlayerLevelChanged = 431)] = "OnPlayerLevelChanged"),
      (e[(e.OnPlayerExpChanged = 432)] = "OnPlayerExpChanged"),
      (e[(e.OnLevelUpLevelRefresh = 433)] = "OnLevelUpLevelRefresh"),
      (e[(e.OnLevelUpExpRefresh = 434)] = "OnLevelUpExpRefresh"),
      (e[(e.OnLevelUpShowLevelOnly = 435)] = "OnLevelUpShowLevelOnly"),
      (e[(e.SelectFilterMultiple = 436)] = "SelectFilterMultiple"),
      (e[(e.SelectFilterSingle = 437)] = "SelectFilterSingle"),
      (e[(e.SelectSort = 438)] = "SelectSort"),
      (e[(e.OnSceneItemHit = 439)] = "OnSceneItemHit"),
      (e[(e.OnSceneItemHitByHitData = 440)] = "OnSceneItemHitByHitData"),
      (e[(e.OnSceneItemEntityHit = 441)] = "OnSceneItemEntityHit"),
      (e[(e.OnSceneItemEntityHitAlways = 442)] = "OnSceneItemEntityHitAlways"),
      (e[(e.OnAnySceneItemEntityHit = 443)] = "OnAnySceneItemEntityHit"),
      (e[(e.OnAnySceneItemDurabilityChange = 444)] =
        "OnAnySceneItemDurabilityChange"),
      (e[(e.OnSceneItemDurabilityChange = 445)] =
        "OnSceneItemDurabilityChange"),
      (e[(e.UpdateSceneItemState = 446)] = "UpdateSceneItemState"),
      (e[(e.OnSceneItemDestroy = 447)] = "OnSceneItemDestroy"),
      (e[(e.OnSceneItemStateChange = 448)] = "OnSceneItemStateChange"),
      (e[(e.OnSceneItemStatePreChange = 449)] = "OnSceneItemStatePreChange"),
      (e[(e.OnSceneItemStatePrechangeInSequence = 450)] =
        "OnSceneItemStatePrechangeInSequence"),
      (e[(e.OnEntityConcealedChange = 451)] = "OnEntityConcealedChange"),
      (e[(e.OnTimeTrackControlUpdate = 452)] = "OnTimeTrackControlUpdate"),
      (e[(e.OnSceneInteractionLoadCompleted = 453)] =
        "OnSceneInteractionLoadCompleted"),
      (e[(e.OnSceneItemVisionCaptureAdd = 454)] =
        "OnSceneItemVisionCaptureAdd"),
      (e[(e.OnSceneItemVisionCaptureRemove = 455)] =
        "OnSceneItemVisionCaptureRemove"),
      (e[(e.OnInputDistributeTagChanged = 456)] =
        "OnInputDistributeTagChanged"),
      (e[(e.ForceReleaseInput = 457)] = "ForceReleaseInput"),
      (e[(e.OnFormationPlayLevelUp = 458)] = "OnFormationPlayLevelUp"),
      (e[(e.OnFormationPlayRevive = 459)] = "OnFormationPlayRevive"),
      (e[(e.OnItemUse = 460)] = "OnItemUse"),
      (e[(e.OnSpecialItemUse = 461)] = "OnSpecialItemUse"),
      (e[(e.OnGameplayTagChanged = 462)] = "OnGameplayTagChanged"),
      (e[(e.OnLevelTagChanged = 463)] = "OnLevelTagChanged"),
      (e[(e.OnGlobalGameplayTagChanged = 464)] = "OnGlobalGameplayTagChanged"),
      (e[(e.LevelEventTriggerExit = 465)] = "LevelEventTriggerExit"),
      (e[(e.OnLevelPlayStateChange = 466)] = "OnLevelPlayStateChange"),
      (e[(e.TodTimeChange = 467)] = "TodTimeChange"),
      (e[(e.DayStateChange = 468)] = "DayStateChange"),
      (e[(e.CrossDay = 469)] = "CrossDay"),
      (e[(e.ClickTimeItem = 470)] = "ClickTimeItem"),
      (e[(e.OnSelectTimeItem = 471)] = "OnSelectTimeItem"),
      (e[(e.AdjustTime = 472)] = "AdjustTime"),
      (e[(e.AdjustTimeInAnim = 473)] = "AdjustTimeInAnim"),
      (e[(e.PowerShopReady = 474)] = "PowerShopReady"),
      (e[(e.OnPowerChanged = 475)] = "OnPowerChanged"),
      (e[(e.OnPowerCountDownChanged = 476)] = "OnPowerCountDownChanged"),
      (e[(e.OnGamePlayCdChanged = 477)] = "OnGamePlayCdChanged"),
      (e[(e.InsertFloatTips = 478)] = "InsertFloatTips"),
      (e[(e.OriginWorldLevelUp = 479)] = "OriginWorldLevelUp"),
      (e[(e.CurWorldLevelChange = 480)] = "CurWorldLevelChange"),
      (e[(e.WorldLevelUpViewRefresh = 481)] = "WorldLevelUpViewRefresh"),
      (e[(e.OnShowMouseCursor = 482)] = "OnShowMouseCursor"),
      (e[(e.RefreshCursor = 483)] = "RefreshCursor"),
      (e[(e.InputDistribute = 484)] = "InputDistribute"),
      (e[(e.OnRefreshJoinTeamRole = 485)] = "OnRefreshJoinTeamRole"),
      (e[(e.LoadLguiEventSystemActor = 486)] = "LoadLguiEventSystemActor"),
      (e[(e.DestroyLguiEventSystemActor = 487)] =
        "DestroyLguiEventSystemActor"),
      (e[(e.OnUseBuffItem = 488)] = "OnUseBuffItem"),
      (e[(e.UpdateQuestDetails = 489)] = "UpdateQuestDetails"),
      (e[(e.UpdateRoleQuestDetails = 490)] = "UpdateRoleQuestDetails"),
      (e[(e.QuestUpdateInfoAdd = 491)] = "QuestUpdateInfoAdd"),
      (e[(e.AddInteractOptionByAction = 492)] = "AddInteractOptionByAction"),
      (e[(e.RemoveInteractOptionByAction = 493)] =
        "RemoveInteractOptionByAction"),
      (e[(e.OnQuestStateChange = 494)] = "OnQuestStateChange"),
      (e[(e.OnQuestRedDotStateChange = 495)] = "OnQuestRedDotStateChange"),
      (e[(e.OnQuestFinishProtocolEnd = 496)] = "OnQuestFinishProtocolEnd"),
      (e[(e.OnRoleQuestAccept = 497)] = "OnRoleQuestAccept"),
      (e[(e.OnRoleQuestPointChange = 498)] = "OnRoleQuestPointChange"),
      (e[(e.OnRoleQuestNewUnlock = 499)] = "OnRoleQuestNewUnlock"),
      (e[(e.OnAddNewQuest = 500)] = "OnAddNewQuest"),
      (e[(e.OnNavigationQuest = 501)] = "OnNavigationQuest"),
      (e[(e.ActivityQuestCountdownEnd = 502)] = "ActivityQuestCountdownEnd"),
      (e[(e.GeneralLogicTreeWakeUp = 503)] = "GeneralLogicTreeWakeUp"),
      (e[(e.OnLogicTreeNodeStatusChange = 504)] =
        "OnLogicTreeNodeStatusChange"),
      (e[(e.OnLogicTreeChildQuestNodeStatusChange = 505)] =
        "OnLogicTreeChildQuestNodeStatusChange"),
      (e[(e.OnLogicTreeNodeProgressChange = 506)] =
        "OnLogicTreeNodeProgressChange"),
      (e[(e.GeneralLogicTreeTimerInfoChanged = 507)] =
        "GeneralLogicTreeTimerInfoChanged"),
      (e[(e.OnLogicTreeTrackUpdate = 508)] = "OnLogicTreeTrackUpdate"),
      (e[(e.CurTrackQuestUnTrackedCheck = 509)] =
        "CurTrackQuestUnTrackedCheck"),
      (e[(e.OnLogicTreeTimerTick = 510)] = "OnLogicTreeTimerTick"),
      (e[(e.GeneralLogicTreeStartShowTrackText = 511)] =
        "GeneralLogicTreeStartShowTrackText"),
      (e[(e.GeneralLogicTreeUpdateShowTrackText = 512)] =
        "GeneralLogicTreeUpdateShowTrackText"),
      (e[(e.GeneralLogicTreeEndShowTrackText = 513)] =
        "GeneralLogicTreeEndShowTrackText"),
      (e[(e.GeneralLogicTreeRemove = 514)] = "GeneralLogicTreeRemove"),
      (e[(e.GeneralLogicTreeSuspend = 515)] = "GeneralLogicTreeSuspend"),
      (e[(e.GeneralLogicTreeCancelSuspend = 516)] =
        "GeneralLogicTreeCancelSuspend"),
      (e[(e.GeneralLogicTreeRemovePrepareRollbackNode = 517)] =
        "GeneralLogicTreeRemovePrepareRollbackNode"),
      (e[(e.GeneralLogicTreeRollbackWaitingUpdate = 518)] =
        "GeneralLogicTreeRollbackWaitingUpdate"),
      (e[(e.GeneralLogicTreeEntityInteractFinished = 519)] =
        "GeneralLogicTreeEntityInteractFinished"),
      (e[(e.GeneralLogicTreeEntityKilled = 520)] =
        "GeneralLogicTreeEntityKilled"),
      (e[(e.GeneralLogicTreeAddTag = 521)] = "GeneralLogicTreeAddTag"),
      (e[(e.GeneralLogicTreeRemoveTag = 522)] = "GeneralLogicTreeRemoveTag"),
      (e[(e.GeneralLogicTreeViewForceRefresh = 523)] =
        "GeneralLogicTreeViewForceRefresh"),
      (e[(e.GeneralLogicTreeApplyExpressionOccupation = 524)] =
        "GeneralLogicTreeApplyExpressionOccupation"),
      (e[(e.GeneralLogicTreeReleaseExpressionOccupation = 525)] =
        "GeneralLogicTreeReleaseExpressionOccupation"),
      (e[(e.MissionPanelProcessEnd = 526)] = "MissionPanelProcessEnd"),
      (e[(e.QuestUpdateTipsClickTrack = 527)] = "QuestUpdateTipsClickTrack"),
      (e[(e.MissionPanelOut = 528)] = "MissionPanelOut"),
      (e[(e.MissionUpdate = 529)] = "MissionUpdate"),
      (e[(e.MissionUpdateAnimEnd = 530)] = "MissionUpdateAnimEnd"),
      (e[(e.MissionPanelStepTitleAnimStart = 531)] =
        "MissionPanelStepTitleAnimStart"),
      (e[(e.MissionPanelStepTitleAnimEnd = 532)] =
        "MissionPanelStepTitleAnimEnd"),
      (e[(e.ParkourFinished = 533)] = "ParkourFinished"),
      (e[(e.OnOpenDebugCommand = 534)] = "OnOpenDebugCommand"),
      (e[(e.ResetToBattleView = 535)] = "ResetToBattleView"),
      (e[(e.ResetModuleByResetToBattleView = 536)] =
        "ResetModuleByResetToBattleView"),
      (e[(e.ExitNormalQueueState = 537)] = "ExitNormalQueueState"),
      (e[(e.OnStartLoadingState = 538)] = "OnStartLoadingState"),
      (e[(e.OnFinishLoadingState = 539)] = "OnFinishLoadingState"),
      (e[(e.OnOpenLoadingView = 540)] = "OnOpenLoadingView"),
      (e[(e.OnCloseLoadingView = 541)] = "OnCloseLoadingView"),
      (e[(e.OnLoadingNetDataDone = 542)] = "OnLoadingNetDataDone"),
      (e[(e.PlayUiComponentCloseTween = 543)] = "PlayUiComponentCloseTween"),
      (e[(e.ChangeUiComponentMarkId = 544)] = "ChangeUiComponentMarkId"),
      (e[(e.ChangeConfigValue = 545)] = "ChangeConfigValue"),
      (e[(e.OnMenuDataEnableChanged = 546)] = "OnMenuDataEnableChanged"),
      (e[(e.RestartFlag = 547)] = "RestartFlag"),
      (e[(e.SettingFrameRateChanged = 548)] = "SettingFrameRateChanged"),
      (e[(e.TextLanguageChange = 549)] = "TextLanguageChange"),
      (e[(e.ConfigLoadChange = 550)] = "ConfigLoadChange"),
      (e[(e.SneakResult = 551)] = "SneakResult"),
      (e[(e.SneakMonsterStart = 552)] = "SneakMonsterStart"),
      (e[(e.SneakMonsterStop = 553)] = "SneakMonsterStop"),
      (e[(e.ChannelReset = 554)] = "ChannelReset"),
      (e[(e.OnShareResult = 555)] = "OnShareResult"),
      (e[(e.OnFirstShare = 556)] = "OnFirstShare"),
      (e[(e.ShowVideo = 557)] = "ShowVideo"),
      (e[(e.VideoStart = 558)] = "VideoStart"),
      (e[(e.PlayVideo = 559)] = "PlayVideo"),
      (e[(e.ScanTrackedStart = 560)] = "ScanTrackedStart"),
      (e[(e.ScanTrackedEnd = 561)] = "ScanTrackedEnd"),
      (e[(e.OnScanStart = 562)] = "OnScanStart"),
      (e[(e.RedDotStart = 563)] = "RedDotStart"),
      (e[(e.RedDotRefreshItemData = 564)] = "RedDotRefreshItemData"),
      (e[(e.RedDotRoleConfigList = 565)] = "RedDotRoleConfigList"),
      (e[(e.RedDotRefreshPhantomEquip = 566)] = "RedDotRefreshPhantomEquip"),
      (e[(e.RedDotRoleChange = 567)] = "RedDotRoleChange"),
      (e[(e.RedDotUnLockPhantom = 568)] = "RedDotUnLockPhantom"),
      (e[(e.RedDotNewTutorial = 569)] = "RedDotNewTutorial"),
      (e[(e.RedDotNewTutorialType = 570)] = "RedDotNewTutorialType"),
      (e[(e.RedDotAdventureManualUpdate = 571)] =
        "RedDotAdventureManualUpdate"),
      (e[(e.RedDotSilentFirstAward = 572)] = "RedDotSilentFirstAward"),
      (e[(e.RedDotSilentFirstAwardCategory = 573)] =
        "RedDotSilentFirstAwardCategory"),
      (e[(e.RedDotSilentFirstAwardResult = 574)] =
        "RedDotSilentFirstAwardResult"),
      (e[(e.RedDotCreateRole = 575)] = "RedDotCreateRole"),
      (e[(e.SilentTipsRefresh = 576)] = "SilentTipsRefresh"),
      (e[(e.OnRefreshElementBallData = 577)] = "OnRefreshElementBallData"),
      (e[(e.ShootTargetStateChanged = 578)] = "ShootTargetStateChanged"),
      (e[(e.InteractNavigation = 579)] = "InteractNavigation"),
      (e[(e.InteractionViewUpdate = 580)] = "InteractionViewUpdate"),
      (e[(e.HideInteractView = 581)] = "HideInteractView"),
      (e[(e.SceneItemInteractionEvent = 582)] = "SceneItemInteractionEvent"),
      (e[(e.OnFunctionOpenSet = 583)] = "OnFunctionOpenSet"),
      (e[(e.OnFunctionOpenUpdate = 584)] = "OnFunctionOpenUpdate"),
      (e[(e.OnFunctionOpenUpdateNotify = 585)] = "OnFunctionOpenUpdateNotify"),
      (e[(e.OnConcertoResponseOpen = 586)] = "OnConcertoResponseOpen"),
      (e[(e.OnFirstOpenShopChanged = 587)] = "OnFirstOpenShopChanged"),
      (e[(e.OnSetHeadStateVisible = 588)] = "OnSetHeadStateVisible"),
      (e[(e.OnSetBossStateVisible = 589)] = "OnSetBossStateVisible"),
      (e[(e.SdkKick = 590)] = "SdkKick"),
      (e[(e.SdkPostWebViewRedPointRefresh = 591)] =
        "SdkPostWebViewRedPointRefresh"),
      (e[(e.SdkCustomerRedPointRefresh = 592)] = "SdkCustomerRedPointRefresh"),
      (e[(e.UpdateFriendViewShow = 593)] = "UpdateFriendViewShow"),
      (e[(e.UpdateRecentlyTeamDataEvent = 594)] =
        "UpdateRecentlyTeamDataEvent"),
      (e[(e.OnRemoveFriend = 595)] = "OnRemoveFriend"),
      (e[(e.FriendApplicationListUpdate = 596)] =
        "FriendApplicationListUpdate"),
      (e[(e.UpdateBlackListShow = 597)] = "UpdateBlackListShow"),
      (e[(e.SearchPlayerInfo = 598)] = "SearchPlayerInfo"),
      (e[(e.FriendRemarkLengthLimit = 599)] = "FriendRemarkLengthLimit"),
      (e[(e.FriendRemarkContainsDirtyWord = 600)] =
        "FriendRemarkContainsDirtyWord"),
      (e[(e.RefreshFriendApplicationRedDot = 601)] =
        "RefreshFriendApplicationRedDot"),
      (e[(e.LoadTestFriendsByGm = 602)] = "LoadTestFriendsByGm"),
      (e[(e.ApplicationHandled = 603)] = "ApplicationHandled"),
      (e[(e.ApplicationSent = 604)] = "ApplicationSent"),
      (e[(e.OnGetFriendInitData = 605)] = "OnGetFriendInitData"),
      (e[(e.OnNavigationViewUiCreated = 606)] = "OnNavigationViewUiCreated"),
      (e[(e.OnUiNavigationViewSetActive = 607)] =
        "OnUiNavigationViewSetActive"),
      (e[(e.InputControllerChange = 608)] = "InputControllerChange"),
      (e[(e.PointerInputTypeChange = 609)] = "PointerInputTypeChange"),
      (e[(e.ChangeScrollBarPosition = 610)] = "ChangeScrollBarPosition"),
      (e[(e.OnSelectChatFriend = 611)] = "OnSelectChatFriend"),
      (e[(e.OnCreatePrivateChatRoom = 612)] = "OnCreatePrivateChatRoom"),
      (e[(e.OnJoinChatRoom = 613)] = "OnJoinChatRoom"),
      (e[(e.OnAddChatContent = 614)] = "OnAddChatContent"),
      (e[(e.OnRefreshChatRedDot = 615)] = "OnRefreshChatRedDot"),
      (e[(e.OnRefreshChatRoomRedDot = 616)] = "OnRefreshChatRoomRedDot"),
      (e[(e.OnAddHistoryChatContentCompleted = 617)] =
        "OnAddHistoryChatContentCompleted"),
      (e[(e.OnPushChatRowData = 618)] = "OnPushChatRowData"),
      (e[(e.OnPopChatRowData = 619)] = "OnPopChatRowData"),
      (e[(e.OnRefreshChatRowData = 620)] = "OnRefreshChatRowData"),
      (e[(e.OnAddMutePlayer = 621)] = "OnAddMutePlayer"),
      (e[(e.OnRemoveMutePlayer = 622)] = "OnRemoveMutePlayer"),
      (e[(e.OnRemovePrivateChatRoom = 623)] = "OnRemovePrivateChatRoom"),
      (e[(e.OnClosePrivateChatRoom = 624)] = "OnClosePrivateChatRoom"),
      (e[(e.OnOpenChatRoom = 625)] = "OnOpenChatRoom"),
      (e[(e.OnSelectExpression = 626)] = "OnSelectExpression"),
      (e[(e.OnServerAttributeChange = 627)] = "OnServerAttributeChange"),
      (e[(e.OnPayItemSuccess = 628)] = "OnPayItemSuccess"),
      (e[(e.RefreshPayItemList = 629)] = "RefreshPayItemList"),
      (e[(e.RefreshPayGiftList = 630)] = "RefreshPayGiftList"),
      (e[(e.OnPlayerCurrencyChange = 631)] = "OnPlayerCurrencyChange"),
      (e[(e.OnRefreshPermissionsSetting = 632)] =
        "OnRefreshPermissionsSetting"),
      (e[(e.OnRefreshApply = 633)] = "OnRefreshApply"),
      (e[(e.OnSearchWorld = 634)] = "OnSearchWorld"),
      (e[(e.OnRefreshWorldList = 635)] = "OnRefreshWorldList"),
      (e[(e.OnRefreshOnlineTeamList = 636)] = "OnRefreshOnlineTeamList"),
      (e[(e.OnWorldTeamPlayerInfoChanged = 637)] =
        "OnWorldTeamPlayerInfoChanged"),
      (e[(e.OnRefreshPlayerPing = 638)] = "OnRefreshPlayerPing"),
      (e[(e.OnRefreshPlayerUiState = 639)] = "OnRefreshPlayerUiState"),
      (e[(e.SwitchPayShopTabItem = 640)] = "SwitchPayShopTabItem"),
      (e[(e.PayShopGoodsBuy = 641)] = "PayShopGoodsBuy"),
      (e[(e.GoodsRefreshDiscountTime = 642)] = "GoodsRefreshDiscountTime"),
      (e[(e.SwitchPayShopView = 643)] = "SwitchPayShopView"),
      (e[(e.RefreshPayShop = 644)] = "RefreshPayShop"),
      (e[(e.RefreshAllPayShop = 645)] = "RefreshAllPayShop"),
      (e[(e.RefreshGoods = 646)] = "RefreshGoods"),
      (e[(e.ShopVersionCodeChange = 647)] = "ShopVersionCodeChange"),
      (e[(e.GoodsSoldOut = 648)] = "GoodsSoldOut"),
      (e[(e.RefreshGoodsList = 649)] = "RefreshGoodsList"),
      (e[(e.UnLockGoods = 650)] = "UnLockGoods"),
      (e[(e.DiscountShopTimerRefresh = 651)] = "DiscountShopTimerRefresh"),
      (e[(e.OnOpenGachaChanged = 652)] = "OnOpenGachaChanged"),
      (e[(e.RefreshGachaMainView = 653)] = "RefreshGachaMainView"),
      (e[(e.GachaPoolSelectResponse = 654)] = "GachaPoolSelectResponse"),
      (e[(e.GachaResponse = 655)] = "GachaResponse"),
      (e[(e.GachaHistoryResponse = 656)] = "GachaHistoryResponse"),
      (e[(e.CloseGachaSceneView = 657)] = "CloseGachaSceneView"),
      (e[(e.EndGachaScene = 658)] = "EndGachaScene"),
      (e[(e.GachaClick = 659)] = "GachaClick"),
      (e[(e.GachaSelectionViewRefresh = 660)] = "GachaSelectionViewRefresh"),
      (e[(e.AfterCloseGachaScene = 661)] = "AfterCloseGachaScene"),
      (e[(e.PlaySequenceEventByStringParam = 662)] =
        "PlaySequenceEventByStringParam"),
      (e[(e.GachaInteractFinish = 663)] = "GachaInteractFinish"),
      (e[(e.ItemExChangeResponse = 664)] = "ItemExChangeResponse"),
      (e[(e.ItemHintVisibilityChange = 665)] = "ItemHintVisibilityChange"),
      (e[(e.ShowAnimalsHeadInfo = 666)] = "ShowAnimalsHeadInfo"),
      (e[(e.OnAnimalDying = 667)] = "OnAnimalDying"),
      (e[(e.OnSkillButtonDataRefresh = 668)] = "OnSkillButtonDataRefresh"),
      (e[(e.OnSkillButtonDataClear = 669)] = "OnSkillButtonDataClear"),
      (e[(e.OnSkillButtonIndexRefresh = 670)] = "OnSkillButtonIndexRefresh"),
      (e[(e.OnSkillButtonEnableRefresh = 671)] = "OnSkillButtonEnableRefresh"),
      (e[(e.OnSkillButtonVisibleRefresh = 672)] =
        "OnSkillButtonVisibleRefresh"),
      (e[(e.OnSkillButtonSkillIdRefresh = 673)] =
        "OnSkillButtonSkillIdRefresh"),
      (e[(e.OnSkillButtonDynamicEffectRefresh = 674)] =
        "OnSkillButtonDynamicEffectRefresh"),
      (e[(e.OnSkillButtonCdRefresh = 675)] = "OnSkillButtonCdRefresh"),
      (e[(e.OnSkillButtonAttributeRefresh = 676)] =
        "OnSkillButtonAttributeRefresh"),
      (e[(e.OnSkillButtonIconPathRefresh = 677)] =
        "OnSkillButtonIconPathRefresh"),
      (e[(e.OnBehaviorButtonVisibleRefresh = 678)] =
        "OnBehaviorButtonVisibleRefresh"),
      (e[(e.OnInputChangeForCond = 679)] = "OnInputChangeForCond"),
      (e[(e.OnGetNewItem = 680)] = "OnGetNewItem"),
      (e[(e.OnElementFusion = 681)] = "OnElementFusion"),
      (e[(e.OnChangeSelectedExploreId = 682)] = "OnChangeSelectedExploreId"),
      (e[(e.OnRouletteViewVisibleChanged = 683)] =
        "OnRouletteViewVisibleChanged"),
      (e[(e.OnRouletteItemSelect = 684)] = "OnRouletteItemSelect"),
      (e[(e.OnRouletteItemUnlock = 685)] = "OnRouletteItemUnlock"),
      (e[(e.OnRouletteSaveDataChange = 686)] = "OnRouletteSaveDataChange"),
      (e[(e.OnAggroAdd = 687)] = "OnAggroAdd"),
      (e[(e.OnAggroRemoved = 688)] = "OnAggroRemoved"),
      (e[(e.OnBossFight = 689)] = "OnBossFight"),
      (e[(e.OnSkillTagChanged = 690)] = "OnSkillTagChanged"),
      (e[(e.OnMatchingChange = 691)] = "OnMatchingChange"),
      (e[(e.OnMatchingBegin = 692)] = "OnMatchingBegin"),
      (e[(e.OnEnterTeam = 693)] = "OnEnterTeam"),
      (e[(e.OnLeaveTeam = 694)] = "OnLeaveTeam"),
      (e[(e.OnEnterOnlineWorld = 695)] = "OnEnterOnlineWorld"),
      (e[(e.OnLeaveOnlineWorld = 696)] = "OnLeaveOnlineWorld"),
      (e[(e.OnlineDisableStateChange = 697)] = "OnlineDisableStateChange"),
      (e[(e.PlayerChallengeStateChange = 698)] = "PlayerChallengeStateChange"),
      (e[(e.OnTriggerVolumeExit = 699)] = "OnTriggerVolumeExit"),
      (e[(e.RefreshAcquireView = 700)] = "RefreshAcquireView"),
      (e[(e.OnResonanceMaterialChange = 701)] = "OnResonanceMaterialChange"),
      (e[(e.OnAddMaterialController = 702)] = "OnAddMaterialController"),
      (e[(e.OnRemoveMaterialController = 703)] = "OnRemoveMaterialController"),
      (e[(e.OnAddMaterialControllerGroup = 704)] =
        "OnAddMaterialControllerGroup"),
      (e[(e.OnRemoveMaterialControllerGroup = 705)] =
        "OnRemoveMaterialControllerGroup"),
      (e[(e.WeatherChange = 706)] = "WeatherChange"),
      (e[(e.OnManipulateSwitchToNewTarget = 707)] =
        "OnManipulateSwitchToNewTarget"),
      (e[(e.OnManipulateStartChanting = 708)] = "OnManipulateStartChanting"),
      (e[(e.OnManipulateCancelChanting = 709)] = "OnManipulateCancelChanting"),
      (e[(e.OnManipulateCompleteChanting = 710)] =
        "OnManipulateCompleteChanting"),
      (e[(e.HiddenManipulateUI = 711)] = "HiddenManipulateUI"),
      (e[(e.ManipulateStartLockCastTarget = 712)] =
        "ManipulateStartLockCastTarget"),
      (e[(e.ManipulateEndLockCastTarget = 713)] =
        "ManipulateEndLockCastTarget"),
      (e[(e.OnManipulatableSceneItemPosInFoundation = 714)] =
        "OnManipulatableSceneItemPosInFoundation"),
      (e[(e.AddSubCameraTag = 715)] = "AddSubCameraTag"),
      (e[(e.RemoveSubCameraTag = 716)] = "RemoveSubCameraTag"),
      (e[(e.AddExtraHoldingTags = 717)] = "AddExtraHoldingTags"),
      (e[(e.RemoveExtraHoldingTags = 718)] = "RemoveExtraHoldingTags"),
      (e[(e.HideJigsawBaseHint = 719)] = "HideJigsawBaseHint"),
      (e[(e.OnModifyJigsawItemPutIndex = 720)] = "OnModifyJigsawItemPutIndex"),
      (e[(e.OnManipulatableItemStateModified = 721)] =
        "OnManipulatableItemStateModified"),
      (e[(e.OnManipulatedItemPosReset = 722)] = "OnManipulatedItemPosReset"),
      (e[(e.SetCameraAimVisible = 723)] = "SetCameraAimVisible"),
      (e[(e.ClickDisplayItem = 724)] = "ClickDisplayItem"),
      (e[(e.OnSelectItemAdd = 725)] = "OnSelectItemAdd"),
      (e[(e.DetectSuccess = 726)] = "DetectSuccess"),
      (e[(e.AdventureTaskStateChange = 727)] = "AdventureTaskStateChange"),
      (e[(e.ChapterRewardReceived = 728)] = "ChapterRewardReceived"),
      (e[(e.SilentRewardReceived = 729)] = "SilentRewardReceived"),
      (e[(e.AdventureHelpBtn = 730)] = "AdventureHelpBtn"),
      (e[(e.NewSoundAreaRefreshReward = 731)] = "NewSoundAreaRefreshReward"),
      (e[(e.DailyActivityTaskUpdate = 732)] = "DailyActivityTaskUpdate"),
      (e[(e.DailyActivityRefresh = 733)] = "DailyActivityRefresh"),
      (e[(e.DailyActivityValueChange = 734)] = "DailyActivityValueChange"),
      (e[(e.DailyActivityRewardTake = 735)] = "DailyActivityRewardTake"),
      (e[(e.RefreshActivityRewardPopUp = 736)] = "RefreshActivityRewardPopUp"),
      (e[(e.DailyActivityCountDownUpdate = 737)] =
        "DailyActivityCountDownUpdate"),
      (e[(e.DailyUpdateNotify = 738)] = "DailyUpdateNotify"),
      (e[(e.DailyActivityStateNotify = 739)] = "DailyActivityStateNotify"),
      (e[(e.DailyTaskAreaItemClick = 740)] = "DailyTaskAreaItemClick"),
      (e[(e.DailyTaskInfluenceItemClick = 741)] =
        "DailyTaskInfluenceItemClick"),
      (e[(e.DailyTaskUnlockAreaChange = 742)] = "DailyTaskUnlockAreaChange"),
      (e[(e.DailyTaskStateChange = 743)] = "DailyTaskStateChange"),
      (e[(e.DailyTaskChange = 744)] = "DailyTaskChange"),
      (e[(e.DailyTaskTendencyChange = 745)] = "DailyTaskTendencyChange"),
      (e[(e.OnAddCommonItem = 746)] = "OnAddCommonItem"),
      (e[(e.OnAddCommonItemList = 747)] = "OnAddCommonItemList"),
      (e[(e.OnAddCommonItemNotify = 748)] = "OnAddCommonItemNotify"),
      (e[(e.OnResponseCommonItem = 749)] = "OnResponseCommonItem"),
      (e[(e.OnRemoveCommonItem = 750)] = "OnRemoveCommonItem"),
      (e[(e.OnCommonItemCountRefresh = 751)] = "OnCommonItemCountRefresh"),
      (e[(e.OnCommonItemCountAnyChange = 752)] = "OnCommonItemCountAnyChange"),
      (e[(e.OnAddWeaponItem = 753)] = "OnAddWeaponItem"),
      (e[(e.OnAddWeaponItemList = 754)] = "OnAddWeaponItemList"),
      (e[(e.OnResponseWeaponItem = 755)] = "OnResponseWeaponItem"),
      (e[(e.OnResponseWeaponAll = 756)] = "OnResponseWeaponAll"),
      (e[(e.OnRemoveWeaponItem = 757)] = "OnRemoveWeaponItem"),
      (e[(e.OnWeaponFunctionValueRefresh = 758)] =
        "OnWeaponFunctionValueRefresh"),
      (e[(e.OnAddPhantomItem = 759)] = "OnAddPhantomItem"),
      (e[(e.OnAddPhantomItemList = 760)] = "OnAddPhantomItemList"),
      (e[(e.OnResponsePhantomItem = 761)] = "OnResponsePhantomItem"),
      (e[(e.OnEquipPhantomItem = 762)] = "OnEquipPhantomItem"),
      (e[(e.OnRemovePhantomItem = 763)] = "OnRemovePhantomItem"),
      (e[(e.OnPhantomFunctionValueRefresh = 764)] =
        "OnPhantomFunctionValueRefresh"),
      (e[(e.OnAddFavorItem = 765)] = "OnAddFavorItem"),
      (e[(e.NotifyInvalidItem = 766)] = "NotifyInvalidItem"),
      (e[(e.EnterPresentationInitRange = 767)] = "EnterPresentationInitRange"),
      (e[(e.EnterLogicRange = 768)] = "EnterLogicRange"),
      (e[(e.LeaveLogicRange = 769)] = "LeaveLogicRange"),
      (e[(e.PlayerSenseTargetEnter = 770)] = "PlayerSenseTargetEnter"),
      (e[(e.PlayerSenseTargetLeave = 771)] = "PlayerSenseTargetLeave"),
      (e[(e.OnAiSenseEntityEnter = 772)] = "OnAiSenseEntityEnter"),
      (e[(e.OnAiSenseEntityLeave = 773)] = "OnAiSenseEntityLeave"),
      (e[(e.OnInteractStateChange = 774)] = "OnInteractStateChange"),
      (e[(e.OnGuideRangeEnter = 775)] = "OnGuideRangeEnter"),
      (e[(e.SwitchCookType = 776)] = "SwitchCookType"),
      (e[(e.UpdateFormula = 777)] = "UpdateFormula"),
      (e[(e.UpdateCookerInfo = 778)] = "UpdateCookerInfo"),
      (e[(e.UpgradeCookerLevel = 779)] = "UpgradeCookerLevel"),
      (e[(e.GetCookData = 780)] = "GetCookData"),
      (e[(e.OpenProcessedStudy = 781)] = "OpenProcessedStudy"),
      (e[(e.CloseProcessedStudy = 782)] = "CloseProcessedStudy"),
      (e[(e.OpenCook = 783)] = "OpenCook"),
      (e[(e.OpenCookLevel = 784)] = "OpenCookLevel"),
      (e[(e.OpenCookRole = 785)] = "OpenCookRole"),
      (e[(e.CloseCookRole = 786)] = "CloseCookRole"),
      (e[(e.CookSuccess = 787)] = "CookSuccess"),
      (e[(e.CookFail = 788)] = "CookFail"),
      (e[(e.MachiningSuccess = 789)] = "MachiningSuccess"),
      (e[(e.MachiningStudyFail = 790)] = "MachiningStudyFail"),
      (e[(e.FixSuccess = 791)] = "FixSuccess"),
      (e[(e.OpenSelected = 792)] = "OpenSelected"),
      (e[(e.CloseSelected = 793)] = "CloseSelected"),
      (e[(e.OnAddCommonEffect = 794)] = "OnAddCommonEffect"),
      (e[(e.ReceiveMonthCardDataEvent = 795)] = "ReceiveMonthCardDataEvent"),
      (e[(e.OnClickSingleTimeTowerStageBtn = 796)] =
        "OnClickSingleTimeTowerStageBtn"),
      (e[(e.OnClickSingleTimeTowerTeamBtn = 797)] =
        "OnClickSingleTimeTowerTeamBtn"),
      (e[(e.OnClickSingleTimeTowerTeamRoleBtn = 798)] =
        "OnClickSingleTimeTowerTeamRoleBtn"),
      (e[(e.OnClickSingleTimeTowerStageDetailBtn = 799)] =
        "OnClickSingleTimeTowerStageDetailBtn");
    (e[(e.OnClickSingleTimeTowerMonsterBtn = 800)] =
      "OnClickSingleTimeTowerMonsterBtn"),
      (e[(e.OnClickSingleTimeTowerDetailSwitchBtn = 801)] =
        "OnClickSingleTimeTowerDetailSwitchBtn"),
      (e[(e.OnInstResultNotify = 802)] = "OnInstResultNotify"),
      (e[(e.OnTowerChallengeChangeTeamNotify = 803)] =
        "OnTowerChallengeChangeTeamNotify"),
      (e[(e.OnTowerRewardReceived = 804)] = "OnTowerRewardReceived"),
      (e[(e.RedDotTowerReward = 805)] = "RedDotTowerReward"),
      (e[(e.RedDotTowerRewardByDifficulties = 806)] =
        "RedDotTowerRewardByDifficulties"),
      (e[(e.OnTowerRefresh = 807)] = "OnTowerRefresh"),
      (e[(e.OnTowerRecordUpdate = 808)] = "OnTowerRecordUpdate"),
      (e[(e.OnShowTowerGuideButton = 809)] = "OnShowTowerGuideButton"),
      (e[(e.OnClickCycleTowerAreaBtn = 810)] = "OnClickCycleTowerAreaBtn"),
      (e[(e.OnResetCycleTowerArea = 811)] = "OnResetCycleTowerArea"),
      (e[(e.OnClickCycleTowerRoleBtn = 812)] = "OnClickCycleTowerRoleBtn"),
      (e[(e.OnClickCycleTowerDetailSwitchBtn = 813)] =
        "OnClickCycleTowerDetailSwitchBtn"),
      (e[(e.OnCycleTowerUpdateSeason = 814)] = "OnCycleTowerUpdateSeason"),
      (e[(e.OnCycleTowerUpdateSeasonNotify = 815)] =
        "OnCycleTowerUpdateSeasonNotify"),
      (e[(e.OnCycleTowerScoreChange = 816)] = "OnCycleTowerScoreChange"),
      (e[(e.OnTowerGuideClose = 817)] = "OnTowerGuideClose"),
      (e[(e.OnTowerRefreshStars = 818)] = "OnTowerRefreshStars"),
      (e[(e.OnReceiveAdviceData = 819)] = "OnReceiveAdviceData"),
      (e[(e.OnCreateAdviceSuccess = 820)] = "OnCreateAdviceSuccess"),
      (e[(e.OnModifyAdviceSuccess = 821)] = "OnModifyAdviceSuccess"),
      (e[(e.OnDeleteAdviceSuccess = 822)] = "OnDeleteAdviceSuccess"),
      (e[(e.OnClickAdviceExpression = 823)] = "OnClickAdviceExpression"),
      (e[(e.OnClickAdviceWord = 824)] = "OnClickAdviceWord"),
      (e[(e.OnChangeAdviceWord = 825)] = "OnChangeAdviceWord"),
      (e[(e.OnClickAdviceSort = 826)] = "OnClickAdviceSort"),
      (e[(e.OnClickAdviceSortWord = 827)] = "OnClickAdviceSortWord"),
      (e[(e.OnClickAdviceMotion = 828)] = "OnClickAdviceMotion"),
      (e[(e.OnChangeAdviceRole = 829)] = "OnChangeAdviceRole"),
      (e[(e.OnClickAdviceSelectItem = 830)] = "OnClickAdviceSelectItem"),
      (e[(e.OnSelectAdviceWord = 831)] = "OnSelectAdviceWord"),
      (e[(e.OnSelectAdviceExpression = 832)] = "OnSelectAdviceExpression"),
      (e[(e.OnAdviceEntityNotify = 833)] = "OnAdviceEntityNotify"),
      (e[(e.OnAdviceVoteNotify = 834)] = "OnAdviceVoteNotify"),
      (e[(e.RefreshAdviceInfoView = 835)] = "RefreshAdviceInfoView"),
      (e[(e.SneakStart = 836)] = "SneakStart"),
      (e[(e.SneakEnd = 837)] = "SneakEnd"),
      (e[(e.AddAlterMark = 838)] = "AddAlterMark"),
      (e[(e.RemoveAlterMark = 839)] = "RemoveAlterMark"),
      (e[(e.OnSneakFoundChange = 840)] = "OnSneakFoundChange"),
      (e[(e.OnChildQuestNodeFinish = 841)] = "OnChildQuestNodeFinish"),
      (e[(e.AddStalkAlertMark = 842)] = "AddStalkAlertMark"),
      (e[(e.RemoveStalkAlertMark = 843)] = "RemoveStalkAlertMark"),
      (e[(e.OnStalkAlert = 844)] = "OnStalkAlert"),
      (e[(e.OnStalkAlertLifted = 845)] = "OnStalkAlertLifted"),
      (e[(e.OnStalkFound = 846)] = "OnStalkFound"),
      (e[(e.OnStalkFailed = 847)] = "OnStalkFailed"),
      (e[(e.AddEavesdropMark = 848)] = "AddEavesdropMark"),
      (e[(e.RemoveEavesdropMark = 849)] = "RemoveEavesdropMark"),
      (e[(e.OnEavesdropFound = 850)] = "OnEavesdropFound"),
      (e[(e.OnAddFullScreenEffect = 851)] = "OnAddFullScreenEffect"),
      (e[(e.OnRemoveFullScreenEffect = 852)] = "OnRemoveFullScreenEffect"),
      (e[(e.OnClearFullScreenEffect = 853)] = "OnClearFullScreenEffect"),
      (e[(e.OnChangeFullScreenNiagaraFloatParameter = 854)] =
        "OnChangeFullScreenNiagaraFloatParameter"),
      (e[(e.OnSceneItemBuffConsumed = 855)] = "OnSceneItemBuffConsumed"),
      (e[(e.OnSceneItemBuffRemoved = 856)] = "OnSceneItemBuffRemoved"),
      (e[(e.OnSceneItemBuffTimeout = 857)] = "OnSceneItemBuffTimeout"),
      (e[(e.OnSceneItemBuffTargetRemoved = 858)] =
        "OnSceneItemBuffTargetRemoved"),
      (e[(e.OnSceneItemBuffConsumerPerformanceComplete = 859)] =
        "OnSceneItemBuffConsumerPerformanceComplete"),
      (e[(e.OnExecuteServerGm = 860)] = "OnExecuteServerGm"),
      (e[(e.SetActiveBattleViewSkill = 861)] = "SetActiveBattleViewSkill"),
      (e[(e.SetEnableStateBattleViewSkill = 862)] =
        "SetEnableStateBattleViewSkill"),
      (e[(e.ActiveBattleView = 863)] = "ActiveBattleView"),
      (e[(e.DisActiveBattleView = 864)] = "DisActiveBattleView"),
      (e[(e.BattleUiCurRoleDataChanged = 865)] = "BattleUiCurRoleDataChanged"),
      (e[(e.BattleUiCurRoleDataChangedNextTick = 866)] =
        "BattleUiCurRoleDataChangedNextTick"),
      (e[(e.BattleUiAllRoleDataChanged = 867)] = "BattleUiAllRoleDataChanged"),
      (e[(e.BattleUiRemoveRoleData = 868)] = "BattleUiRemoveRoleData"),
      (e[(e.BattleUiElementEnergyChanged = 869)] =
        "BattleUiElementEnergyChanged"),
      (e[(e.BattleUiElementHideTagChanged = 870)] =
        "BattleUiElementHideTagChanged"),
      (e[(e.BattleUiDeadTagChanged = 871)] = "BattleUiDeadTagChanged"),
      (e[(e.BattleUiQteEnableTagChanged = 872)] =
        "BattleUiQteEnableTagChanged"),
      (e[(e.BattleUiQteCdTagChanged = 873)] = "BattleUiQteCdTagChanged"),
      (e[(e.BattleUiUseQteTagChanged = 874)] = "BattleUiUseQteTagChanged"),
      (e[(e.BattleUiConcertoEnableTagChanged = 875)] =
        "BattleUiConcertoEnableTagChanged"),
      (e[(e.BattleUiPoisonChanged = 876)] = "BattleUiPoisonChanged"),
      (e[(e.BattleUiHealthChanged = 877)] = "BattleUiHealthChanged"),
      (e[(e.BattleUiShieldChanged = 878)] = "BattleUiShieldChanged"),
      (e[(e.BattleUiLevelChanged = 879)] = "BattleUiLevelChanged"),
      (e[(e.BattleUiFloatTipUpdate = 880)] = "BattleUiFloatTipUpdate"),
      (e[(e.BattleUiPlayAudio = 881)] = "BattleUiPlayAudio"),
      (e[(e.BattleUiExploreModeChanged = 882)] = "BattleUiExploreModeChanged"),
      (e[(e.BattleUiMergeHeadStateVisibleChanged = 883)] =
        "BattleUiMergeHeadStateVisibleChanged"),
      (e[(e.BattleUiMergeHeadStateHealthChanged = 884)] =
        "BattleUiMergeHeadStateHealthChanged"),
      (e[(e.BattleUiEnvironmentKeyChanged = 885)] =
        "BattleUiEnvironmentKeyChanged"),
      (e[(e.BattleUiPressCombineButtonChanged = 886)] =
        "BattleUiPressCombineButtonChanged"),
      (e[(e.BattleUiToggleSilentAreaInfoView = 887)] =
        "BattleUiToggleSilentAreaInfoView"),
      (e[(e.BattleSettlementStateChanged = 888)] =
        "BattleSettlementStateChanged"),
      (e[(e.BattleScoreChanged = 889)] = "BattleScoreChanged"),
      (e[(e.RefreshInfluencePanel = 890)] = "RefreshInfluencePanel"),
      (e[(e.ReceiveReputationReward = 891)] = "ReceiveReputationReward"),
      (e[(e.SearchInfluence = 892)] = "SearchInfluence"),
      (e[(e.RedDotInfluence = 893)] = "RedDotInfluence"),
      (e[(e.BehaviorTreeStartActionSession = 894)] =
        "BehaviorTreeStartActionSession"),
      (e[(e.UiPlayCloseAudio = 895)] = "UiPlayCloseAudio"),
      (e[(e.OnSceneItemLockPropChange = 896)] = "OnSceneItemLockPropChange"),
      (e[(e.OnSpecialItemUpdate = 897)] = "OnSpecialItemUpdate"),
      (e[(e.EquipAndSwitchSpecialItem = 898)] = "EquipAndSwitchSpecialItem"),
      (e[(e.UnEquipSpecialItem = 899)] = "UnEquipSpecialItem"),
      (e[(e.ShowPlayerPosition = 900)] = "ShowPlayerPosition"),
      (e[(e.BattlePassHadEnterUpdate = 901)] = "BattlePassHadEnterUpdate"),
      (e[(e.GetBattlePassRewardEvent = 902)] = "GetBattlePassRewardEvent"),
      (e[(e.ReceiveBattlePassDataEvent = 903)] = "ReceiveBattlePassDataEvent"),
      (e[(e.BattlePassFirstUnlockAnime = 904)] = "BattlePassFirstUnlockAnime"),
      (e[(e.ReceiveBattlePassTaskEvent = 905)] = "ReceiveBattlePassTaskEvent"),
      (e[(e.OnChoseLevelItemEvent = 906)] = "OnChoseLevelItemEvent"),
      (e[(e.OnClickLevelItemEvent = 907)] = "OnClickLevelItemEvent"),
      (e[(e.UpdateBattlePassTaskEvent = 908)] = "UpdateBattlePassTaskEvent"),
      (e[(e.OnBattlePassLevelUpEvent = 909)] = "OnBattlePassLevelUpEvent"),
      (e[(e.OnBattlePassExpireEvent = 910)] = "OnBattlePassExpireEvent"),
      (e[(e.BattlePassMainViewHide = 911)] = "BattlePassMainViewHide"),
      (e[(e.SwitchViewType = 912)] = "SwitchViewType"),
      (e[(e.SwitchComposeType = 913)] = "SwitchComposeType"),
      (e[(e.GetComposeData = 914)] = "GetComposeData"),
      (e[(e.UpgradeComposeLevel = 915)] = "UpgradeComposeLevel"),
      (e[(e.OpenComposeLevel = 916)] = "OpenComposeLevel"),
      (e[(e.OpenCompose = 917)] = "OpenCompose"),
      (e[(e.ComposeSuccess = 918)] = "ComposeSuccess"),
      (e[(e.ComposeFail = 919)] = "ComposeFail"),
      (e[(e.OpenHelpRole = 920)] = "OpenHelpRole"),
      (e[(e.CloseHelpRole = 921)] = "CloseHelpRole"),
      (e[(e.UpdateComposeFormula = 922)] = "UpdateComposeFormula"),
      (e[(e.UpdateComposeInfo = 923)] = "UpdateComposeInfo"),
      (e[(e.UpdateForgingFormula = 924)] = "UpdateForgingFormula"),
      (e[(e.OpenForging = 925)] = "OpenForging"),
      (e[(e.GetForgingData = 926)] = "GetForgingData"),
      (e[(e.ForgingSuccess = 927)] = "ForgingSuccess"),
      (e[(e.ForgingFail = 928)] = "ForgingFail"),
      (e[(e.ChangePlayerInfoId = 929)] = "ChangePlayerInfoId"),
      (e[(e.OnShowGridAnimation = 930)] = "OnShowGridAnimation"),
      (e[(e.OnActivateUiCameraAnimationHandle = 931)] =
        "OnActivateUiCameraAnimationHandle"),
      (e[(e.OnActivateUiCameraAnimationHandleFail = 932)] =
        "OnActivateUiCameraAnimationHandleFail"),
      (e[(e.OnUiBlendInCameraSequenceFinished = 933)] =
        "OnUiBlendInCameraSequenceFinished"),
      (e[(e.RoleHandBookActive = 934)] = "RoleHandBookActive"),
      (e[(e.OnSequenceCameraStatus = 935)] = "OnSequenceCameraStatus"),
      (e[(e.LocalStorageInitPlayerId = 936)] = "LocalStorageInitPlayerId"),
      (e[(e.DynamicInteractServerResponse = 937)] =
        "DynamicInteractServerResponse"),
      (e[(e.UpdateCameraInfo = 938)] = "UpdateCameraInfo"),
      (e[(e.PlayCameraLevelSequence = 939)] = "PlayCameraLevelSequence"),
      (e[(e.CameraModeChanged = 940)] = "CameraModeChanged"),
      (e[(e.CameraViewTargetChanged = 941)] = "CameraViewTargetChanged"),
      (e[(e.FixedCameraRestored = 942)] = "FixedCameraRestored"),
      (e[(e.CameraCharacterChanged = 943)] = "CameraCharacterChanged"),
      (e[(e.OpenTreasureBox = 944)] = "OpenTreasureBox"),
      (e[(e.OnHandBookDataInit = 945)] = "OnHandBookDataInit"),
      (e[(e.OnHandBookDataUpdate = 946)] = "OnHandBookDataUpdate"),
      (e[(e.OnHandBookRedDotUpdate = 947)] = "OnHandBookRedDotUpdate"),
      (e[(e.OnHandBookRead = 948)] = "OnHandBookRead"),
      (e[(e.OnPhantomReadRedDotUpdate = 949)] = "OnPhantomReadRedDotUpdate"),
      (e[(e.OnItemReadRedDotUpdate = 950)] = "OnItemReadRedDotUpdate"),
      (e[(e.OnPhotoSelect = 951)] = "OnPhotoSelect"),
      (e[(e.OnGeographyPhotoSelect = 952)] = "OnGeographyPhotoSelect"),
      (e[(e.OnHandBookPlotNodeRefresh = 953)] = "OnHandBookPlotNodeRefresh"),
      (e[(e.RemoveCreatureDataComponentCache = 954)] =
        "RemoveCreatureDataComponentCache"),
      (e[(e.TravelClearView = 955)] = "TravelClearView"),
      (e[(e.OnPressOrReleaseBehaviorButton = 956)] =
        "OnPressOrReleaseBehaviorButton"),
      (e[(e.SetImageQuality = 957)] = "SetImageQuality"),
      (e[(e.SetDisplayMode = 958)] = "SetDisplayMode"),
      (e[(e.SetResolution = 959)] = "SetResolution"),
      (e[(e.SetGmIsOpen = 960)] = "SetGmIsOpen"),
      (e[(e.AddToTickList = 961)] = "AddToTickList"),
      (e[(e.HandleNextAction = 962)] = "HandleNextAction"),
      (e[(e.HandleActionFailure = 963)] = "HandleActionFailure"),
      (e[(e.AddGuaranteeAction = 964)] = "AddGuaranteeAction"),
      (e[(e.RemGuaranteeAction = 965)] = "RemGuaranteeAction"),
      (e[(e.ShareGroupCd = 966)] = "ShareGroupCd"),
      (e[(e.AddShareGroupLimitCount = 967)] = "AddShareGroupLimitCount"),
      (e[(e.OnInteractPlotStart = 968)] = "OnInteractPlotStart"),
      (e[(e.OnInteractPlotEnd = 969)] = "OnInteractPlotEnd"),
      (e[(e.OnAchievementDataNotify = 970)] = "OnAchievementDataNotify"),
      (e[(e.OnAchievementDataWithIdNotify = 971)] =
        "OnAchievementDataWithIdNotify"),
      (e[(e.OnAchievementGroupDataNotify = 972)] =
        "OnAchievementGroupDataNotify"),
      (e[(e.OnGetAchievementBaseData = 973)] = "OnGetAchievementBaseData"),
      (e[(e.OnGetAchievementSearchTextChange = 974)] =
        "OnGetAchievementSearchTextChange"),
      (e[(e.OnAchievementGroupChange = 975)] = "OnAchievementGroupChange"),
      (e[(e.RefreshAchievementRedPoint = 976)] = "RefreshAchievementRedPoint"),
      (e[(e.OnActivityUpdate = 977)] = "OnActivityUpdate"),
      (e[(e.OnSelectActivity = 978)] = "OnSelectActivity"),
      (e[(e.RefreshActivityTab = 979)] = "RefreshActivityTab"),
      (e[(e.OnReceiveActivityData = 980)] = "OnReceiveActivityData"),
      (e[(e.SetActivityViewState = 981)] = "SetActivityViewState"),
      (e[(e.SetActivityViewCurrency = 982)] = "SetActivityViewCurrency"),
      (e[(e.OnClickActivityRunChallenge = 983)] =
        "OnClickActivityRunChallenge"),
      (e[(e.OnSelectActivityRunChallengeItem = 984)] =
        "OnSelectActivityRunChallengeItem"),
      (e[(e.RefreshCommonActivityRedDot = 985)] =
        "RefreshCommonActivityRedDot"),
      (e[(e.RefreshRunActivityRedDot = 986)] = "RefreshRunActivityRedDot"),
      (e[(e.OnGetRunActivityReward = 987)] = "OnGetRunActivityReward"),
      (e[(e.OnActivityClose = 988)] = "OnActivityClose"),
      (e[(e.OnActivityOpen = 989)] = "OnActivityOpen"),
      (e[(e.OnActivitySequenceEmitEvent = 990)] =
        "OnActivitySequenceEmitEvent"),
      (e[(e.RefreshCommonActivityRewardPopUpView = 991)] =
        "RefreshCommonActivityRewardPopUpView"),
      (e[(e.ActivityViewChange = 992)] = "ActivityViewChange"),
      (e[(e.ActivityViewRefreshCurrent = 993)] = "ActivityViewRefreshCurrent"),
      (e[(e.LongShanUpdate = 994)] = "LongShanUpdate"),
      (e[(e.OnPhantomCollectUpdate = 995)] = "OnPhantomCollectUpdate"),
      (e[(e.TurntableStartRun = 996)] = "TurntableStartRun"),
      (e[(e.GmAutoModeChange = 997)] = "GmAutoModeChange"),
      (e[(e.OnAddNotAllowFightInputViewName = 998)] =
        "OnAddNotAllowFightInputViewName"),
      (e[(e.OnRemoveNotAllowFightInputViewName = 999)] =
        "OnRemoveNotAllowFightInputViewName"),
      (e[(e.OnClearNotAllowFightInputViewName = 1e3)] =
        "OnClearNotAllowFightInputViewName"),
      (e[(e.OnSelectedEditPanelItem = 1001)] = "OnSelectedEditPanelItem"),
      (e[(e.UiRoleSequenceEndKeyFrame = 1002)] = "UiRoleSequenceEndKeyFrame"),
      (e[(e.DropItemStarted = 1003)] = "DropItemStarted"),
      (e[(e.OnRoleChangeEnd = 1004)] = "OnRoleChangeEnd"),
      (e[(e.ComboTeachingPress = 1005)] = "ComboTeachingPress"),
      (e[(e.ComboTeachingRelease = 1006)] = "ComboTeachingRelease"),
      (e[(e.ComboTeachingHold = 1007)] = "ComboTeachingHold"),
      (e[(e.ComboTeachingNodeEnd = 1008)] = "ComboTeachingNodeEnd"),
      (e[(e.ComboTeachingViewOpen = 1009)] = "ComboTeachingViewOpen"),
      (e[(e.SkillAcceptChanged = 1010)] = "SkillAcceptChanged"),
      (e[(e.ComboTeachingFinish = 1011)] = "ComboTeachingFinish"),
      (e[(e.ComboTeachingCloseGuide = 1012)] = "ComboTeachingCloseGuide"),
      (e[(e.RequestClearMeshRotationBuffer = 1013)] =
        "RequestClearMeshRotationBuffer"),
      (e[(e.NavigationViewCreate = 1014)] = "NavigationViewCreate"),
      (e[(e.NavigationViewDestroy = 1015)] = "NavigationViewDestroy"),
      (e[(e.ResetNavigationListener = 1016)] = "ResetNavigationListener"),
      (e[(e.NavigationTriggerMapForward = 1017)] =
        "NavigationTriggerMapForward"),
      (e[(e.NavigationTriggerMapRight = 1018)] = "NavigationTriggerMapRight"),
      (e[(e.NavigationTriggerMapZoom = 1019)] = "NavigationTriggerMapZoom"),
      (e[(e.NavigationTriggerRoleLookUp = 1020)] =
        "NavigationTriggerRoleLookUp"),
      (e[(e.NavigationTriggerRoleTurn = 1021)] = "NavigationTriggerRoleTurn"),
      (e[(e.NavigationTriggerRoleZoom = 1022)] = "NavigationTriggerRoleZoom"),
      (e[(e.NavigationTriggerRoleReset = 1023)] = "NavigationTriggerRoleReset"),
      (e[(e.FunctionGridSelected = 1024)] = "FunctionGridSelected"),
      (e[(e.OnPersonalCardRead = 1025)] = "OnPersonalCardRead"),
      (e[(e.OnHeadIconChange = 1026)] = "OnHeadIconChange"),
      (e[(e.OnSignChange = 1027)] = "OnSignChange"),
      (e[(e.OnNameChange = 1028)] = "OnNameChange"),
      (e[(e.OnBirthChange = 1029)] = "OnBirthChange"),
      (e[(e.OnBirthDisplayChange = 1030)] = "OnBirthDisplayChange"),
      (e[(e.OnCardChange = 1031)] = "OnCardChange"),
      (e[(e.ResetRoleFlag = 1032)] = "ResetRoleFlag"),
      (e[(e.OnRoleShowListChange = 1033)] = "OnRoleShowListChange"),
      (e[(e.OnRoleElementChange = 1034)] = "OnRoleElementChange"),
      (e[(e.ShowRoleElementChangePreviewEffect = 1035)] =
        "ShowRoleElementChangePreviewEffect"),
      (e[(e.OnChangedActionKeys = 1036)] = "OnChangedActionKeys"),
      (e[(e.OnChangedAxisKeys = 1037)] = "OnChangedAxisKeys"),
      (e[(e.SelectRoleTab = 1038)] = "SelectRoleTab"),
      (e[(e.SelectRoleTabOutside = 1039)] = "SelectRoleTabOutside"),
      (e[(e.OnFunctionViewShow = 1040)] = "OnFunctionViewShow"),
      (e[(e.UpdatePanelQteWorldTimeDilation = 1041)] =
        "UpdatePanelQteWorldTimeDilation"),
      (e[(e.PanelQteStart = 1042)] = "PanelQteStart"),
      (e[(e.PanelQteEnd = 1043)] = "PanelQteEnd"),
      (e[(e.StartHeartBeat = 1044)] = "StartHeartBeat"),
      (e[(e.StopHeartBeat = 1045)] = "StopHeartBeat"),
      (e[(e.CreateEffectHandle = 1046)] = "CreateEffectHandle"),
      (e[(e.RemoveEffectHandle = 1047)] = "RemoveEffectHandle"),
      (e[(e.LoadEffect = 1048)] = "LoadEffect"),
      (e[(e.BeforePlayEffect = 1049)] = "BeforePlayEffect"),
      (e[(e.AfterPlayEffect = 1050)] = "AfterPlayEffect"),
      (e[(e.FinishEffect = 1051)] = "FinishEffect"),
      (e[(e.TestQuestAutoPilotFinish = 1052)] = "TestQuestAutoPilotFinish"),
      (e[(e.TestQuestFunctionFinish = 1053)] = "TestQuestFunctionFinish"),
      (e[(e.OnRefreshRewardViewItemList = 1054)] =
        "OnRefreshRewardViewItemList"),
      (e[(e.OnRefreshRewardProgressBar = 1055)] = "OnRefreshRewardProgressBar"),
      (e[(e.OnRefreshRewardButton = 1056)] = "OnRefreshRewardButton"),
      (e[(e.OnItemRewardNotify = 1057)] = "OnItemRewardNotify"),
      (e[(e.OnShowRewardView = 1058)] = "OnShowRewardView"),
      (e[(e.OnCloseRewardView = 1059)] = "OnCloseRewardView"),
      (e[(e.OnPlotWaitViewDone = 1060)] = "OnPlotWaitViewDone"),
      (e[(e.OnPlayCameraAnimationStart = 1061)] = "OnPlayCameraAnimationStart"),
      (e[(e.OnPlayCameraAnimationFinish = 1062)] =
        "OnPlayCameraAnimationFinish"),
      (e[(e.CommunicateFinished = 1063)] = "CommunicateFinished"),
      (e[(e.CommunicateAgain = 1064)] = "CommunicateAgain"),
      (e[(e.OnPhotographSetUpViewVisibleChanged = 1065)] =
        "OnPhotographSetUpViewVisibleChanged"),
      (e[(e.OnEntityCameraOneSituationChanged = 1066)] =
        "OnEntityCameraOneSituationChanged"),
      (e[(e.OnEntityCameraSearchGreat = 1067)] = "OnEntityCameraSearchGreat"),
      (e[(e.OnEntityCameraFinished = 1068)] = "OnEntityCameraFinished"),
      (e[(e.OnScreenShotDone = 1069)] = "OnScreenShotDone"),
      (e[(e.OnSubmitItemSuccess = 1070)] = "OnSubmitItemSuccess"),
      (e[(e.OnSubmitItemFail = 1071)] = "OnSubmitItemFail"),
      (e[(e.OnSubmitItemLevelUp = 1072)] = "OnSubmitItemLevelUp"),
      (e[(e.OnSubmitItemLevelMax = 1073)] = "OnSubmitItemLevelMax"),
      (e[(e.OnCameraSequenceSetUiVisible = 1074)] =
        "OnCameraSequenceSetUiVisible"),
      (e[(e.OnUiScreenRootVisibleChange = 1075)] =
        "OnUiScreenRootVisibleChange"),
      (e[(e.OnTurntableControllerBusyStateChange = 1076)] =
        "OnTurntableControllerBusyStateChange"),
      (e[(e.OnAnyProgressControlEnableStateChange = 1077)] =
        "OnAnyProgressControlEnableStateChange"),
      (e[(e.OnDropItemSuccess = 1078)] = "OnDropItemSuccess"),
      (e[(e.OnInteractDropItemSuccess = 1079)] = "OnInteractDropItemSuccess"),
      (e[(e.OnExecuteUiCameraSequenceEvent = 1080)] =
        "OnExecuteUiCameraSequenceEvent"),
      (e[(e.OnInputAnyKey = 1081)] = "OnInputAnyKey"),
      (e[(e.OnFilterDataUpdate = 1082)] = "OnFilterDataUpdate"),
      (e[(e.OnPlayNpcPerformSequence = 1083)] = "OnPlayNpcPerformSequence"),
      (e[(e.OnNpcPerformSequenceFinished = 1084)] =
        "OnNpcPerformSequenceFinished"),
      (e[(e.OnAntiqueShopUpgradeSequenceFinished = 1085)] =
        "OnAntiqueShopUpgradeSequenceFinished"),
      (e[(e.OnAntiqueShopLevelMaxSequenceFinished = 1086)] =
        "OnAntiqueShopLevelMaxSequenceFinished"),
      (e[(e.OnAntiqueShopUpgradeSequencePlayFail = 1087)] =
        "OnAntiqueShopUpgradeSequencePlayFail"),
      (e[(e.OnCookSuccessSequenceFinished = 1088)] =
        "OnCookSuccessSequenceFinished"),
      (e[(e.OnBeginPlayCookSuccessDisplay = 1089)] =
        "OnBeginPlayCookSuccessDisplay"),
      (e[(e.OnPlayCookSuccessDisplayFinished = 1090)] =
        "OnPlayCookSuccessDisplayFinished"),
      (e[(e.OnBeginPlayCookFailDisplay = 1091)] = "OnBeginPlayCookFailDisplay"),
      (e[(e.OnPlayCookFailDisplayFinished = 1092)] =
        "OnPlayCookFailDisplayFinished"),
      (e[(e.OnBeginPlayCompositeWorkingDisplay = 1093)] =
        "OnBeginPlayCompositeWorkingDisplay"),
      (e[(e.OnPlayCompositeWorkingDisplayFinished = 1094)] =
        "OnPlayCompositeWorkingDisplayFinished"),
      (e[(e.OnBeginPlayForgingWorkingDisplay = 1095)] =
        "OnBeginPlayForgingWorkingDisplay"),
      (e[(e.OnPlayForgingWorkingDisplayFinished = 1096)] =
        "OnPlayForgingWorkingDisplayFinished"),
      (e[(e.OnCharFootOnTheGround = 1097)] = "OnCharFootOnTheGround"),
      (e[(e.BattleViewActiveSequenceFinish = 1098)] =
        "BattleViewActiveSequenceFinish"),
      (e[(e.SmartObjectAiAlterNotify = 1099)] = "SmartObjectAiAlterNotify"),
      (e[(e.OnSetActorHidden = 1100)] = "OnSetActorHidden"),
      (e[(e.OnCheckGamePing = 1101)] = "OnCheckGamePing"),
      (e[(e.OnRemoveItemRedDot = 1102)] = "OnRemoveItemRedDot"),
      (e[(e.RunGm = 1103)] = "RunGm"),
      (e[(e.GmHandleActionFailed = 1104)] = "GmHandleActionFailed"),
      (e[(e.TestEffectAddDaRec = 1105)] = "TestEffectAddDaRec"),
      (e[(e.TestEffectAddEffectRec = 1106)] = "TestEffectAddEffectRec"),
      (e[(e.TestManuallyGarbageCollection = 1107)] =
        "TestManuallyGarbageCollection"),
      (e[(e.GmEntityPerformanceTestFinish = 1108)] =
        "GmEntityPerformanceTestFinish"),
      (e[(e.GmOnlyShowMiniMap = 1109)] = "GmOnlyShowMiniMap"),
      (e[(e.GmOnlyShowJoyStick = 1110)] = "GmOnlyShowJoyStick"),
      (e[(e.RoguelikeCloseGainSelectView = 1111)] =
        "RoguelikeCloseGainSelectView"),
      (e[(e.RoguelikeDataUpdate = 1112)] = "RoguelikeDataUpdate"),
      (e[(e.RoguelikeChooseDataResult = 1113)] = "RoguelikeChooseDataResult"),
      (e[(e.RoguelikeChooseDataNotify = 1114)] = "RoguelikeChooseDataNotify"),
      (e[(e.RoguelikeInfoSelectedToken = 1115)] = "RoguelikeInfoSelectedToken"),
      (e[(e.RoguelikeRefreshGain = 1116)] = "RoguelikeRefreshGain"),
      (e[(e.RoguelikeSelectSkill = 1117)] = "RoguelikeSelectSkill"),
      (e[(e.RoguelikeTalentLevelUp = 1118)] = "RoguelikeTalentLevelUp"),
      (e[(e.RoguelikeCurrencyUpdate = 1119)] = "RoguelikeCurrencyUpdate"),
      (e[(e.RoguelikeSelectToken = 1120)] = "RoguelikeSelectToken"),
      (e[(e.RoguelikeSelectSeason = 1121)] = "RoguelikeSelectSeason"),
      (e[(e.RoguelikeGetTokenReward = 1122)] = "RoguelikeGetTokenReward"),
      (e[(e.RogueTermUnlock = 1123)] = "RogueTermUnlock"),
      (e[(e.OnMarkItemViewCreate = 1124)] = "OnMarkItemViewCreate"),
      (e[(e.OnMarkItemViewDestroy = 1125)] = "OnMarkItemViewDestroy"),
      (e[(e.OnMarkItemViewEnter = 1126)] = "OnMarkItemViewEnter"),
      (e[(e.OnMarkItemViewExit = 1127)] = "OnMarkItemViewExit"),
      (e[(e.OnOpenSystemFeed = 1128)] = "OnOpenSystemFeed"),
      (e[(e.OnCloseSystemFeed = 1129)] = "OnCloseSystemFeed"),
      (e[(e.OnDeliveryProps = 1130)] = "OnDeliveryProps"),
      (e[(e.OnWorldMapTrackMarkItem = 1131)] = "OnWorldMapTrackMarkItem"),
      (e[(e.OnSundialRingChangeShine = 1132)] = "OnSundialRingChangeShine"),
      (e[(e.OnSundialRingSwitch = 1133)] = "OnSundialRingSwitch"),
      (e[(e.OnNeedUpdateSundialTips = 1134)] = "OnNeedUpdateSundialTips"),
      (e[(e.OnSignalDeviceLinkingCheck = 1135)] = "OnSignalDeviceLinkingCheck"),
      (e[(e.OnSignalDeviceReset = 1136)] = "OnSignalDeviceReset"),
      (e[(e.OnSignalDeviceLinking = 1137)] = "OnSignalDeviceLinking"),
      (e[(e.OnSignalDeviceFinish = 1138)] = "OnSignalDeviceFinish"),
      (e[(e.OnOverlapSceneItemExploreInteractRange = 1139)] =
        "OnOverlapSceneItemExploreInteractRange"),
      (e[(e.OnUseMapExploreToolSuccess = 1140)] = "OnUseMapExploreToolSuccess"),
      (e[(e.OnMapExploreToolPlaceNumUpdated = 1141)] =
        "OnMapExploreToolPlaceNumUpdated"),
      (e[(e.DoLeaveLevel = 1142)] = "DoLeaveLevel"),
      (e[(e.ClearSceneBegin = 1143)] = "ClearSceneBegin"),
      (e[(e.OnExploreProgressResponse = 1144)] = "OnExploreProgressResponse"),
      (e[(e.OnExploreScoreRewardResponse = 1145)] =
        "OnExploreScoreRewardResponse"),
      (e[(e.OnCountryExploreScoreInfoResponse = 1146)] =
        "OnCountryExploreScoreInfoResponse"),
      (e[(e.OnExploreLevelNotify = 1147)] = "OnExploreLevelNotify"),
      (e[(e.OnSignalCatchSuccess = 1148)] = "OnSignalCatchSuccess"),
      (e[(e.OnSignalCatchFailed = 1149)] = "OnSignalCatchFailed"),
      (e[(e.OnSignalCatchStart = 1150)] = "OnSignalCatchStart"),
      (e[(e.OnSignalCatchContinue = 1151)] = "OnSignalCatchContinue"),
      (e[(e.OnSignalCatchStartAgain = 1152)] = "OnSignalCatchStartAgain"),
      (e[(e.RefreshMonthCardRedDot = 1153)] = "RefreshMonthCardRedDot"),
      (e[(e.OnSetJoystickMode = 1154)] = "OnSetJoystickMode"),
      (e[(e.OnOverlapEncloseSpace = 1155)] = "OnOverlapEncloseSpace"),
      (e[(e.OnEncloseSpaceTypeChange = 1156)] = "OnEncloseSpaceTypeChange"),
      (e[(e.OnAndroidConfigurationChange = 1157)] =
        "OnAndroidConfigurationChange"),
      (e[(e.OnChatPlayerInfoChanged = 1158)] = "OnChatPlayerInfoChanged"),
      (e[(e.OnPlotTransitionRemoveCallback = 1159)] =
        "OnPlotTransitionRemoveCallback"),
      (e[(e.OnEnterOrExitExecutionRange = 1160)] =
        "OnEnterOrExitExecutionRange"),
      (e[(e.OnExecutionOptionChange = 1161)] = "OnExecutionOptionChange"),
      (e[(e.OnInteractActionEnd = 1162)] = "OnInteractActionEnd"),
      (e[(e.OnLevelFuncFlagSet = 1163)] = "OnLevelFuncFlagSet"),
      (e[(e.OnLevelFuncFlagChanged = 1164)] = "OnLevelFuncFlagChanged"),
      (e[(e.OnRefreshRewardView = 1165)] = "OnRefreshRewardView"),
      (e[(e.OnRefreshSpecialItemAllowReqUse = 1166)] =
        "OnRefreshSpecialItemAllowReqUse"),
      (e[(e.OnQueryProductInfo = 1167)] = "OnQueryProductInfo"),
      (e[(e.ReconnectClearData = 1168)] = "ReconnectClearData"),
      (e[(e.OnPreEndPIE = 1169)] = "OnPreEndPIE"),
      (e[(e.NoticeJourneyReceive = 1170)] = "NoticeJourneyReceive"),
      (e[(e.OnEntityInOutRangeLocal = 1171)] = "OnEntityInOutRangeLocal"),
      (e[(e.OnMyPlayerInOutRangeLocal = 1172)] = "OnMyPlayerInOutRangeLocal"),
      (e[(e.OnActorInOutRangeLocal = 1173)] = "OnActorInOutRangeLocal"),
      (e[(e.OnEntityInOutRangeOnline = 1174)] = "OnEntityInOutRangeOnline"),
      (e[(e.OnPlayerInOutRangeOnline = 1175)] = "OnPlayerInOutRangeOnline"),
      (e[(e.OnSetLoginServerId = 1176)] = "OnSetLoginServerId"),
      (e[(e.SetDecalShadowEnabled = 1177)] = "SetDecalShadowEnabled"),
      (e[(e.OnSelectTimePreset = 1178)] = "OnSelectTimePreset"),
      (e[(e.OnActionKeyChanged = 1179)] = "OnActionKeyChanged"),
      (e[(e.OnAxisKeyChanged = 1180)] = "OnAxisKeyChanged"),
      (e[(e.BeamCastStart = 1181)] = "BeamCastStart"),
      (e[(e.BeamCastStop = 1182)] = "BeamCastStop"),
      (e[(e.OnResetPhotographCamera = 1183)] = "OnResetPhotographCamera"),
      (e[(e.OnSpecialItemNotAllow = 1184)] = "OnSpecialItemNotAllow"),
      (e[(e.OnMarkItemShowStateChange = 1185)] = "OnMarkItemShowStateChange"),
      (e[(e.OnAbsoluteTimeStop = 1186)] = "OnAbsoluteTimeStop"),
      (e[(e.OnFightTestEnd = 1187)] = "OnFightTestEnd"),
      (e[(e.OnManipulateShowLandTips = 1188)] = "OnManipulateShowLandTips"),
      (e[(e.BeforeUiModelLoadStart = 1189)] = "BeforeUiModelLoadStart"),
      (e[(e.OnUiModelRoleConfigIdChange = 1190)] =
        "OnUiModelRoleConfigIdChange"),
      (e[(e.OnUiModelRoleDataIdChange = 1191)] = "OnUiModelRoleDataIdChange"),
      (e[(e.OnUiModelLoadComplete = 1192)] = "OnUiModelLoadComplete"),
      (e[(e.OnUiModelVisibleChange = 1193)] = "OnUiModelVisibleChange"),
      (e[(e.OnUiModelSetDitherEffect = 1194)] = "OnUiModelSetDitherEffect"),
      (e[(e.WorldMapSubMapChanged = 1195)] = "WorldMapSubMapChanged"),
      (e[(e.WorldMapSelectMultiMap = 1196)] = "WorldMapSelectMultiMap"),
      (e[(e.RoguelikePopularEntriesChange = 1197)] =
        "RoguelikePopularEntriesChange"),
      (e[(e.OnSceneItemMoveEventBroken = 1198)] = "OnSceneItemMoveEventBroken"),
      (e[(e.OnFragmentMemoryDataUpdate = 1199)] = "OnFragmentMemoryDataUpdate"),
      (e[(e.OnFragmentMemoryCollectUpdate = 1200)] =
        "OnFragmentMemoryCollectUpdate"),
      (e[(e.OnFragmentTopicSelect = 1201)] = "OnFragmentTopicSelect"),
      (e[(e.OnFragmentTopicClick = 1202)] = "OnFragmentTopicClick"),
      (e[(e.FragmentRewardRedDot = 1203)] = "FragmentRewardRedDot"),
      (e[(e.FragmentRewardTopicRedDot = 1204)] = "FragmentRewardTopicRedDot"),
      (e[(e.FragmentRewardEntranceRedDot = 1205)] =
        "FragmentRewardEntranceRedDot"),
      (e[(e.OnChangeBossRushBuff = 1206)] = "OnChangeBossRushBuff"),
      (e[(e.RequestChangeBossRushView = 1207)] = "RequestChangeBossRushView"),
      (e[(e.BossRushDataUpdate = 1208)] = "BossRushDataUpdate"),
      (e[(e.BossRefreshBossRushRewardRedDot = 1209)] =
        "BossRefreshBossRushRewardRedDot"),
      (e[(e.OnSetGameModeDataDone = 1210)] = "OnSetGameModeDataDone"),
      (e[(e.OnBossRushBuffViewOpened = 1211)] = "OnBossRushBuffViewOpened"),
      (e[(e.OnTutorialTipExistChanged = 1212)] = "OnTutorialTipExistChanged"),
      (e[(e.OnTutorialUpdate = 1213)] = "OnTutorialUpdate"),
      (e[(e.LevelLoadingLockTimeDilation = 1214)] =
        "LevelLoadingLockTimeDilation"),
      (e[(e.LevelLoadingUnlockDilation = 1215)] = "LevelLoadingUnlockDilation");
  })((EEventName = exports.EEventName || (exports.EEventName = {})));
//# sourceMappingURL=EventDefine.js.map
