"use strict";
var EEventName;
Object.defineProperty(exports, "__esModule", { value: !0 }),
  (exports.EEventName = void 0),
  (function (e) {
    (e[(e.SetEntityCreatureDataRelation = 0)] =
      "SetEntityCreatureDataRelation"),
      (e[(e.KeyClick = 1)] = "KeyClick"),
      (e[(e.UiSceneLoaded = 2)] = "UiSceneLoaded"),
      (e[(e.UiSceneStartLoad = 3)] = "UiSceneStartLoad"),
      (e[(e.OpenView = 4)] = "OpenView"),
      (e[(e.StackPreOpenView = 5)] = "StackPreOpenView"),
      (e[(e.StackOpenView = 6)] = "StackOpenView"),
      (e[(e.StackCloseView = 7)] = "StackCloseView"),
      (e[(e.OpenViewBegined = 8)] = "OpenViewBegined"),
      (e[(e.OpenViewFail = 9)] = "OpenViewFail"),
      (e[(e.CreateViewInstance = 10)] = "CreateViewInstance"),
      (e[(e.OnViewLoadCompleted = 11)] = "OnViewLoadCompleted"),
      (e[(e.OnViewDone = 12)] = "OnViewDone"),
      (e[(e.OnViewHidden = 13)] = "OnViewHidden"),
      (e[(e.CloseView = 14)] = "CloseView"),
      (e[(e.OpenTabView = 15)] = "OpenTabView"),
      (e[(e.TriggerUiTimeDilation = 16)] = "TriggerUiTimeDilation"),
      (e[(e.CloseTabView = 17)] = "CloseTabView"),
      (e[(e.ChangeChildView = 18)] = "ChangeChildView"),
      (e[(e.UiManagerInit = 19)] = "UiManagerInit"),
      (e[(e.UiManagerDestroy = 20)] = "UiManagerDestroy"),
      (e[(e.HotKeyInput = 21)] = "HotKeyInput"),
      (e[(e.ViewHotKeyInputPress = 22)] = "ViewHotKeyInputPress"),
      (e[(e.ViewHotKeyInputRelease = 23)] = "ViewHotKeyInputRelease"),
      (e[(e.ResetNormalAction = 24)] = "ResetNormalAction"),
      (e[(e.UnBlockCharacterAction = 25)] = "UnBlockCharacterAction"),
      (e[(e.ResetSystemAction = 26)] = "ResetSystemAction"),
      (e[(e.OnReduceDamageViewDepth = 27)] = "OnReduceDamageViewDepth"),
      (e[(e.LoginSuccess = 28)] = "LoginSuccess"),
      (e[(e.EnterGameSuccess = 29)] = "EnterGameSuccess"),
      (e[(e.LoginStatusChange = 30)] = "LoginStatusChange"),
      (e[(e.LoginRequestResult = 31)] = "LoginRequestResult"),
      (e[(e.SdkLoginResult = 32)] = "SdkLoginResult"),
      (e[(e.OnGetLoginPlayerInfo = 33)] = "OnGetLoginPlayerInfo"),
      (e[(e.OnSelectServerItem = 34)] = "OnSelectServerItem"),
      (e[(e.OnConfirmServerItem = 35)] = "OnConfirmServerItem"),
      (e[(e.SendHeartbeat = 36)] = "SendHeartbeat"),
      (e[(e.SdkInitDone = 37)] = "SdkInitDone"),
      (e[(e.CharQteActive = 38)] = "CharQteActive"),
      (e[(e.CharQteConsume = 39)] = "CharQteConsume"),
      (e[(e.CharInQteChanged = 40)] = "CharInQteChanged"),
      (e[(e.CharExecuteMultiQte = 41)] = "CharExecuteMultiQte"),
      (e[(e.CharQteTagRowNameChanged = 42)] = "CharQteTagRowNameChanged"),
      (e[(e.CharHitLocal = 43)] = "CharHitLocal"),
      (e[(e.CharHitRemote = 44)] = "CharHitRemote"),
      (e[(e.CharBeHitLocal = 45)] = "CharBeHitLocal"),
      (e[(e.CharHitIncludingVision = 46)] = "CharHitIncludingVision"),
      (e[(e.CharBeHitRemote = 47)] = "CharBeHitRemote"),
      (e[(e.CharLimitDodge = 48)] = "CharLimitDodge"),
      (e[(e.CharBeHitAnim = 49)] = "CharBeHitAnim"),
      (e[(e.CharBeHitTimeScale = 50)] = "CharBeHitTimeScale"),
      (e[(e.CharShieldChange = 51)] = "CharShieldChange"),
      (e[(e.CharAnimBreakPoint = 52)] = "CharAnimBreakPoint"),
      (e[(e.CharBeforeSkillWithTarget = 53)] = "CharBeforeSkillWithTarget"),
      (e[(e.CharUseSkill = 54)] = "CharUseSkill"),
      (e[(e.OnSkillEnd = 55)] = "OnSkillEnd"),
      (e[(e.OnMultiSkillIdChanged = 56)] = "OnMultiSkillIdChanged"),
      (e[(e.OnMultiSkillEnable = 57)] = "OnMultiSkillEnable"),
      (e[(e.CharSwitchControl = 58)] = "CharSwitchControl"),
      (e[(e.CharInputPress = 59)] = "CharInputPress"),
      (e[(e.CharInputHold = 60)] = "CharInputHold"),
      (e[(e.CharSkillTargetChanged = 61)] = "CharSkillTargetChanged"),
      (e[(e.CharDeleteSkill = 62)] = "CharDeleteSkill"),
      (e[(e.CharResetSkill = 63)] = "CharResetSkill"),
      (e[(e.CharInterruptSkill = 64)] = "CharInterruptSkill"),
      (e[(e.CharSkillCountChanged = 65)] = "CharSkillCountChanged"),
      (e[(e.CharSkillRemainCdChanged = 66)] = "CharSkillRemainCdChanged"),
      (e[(e.CharSkillCdPauseStateChanged = 67)] =
        "CharSkillCdPauseStateChanged"),
      (e[(e.CharClearSkill = 68)] = "CharClearSkill"),
      (e[(e.CharDamage = 69)] = "CharDamage"),
      (e[(e.CharBeDamage = 70)] = "CharBeDamage"),
      (e[(e.GlobalCharDamage = 71)] = "GlobalCharDamage"),
      (e[(e.FormationPanelUIShowRoleHeal = 72)] =
        "FormationPanelUIShowRoleHeal"),
      (e[(e.CharPartDamage = 73)] = "CharPartDamage"),
      (e[(e.CharClimbStartExit = 74)] = "CharClimbStartExit"),
      (e[(e.CharActivateClimbInput = 75)] = "CharActivateClimbInput"),
      (e[(e.CharClimbJumpCheck = 76)] = "CharClimbJumpCheck"),
      (e[(e.CustomMoveSwim = 77)] = "CustomMoveSwim"),
      (e[(e.CustomMoveSlide = 78)] = "CustomMoveSlide"),
      (e[(e.CustomMoveSki = 79)] = "CustomMoveSki"),
      (e[(e.CustomMoveWalkOnWater = 80)] = "CustomMoveWalkOnWater"),
      (e[(e.CustomMoveClimb = 81)] = "CustomMoveClimb"),
      (e[(e.CustomMoveGlide = 82)] = "CustomMoveGlide"),
      (e[(e.CustomMovePendulum = 83)] = "CustomMovePendulum"),
      (e[(e.CustomMoveCatapult = 84)] = "CustomMoveCatapult"),
      (e[(e.CustomMoveSoar = 85)] = "CustomMoveSoar"),
      (e[(e.CharTurnBegin = 86)] = "CharTurnBegin"),
      (e[(e.CharTurnEnd = 87)] = "CharTurnEnd"),
      (e[(e.CharMovementModeChanged = 88)] = "CharMovementModeChanged"),
      (e[(e.CharActivate = 89)] = "CharActivate"),
      (e[(e.CharOnAttrChanged = 90)] = "CharOnAttrChanged"),
      (e[(e.CharGravityDirectChanged = 91)] = "CharGravityDirectChanged"),
      (e[(e.CharOnRoleDrown = 92)] = "CharOnRoleDrown"),
      (e[(e.CharOnRoleDrownInjure = 93)] = "CharOnRoleDrownInjure"),
      (e[(e.CharOnEnergyChanged = 94)] = "CharOnEnergyChanged"),
      (e[(e.CharOnHealthChanged = 95)] = "CharOnHealthChanged"),
      (e[(e.CharOnHealthMaxChanged = 96)] = "CharOnHealthMaxChanged"),
      (e[(e.CharOnElementEnergyChanged = 97)] = "CharOnElementEnergyChanged"),
      (e[(e.CharOnUnifiedMoveStateChanged = 98)] =
        "CharOnUnifiedMoveStateChanged"),
      (e[(e.CharOnPositionStateChanged = 99)] = "CharOnPositionStateChanged"),
      (e[(e.CharOnDirectionStateChanged = 100)] =
        "CharOnDirectionStateChanged"),
      (e[(e.CharOnPositionSubStateChanged = 101)] =
        "CharOnPositionSubStateChanged"),
      (e[(e.CharSwimStrengthChanged = 102)] = "CharSwimStrengthChanged"),
      (e[(e.RoleOnStateInherit = 103)] = "RoleOnStateInherit"),
      (e[(e.CharOnEndPlay = 104)] = "CharOnEndPlay"),
      (e[(e.CharOnBuffAddUITexture = 105)] = "CharOnBuffAddUITexture"),
      (e[(e.CharOnBuffAddUIPrefab = 106)] = "CharOnBuffAddUIPrefab"),
      (e[(e.CharOnBuffAddUIDamage = 107)] = "CharOnBuffAddUIDamage"),
      (e[(e.CharOnAnimNotifyStateDurationChange = 108)] =
        "CharOnAnimNotifyStateDurationChange"),
      (e[(e.CharOnLand = 109)] = "CharOnLand"),
      (e[(e.CharPossessed = 110)] = "CharPossessed"),
      (e[(e.CharUnpossessed = 111)] = "CharUnpossessed"),
      (e[(e.CharChangeMeshAnim = 112)] = "CharChangeMeshAnim"),
      (e[(e.CharRecordOperate = 113)] = "CharRecordOperate"),
      (e[(e.CharOnRoleDead = 114)] = "CharOnRoleDead"),
      (e[(e.CharOnRoleDeadTargetSelf = 115)] = "CharOnRoleDeadTargetSelf"),
      (e[(e.OnRevive = 116)] = "OnRevive"),
      (e[(e.CharOnRevive = 117)] = "CharOnRevive"),
      (e[(e.OnTeamLivingStateChange = 118)] = "OnTeamLivingStateChange"),
      (e[(e.CharOnSetNewBeHit = 119)] = "CharOnSetNewBeHit"),
      (e[(e.OnBattleStateChanged = 120)] = "OnBattleStateChanged"),
      (e[(e.OnChangeWalkOrRun = 121)] = "OnChangeWalkOrRun"),
      (e[(e.CharOnFallInjure = 122)] = "CharOnFallInjure"),
      (e[(e.ChangeAiTeamLevel = 123)] = "ChangeAiTeamLevel"),
      (e[(e.AiHateAddOrRemove = 124)] = "AiHateAddOrRemove"),
      (e[(e.AiInFight = 125)] = "AiInFight"),
      (e[(e.AiHateTargetChanged = 126)] = "AiHateTargetChanged"),
      (e[(e.AiTauntAddOrRemove = 127)] = "AiTauntAddOrRemove"),
      (e[(e.AiTaskWanderForResetEnd = 128)] = "AiTaskWanderForResetEnd"),
      (e[(e.OnRunBehaviorTree = 129)] = "OnRunBehaviorTree"),
      (e[(e.OnAiEnable = 130)] = "OnAiEnable"),
      (e[(e.OnAiDisable = 131)] = "OnAiDisable"),
      (e[(e.CloseItemTips = 132)] = "CloseItemTips"),
      (e[(e.CreateRoleForwardAnimEnd = 133)] = "CreateRoleForwardAnimEnd"),
      (e[(e.CreateRoleShowInputName = 134)] = "CreateRoleShowInputName"),
      (e[(e.GuideFinish = 135)] = "GuideFinish"),
      (e[(e.GuideGroupOpening = 136)] = "GuideGroupOpening"),
      (e[(e.GuideGroupFinished = 137)] = "GuideGroupFinished"),
      (e[(e.GuideGroupBreak = 138)] = "GuideGroupBreak"),
      (e[(e.GuideGroupRest = 139)] = "GuideGroupRest"),
      (e[(e.GuideFocusNeedUiTabView = 140)] = "GuideFocusNeedUiTabView"),
      (e[(e.FinishGuideStepByEvent = 141)] = "FinishGuideStepByEvent"),
      (e[(e.GuideTouchIdInject = 142)] = "GuideTouchIdInject"),
      (e[(e.OnRefreshRoleHp = 143)] = "OnRefreshRoleHp"),
      (e[(e.BeforeLoadMap = 144)] = "BeforeLoadMap"),
      (e[(e.BeforeTravelMap = 145)] = "BeforeTravelMap"),
      (e[(e.EndTravelMap = 146)] = "EndTravelMap"),
      (e[(e.OnEnterTransitionMap = 147)] = "OnEnterTransitionMap"),
      (e[(e.AfterLoadMap = 148)] = "AfterLoadMap"),
      (e[(e.ClearWorld = 149)] = "ClearWorld"),
      (e[(e.WorldDone = 150)] = "WorldDone"),
      (e[(e.WorldDoneAndCloseLoading = 151)] = "WorldDoneAndCloseLoading"),
      (e[(e.ChangeMode = 152)] = "ChangeMode"),
      (e[(e.ChangeModeFinish = 153)] = "ChangeModeFinish"),
      (e[(e.ChangePerformanceLimitMode = 154)] = "ChangePerformanceLimitMode"),
      (e[(e.PauseGame = 155)] = "PauseGame"),
      (e[(e.OnChangeRole = 156)] = "OnChangeRole"),
      (e[(e.OnOtherChangeRole = 157)] = "OnOtherChangeRole"),
      (e[(e.OnChangeRoleCoolDownChanged = 158)] =
        "OnChangeRoleCoolDownChanged"),
      (e[(e.OnRoleGoDown = 159)] = "OnRoleGoDown"),
      (e[(e.OnRoleGoDownFinish = 160)] = "OnRoleGoDownFinish"),
      (e[(e.OnClearFollowData = 161)] = "OnClearFollowData"),
      (e[(e.InitArea = 162)] = "InitArea"),
      (e[(e.ChangeArea = 163)] = "ChangeArea"),
      (e[(e.UpdateAreaView = 164)] = "UpdateAreaView"),
      (e[(e.CreateEntity = 165)] = "CreateEntity"),
      (e[(e.CreateEntityFail = 166)] = "CreateEntityFail"),
      (e[(e.AddEntity = 167)] = "AddEntity"),
      (e[(e.FixBornLocation = 168)] = "FixBornLocation"),
      (e[(e.CharBornFinished = 169)] = "CharBornFinished"),
      (e[(e.PreloadEntityFinished = 170)] = "PreloadEntityFinished"),
      (e[(e.DelayRemoveEntityFinished = 171)] = "DelayRemoveEntityFinished"),
      (e[(e.RemoveEntity = 172)] = "RemoveEntity"),
      (e[(e.EntityOnLandedPush = 173)] = "EntityOnLandedPush"),
      (e[(e.SpawnBoss = 174)] = "SpawnBoss"),
      (e[(e.OnUpdateTeamGroupType = 175)] = "OnUpdateTeamGroupType"),
      (e[(e.OnUpdateSceneTeam = 176)] = "OnUpdateSceneTeam"),
      (e[(e.OnItemDecompose = 177)] = "OnItemDecompose"),
      (e[(e.OnItemLock = 178)] = "OnItemLock"),
      (e[(e.OnGetReward = 179)] = "OnGetReward"),
      (e[(e.OnReceivePlayerVar = 180)] = "OnReceivePlayerVar"),
      (e[(e.OpenItemInfo = 181)] = "OpenItemInfo"),
      (e[(e.CloseItemInfo = 182)] = "CloseItemInfo"),
      (e[(e.BoughtItem = 183)] = "BoughtItem"),
      (e[(e.ShopUpdate = 184)] = "ShopUpdate"),
      (e[(e.OnShopInfoResponded = 185)] = "OnShopInfoResponded"),
      (e[(e.OnGoodUnlock = 186)] = "OnGoodUnlock"),
      (e[(e.SelectedMail = 187)] = "SelectedMail"),
      (e[(e.PickingAttachment = 188)] = "PickingAttachment"),
      (e[(e.DeletingMail = 189)] = "DeletingMail"),
      (e[(e.DeletingMailPassively = 190)] = "DeletingMailPassively"),
      (e[(e.AddingNewMail = 191)] = "AddingNewMail"),
      (e[(e.SwitchUnfinishedFlag = 192)] = "SwitchUnfinishedFlag"),
      (e[(e.CloseMailView = 193)] = "CloseMailView"),
      (e[(e.OnlyCloseMailContentView = 194)] = "OnlyCloseMailContentView"),
      (e[(e.SceneBulletOwnerCreated = 195)] = "SceneBulletOwnerCreated"),
      (e[(e.BulletCreate = 196)] = "BulletCreate"),
      (e[(e.BulletDestroy = 197)] = "BulletDestroy"),
      (e[(e.BulletHit = 198)] = "BulletHit"),
      (e[(e.BulletRebound = 199)] = "BulletRebound"),
      (e[(e.BulletHitSpecialCharacter = 200)] = "BulletHitSpecialCharacter"),
      (e[(e.ScenePlayerChanged = 201)] = "ScenePlayerChanged"),
      (e[(e.ScenePlayerLocationChanged = 202)] = "ScenePlayerLocationChanged"),
      (e[(e.ScenePlayerLeaveScene = 203)] = "ScenePlayerLeaveScene"),
      (e[(e.ScenePlayerMarkItemStateChange = 204)] =
        "ScenePlayerMarkItemStateChange"),
      (e[(e.MatchTeamFlagChange = 205)] = "MatchTeamFlagChange"),
      (e[(e.LoadingViewProgressSequenceEnd = 206)] =
        "LoadingViewProgressSequenceEnd"),
      (e[(e.DestroyAllUiCameraAnimationHandles = 207)] =
        "DestroyAllUiCameraAnimationHandles"),
      (e[(e.RoleSelectionListUpdate = 208)] = "RoleSelectionListUpdate"),
      (e[(e.SelectRole = 209)] = "SelectRole"),
      (e[(e.SelectSkill = 210)] = "SelectSkill"),
      (e[(e.SelectLevelUpItemCount = 211)] = "SelectLevelUpItemCount"),
      (e[(e.SelectLevelUpItem = 212)] = "SelectLevelUpItem"),
      (e[(e.RoleInfoUpdate = 213)] = "RoleInfoUpdate"),
      (e[(e.RoleRefreshAttribute = 214)] = "RoleRefreshAttribute"),
      (e[(e.RoleSkillLevelUp = 215)] = "RoleSkillLevelUp"),
      (e[(e.RoleLevelUp = 216)] = "RoleLevelUp"),
      (e[(e.RoleLevelUpReceiveItem = 217)] = "RoleLevelUpReceiveItem"),
      (e[(e.RoleBreakUp = 218)] = "RoleBreakUp"),
      (e[(e.ActiveRole = 219)] = "ActiveRole"),
      (e[(e.RoleResonUplevel = 220)] = "RoleResonUplevel"),
      (e[(e.RoleResonActive = 221)] = "RoleResonActive"),
      (e[(e.RoleResonAnimationSuccess = 222)] = "RoleResonAnimationSuccess"),
      (e[(e.RoleResonPlayAnimation = 223)] = "RoleResonPlayAnimation"),
      (e[(e.CloseRoleView = 224)] = "CloseRoleView"),
      (e[(e.SelectedResonanceTab = 225)] = "SelectedResonanceTab"),
      (e[(e.UnSelectedResonanceTab = 226)] = "UnSelectedResonanceTab"),
      (e[(e.SwitchRootTabState = 227)] = "SwitchRootTabState"),
      (e[(e.RoleRefreshName = 228)] = "RoleRefreshName"),
      (e[(e.RoleSystemChangeRole = 229)] = "RoleSystemChangeRole"),
      (e[(e.OnSelectedRoleChanged = 230)] = "OnSelectedRoleChanged"),
      (e[(e.ChangeResonance = 231)] = "ChangeResonance"),
      (e[(e.OnRoleInternalViewEnter = 232)] = "OnRoleInternalViewEnter"),
      (e[(e.OnRoleInternalViewQuit = 233)] = "OnRoleInternalViewQuit"),
      (e[(e.AttributeComponentEvent = 234)] = "AttributeComponentEvent"),
      (e[(e.UpdateRoleLevelUpViewData = 235)] = "UpdateRoleLevelUpViewData"),
      (e[(e.UpdateRoleResonanceDetailView = 236)] =
        "UpdateRoleResonanceDetailView"),
      (e[(e.UpdateRoleSkillView = 237)] = "UpdateRoleSkillView"),
      (e[(e.UpdateRoleSkillLevelUpView = 238)] = "UpdateRoleSkillLevelUpView"),
      (e[(e.RefreshSkillTreeInfoTabView = 239)] =
        "RefreshSkillTreeInfoTabView"),
      (e[(e.SkillTreeRefresh = 240)] = "SkillTreeRefresh"),
      (e[(e.RefreshSkillTreeLeftSkillPoint = 241)] =
        "RefreshSkillTreeLeftSkillPoint"),
      (e[(e.SkillTreeReset = 242)] = "SkillTreeReset"),
      (e[(e.SkillTreeClickEmpty = 243)] = "SkillTreeClickEmpty"),
      (e[(e.SkillTreeNodeActive = 244)] = "SkillTreeNodeActive"),
      (e[(e.SkillTreeNodeLevelUp = 245)] = "SkillTreeNodeLevelUp"),
      (e[(e.UpdateSkillTreeInfoView = 246)] = "UpdateSkillTreeInfoView"),
      (e[(e.OnSkillTreeNodeToggleClick = 247)] = "OnSkillTreeNodeToggleClick"),
      (e[(e.UpdateRoleFavorData = 248)] = "UpdateRoleFavorData"),
      (e[(e.UnLockRoleFavorItem = 249)] = "UnLockRoleFavorItem"),
      (e[(e.RoleFavorExpChange = 250)] = "RoleFavorExpChange"),
      (e[(e.UpdateRoleFavorHintView = 251)] = "UpdateRoleFavorHintView"),
      (e[(e.RefreshFunctionOpenView = 252)] = "RefreshFunctionOpenView"),
      (e[(e.RoleFindFixHook = 253)] = "RoleFindFixHook"),
      (e[(e.UpdateRoleBreachView = 254)] = "UpdateRoleBreachView"),
      (e[(e.OnClickSkillLevelUp = 255)] = "OnClickSkillLevelUp"),
      (e[(e.OnClickSkillActive = 256)] = "OnClickSkillActive"),
      (e[(e.OnEnterOrExitUltraSkill = 257)] = "OnEnterOrExitUltraSkill"),
      (e[(e.WeaponLevelUp = 258)] = "WeaponLevelUp"),
      (e[(e.WeaponLevelUpReceiveItem = 259)] = "WeaponLevelUpReceiveItem"),
      (e[(e.WeaponCanGoBreach = 260)] = "WeaponCanGoBreach"),
      (e[(e.WeaponItemClick = 261)] = "WeaponItemClick"),
      (e[(e.WeaponEmptyClick = 262)] = "WeaponEmptyClick"),
      (e[(e.WeaponSortClick = 263)] = "WeaponSortClick"),
      (e[(e.WeaponMaterialPropClick = 264)] = "WeaponMaterialPropClick"),
      (e[(e.EquipWeapon = 265)] = "EquipWeapon"),
      (e[(e.ContrastWeapon = 266)] = "ContrastWeapon"),
      (e[(e.WeaponResonanceSuccess = 267)] = "WeaponResonanceSuccess"),
      (e[(e.ReConnectBegin = 268)] = "ReConnectBegin"),
      (e[(e.ReConnectFail = 269)] = "ReConnectFail"),
      (e[(e.CanNotReConnect = 270)] = "CanNotReConnect"),
      (e[(e.ReConnectSuccess = 271)] = "ReConnectSuccess"),
      (e[(e.BackLoginView = 272)] = "BackLoginView"),
      (e[(e.LogOut = 273)] = "LogOut"),
      (e[(e.ExitGamePush = 274)] = "ExitGamePush"),
      (e[(e.NetWorkMaskRpcAdd = 275)] = "NetWorkMaskRpcAdd"),
      (e[(e.NetWorkMaskRpcRemove = 276)] = "NetWorkMaskRpcRemove"),
      (e[(e.OnAimStateChanged = 277)] = "OnAimStateChanged"),
      (e[(e.OnPhantomInputDataUpdate = 278)] = "OnPhantomInputDataUpdate"),
      (e[(e.OpenDragonPoolView = 279)] = "OpenDragonPoolView"),
      (e[(e.UpdateDragonPoolView = 280)] = "UpdateDragonPoolView"),
      (e[(e.LoadMapTileFinish = 281)] = "LoadMapTileFinish"),
      (e[(e.MapOpenAreaChange = 282)] = "MapOpenAreaChange"),
      (e[(e.MapOpenAreaFullUpdate = 283)] = "MapOpenAreaFullUpdate"),
      (e[(e.WorldMapSecondaryUiClosed = 284)] = "WorldMapSecondaryUiClosed"),
      (e[(e.WorldMapSecondaryUiOpened = 285)] = "WorldMapSecondaryUiOpened"),
      (e[(e.BlackScreenFadeOnPlotToWorldMap = 286)] =
        "BlackScreenFadeOnPlotToWorldMap"),
      (e[(e.MarkMenuClickItem = 287)] = "MarkMenuClickItem"),
      (e[(e.RefreshMenuSetting = 288)] = "RefreshMenuSetting"),
      (e[(e.ModelReady = 289)] = "ModelReady"),
      (e[(e.MapReplaceMarkResponse = 290)] = "MapReplaceMarkResponse"),
      (e[(e.CreateMapMark = 291)] = "CreateMapMark"),
      (e[(e.RemoveMapMark = 292)] = "RemoveMapMark"),
      (e[(e.TrackMapMark = 293)] = "TrackMapMark"),
      (e[(e.UnlockTeleport = 294)] = "UnlockTeleport"),
      (e[(e.TrackMark = 295)] = "TrackMark"),
      (e[(e.UnTrackMark = 296)] = "UnTrackMark"),
      (e[(e.ClearTrackMark = 297)] = "ClearTrackMark"),
      (e[(e.MarkForceVisibleChanged = 298)] = "MarkForceVisibleChanged"),
      (e[(e.UpdateTrackTarget = 299)] = "UpdateTrackTarget"),
      (e[(e.SetTrackMarkOccupied = 300)] = "SetTrackMarkOccupied"),
      (e[(e.TeleportComplete = 301)] = "TeleportComplete"),
      (e[(e.TeleportStart = 302)] = "TeleportStart"),
      (e[(e.TeleportStartEntity = 303)] = "TeleportStartEntity"),
      (e[(e.OnEnterDailyQuestNotifyRange = 304)] =
        "OnEnterDailyQuestNotifyRange"),
      (e[(e.OnEnterNearbyTrackRange = 305)] = "OnEnterNearbyTrackRange"),
      (e[(e.OnLeaveNearbyTrackRange = 306)] = "OnLeaveNearbyTrackRange"),
      (e[(e.RemoveNearbyTrack = 307)] = "RemoveNearbyTrack"),
      (e[(e.UpdateNearbyTrackTag = 308)] = "UpdateNearbyTrackTag"),
      (e[(e.OnUpdateNearbyEnable = 309)] = "OnUpdateNearbyEnable"),
      (e[(e.WorldMapViewOpened = 310)] = "WorldMapViewOpened"),
      (e[(e.WorldMapPointerDown = 311)] = "WorldMapPointerDown"),
      (e[(e.WorldMapPointerDrag = 312)] = "WorldMapPointerDrag"),
      (e[(e.WorldMapJoystickMoveForward = 313)] =
        "WorldMapJoystickMoveForward"),
      (e[(e.WorldMapJoystickMoveRight = 314)] = "WorldMapJoystickMoveRight"),
      (e[(e.WorldMapJoystickFocusPlayer = 315)] =
        "WorldMapJoystickFocusPlayer"),
      (e[(e.WorldMapDragInertia = 316)] = "WorldMapDragInertia"),
      (e[(e.WorldMapPointerUp = 317)] = "WorldMapPointerUp"),
      (e[(e.WorldMapFingerExpandClose = 318)] = "WorldMapFingerExpandClose"),
      (e[(e.WorldMapWheelAxisInput = 319)] = "WorldMapWheelAxisInput"),
      (e[(e.WorldMapHandleTriggerAxisInput = 320)] =
        "WorldMapHandleTriggerAxisInput"),
      (e[(e.WorldMapScaleChanged = 321)] = "WorldMapScaleChanged"),
      (e[(e.WorldMapPositionChanged = 322)] = "WorldMapPositionChanged"),
      (e[(e.TaskRangeTrackStateChange = 323)] = "TaskRangeTrackStateChange"),
      (e[(e.RangeTrackStateChanged = 324)] = "RangeTrackStateChanged"),
      (e[(e.GetAreaProgress = 325)] = "GetAreaProgress"),
      (e[(e.PlaySoundTrackEffect = 326)] = "PlaySoundTrackEffect"),
      (e[(e.UpdatePlotSubtitle = 327)] = "UpdatePlotSubtitle"),
      (e[(e.ShowPlotSubtitleOptions = 328)] = "ShowPlotSubtitleOptions"),
      (e[(e.UpdatePlotCenterText = 329)] = "UpdatePlotCenterText"),
      (e[(e.UpdatePortraitVisible = 330)] = "UpdatePortraitVisible"),
      (e[(e.OnStartFlow = 331)] = "OnStartFlow"),
      (e[(e.PlotNetworkStart = 332)] = "PlotNetworkStart"),
      (e[(e.PlotNetworkEnd = 333)] = "PlotNetworkEnd"),
      (e[(e.PlotConfigChanged = 334)] = "PlotConfigChanged"),
      (e[(e.PlotDoingTextShow = 335)] = "PlotDoingTextShow"),
      (e[(e.ClearPlotSubtitle = 336)] = "ClearPlotSubtitle"),
      (e[(e.HidePlotUi = 337)] = "HidePlotUi"),
      (e[(e.PlotInteractViewOpen = 338)] = "PlotInteractViewOpen"),
      (e[(e.TriggerPlotInteraction = 339)] = "TriggerPlotInteraction"),
      (e[(e.TriggerBlackSequence = 340)] = "TriggerBlackSequence"),
      (e[(e.OnBlackFadeScreenStart = 341)] = "OnBlackFadeScreenStart"),
      (e[(e.OnBlackFadeScreenFinish = 342)] = "OnBlackFadeScreenFinish"),
      (e[(e.EnableSkipPlot = 343)] = "EnableSkipPlot"),
      (e[(e.PlotSequencePlay = 344)] = "PlotSequencePlay"),
      (e[(e.HangPlotViewHud = 345)] = "HangPlotViewHud"),
      (e[(e.UpdatePlotUiParam = 346)] = "UpdatePlotUiParam"),
      (e[(e.PlotViewChange = 347)] = "PlotViewChange"),
      (e[(e.PlotViewBgFadePhoto = 348)] = "PlotViewBgFadePhoto"),
      (e[(e.PlotViewBgFadeBlackScreen = 349)] = "PlotViewBgFadeBlackScreen"),
      (e[(e.PlotStartShowTalk = 350)] = "PlotStartShowTalk"),
      (e[(e.PlotEndShowTalk = 351)] = "PlotEndShowTalk"),
      (e[(e.PrewarFormationChanged = 352)] = "PrewarFormationChanged"),
      (e[(e.PrewarReadyChanged = 353)] = "PrewarReadyChanged"),
      (e[(e.DissolvePrewar = 354)] = "DissolvePrewar"),
      (e[(e.SceneStepGroupChanged = 355)] = "SceneStepGroupChanged"),
      (e[(e.InstanceStepChanged = 356)] = "InstanceStepChanged"),
      (e[(e.InstanceEnterCountChanged = 357)] = "InstanceEnterCountChanged"),
      (e[(e.InstanceEntranceUnlock = 358)] = "InstanceEntranceUnlock"),
      (e[(e.EnterInstanceDungeon = 359)] = "EnterInstanceDungeon"),
      (e[(e.LeaveInstanceDungeon = 360)] = "LeaveInstanceDungeon"),
      (e[(e.DungeonGuideChange = 361)] = "DungeonGuideChange"),
      (e[(e.LeaveInstanceDungeonConfirm = 362)] =
        "LeaveInstanceDungeonConfirm"),
      (e[(e.OnDungeonFinish = 363)] = "OnDungeonFinish"),
      (e[(e.OnSelectInstance = 364)] = "OnSelectInstance"),
      (e[(e.OnRefreshEditBattleRoleSlotData = 365)] =
        "OnRefreshEditBattleRoleSlotData"),
      (e[(e.OnRefreshEditBattleRoleReady = 366)] =
        "OnRefreshEditBattleRoleReady"),
      (e[(e.EntityVisionSkillChanged = 367)] = "EntityVisionSkillChanged"),
      (e[(e.GetAllVisionSkill = 368)] = "GetAllVisionSkill"),
      (e[(e.VisionSkillUp = 369)] = "VisionSkillUp"),
      (e[(e.ExploreVisionSkill = 370)] = "ExploreVisionSkill"),
      (e[(e.VisionMorphBegin = 371)] = "VisionMorphBegin"),
      (e[(e.VisionMorphEnd = 372)] = "VisionMorphEnd"),
      (e[(e.VisionMorphInterrupt = 373)] = "VisionMorphInterrupt"),
      (e[(e.AddExploreVisionSkill = 374)] = "AddExploreVisionSkill"),
      (e[(e.ChangeVisionSkillByTab = 375)] = "ChangeVisionSkillByTab"),
      (e[(e.ChangeVisionSimplyState = 376)] = "ChangeVisionSimplyState"),
      (e[(e.VisionSkinViewClose = 377)] = "VisionSkinViewClose"),
      (e[(e.ChangeCalabashCollectSimplyState = 378)] =
        "ChangeCalabashCollectSimplyState"),
      (e[(e.SelectedPhantom = 379)] = "SelectedPhantom"),
      (e[(e.CheckNewUnlock = 380)] = "CheckNewUnlock"),
      (e[(e.PhantomEquip = 381)] = "PhantomEquip"),
      (e[(e.PhantomEquipError = 382)] = "PhantomEquipError"),
      (e[(e.VisionFilterMonster = 383)] = "VisionFilterMonster"),
      (e[(e.OnRolePropUpdate = 384)] = "OnRolePropUpdate"),
      (e[(e.RefreshVisionIntensifyViewBackBtnState = 385)] =
        "RefreshVisionIntensifyViewBackBtnState"),
      (e[(e.OnClickVisionIntensifyItemJump = 386)] =
        "OnClickVisionIntensifyItemJump"),
      (e[(e.VisionIntensifyTabOpen = 387)] = "VisionIntensifyTabOpen"),
      (e[(e.PhantomPersonalSkillActive = 388)] = "PhantomPersonalSkillActive"),
      (e[(e.PhantomEquipWithSourceAndTargetPos = 389)] =
        "PhantomEquipWithSourceAndTargetPos"),
      (e[(e.PhantomCostInsufficient = 390)] = "PhantomCostInsufficient"),
      (e[(e.PhantomExpPreviewChange = 391)] = "PhantomExpPreviewChange"),
      (e[(e.PhantomLevelUp = 392)] = "PhantomLevelUp"),
      (e[(e.PhantomLevelUpWithId = 393)] = "PhantomLevelUpWithId"),
      (e[(e.PhantomLevelUpReceiveItem = 394)] = "PhantomLevelUpReceiveItem"),
      (e[(e.CloseSubPhantomView = 395)] = "CloseSubPhantomView"),
      (e[(e.PhantomBreach = 396)] = "PhantomBreach"),
      (e[(e.PhantomBreachPreview = 397)] = "PhantomBreachPreview"),
      (e[(e.PhantomDecomposePreview = 398)] = "PhantomDecomposePreview"),
      (e[(e.PhantomDecompose = 399)] = "PhantomDecompose"),
      (e[(e.PhantomMaxLevelSkip = 400)] = "PhantomMaxLevelSkip"),
      (e[(e.HideDelFettersText = 401)] = "HideDelFettersText"),
      (e[(e.PhantomRecommendResponse = 402)] = "PhantomRecommendResponse"),
      (e[(e.ClosePhantomSkillTips = 403)] = "ClosePhantomSkillTips"),
      (e[(e.OnPhantomItemUpdate = 404)] = "OnPhantomItemUpdate"),
      (e[(e.OnPhantomSlotUpdate = 405)] = "OnPhantomSlotUpdate"),
      (e[(e.OnPhantomEnableStateChange = 406)] = "OnPhantomEnableStateChange"),
      (e[(e.OnVisionIdentify = 407)] = "OnVisionIdentify"),
      (e[(e.OnVisionIdentifyWithId = 408)] = "OnVisionIdentifyWithId"),
      (e[(e.OnVisionIdentifyDoAnimation = 409)] =
        "OnVisionIdentifyDoAnimation"),
      (e[(e.RefreshVisionIdentifyRedPoint = 410)] =
        "RefreshVisionIdentifyRedPoint"),
      (e[(e.RefreshVisionEquipRedPoint = 411)] = "RefreshVisionEquipRedPoint"),
      (e[(e.JumpToCalabashCollect = 412)] = "JumpToCalabashCollect"),
      (e[(e.JumpToPhantomBattleFettersTabView = 413)] =
        "JumpToPhantomBattleFettersTabView"),
      (e[(e.OnVisionSkinEquip = 414)] = "OnVisionSkinEquip"),
      (e[(e.RedDotRefreshCalabash = 415)] = "RedDotRefreshCalabash"),
      (e[(e.HasCalabashExp = 416)] = "HasCalabashExp"),
      (e[(e.CloseUpgradeCalabashView = 417)] = "CloseUpgradeCalabashView"),
      (e[(e.CloseCalabashExpAddView = 418)] = "CloseCalabashExpAddView"),
      (e[(e.ShowCalabashControllerView = 419)] = "ShowCalabashControllerView"),
      (e[(e.GetCalabashRewardSuccess = 420)] = "GetCalabashRewardSuccess"),
      (e[(e.ShowCalabashUnlockItemTips = 421)] = "ShowCalabashUnlockItemTips"),
      (e[(e.GetCalabashReward = 422)] = "GetCalabashReward"),
      (e[(e.CalabashLevelUpdate = 423)] = "CalabashLevelUpdate"),
      (e[(e.CalabashEnterInternalView = 424)] = "CalabashEnterInternalView"),
      (e[(e.CalabashQuitInternalView = 425)] = "CalabashQuitInternalView"),
      (e[(e.OnVisionRecoveryResult = 426)] = "OnVisionRecoveryResult"),
      (e[(e.OnRefreshCalabashTabShowState = 427)] =
        "OnRefreshCalabashTabShowState"),
      (e[(e.OnSetPartStateVisible = 428)] = "OnSetPartStateVisible"),
      (e[(e.ShowHUD = 429)] = "ShowHUD"),
      (e[(e.HideHUD = 430)] = "HideHUD"),
      (e[(e.OnGetPlayerBasicInfo = 431)] = "OnGetPlayerBasicInfo"),
      (e[(e.OnLoadedNewFlagConfig = 432)] = "OnLoadedNewFlagConfig"),
      (e[(e.OnPlayerLevelChanged = 433)] = "OnPlayerLevelChanged"),
      (e[(e.OnPlayerExpChanged = 434)] = "OnPlayerExpChanged"),
      (e[(e.OnLevelUpLevelRefresh = 435)] = "OnLevelUpLevelRefresh"),
      (e[(e.OnLevelUpExpRefresh = 436)] = "OnLevelUpExpRefresh"),
      (e[(e.OnLevelUpShowLevelOnly = 437)] = "OnLevelUpShowLevelOnly"),
      (e[(e.SelectFilterMultiple = 438)] = "SelectFilterMultiple"),
      (e[(e.SelectFilterSingle = 439)] = "SelectFilterSingle"),
      (e[(e.SelectSort = 440)] = "SelectSort"),
      (e[(e.OnSceneItemHit = 441)] = "OnSceneItemHit"),
      (e[(e.OnSceneItemHitByHitData = 442)] = "OnSceneItemHitByHitData"),
      (e[(e.OnSceneItemEntityHit = 443)] = "OnSceneItemEntityHit"),
      (e[(e.OnSceneItemEntityHitAlways = 444)] = "OnSceneItemEntityHitAlways"),
      (e[(e.OnAnySceneItemEntityHit = 445)] = "OnAnySceneItemEntityHit"),
      (e[(e.OnAnySceneItemDurabilityChange = 446)] =
        "OnAnySceneItemDurabilityChange"),
      (e[(e.OnSceneItemDurabilityChange = 447)] =
        "OnSceneItemDurabilityChange"),
      (e[(e.UpdateSceneItemState = 448)] = "UpdateSceneItemState"),
      (e[(e.OnSceneItemDestroy = 449)] = "OnSceneItemDestroy"),
      (e[(e.OnSceneItemStateChange = 450)] = "OnSceneItemStateChange"),
      (e[(e.OnSceneItemStatePreChange = 451)] = "OnSceneItemStatePreChange"),
      (e[(e.OnSceneItemStatePrechangeInSequence = 452)] =
        "OnSceneItemStatePrechangeInSequence"),
      (e[(e.OnEntityConcealedChange = 453)] = "OnEntityConcealedChange"),
      (e[(e.OnTimeTrackControlUpdate = 454)] = "OnTimeTrackControlUpdate"),
      (e[(e.OnSceneInteractionLoadCompleted = 455)] =
        "OnSceneInteractionLoadCompleted"),
      (e[(e.OnSceneItemVisionCaptureAdd = 456)] =
        "OnSceneItemVisionCaptureAdd"),
      (e[(e.OnSceneItemVisionCaptureRemove = 457)] =
        "OnSceneItemVisionCaptureRemove"),
      (e[(e.OnInputDistributeTagChanged = 458)] =
        "OnInputDistributeTagChanged"),
      (e[(e.ForceReleaseInput = 459)] = "ForceReleaseInput"),
      (e[(e.OnFormationPlayLevelUp = 460)] = "OnFormationPlayLevelUp"),
      (e[(e.OnFormationPlayRevive = 461)] = "OnFormationPlayRevive"),
      (e[(e.OnItemUse = 462)] = "OnItemUse"),
      (e[(e.OnSpecialItemUse = 463)] = "OnSpecialItemUse"),
      (e[(e.OnGameplayTagChanged = 464)] = "OnGameplayTagChanged"),
      (e[(e.OnLevelTagChanged = 465)] = "OnLevelTagChanged"),
      (e[(e.OnGlobalGameplayTagChanged = 466)] = "OnGlobalGameplayTagChanged"),
      (e[(e.LevelEventTriggerExit = 467)] = "LevelEventTriggerExit"),
      (e[(e.OnLevelPlayStateChange = 468)] = "OnLevelPlayStateChange"),
      (e[(e.TodTimeChange = 469)] = "TodTimeChange"),
      (e[(e.DayStateChange = 470)] = "DayStateChange"),
      (e[(e.CrossDay = 471)] = "CrossDay"),
      (e[(e.ClickTimeItem = 472)] = "ClickTimeItem"),
      (e[(e.OnSelectTimeItem = 473)] = "OnSelectTimeItem"),
      (e[(e.AdjustTime = 474)] = "AdjustTime"),
      (e[(e.AdjustTimeInAnim = 475)] = "AdjustTimeInAnim"),
      (e[(e.PowerShopReady = 476)] = "PowerShopReady"),
      (e[(e.OnPowerChanged = 477)] = "OnPowerChanged"),
      (e[(e.OnPowerChangedWithId = 478)] = "OnPowerChangedWithId"),
      (e[(e.OnGamePlayCdChanged = 479)] = "OnGamePlayCdChanged"),
      (e[(e.InsertFloatTips = 480)] = "InsertFloatTips"),
      (e[(e.OriginWorldLevelUp = 481)] = "OriginWorldLevelUp"),
      (e[(e.CurWorldLevelChange = 482)] = "CurWorldLevelChange"),
      (e[(e.WorldLevelUpViewRefresh = 483)] = "WorldLevelUpViewRefresh"),
      (e[(e.OnShowMouseCursor = 484)] = "OnShowMouseCursor"),
      (e[(e.RefreshCursor = 485)] = "RefreshCursor"),
      (e[(e.InputDistribute = 486)] = "InputDistribute"),
      (e[(e.OnRefreshJoinTeamRole = 487)] = "OnRefreshJoinTeamRole"),
      (e[(e.LoadLguiEventSystemActor = 488)] = "LoadLguiEventSystemActor"),
      (e[(e.DestroyLguiEventSystemActor = 489)] =
        "DestroyLguiEventSystemActor"),
      (e[(e.OnUseBuffItem = 490)] = "OnUseBuffItem"),
      (e[(e.UpdateQuestDetails = 491)] = "UpdateQuestDetails"),
      (e[(e.UpdateRoleQuestDetails = 492)] = "UpdateRoleQuestDetails"),
      (e[(e.QuestUpdateInfoAdd = 493)] = "QuestUpdateInfoAdd"),
      (e[(e.AddInteractOptionByAction = 494)] = "AddInteractOptionByAction"),
      (e[(e.RemoveInteractOptionByAction = 495)] =
        "RemoveInteractOptionByAction"),
      (e[(e.OnQuestStateChange = 496)] = "OnQuestStateChange"),
      (e[(e.OnQuestRedDotStateChange = 497)] = "OnQuestRedDotStateChange"),
      (e[(e.OnQuestFinishProtocolEnd = 498)] = "OnQuestFinishProtocolEnd"),
      (e[(e.OnRoleQuestAccept = 499)] = "OnRoleQuestAccept"),
      (e[(e.OnRoleQuestPointChange = 500)] = "OnRoleQuestPointChange"),
      (e[(e.OnRoleQuestNewUnlock = 501)] = "OnRoleQuestNewUnlock"),
      (e[(e.OnAddNewQuest = 502)] = "OnAddNewQuest"),
      (e[(e.OnNavigationQuest = 503)] = "OnNavigationQuest"),
      (e[(e.ActivityQuestCountdownEnd = 504)] = "ActivityQuestCountdownEnd"),
      (e[(e.OnQuestStageNameChange = 505)] = "OnQuestStageNameChange"),
      (e[(e.GeneralLogicTreeWakeUp = 506)] = "GeneralLogicTreeWakeUp"),
      (e[(e.OnLogicTreeNodeStatusChange = 507)] =
        "OnLogicTreeNodeStatusChange"),
      (e[(e.OnLogicTreeChildQuestNodeStatusChange = 508)] =
        "OnLogicTreeChildQuestNodeStatusChange"),
      (e[(e.OnLogicTreeNodeProgressChange = 509)] =
        "OnLogicTreeNodeProgressChange"),
      (e[(e.GeneralLogicTreeTimerInfoChanged = 510)] =
        "GeneralLogicTreeTimerInfoChanged"),
      (e[(e.OnLogicTreeTrackUpdate = 511)] = "OnLogicTreeTrackUpdate"),
      (e[(e.CurTrackQuestUnTrackedCheck = 512)] =
        "CurTrackQuestUnTrackedCheck"),
      (e[(e.OnLogicTreeTimerTick = 513)] = "OnLogicTreeTimerTick"),
      (e[(e.GeneralLogicTreeStartShowTrackText = 514)] =
        "GeneralLogicTreeStartShowTrackText"),
      (e[(e.GeneralLogicTreeUpdateShowTrackText = 515)] =
        "GeneralLogicTreeUpdateShowTrackText"),
      (e[(e.GeneralLogicTreeEndShowTrackText = 516)] =
        "GeneralLogicTreeEndShowTrackText"),
      (e[(e.GeneralLogicTreeRemove = 517)] = "GeneralLogicTreeRemove"),
      (e[(e.GeneralLogicTreeSuspend = 518)] = "GeneralLogicTreeSuspend"),
      (e[(e.GeneralLogicTreeCancelSuspend = 519)] =
        "GeneralLogicTreeCancelSuspend"),
      (e[(e.GeneralLogicTreeRemovePrepareRollbackNode = 520)] =
        "GeneralLogicTreeRemovePrepareRollbackNode"),
      (e[(e.GeneralLogicTreeRollbackWaitingUpdate = 521)] =
        "GeneralLogicTreeRollbackWaitingUpdate"),
      (e[(e.GeneralLogicTreeEntityInteractFinished = 522)] =
        "GeneralLogicTreeEntityInteractFinished"),
      (e[(e.GeneralLogicTreeEntityKilled = 523)] =
        "GeneralLogicTreeEntityKilled"),
      (e[(e.GeneralLogicTreeAddTag = 524)] = "GeneralLogicTreeAddTag"),
      (e[(e.GeneralLogicTreeRemoveTag = 525)] = "GeneralLogicTreeRemoveTag"),
      (e[(e.GeneralLogicTreeViewForceRefresh = 526)] =
        "GeneralLogicTreeViewForceRefresh"),
      (e[(e.GeneralLogicTreeApplyExpressionOccupation = 527)] =
        "GeneralLogicTreeApplyExpressionOccupation"),
      (e[(e.GeneralLogicTreeReleaseExpressionOccupation = 528)] =
        "GeneralLogicTreeReleaseExpressionOccupation"),
      (e[(e.MissionPanelProcessEnd = 529)] = "MissionPanelProcessEnd"),
      (e[(e.QuestUpdateTipsClickTrack = 530)] = "QuestUpdateTipsClickTrack"),
      (e[(e.MissionPanelOut = 531)] = "MissionPanelOut"),
      (e[(e.MissionUpdate = 532)] = "MissionUpdate"),
      (e[(e.MissionUpdateAnimEnd = 533)] = "MissionUpdateAnimEnd"),
      (e[(e.MissionPanelStepTitleAnimStart = 534)] =
        "MissionPanelStepTitleAnimStart"),
      (e[(e.MissionPanelStepTitleAnimEnd = 535)] =
        "MissionPanelStepTitleAnimEnd"),
      (e[(e.ParkourFinished = 536)] = "ParkourFinished"),
      (e[(e.OnOpenDebugCommand = 537)] = "OnOpenDebugCommand"),
      (e[(e.ResetToBattleView = 538)] = "ResetToBattleView"),
      (e[(e.ResetModuleByResetToBattleView = 539)] =
        "ResetModuleByResetToBattleView"),
      (e[(e.ResetModuleAfterResetToBattleView = 540)] =
        "ResetModuleAfterResetToBattleView"),
      (e[(e.ExitNormalQueueState = 541)] = "ExitNormalQueueState"),
      (e[(e.OnStartLoadingState = 542)] = "OnStartLoadingState"),
      (e[(e.OnFinishLoadingState = 543)] = "OnFinishLoadingState"),
      (e[(e.OnOpenLoadingView = 544)] = "OnOpenLoadingView"),
      (e[(e.OnCloseLoadingView = 545)] = "OnCloseLoadingView"),
      (e[(e.OnLoadingNetDataDone = 546)] = "OnLoadingNetDataDone"),
      (e[(e.PlayUiComponentCloseTween = 547)] = "PlayUiComponentCloseTween"),
      (e[(e.ChangeUiComponentMarkId = 548)] = "ChangeUiComponentMarkId"),
      (e[(e.OnMenuDataEnableChanged = 549)] = "OnMenuDataEnableChanged"),
      (e[(e.OnSelectMenuMainType = 550)] = "OnSelectMenuMainType"),
      (e[(e.ChangeConfigValue = 551)] = "ChangeConfigValue"),
      (e[(e.RestartFlag = 552)] = "RestartFlag"),
      (e[(e.SettingFrameRateChanged = 553)] = "SettingFrameRateChanged"),
      (e[(e.TextLanguageChange = 554)] = "TextLanguageChange"),
      (e[(e.ConfigLoadChange = 555)] = "ConfigLoadChange"),
      (e[(e.SneakResult = 556)] = "SneakResult"),
      (e[(e.SneakMonsterStart = 557)] = "SneakMonsterStart"),
      (e[(e.SneakMonsterStop = 558)] = "SneakMonsterStop"),
      (e[(e.ChannelReset = 559)] = "ChannelReset"),
      (e[(e.OnShareResult = 560)] = "OnShareResult"),
      (e[(e.OnFirstShare = 561)] = "OnFirstShare"),
      (e[(e.ShowVideo = 562)] = "ShowVideo"),
      (e[(e.VideoStart = 563)] = "VideoStart"),
      (e[(e.PlayVideo = 564)] = "PlayVideo"),
      (e[(e.ScanTrackedStart = 565)] = "ScanTrackedStart"),
      (e[(e.ScanTrackedEnd = 566)] = "ScanTrackedEnd"),
      (e[(e.OnScanStart = 567)] = "OnScanStart"),
      (e[(e.RedDotStart = 568)] = "RedDotStart"),
      (e[(e.RedDotRefreshItemData = 569)] = "RedDotRefreshItemData"),
      (e[(e.RedDotRoleConfigList = 570)] = "RedDotRoleConfigList"),
      (e[(e.RedDotRefreshPhantomEquip = 571)] = "RedDotRefreshPhantomEquip"),
      (e[(e.RedDotRoleChange = 572)] = "RedDotRoleChange"),
      (e[(e.RedDotUnLockPhantom = 573)] = "RedDotUnLockPhantom"),
      (e[(e.RedDotNewTutorial = 574)] = "RedDotNewTutorial"),
      (e[(e.RedDotNewTutorialType = 575)] = "RedDotNewTutorialType"),
      (e[(e.RedDotAdventureManualUpdate = 576)] =
        "RedDotAdventureManualUpdate"),
      (e[(e.RedDotSilentFirstAward = 577)] = "RedDotSilentFirstAward"),
      (e[(e.RedDotSilentFirstAwardCategory = 578)] =
        "RedDotSilentFirstAwardCategory"),
      (e[(e.RedDotSilentFirstAwardResult = 579)] =
        "RedDotSilentFirstAwardResult"),
      (e[(e.RedDotCreateRole = 580)] = "RedDotCreateRole"),
      (e[(e.RouletteRefreshRedDot = 581)] = "RouletteRefreshRedDot"),
      (e[(e.SilentTipsRefresh = 582)] = "SilentTipsRefresh"),
      (e[(e.OnRefreshElementBallData = 583)] = "OnRefreshElementBallData"),
      (e[(e.ShootTargetStateChanged = 584)] = "ShootTargetStateChanged"),
      (e[(e.InteractNavigation = 585)] = "InteractNavigation"),
      (e[(e.InteractionViewUpdate = 586)] = "InteractionViewUpdate"),
      (e[(e.HideInteractView = 587)] = "HideInteractView"),
      (e[(e.SceneItemInteractionEvent = 588)] = "SceneItemInteractionEvent"),
      (e[(e.OnFunctionOpenSet = 589)] = "OnFunctionOpenSet"),
      (e[(e.OnFunctionOpenUpdate = 590)] = "OnFunctionOpenUpdate"),
      (e[(e.OnFunctionOpenUpdateNotify = 591)] = "OnFunctionOpenUpdateNotify"),
      (e[(e.OnConcertoResponseOpen = 592)] = "OnConcertoResponseOpen"),
      (e[(e.OnFirstOpenShopChanged = 593)] = "OnFirstOpenShopChanged"),
      (e[(e.OnSetHeadStateVisible = 594)] = "OnSetHeadStateVisible"),
      (e[(e.OnSetBossStateVisible = 595)] = "OnSetBossStateVisible"),
      (e[(e.SdkKick = 596)] = "SdkKick"),
      (e[(e.SdkPostWebViewRedPointRefresh = 597)] =
        "SdkPostWebViewRedPointRefresh"),
      (e[(e.SdkCustomerRedPointRefresh = 598)] = "SdkCustomerRedPointRefresh"),
      (e[(e.UpdateFriendViewShow = 599)] = "UpdateFriendViewShow"),
      (e[(e.UpdateRecentlyTeamDataEvent = 600)] =
        "UpdateRecentlyTeamDataEvent"),
      (e[(e.OnRemoveFriend = 601)] = "OnRemoveFriend"),
      (e[(e.FriendApplicationListUpdate = 602)] =
        "FriendApplicationListUpdate"),
      (e[(e.UpdateBlackListShow = 603)] = "UpdateBlackListShow"),
      (e[(e.SearchPlayerInfo = 604)] = "SearchPlayerInfo"),
      (e[(e.FriendRemarkLengthLimit = 605)] = "FriendRemarkLengthLimit"),
      (e[(e.FriendRemarkContainsDirtyWord = 606)] =
        "FriendRemarkContainsDirtyWord"),
      (e[(e.RefreshFriendApplicationRedDot = 607)] =
        "RefreshFriendApplicationRedDot"),
      (e[(e.FriendApplyReceived = 608)] = "FriendApplyReceived"),
      (e[(e.FriendAdded = 609)] = "FriendAdded"),
      (e[(e.LoadTestFriendsByGm = 610)] = "LoadTestFriendsByGm"),
      (e[(e.ApplicationHandled = 611)] = "ApplicationHandled"),
      (e[(e.ApplicationSent = 612)] = "ApplicationSent"),
      (e[(e.OnGetFriendInitData = 613)] = "OnGetFriendInitData"),
      (e[(e.FriendOnMultiItemAction = 614)] = "FriendOnMultiItemAction"),
      (e[(e.OnNavigationViewUiCreated = 615)] = "OnNavigationViewUiCreated"),
      (e[(e.OnUiNavigationViewSetActive = 616)] =
        "OnUiNavigationViewSetActive"),
      (e[(e.InputControllerChange = 617)] = "InputControllerChange"),
      (e[(e.InputControllerMainTypeChange = 618)] =
        "InputControllerMainTypeChange"),
      (e[(e.ShowTypeChange = 619)] = "ShowTypeChange"),
      (e[(e.PointerInputTypeChange = 620)] = "PointerInputTypeChange"),
      (e[(e.ChangeScrollBarPosition = 621)] = "ChangeScrollBarPosition"),
      (e[(e.OnSelectChatFriend = 622)] = "OnSelectChatFriend"),
      (e[(e.OnCreatePrivateChatRoom = 623)] = "OnCreatePrivateChatRoom"),
      (e[(e.OnJoinChatRoom = 624)] = "OnJoinChatRoom"),
      (e[(e.OnAddChatContent = 625)] = "OnAddChatContent"),
      (e[(e.OnRefreshChatRedDot = 626)] = "OnRefreshChatRedDot"),
      (e[(e.OnRefreshChatRoomRedDot = 627)] = "OnRefreshChatRoomRedDot"),
      (e[(e.OnAddHistoryChatContentCompleted = 628)] =
        "OnAddHistoryChatContentCompleted"),
      (e[(e.OnPushChatRowData = 629)] = "OnPushChatRowData"),
      (e[(e.OnPopChatRowData = 630)] = "OnPopChatRowData"),
      (e[(e.OnRefreshChatRowData = 631)] = "OnRefreshChatRowData"),
      (e[(e.OnAddMutePlayer = 632)] = "OnAddMutePlayer"),
      (e[(e.OnRemoveMutePlayer = 633)] = "OnRemoveMutePlayer"),
      (e[(e.OnRemovePrivateChatRoom = 634)] = "OnRemovePrivateChatRoom"),
      (e[(e.OnClosePrivateChatRoom = 635)] = "OnClosePrivateChatRoom"),
      (e[(e.OnOpenChatRoom = 636)] = "OnOpenChatRoom"),
      (e[(e.OnSelectExpression = 637)] = "OnSelectExpression"),
      (e[(e.OnServerAttributeChange = 638)] = "OnServerAttributeChange"),
      (e[(e.OnPayItemSuccess = 639)] = "OnPayItemSuccess"),
      (e[(e.RefreshPayItemList = 640)] = "RefreshPayItemList"),
      (e[(e.RefreshPayGiftList = 641)] = "RefreshPayGiftList"),
      (e[(e.OnPlayerCurrencyChange = 642)] = "OnPlayerCurrencyChange"),
      (e[(e.OnRefreshPermissionsSetting = 643)] =
        "OnRefreshPermissionsSetting"),
      (e[(e.OnRefreshApply = 644)] = "OnRefreshApply"),
      (e[(e.OnSearchWorld = 645)] = "OnSearchWorld"),
      (e[(e.OnRefreshWorldList = 646)] = "OnRefreshWorldList"),
      (e[(e.OnRefreshOnlineTeamList = 647)] = "OnRefreshOnlineTeamList"),
      (e[(e.OnWorldTeamPlayerInfoChanged = 648)] =
        "OnWorldTeamPlayerInfoChanged"),
      (e[(e.OnRefreshPlayerPing = 649)] = "OnRefreshPlayerPing"),
      (e[(e.OnRefreshPlayerUiState = 650)] = "OnRefreshPlayerUiState"),
      (e[(e.OnRefreshOnlineChallengePlayer = 651)] =
        "OnRefreshOnlineChallengePlayer"),
      (e[(e.OnRefreshSuggestChallengePlayerInfo = 652)] =
        "OnRefreshSuggestChallengePlayerInfo"),
      (e[(e.SwitchPayShopTabItem = 653)] = "SwitchPayShopTabItem"),
      (e[(e.PayShopGoodsBuy = 654)] = "PayShopGoodsBuy"),
      (e[(e.GoodsRefreshDiscountTime = 655)] = "GoodsRefreshDiscountTime"),
      (e[(e.SwitchPayShopView = 656)] = "SwitchPayShopView"),
      (e[(e.RefreshPayShop = 657)] = "RefreshPayShop"),
      (e[(e.RefreshAllPayShop = 658)] = "RefreshAllPayShop"),
      (e[(e.RefreshGoods = 659)] = "RefreshGoods"),
      (e[(e.ShopVersionCodeChange = 660)] = "ShopVersionCodeChange"),
      (e[(e.GoodsSoldOut = 661)] = "GoodsSoldOut"),
      (e[(e.RefreshGoodsList = 662)] = "RefreshGoodsList"),
      (e[(e.UnLockGoods = 663)] = "UnLockGoods"),
      (e[(e.DiscountShopTimerRefresh = 664)] = "DiscountShopTimerRefresh"),
      (e[(e.OnOpenGachaChanged = 665)] = "OnOpenGachaChanged"),
      (e[(e.RefreshGachaMainView = 666)] = "RefreshGachaMainView"),
      (e[(e.GachaPoolSelectResponse = 667)] = "GachaPoolSelectResponse"),
      (e[(e.GachaResponse = 668)] = "GachaResponse"),
      (e[(e.GachaHistoryResponse = 669)] = "GachaHistoryResponse"),
      (e[(e.CloseGachaSceneView = 670)] = "CloseGachaSceneView"),
      (e[(e.EndGachaScene = 671)] = "EndGachaScene"),
      (e[(e.GachaClick = 672)] = "GachaClick"),
      (e[(e.GachaSelectionViewRefresh = 673)] = "GachaSelectionViewRefresh"),
      (e[(e.AfterCloseGachaScene = 674)] = "AfterCloseGachaScene"),
      (e[(e.PlaySequenceEventByStringParam = 675)] =
        "PlaySequenceEventByStringParam"),
      (e[(e.GachaInteractFinish = 676)] = "GachaInteractFinish"),
      (e[(e.ItemExChangeResponse = 677)] = "ItemExChangeResponse"),
      (e[(e.ItemHintVisibilityChange = 678)] = "ItemHintVisibilityChange"),
      (e[(e.ShowAnimalsHeadInfo = 679)] = "ShowAnimalsHeadInfo"),
      (e[(e.OnAnimalDying = 680)] = "OnAnimalDying"),
      (e[(e.OnSkillButtonDataRefresh = 681)] = "OnSkillButtonDataRefresh"),
      (e[(e.OnSkillButtonDataClear = 682)] = "OnSkillButtonDataClear"),
      (e[(e.OnSkillButtonIndexRefresh = 683)] = "OnSkillButtonIndexRefresh"),
      (e[(e.OnSkillButtonEnableRefresh = 684)] = "OnSkillButtonEnableRefresh"),
      (e[(e.OnSkillButtonVisibleRefresh = 685)] =
        "OnSkillButtonVisibleRefresh"),
      (e[(e.OnSkillButtonSkillIdRefresh = 686)] =
        "OnSkillButtonSkillIdRefresh"),
      (e[(e.OnSkillButtonDynamicEffectRefresh = 687)] =
        "OnSkillButtonDynamicEffectRefresh"),
      (e[(e.OnSkillButtonCdRefresh = 688)] = "OnSkillButtonCdRefresh"),
      (e[(e.OnSkillButtonAttributeRefresh = 689)] =
        "OnSkillButtonAttributeRefresh"),
      (e[(e.OnSkillButtonIconPathRefresh = 690)] =
        "OnSkillButtonIconPathRefresh"),
      (e[(e.OnBehaviorButtonVisibleRefresh = 691)] =
        "OnBehaviorButtonVisibleRefresh"),
      (e[(e.OnInputChangeForCond = 692)] = "OnInputChangeForCond"),
      (e[(e.OnGetNewItem = 693)] = "OnGetNewItem"),
      (e[(e.OnElementFusion = 694)] = "OnElementFusion"),
      (e[(e.OnChangeSelectedExploreId = 695)] = "OnChangeSelectedExploreId"),
      (e[(e.OnRouletteViewVisibleChanged = 696)] =
        "OnRouletteViewVisibleChanged"),
      (e[(e.OnRouletteItemSelect = 697)] = "OnRouletteItemSelect"),
      (e[(e.OnRouletteItemUnlock = 698)] = "OnRouletteItemUnlock"),
      (e[(e.OnRouletteSaveDataChange = 699)] = "OnRouletteSaveDataChange"),
      (e[(e.OnAggroAdd = 700)] = "OnAggroAdd"),
      (e[(e.OnAggroRemoved = 701)] = "OnAggroRemoved"),
      (e[(e.OnBossFight = 702)] = "OnBossFight"),
      (e[(e.OnSkillTagChanged = 703)] = "OnSkillTagChanged"),
      (e[(e.OnMatchingChange = 704)] = "OnMatchingChange"),
      (e[(e.OnMatchingBegin = 705)] = "OnMatchingBegin"),
      (e[(e.OnEnterTeam = 706)] = "OnEnterTeam"),
      (e[(e.OnLeaveTeam = 707)] = "OnLeaveTeam"),
      (e[(e.OnEnterOnlineWorld = 708)] = "OnEnterOnlineWorld"),
      (e[(e.OnLeaveOnlineWorld = 709)] = "OnLeaveOnlineWorld"),
      (e[(e.OnlineDisableStateChange = 710)] = "OnlineDisableStateChange"),
      (e[(e.PlayerChallengeStateChange = 711)] = "PlayerChallengeStateChange"),
      (e[(e.OnTriggerVolumeExit = 712)] = "OnTriggerVolumeExit"),
      (e[(e.RefreshAcquireView = 713)] = "RefreshAcquireView"),
      (e[(e.OnResonanceMaterialChange = 714)] = "OnResonanceMaterialChange"),
      (e[(e.OnAddMaterialController = 715)] = "OnAddMaterialController"),
      (e[(e.OnRemoveMaterialController = 716)] = "OnRemoveMaterialController"),
      (e[(e.OnAddMaterialControllerGroup = 717)] =
        "OnAddMaterialControllerGroup"),
      (e[(e.OnRemoveMaterialControllerGroup = 718)] =
        "OnRemoveMaterialControllerGroup"),
      (e[(e.WeatherChange = 719)] = "WeatherChange"),
      (e[(e.OnManipulateSwitchToNewTarget = 720)] =
        "OnManipulateSwitchToNewTarget"),
      (e[(e.OnManipulateStartChanting = 721)] = "OnManipulateStartChanting"),
      (e[(e.OnManipulateCancelChanting = 722)] = "OnManipulateCancelChanting"),
      (e[(e.OnManipulateCompleteChanting = 723)] =
        "OnManipulateCompleteChanting"),
      (e[(e.HiddenManipulateUI = 724)] = "HiddenManipulateUI"),
      (e[(e.ManipulateStartLockCastTarget = 725)] =
        "ManipulateStartLockCastTarget"),
      (e[(e.ManipulateEndLockCastTarget = 726)] =
        "ManipulateEndLockCastTarget"),
      (e[(e.OnManipulatableSceneItemPosInFoundation = 727)] =
        "OnManipulatableSceneItemPosInFoundation"),
      (e[(e.AddSubCameraTag = 728)] = "AddSubCameraTag"),
      (e[(e.RemoveSubCameraTag = 729)] = "RemoveSubCameraTag"),
      (e[(e.AddExtraHoldingTags = 730)] = "AddExtraHoldingTags"),
      (e[(e.RemoveExtraHoldingTags = 731)] = "RemoveExtraHoldingTags"),
      (e[(e.HideJigsawBaseHint = 732)] = "HideJigsawBaseHint"),
      (e[(e.OnModifyJigsawItemPutIndex = 733)] = "OnModifyJigsawItemPutIndex"),
      (e[(e.OnManipulatableItemStateModified = 734)] =
        "OnManipulatableItemStateModified"),
      (e[(e.OnManipulatedItemPosReset = 735)] = "OnManipulatedItemPosReset"),
      (e[(e.SetCameraAimVisible = 736)] = "SetCameraAimVisible"),
      (e[(e.ClickDisplayItem = 737)] = "ClickDisplayItem"),
      (e[(e.OnSelectItemAdd = 738)] = "OnSelectItemAdd"),
      (e[(e.DetectSuccess = 739)] = "DetectSuccess"),
      (e[(e.AdventureTaskStateChange = 740)] = "AdventureTaskStateChange"),
      (e[(e.ChapterRewardReceived = 741)] = "ChapterRewardReceived"),
      (e[(e.SilentRewardReceived = 742)] = "SilentRewardReceived"),
      (e[(e.AdventureHelpBtn = 743)] = "AdventureHelpBtn"),
      (e[(e.NewSoundAreaRefreshReward = 744)] = "NewSoundAreaRefreshReward"),
      (e[(e.DailyActivityTaskUpdate = 745)] = "DailyActivityTaskUpdate"),
      (e[(e.DailyActivityRefresh = 746)] = "DailyActivityRefresh"),
      (e[(e.DailyActivityValueChange = 747)] = "DailyActivityValueChange"),
      (e[(e.DailyActivityRewardTake = 748)] = "DailyActivityRewardTake"),
      (e[(e.RefreshActivityRewardPopUp = 749)] = "RefreshActivityRewardPopUp"),
      (e[(e.DailyActivityCountDownUpdate = 750)] =
        "DailyActivityCountDownUpdate"),
      (e[(e.DailyUpdateNotify = 751)] = "DailyUpdateNotify"),
      (e[(e.DailyActivityStateNotify = 752)] = "DailyActivityStateNotify"),
      (e[(e.DailyTaskAreaItemClick = 753)] = "DailyTaskAreaItemClick"),
      (e[(e.DailyTaskInfluenceItemClick = 754)] =
        "DailyTaskInfluenceItemClick"),
      (e[(e.DailyTaskUnlockAreaChange = 755)] = "DailyTaskUnlockAreaChange"),
      (e[(e.DailyTaskStateChange = 756)] = "DailyTaskStateChange"),
      (e[(e.DailyTaskChange = 757)] = "DailyTaskChange"),
      (e[(e.DailyTaskTendencyChange = 758)] = "DailyTaskTendencyChange"),
      (e[(e.OnAddCommonItem = 759)] = "OnAddCommonItem"),
      (e[(e.OnAddCommonItemList = 760)] = "OnAddCommonItemList"),
      (e[(e.OnAddCommonItemNotify = 761)] = "OnAddCommonItemNotify"),
      (e[(e.OnResponseCommonItem = 762)] = "OnResponseCommonItem"),
      (e[(e.OnRemoveCommonItem = 763)] = "OnRemoveCommonItem"),
      (e[(e.OnCommonItemCountRefresh = 764)] = "OnCommonItemCountRefresh"),
      (e[(e.OnCommonItemCountAnyChange = 765)] = "OnCommonItemCountAnyChange"),
      (e[(e.OnAddWeaponItem = 766)] = "OnAddWeaponItem"),
      (e[(e.OnAddWeaponItemList = 767)] = "OnAddWeaponItemList"),
      (e[(e.OnResponseWeaponItem = 768)] = "OnResponseWeaponItem"),
      (e[(e.OnResponseWeaponAll = 769)] = "OnResponseWeaponAll"),
      (e[(e.OnRemoveWeaponItem = 770)] = "OnRemoveWeaponItem"),
      (e[(e.OnWeaponFunctionValueRefresh = 771)] =
        "OnWeaponFunctionValueRefresh"),
      (e[(e.OnAddPhantomItem = 772)] = "OnAddPhantomItem"),
      (e[(e.OnAddPhantomItemList = 773)] = "OnAddPhantomItemList"),
      (e[(e.OnResponsePhantomItem = 774)] = "OnResponsePhantomItem"),
      (e[(e.OnEquipPhantomItem = 775)] = "OnEquipPhantomItem"),
      (e[(e.OnRemovePhantomItem = 776)] = "OnRemovePhantomItem"),
      (e[(e.OnPhantomFunctionValueRefresh = 777)] =
        "OnPhantomFunctionValueRefresh"),
      (e[(e.OnAddFavorItem = 778)] = "OnAddFavorItem"),
      (e[(e.NotifyInvalidItem = 779)] = "NotifyInvalidItem"),
      (e[(e.EnterPresentationInitRange = 780)] = "EnterPresentationInitRange"),
      (e[(e.EnterLogicRange = 781)] = "EnterLogicRange"),
      (e[(e.LeaveLogicRange = 782)] = "LeaveLogicRange"),
      (e[(e.PlayerSenseTargetEnter = 783)] = "PlayerSenseTargetEnter"),
      (e[(e.PlayerSenseTargetLeave = 784)] = "PlayerSenseTargetLeave"),
      (e[(e.OnAiSenseEntityEnter = 785)] = "OnAiSenseEntityEnter"),
      (e[(e.OnAiSenseEntityLeave = 786)] = "OnAiSenseEntityLeave"),
      (e[(e.OnInteractStateChange = 787)] = "OnInteractStateChange"),
      (e[(e.OnGuideRangeEnter = 788)] = "OnGuideRangeEnter"),
      (e[(e.SwitchCookType = 789)] = "SwitchCookType"),
      (e[(e.UpdateFormula = 790)] = "UpdateFormula"),
      (e[(e.UpdateCookerInfo = 791)] = "UpdateCookerInfo"),
      (e[(e.UpgradeCookerLevel = 792)] = "UpgradeCookerLevel"),
      (e[(e.GetCookData = 793)] = "GetCookData"),
      (e[(e.OpenProcessedStudy = 794)] = "OpenProcessedStudy"),
      (e[(e.CloseProcessedStudy = 795)] = "CloseProcessedStudy"),
      (e[(e.OpenCook = 796)] = "OpenCook"),
      (e[(e.OpenCookLevel = 797)] = "OpenCookLevel"),
      (e[(e.OpenCookRole = 798)] = "OpenCookRole"),
      (e[(e.CloseCookRole = 799)] = "CloseCookRole");
    (e[(e.CookSuccess = 800)] = "CookSuccess"),
      (e[(e.CookFail = 801)] = "CookFail"),
      (e[(e.MachiningSuccess = 802)] = "MachiningSuccess"),
      (e[(e.MachiningStudyFail = 803)] = "MachiningStudyFail"),
      (e[(e.FixSuccess = 804)] = "FixSuccess"),
      (e[(e.OpenSelected = 805)] = "OpenSelected"),
      (e[(e.CloseSelected = 806)] = "CloseSelected"),
      (e[(e.OnAddCommonEffect = 807)] = "OnAddCommonEffect"),
      (e[(e.RefreshRewardPopUp = 808)] = "RefreshRewardPopUp"),
      (e[(e.ReceiveMonthCardDataEvent = 809)] = "ReceiveMonthCardDataEvent"),
      (e[(e.OnClickSingleTimeTowerStageBtn = 810)] =
        "OnClickSingleTimeTowerStageBtn"),
      (e[(e.OnClickSingleTimeTowerTeamBtn = 811)] =
        "OnClickSingleTimeTowerTeamBtn"),
      (e[(e.OnClickSingleTimeTowerTeamRoleBtn = 812)] =
        "OnClickSingleTimeTowerTeamRoleBtn"),
      (e[(e.OnClickSingleTimeTowerStageDetailBtn = 813)] =
        "OnClickSingleTimeTowerStageDetailBtn"),
      (e[(e.OnClickSingleTimeTowerMonsterBtn = 814)] =
        "OnClickSingleTimeTowerMonsterBtn"),
      (e[(e.OnClickSingleTimeTowerDetailSwitchBtn = 815)] =
        "OnClickSingleTimeTowerDetailSwitchBtn"),
      (e[(e.OnInstResultNotify = 816)] = "OnInstResultNotify"),
      (e[(e.OnTowerChallengeChangeTeamNotify = 817)] =
        "OnTowerChallengeChangeTeamNotify"),
      (e[(e.OnTowerRewardReceived = 818)] = "OnTowerRewardReceived"),
      (e[(e.RedDotTowerReward = 819)] = "RedDotTowerReward"),
      (e[(e.RedDotTowerRewardByDifficulties = 820)] =
        "RedDotTowerRewardByDifficulties"),
      (e[(e.OnTowerRefresh = 821)] = "OnTowerRefresh"),
      (e[(e.OnTowerRecordUpdate = 822)] = "OnTowerRecordUpdate"),
      (e[(e.OnShowTowerGuideButton = 823)] = "OnShowTowerGuideButton"),
      (e[(e.OnClickCycleTowerAreaBtn = 824)] = "OnClickCycleTowerAreaBtn"),
      (e[(e.OnResetCycleTowerArea = 825)] = "OnResetCycleTowerArea"),
      (e[(e.OnClickCycleTowerRoleBtn = 826)] = "OnClickCycleTowerRoleBtn"),
      (e[(e.OnClickCycleTowerDetailSwitchBtn = 827)] =
        "OnClickCycleTowerDetailSwitchBtn"),
      (e[(e.OnCycleTowerUpdateSeason = 828)] = "OnCycleTowerUpdateSeason"),
      (e[(e.OnCycleTowerUpdateSeasonNotify = 829)] =
        "OnCycleTowerUpdateSeasonNotify"),
      (e[(e.OnCycleTowerScoreChange = 830)] = "OnCycleTowerScoreChange"),
      (e[(e.OnTowerGuideClose = 831)] = "OnTowerGuideClose"),
      (e[(e.OnTowerRefreshStars = 832)] = "OnTowerRefreshStars"),
      (e[(e.OnReceiveAdviceData = 833)] = "OnReceiveAdviceData"),
      (e[(e.OnCreateAdviceSuccess = 834)] = "OnCreateAdviceSuccess"),
      (e[(e.OnModifyAdviceSuccess = 835)] = "OnModifyAdviceSuccess"),
      (e[(e.OnDeleteAdviceSuccess = 836)] = "OnDeleteAdviceSuccess"),
      (e[(e.OnClickAdviceExpression = 837)] = "OnClickAdviceExpression"),
      (e[(e.OnClickAdviceWord = 838)] = "OnClickAdviceWord"),
      (e[(e.OnChangeAdviceWord = 839)] = "OnChangeAdviceWord"),
      (e[(e.OnClickAdviceSort = 840)] = "OnClickAdviceSort"),
      (e[(e.OnClickAdviceSortWord = 841)] = "OnClickAdviceSortWord"),
      (e[(e.OnClickAdviceMotion = 842)] = "OnClickAdviceMotion"),
      (e[(e.OnChangeAdviceRole = 843)] = "OnChangeAdviceRole"),
      (e[(e.OnClickAdviceSelectItem = 844)] = "OnClickAdviceSelectItem"),
      (e[(e.OnSelectAdviceWord = 845)] = "OnSelectAdviceWord"),
      (e[(e.OnSelectAdviceExpression = 846)] = "OnSelectAdviceExpression"),
      (e[(e.OnAdviceEntityNotify = 847)] = "OnAdviceEntityNotify"),
      (e[(e.OnAdviceVoteNotify = 848)] = "OnAdviceVoteNotify"),
      (e[(e.RefreshAdviceInfoView = 849)] = "RefreshAdviceInfoView"),
      (e[(e.SneakStart = 850)] = "SneakStart"),
      (e[(e.SneakEnd = 851)] = "SneakEnd"),
      (e[(e.AddAlterMark = 852)] = "AddAlterMark"),
      (e[(e.RemoveAlterMark = 853)] = "RemoveAlterMark"),
      (e[(e.OnSneakFoundChange = 854)] = "OnSneakFoundChange"),
      (e[(e.OnChildQuestNodeFinish = 855)] = "OnChildQuestNodeFinish"),
      (e[(e.AddStalkAlertMark = 856)] = "AddStalkAlertMark"),
      (e[(e.RemoveStalkAlertMark = 857)] = "RemoveStalkAlertMark"),
      (e[(e.OnStalkAlert = 858)] = "OnStalkAlert"),
      (e[(e.OnStalkAlertLifted = 859)] = "OnStalkAlertLifted"),
      (e[(e.OnStalkFound = 860)] = "OnStalkFound"),
      (e[(e.OnStalkFailed = 861)] = "OnStalkFailed"),
      (e[(e.AddEavesdropMark = 862)] = "AddEavesdropMark"),
      (e[(e.RemoveEavesdropMark = 863)] = "RemoveEavesdropMark"),
      (e[(e.OnEavesdropFound = 864)] = "OnEavesdropFound"),
      (e[(e.OnAddFullScreenEffect = 865)] = "OnAddFullScreenEffect"),
      (e[(e.OnRemoveFullScreenEffect = 866)] = "OnRemoveFullScreenEffect"),
      (e[(e.OnClearFullScreenEffect = 867)] = "OnClearFullScreenEffect"),
      (e[(e.OnChangeFullScreenNiagaraFloatParameter = 868)] =
        "OnChangeFullScreenNiagaraFloatParameter"),
      (e[(e.OnSceneItemBuffConsumed = 869)] = "OnSceneItemBuffConsumed"),
      (e[(e.OnSceneItemBuffRemoved = 870)] = "OnSceneItemBuffRemoved"),
      (e[(e.OnSceneItemBuffTimeout = 871)] = "OnSceneItemBuffTimeout"),
      (e[(e.OnSceneItemBuffTargetRemoved = 872)] =
        "OnSceneItemBuffTargetRemoved"),
      (e[(e.OnSceneItemBuffConsumerPerformanceComplete = 873)] =
        "OnSceneItemBuffConsumerPerformanceComplete"),
      (e[(e.OnExecuteServerGm = 874)] = "OnExecuteServerGm"),
      (e[(e.ActiveBattleView = 875)] = "ActiveBattleView"),
      (e[(e.DisActiveBattleView = 876)] = "DisActiveBattleView"),
      (e[(e.BattleUiCurRoleDataChanged = 877)] = "BattleUiCurRoleDataChanged"),
      (e[(e.BattleUiCurRoleDataChangedNextTick = 878)] =
        "BattleUiCurRoleDataChangedNextTick"),
      (e[(e.BattleUiAllRoleDataChanged = 879)] = "BattleUiAllRoleDataChanged"),
      (e[(e.BattleUiRemoveRoleData = 880)] = "BattleUiRemoveRoleData"),
      (e[(e.BattleUiElementEnergyChanged = 881)] =
        "BattleUiElementEnergyChanged"),
      (e[(e.BattleUiElementHideTagChanged = 882)] =
        "BattleUiElementHideTagChanged"),
      (e[(e.BattleUiDeadTagChanged = 883)] = "BattleUiDeadTagChanged"),
      (e[(e.BattleUiQteEnableTagChanged = 884)] =
        "BattleUiQteEnableTagChanged"),
      (e[(e.BattleUiQteCdTagChanged = 885)] = "BattleUiQteCdTagChanged"),
      (e[(e.BattleUiUseQteTagChanged = 886)] = "BattleUiUseQteTagChanged"),
      (e[(e.BattleUiConcertoEnableTagChanged = 887)] =
        "BattleUiConcertoEnableTagChanged"),
      (e[(e.BattleUiPoisonChanged = 888)] = "BattleUiPoisonChanged"),
      (e[(e.BattleUiHealthChanged = 889)] = "BattleUiHealthChanged"),
      (e[(e.BattleUiShieldChanged = 890)] = "BattleUiShieldChanged"),
      (e[(e.BattleUiLevelChanged = 891)] = "BattleUiLevelChanged"),
      (e[(e.BattleUiFloatTipUpdate = 892)] = "BattleUiFloatTipUpdate"),
      (e[(e.BattleUiPlayAudio = 893)] = "BattleUiPlayAudio"),
      (e[(e.BattleUiExploreModeChanged = 894)] = "BattleUiExploreModeChanged"),
      (e[(e.BattleUiMergeHeadStateVisibleChanged = 895)] =
        "BattleUiMergeHeadStateVisibleChanged"),
      (e[(e.BattleUiMergeHeadStateHealthChanged = 896)] =
        "BattleUiMergeHeadStateHealthChanged"),
      (e[(e.BattleUiEnvironmentKeyChanged = 897)] =
        "BattleUiEnvironmentKeyChanged"),
      (e[(e.BattleUiPressCombineButtonChanged = 898)] =
        "BattleUiPressCombineButtonChanged"),
      (e[(e.BattleUiToggleSilentAreaInfoView = 899)] =
        "BattleUiToggleSilentAreaInfoView"),
      (e[(e.BattleInputEnableChanged = 900)] = "BattleInputEnableChanged"),
      (e[(e.BattleInputVisibleChanged = 901)] = "BattleInputVisibleChanged"),
      (e[(e.BattleUiFollowerAimStateChanged = 902)] =
        "BattleUiFollowerAimStateChanged"),
      (e[(e.BattleUiToggleTowerDefenseInfoView = 903)] =
        "BattleUiToggleTowerDefenseInfoView"),
      (e[(e.BattleSettlementStateChanged = 904)] =
        "BattleSettlementStateChanged"),
      (e[(e.BattleScoreChanged = 905)] = "BattleScoreChanged"),
      (e[(e.RefreshInfluencePanel = 906)] = "RefreshInfluencePanel"),
      (e[(e.ReceiveReputationReward = 907)] = "ReceiveReputationReward"),
      (e[(e.SearchInfluence = 908)] = "SearchInfluence"),
      (e[(e.RedDotInfluence = 909)] = "RedDotInfluence"),
      (e[(e.BehaviorTreeStartActionSession = 910)] =
        "BehaviorTreeStartActionSession"),
      (e[(e.UiPlayCloseAudio = 911)] = "UiPlayCloseAudio"),
      (e[(e.OnSceneItemLockPropChange = 912)] = "OnSceneItemLockPropChange"),
      (e[(e.OnSpecialItemUpdate = 913)] = "OnSpecialItemUpdate"),
      (e[(e.EquipAndSwitchSpecialItem = 914)] = "EquipAndSwitchSpecialItem"),
      (e[(e.UnEquipSpecialItem = 915)] = "UnEquipSpecialItem"),
      (e[(e.ShowPlayerPosition = 916)] = "ShowPlayerPosition"),
      (e[(e.BattlePassHadEnterUpdate = 917)] = "BattlePassHadEnterUpdate"),
      (e[(e.GetBattlePassRewardEvent = 918)] = "GetBattlePassRewardEvent"),
      (e[(e.ReceiveBattlePassDataEvent = 919)] = "ReceiveBattlePassDataEvent"),
      (e[(e.BattlePassFirstUnlockAnime = 920)] = "BattlePassFirstUnlockAnime"),
      (e[(e.ReceiveBattlePassTaskEvent = 921)] = "ReceiveBattlePassTaskEvent"),
      (e[(e.OnChoseLevelItemEvent = 922)] = "OnChoseLevelItemEvent"),
      (e[(e.OnClickLevelItemEvent = 923)] = "OnClickLevelItemEvent"),
      (e[(e.UpdateBattlePassTaskEvent = 924)] = "UpdateBattlePassTaskEvent"),
      (e[(e.OnBattlePassLevelUpEvent = 925)] = "OnBattlePassLevelUpEvent"),
      (e[(e.OnBattlePassExpireEvent = 926)] = "OnBattlePassExpireEvent"),
      (e[(e.BattlePassMainViewHide = 927)] = "BattlePassMainViewHide"),
      (e[(e.SwitchViewType = 928)] = "SwitchViewType"),
      (e[(e.SwitchComposeType = 929)] = "SwitchComposeType"),
      (e[(e.GetComposeData = 930)] = "GetComposeData"),
      (e[(e.UpgradeComposeLevel = 931)] = "UpgradeComposeLevel"),
      (e[(e.OpenComposeLevel = 932)] = "OpenComposeLevel"),
      (e[(e.OpenCompose = 933)] = "OpenCompose"),
      (e[(e.ComposeSuccess = 934)] = "ComposeSuccess"),
      (e[(e.ComposeFail = 935)] = "ComposeFail"),
      (e[(e.OpenHelpRole = 936)] = "OpenHelpRole"),
      (e[(e.CloseHelpRole = 937)] = "CloseHelpRole"),
      (e[(e.UpdateComposeFormula = 938)] = "UpdateComposeFormula"),
      (e[(e.UpdateComposeInfo = 939)] = "UpdateComposeInfo"),
      (e[(e.UpdateForgingFormula = 940)] = "UpdateForgingFormula"),
      (e[(e.OpenForging = 941)] = "OpenForging"),
      (e[(e.GetForgingData = 942)] = "GetForgingData"),
      (e[(e.ForgingSuccess = 943)] = "ForgingSuccess"),
      (e[(e.ForgingFail = 944)] = "ForgingFail"),
      (e[(e.ChangePlayerInfoId = 945)] = "ChangePlayerInfoId"),
      (e[(e.OnShowGridAnimation = 946)] = "OnShowGridAnimation"),
      (e[(e.OnActivateUiCameraAnimationHandle = 947)] =
        "OnActivateUiCameraAnimationHandle"),
      (e[(e.OnActivateUiCameraAnimationHandleFail = 948)] =
        "OnActivateUiCameraAnimationHandleFail"),
      (e[(e.OnUiBlendInCameraSequenceFinished = 949)] =
        "OnUiBlendInCameraSequenceFinished"),
      (e[(e.RoleHandBookActive = 950)] = "RoleHandBookActive"),
      (e[(e.OnSequenceCameraStatus = 951)] = "OnSequenceCameraStatus"),
      (e[(e.LocalStorageInitPlayerId = 952)] = "LocalStorageInitPlayerId"),
      (e[(e.DynamicInteractServerResponse = 953)] =
        "DynamicInteractServerResponse"),
      (e[(e.UpdateCameraInfo = 954)] = "UpdateCameraInfo"),
      (e[(e.PlayCameraLevelSequence = 955)] = "PlayCameraLevelSequence"),
      (e[(e.CameraModeChanged = 956)] = "CameraModeChanged"),
      (e[(e.CameraViewTargetChanged = 957)] = "CameraViewTargetChanged"),
      (e[(e.FixedCameraRestored = 958)] = "FixedCameraRestored"),
      (e[(e.CameraCharacterChanged = 959)] = "CameraCharacterChanged"),
      (e[(e.OpenTreasureBox = 960)] = "OpenTreasureBox"),
      (e[(e.OnHandBookDataInit = 961)] = "OnHandBookDataInit"),
      (e[(e.OnHandBookDataUpdate = 962)] = "OnHandBookDataUpdate"),
      (e[(e.OnHandBookRedDotUpdate = 963)] = "OnHandBookRedDotUpdate"),
      (e[(e.OnHandBookRead = 964)] = "OnHandBookRead"),
      (e[(e.OnPhantomReadRedDotUpdate = 965)] = "OnPhantomReadRedDotUpdate"),
      (e[(e.OnItemReadRedDotUpdate = 966)] = "OnItemReadRedDotUpdate"),
      (e[(e.OnPhotoSelect = 967)] = "OnPhotoSelect"),
      (e[(e.OnGeographyPhotoSelect = 968)] = "OnGeographyPhotoSelect"),
      (e[(e.OnHandBookPlotNodeRefresh = 969)] = "OnHandBookPlotNodeRefresh"),
      (e[(e.RemoveCreatureDataComponentCache = 970)] =
        "RemoveCreatureDataComponentCache"),
      (e[(e.TravelClearView = 971)] = "TravelClearView"),
      (e[(e.OnPressOrReleaseBehaviorButton = 972)] =
        "OnPressOrReleaseBehaviorButton"),
      (e[(e.SetImageQuality = 973)] = "SetImageQuality"),
      (e[(e.SetDisplayMode = 974)] = "SetDisplayMode"),
      (e[(e.SetResolution = 975)] = "SetResolution"),
      (e[(e.SetNiagaraQuality = 976)] = "SetNiagaraQuality"),
      (e[(e.AfterGameQualitySettingsManagerInitialize = 977)] =
        "AfterGameQualitySettingsManagerInitialize"),
      (e[(e.SetGmIsOpen = 978)] = "SetGmIsOpen"),
      (e[(e.AddToTickList = 979)] = "AddToTickList"),
      (e[(e.HandleNextAction = 980)] = "HandleNextAction"),
      (e[(e.HandleActionFailure = 981)] = "HandleActionFailure"),
      (e[(e.AddGuaranteeAction = 982)] = "AddGuaranteeAction"),
      (e[(e.RemGuaranteeAction = 983)] = "RemGuaranteeAction"),
      (e[(e.ShareGroupCd = 984)] = "ShareGroupCd"),
      (e[(e.AddShareGroupLimitCount = 985)] = "AddShareGroupLimitCount"),
      (e[(e.OnInteractPlotStart = 986)] = "OnInteractPlotStart"),
      (e[(e.OnInteractPlotEnd = 987)] = "OnInteractPlotEnd"),
      (e[(e.OnAchievementDataNotify = 988)] = "OnAchievementDataNotify"),
      (e[(e.OnAchievementDataWithIdNotify = 989)] =
        "OnAchievementDataWithIdNotify"),
      (e[(e.OnAchievementGroupDataNotify = 990)] =
        "OnAchievementGroupDataNotify"),
      (e[(e.OnGetAchievementBaseData = 991)] = "OnGetAchievementBaseData"),
      (e[(e.OnGetAchievementSearchTextChange = 992)] =
        "OnGetAchievementSearchTextChange"),
      (e[(e.OnAchievementGroupChange = 993)] = "OnAchievementGroupChange"),
      (e[(e.RefreshAchievementRedPoint = 994)] = "RefreshAchievementRedPoint"),
      (e[(e.OnActivityUpdate = 995)] = "OnActivityUpdate"),
      (e[(e.OnSelectActivity = 996)] = "OnSelectActivity"),
      (e[(e.OnSelectActivityAndSubViewReady = 997)] =
        "OnSelectActivityAndSubViewReady"),
      (e[(e.RefreshActivityTab = 998)] = "RefreshActivityTab"),
      (e[(e.OnReceiveActivityData = 999)] = "OnReceiveActivityData"),
      (e[(e.SetActivityViewState = 1e3)] = "SetActivityViewState"),
      (e[(e.SetActivityViewCurrency = 1001)] = "SetActivityViewCurrency"),
      (e[(e.OnClickActivityRunChallenge = 1002)] =
        "OnClickActivityRunChallenge"),
      (e[(e.OnSelectActivityRunChallengeItem = 1003)] =
        "OnSelectActivityRunChallengeItem"),
      (e[(e.RefreshCommonActivityRedDot = 1004)] =
        "RefreshCommonActivityRedDot"),
      (e[(e.RefreshRunActivityRedDot = 1005)] = "RefreshRunActivityRedDot"),
      (e[(e.OnGetRunActivityReward = 1006)] = "OnGetRunActivityReward"),
      (e[(e.OnActivityClose = 1007)] = "OnActivityClose"),
      (e[(e.OnActivityOpen = 1008)] = "OnActivityOpen"),
      (e[(e.OnActivitySequenceEmitEvent = 1009)] =
        "OnActivitySequenceEmitEvent"),
      (e[(e.RefreshCommonActivityRewardPopUpView = 1010)] =
        "RefreshCommonActivityRewardPopUpView"),
      (e[(e.ActivityViewChange = 1011)] = "ActivityViewChange"),
      (e[(e.ActivityViewRefreshCurrent = 1012)] = "ActivityViewRefreshCurrent"),
      (e[(e.LongShanUpdate = 1013)] = "LongShanUpdate"),
      (e[(e.OnPhantomCollectUpdate = 1014)] = "OnPhantomCollectUpdate"),
      (e[(e.TurntableStartRun = 1015)] = "TurntableStartRun"),
      (e[(e.TrackMoonHandbookUpdate = 1016)] = "TrackMoonHandbookUpdate"),
      (e[(e.MoonChasingRefreshBuildingRedDot = 1017)] =
        "MoonChasingRefreshBuildingRedDot"),
      (e[(e.MoonChasingRefreshRewardRedDot = 1018)] =
        "MoonChasingRefreshRewardRedDot"),
      (e[(e.MoonChasingRefreshDelegationRedDot = 1019)] =
        "MoonChasingRefreshDelegationRedDot"),
      (e[(e.MoonChasingRefreshRoleRedDot = 1020)] =
        "MoonChasingRefreshRoleRedDot"),
      (e[(e.MoonChasingRefreshQuestRedDot = 1021)] =
        "MoonChasingRefreshQuestRedDot"),
      (e[(e.MoonChasingOnOpenInteractive = 1022)] =
        "MoonChasingOnOpenInteractive"),
      (e[(e.GmAutoModeChange = 1023)] = "GmAutoModeChange"),
      (e[(e.OnAddNotAllowFightInputViewName = 1024)] =
        "OnAddNotAllowFightInputViewName"),
      (e[(e.OnRemoveNotAllowFightInputViewName = 1025)] =
        "OnRemoveNotAllowFightInputViewName"),
      (e[(e.OnClearNotAllowFightInputViewName = 1026)] =
        "OnClearNotAllowFightInputViewName"),
      (e[(e.OnSelectedEditPanelItem = 1027)] = "OnSelectedEditPanelItem"),
      (e[(e.UiRoleSequenceEndKeyFrame = 1028)] = "UiRoleSequenceEndKeyFrame"),
      (e[(e.DropItemStarted = 1029)] = "DropItemStarted"),
      (e[(e.OnRoleChangeEnd = 1030)] = "OnRoleChangeEnd"),
      (e[(e.ComboTeachingPress = 1031)] = "ComboTeachingPress"),
      (e[(e.ComboTeachingRelease = 1032)] = "ComboTeachingRelease"),
      (e[(e.ComboTeachingHold = 1033)] = "ComboTeachingHold"),
      (e[(e.ComboTeachingNodeEnd = 1034)] = "ComboTeachingNodeEnd"),
      (e[(e.ComboTeachingViewOpen = 1035)] = "ComboTeachingViewOpen"),
      (e[(e.SkillAcceptChanged = 1036)] = "SkillAcceptChanged"),
      (e[(e.ComboTeachingFinish = 1037)] = "ComboTeachingFinish"),
      (e[(e.ComboTeachingCloseGuide = 1038)] = "ComboTeachingCloseGuide"),
      (e[(e.RequestClearMeshRotationBuffer = 1039)] =
        "RequestClearMeshRotationBuffer"),
      (e[(e.NavigationViewCreate = 1040)] = "NavigationViewCreate"),
      (e[(e.NavigationViewDestroy = 1041)] = "NavigationViewDestroy"),
      (e[(e.ResetNavigationListener = 1042)] = "ResetNavigationListener"),
      (e[(e.NavigationTriggerMapForward = 1043)] =
        "NavigationTriggerMapForward"),
      (e[(e.NavigationTriggerMapRight = 1044)] = "NavigationTriggerMapRight"),
      (e[(e.NavigationTriggerMapZoom = 1045)] = "NavigationTriggerMapZoom"),
      (e[(e.NavigationTriggerRoleLookUp = 1046)] =
        "NavigationTriggerRoleLookUp"),
      (e[(e.NavigationTriggerRoleTurn = 1047)] = "NavigationTriggerRoleTurn"),
      (e[(e.NavigationTriggerRoleZoom = 1048)] = "NavigationTriggerRoleZoom"),
      (e[(e.NavigationTriggerRoleReset = 1049)] = "NavigationTriggerRoleReset"),
      (e[(e.GamepadMoveOverScreen = 1050)] = "GamepadMoveOverScreen"),
      (e[(e.FunctionGridSelected = 1051)] = "FunctionGridSelected"),
      (e[(e.OnPersonalCardRead = 1052)] = "OnPersonalCardRead"),
      (e[(e.OnPersonalCardRefreshRedDot = 1053)] =
        "OnPersonalCardRefreshRedDot"),
      (e[(e.OnHeadIconChange = 1054)] = "OnHeadIconChange"),
      (e[(e.OnSignChange = 1055)] = "OnSignChange"),
      (e[(e.OnNameChange = 1056)] = "OnNameChange"),
      (e[(e.OnModifyNameStateChange = 1057)] = "OnModifyNameStateChange"),
      (e[(e.OnBirthChange = 1058)] = "OnBirthChange"),
      (e[(e.OnBirthDisplayChange = 1059)] = "OnBirthDisplayChange"),
      (e[(e.OnCardChange = 1060)] = "OnCardChange"),
      (e[(e.ResetRoleFlag = 1061)] = "ResetRoleFlag"),
      (e[(e.OnRoleShowListChange = 1062)] = "OnRoleShowListChange"),
      (e[(e.OnRoleElementChange = 1063)] = "OnRoleElementChange"),
      (e[(e.ShowRoleElementChangePreviewEffect = 1064)] =
        "ShowRoleElementChangePreviewEffect"),
      (e[(e.OnChangedActionKeys = 1065)] = "OnChangedActionKeys"),
      (e[(e.OnChangedAxisKeys = 1066)] = "OnChangedAxisKeys"),
      (e[(e.SelectRoleTab = 1067)] = "SelectRoleTab"),
      (e[(e.SelectRoleTabOutside = 1068)] = "SelectRoleTabOutside"),
      (e[(e.OnFunctionViewShow = 1069)] = "OnFunctionViewShow"),
      (e[(e.UpdatePanelQteWorldTimeDilation = 1070)] =
        "UpdatePanelQteWorldTimeDilation"),
      (e[(e.PanelQteStart = 1071)] = "PanelQteStart"),
      (e[(e.PanelQteEnd = 1072)] = "PanelQteEnd"),
      (e[(e.StartHeartBeat = 1073)] = "StartHeartBeat"),
      (e[(e.StopHeartBeat = 1074)] = "StopHeartBeat"),
      (e[(e.CreateEffectHandle = 1075)] = "CreateEffectHandle"),
      (e[(e.RemoveEffectHandle = 1076)] = "RemoveEffectHandle"),
      (e[(e.LoadEffect = 1077)] = "LoadEffect"),
      (e[(e.BeforePlayEffect = 1078)] = "BeforePlayEffect"),
      (e[(e.AfterPlayEffect = 1079)] = "AfterPlayEffect"),
      (e[(e.FinishEffect = 1080)] = "FinishEffect"),
      (e[(e.TestQuestAutoPilotFinish = 1081)] = "TestQuestAutoPilotFinish"),
      (e[(e.TestQuestFunctionFinish = 1082)] = "TestQuestFunctionFinish"),
      (e[(e.OnRefreshRewardViewItemList = 1083)] =
        "OnRefreshRewardViewItemList"),
      (e[(e.OnRefreshRewardProgressBar = 1084)] = "OnRefreshRewardProgressBar"),
      (e[(e.OnRefreshRewardButton = 1085)] = "OnRefreshRewardButton"),
      (e[(e.OnItemRewardNotify = 1086)] = "OnItemRewardNotify"),
      (e[(e.OnShowRewardView = 1087)] = "OnShowRewardView"),
      (e[(e.OnCloseRewardView = 1088)] = "OnCloseRewardView"),
      (e[(e.OnPlotWaitViewDone = 1089)] = "OnPlotWaitViewDone"),
      (e[(e.OnPlayCameraAnimationStart = 1090)] = "OnPlayCameraAnimationStart"),
      (e[(e.OnPlayCameraAnimationFinish = 1091)] =
        "OnPlayCameraAnimationFinish"),
      (e[(e.CommunicateFinished = 1092)] = "CommunicateFinished"),
      (e[(e.CommunicateAgain = 1093)] = "CommunicateAgain"),
      (e[(e.OnPhotographSetUpViewVisibleChanged = 1094)] =
        "OnPhotographSetUpViewVisibleChanged"),
      (e[(e.OnEntityCameraOneSituationChanged = 1095)] =
        "OnEntityCameraOneSituationChanged"),
      (e[(e.OnEntityCameraSearchGreat = 1096)] = "OnEntityCameraSearchGreat"),
      (e[(e.OnEntityCameraFinished = 1097)] = "OnEntityCameraFinished"),
      (e[(e.OnScreenShotDone = 1098)] = "OnScreenShotDone"),
      (e[(e.OnSubmitItemSuccess = 1099)] = "OnSubmitItemSuccess"),
      (e[(e.OnSubmitItemFail = 1100)] = "OnSubmitItemFail"),
      (e[(e.OnSubmitItemLevelUp = 1101)] = "OnSubmitItemLevelUp"),
      (e[(e.OnSubmitItemLevelMax = 1102)] = "OnSubmitItemLevelMax"),
      (e[(e.OnCameraSequenceSetUiVisible = 1103)] =
        "OnCameraSequenceSetUiVisible"),
      (e[(e.OnUiScreenRootVisibleChange = 1104)] =
        "OnUiScreenRootVisibleChange"),
      (e[(e.OnTurntableControllerBusyStateChange = 1105)] =
        "OnTurntableControllerBusyStateChange"),
      (e[(e.OnAnyProgressControlEnableStateChange = 1106)] =
        "OnAnyProgressControlEnableStateChange"),
      (e[(e.OnDropItemSuccess = 1107)] = "OnDropItemSuccess"),
      (e[(e.OnInteractDropItemSuccess = 1108)] = "OnInteractDropItemSuccess"),
      (e[(e.OnExecuteUiCameraSequenceEvent = 1109)] =
        "OnExecuteUiCameraSequenceEvent"),
      (e[(e.OnInputAnyKey = 1110)] = "OnInputAnyKey"),
      (e[(e.OnFilterDataUpdate = 1111)] = "OnFilterDataUpdate"),
      (e[(e.OnPlayNpcPerformSequence = 1112)] = "OnPlayNpcPerformSequence"),
      (e[(e.OnNpcPerformSequenceFinished = 1113)] =
        "OnNpcPerformSequenceFinished"),
      (e[(e.OnAntiqueShopUpgradeSequenceFinished = 1114)] =
        "OnAntiqueShopUpgradeSequenceFinished"),
      (e[(e.OnAntiqueShopLevelMaxSequenceFinished = 1115)] =
        "OnAntiqueShopLevelMaxSequenceFinished"),
      (e[(e.OnAntiqueShopUpgradeSequencePlayFail = 1116)] =
        "OnAntiqueShopUpgradeSequencePlayFail"),
      (e[(e.OnCookSuccessSequenceFinished = 1117)] =
        "OnCookSuccessSequenceFinished"),
      (e[(e.OnBeginPlayCookSuccessDisplay = 1118)] =
        "OnBeginPlayCookSuccessDisplay"),
      (e[(e.OnPlayCookSuccessDisplayFinished = 1119)] =
        "OnPlayCookSuccessDisplayFinished"),
      (e[(e.OnBeginPlayCookFailDisplay = 1120)] = "OnBeginPlayCookFailDisplay"),
      (e[(e.OnPlayCookFailDisplayFinished = 1121)] =
        "OnPlayCookFailDisplayFinished"),
      (e[(e.OnBeginPlayCompositeWorkingDisplay = 1122)] =
        "OnBeginPlayCompositeWorkingDisplay"),
      (e[(e.OnPlayCompositeWorkingDisplayFinished = 1123)] =
        "OnPlayCompositeWorkingDisplayFinished"),
      (e[(e.OnBeginPlayForgingWorkingDisplay = 1124)] =
        "OnBeginPlayForgingWorkingDisplay"),
      (e[(e.OnPlayForgingWorkingDisplayFinished = 1125)] =
        "OnPlayForgingWorkingDisplayFinished"),
      (e[(e.OnCharFootOnTheGround = 1126)] = "OnCharFootOnTheGround"),
      (e[(e.BattleViewActiveSequenceFinish = 1127)] =
        "BattleViewActiveSequenceFinish"),
      (e[(e.SmartObjectAiAlterNotify = 1128)] = "SmartObjectAiAlterNotify"),
      (e[(e.OnSetActorHidden = 1129)] = "OnSetActorHidden"),
      (e[(e.OnCheckGamePing = 1130)] = "OnCheckGamePing"),
      (e[(e.OnRemoveItemRedDot = 1131)] = "OnRemoveItemRedDot"),
      (e[(e.RunGm = 1132)] = "RunGm"),
      (e[(e.GmHandleActionFailed = 1133)] = "GmHandleActionFailed"),
      (e[(e.TestEffectAddDaRec = 1134)] = "TestEffectAddDaRec"),
      (e[(e.TestEffectAddEffectRec = 1135)] = "TestEffectAddEffectRec"),
      (e[(e.TestManuallyGarbageCollection = 1136)] =
        "TestManuallyGarbageCollection"),
      (e[(e.GmEntityPerformanceTestFinish = 1137)] =
        "GmEntityPerformanceTestFinish"),
      (e[(e.GmOnlyShowMiniMap = 1138)] = "GmOnlyShowMiniMap"),
      (e[(e.GmOnlyShowJoyStick = 1139)] = "GmOnlyShowJoyStick"),
      (e[(e.RoguelikeCloseGainSelectView = 1140)] =
        "RoguelikeCloseGainSelectView"),
      (e[(e.RoguelikeDataUpdate = 1141)] = "RoguelikeDataUpdate"),
      (e[(e.RoguelikeChooseDataResult = 1142)] = "RoguelikeChooseDataResult"),
      (e[(e.RoguelikeChooseDataNotify = 1143)] = "RoguelikeChooseDataNotify"),
      (e[(e.RoguelikeInfoSelectedToken = 1144)] = "RoguelikeInfoSelectedToken"),
      (e[(e.RoguelikeRefreshGain = 1145)] = "RoguelikeRefreshGain"),
      (e[(e.RoguelikeSelectSkill = 1146)] = "RoguelikeSelectSkill"),
      (e[(e.RoguelikeTalentLevelUp = 1147)] = "RoguelikeTalentLevelUp"),
      (e[(e.RoguelikeCurrencyUpdate = 1148)] = "RoguelikeCurrencyUpdate"),
      (e[(e.RoguelikeSelectToken = 1149)] = "RoguelikeSelectToken"),
      (e[(e.RoguelikeSelectSeason = 1150)] = "RoguelikeSelectSeason"),
      (e[(e.RoguelikeGetTokenReward = 1151)] = "RoguelikeGetTokenReward"),
      (e[(e.RogueTermUnlock = 1152)] = "RogueTermUnlock"),
      (e[(e.OnMarkItemViewCreate = 1153)] = "OnMarkItemViewCreate"),
      (e[(e.OnMarkItemViewDestroy = 1154)] = "OnMarkItemViewDestroy"),
      (e[(e.OnMarkItemViewEnter = 1155)] = "OnMarkItemViewEnter"),
      (e[(e.OnMarkItemViewExit = 1156)] = "OnMarkItemViewExit"),
      (e[(e.LogCustomMarkInfo = 1157)] = "LogCustomMarkInfo"),
      (e[(e.OnOpenSystemFeed = 1158)] = "OnOpenSystemFeed"),
      (e[(e.OnCloseSystemFeed = 1159)] = "OnCloseSystemFeed"),
      (e[(e.OnDeliveryProps = 1160)] = "OnDeliveryProps"),
      (e[(e.OnWorldMapTrackMarkItem = 1161)] = "OnWorldMapTrackMarkItem"),
      (e[(e.OnSundialRingChangeShine = 1162)] = "OnSundialRingChangeShine"),
      (e[(e.OnSundialRingSwitch = 1163)] = "OnSundialRingSwitch"),
      (e[(e.OnNeedUpdateSundialTips = 1164)] = "OnNeedUpdateSundialTips"),
      (e[(e.OnSignalDeviceLinkingCheck = 1165)] = "OnSignalDeviceLinkingCheck"),
      (e[(e.OnSignalDeviceReset = 1166)] = "OnSignalDeviceReset"),
      (e[(e.OnSignalDeviceLinking = 1167)] = "OnSignalDeviceLinking"),
      (e[(e.OnSignalDeviceFinish = 1168)] = "OnSignalDeviceFinish"),
      (e[(e.OnOverlapSceneItemExploreInteractRange = 1169)] =
        "OnOverlapSceneItemExploreInteractRange"),
      (e[(e.OnUseMapExploreToolSuccess = 1170)] = "OnUseMapExploreToolSuccess"),
      (e[(e.OnMapExploreToolPlaceNumUpdated = 1171)] =
        "OnMapExploreToolPlaceNumUpdated"),
      (e[(e.DoLeaveLevel = 1172)] = "DoLeaveLevel"),
      (e[(e.ClearSceneBegin = 1173)] = "ClearSceneBegin"),
      (e[(e.OnExploreProgressResponse = 1174)] = "OnExploreProgressResponse"),
      (e[(e.OnExploreScoreRewardResponse = 1175)] =
        "OnExploreScoreRewardResponse"),
      (e[(e.OnCountryExploreScoreInfoResponse = 1176)] =
        "OnCountryExploreScoreInfoResponse"),
      (e[(e.OnExploreLevelNotify = 1177)] = "OnExploreLevelNotify"),
      (e[(e.OnSignalCatchSuccess = 1178)] = "OnSignalCatchSuccess"),
      (e[(e.OnSignalCatchFailed = 1179)] = "OnSignalCatchFailed"),
      (e[(e.OnSignalCatchStart = 1180)] = "OnSignalCatchStart"),
      (e[(e.OnSignalCatchContinue = 1181)] = "OnSignalCatchContinue"),
      (e[(e.OnSignalCatchStartAgain = 1182)] = "OnSignalCatchStartAgain"),
      (e[(e.RefreshMonthCardRedDot = 1183)] = "RefreshMonthCardRedDot"),
      (e[(e.OnSetJoystickMode = 1184)] = "OnSetJoystickMode"),
      (e[(e.OnOverlapEncloseSpace = 1185)] = "OnOverlapEncloseSpace"),
      (e[(e.OnEncloseSpaceTypeChange = 1186)] = "OnEncloseSpaceTypeChange"),
      (e[(e.OnAndroidConfigurationChange = 1187)] =
        "OnAndroidConfigurationChange"),
      (e[(e.OnChatPlayerInfoChanged = 1188)] = "OnChatPlayerInfoChanged"),
      (e[(e.OnPlotTransitionRemoveCallback = 1189)] =
        "OnPlotTransitionRemoveCallback"),
      (e[(e.OnEnterOrExitExecutionRange = 1190)] =
        "OnEnterOrExitExecutionRange"),
      (e[(e.OnExecutionOptionChange = 1191)] = "OnExecutionOptionChange"),
      (e[(e.OnInteractActionEnd = 1192)] = "OnInteractActionEnd"),
      (e[(e.OnLevelFuncFlagSet = 1193)] = "OnLevelFuncFlagSet"),
      (e[(e.OnLevelFuncFlagChanged = 1194)] = "OnLevelFuncFlagChanged"),
      (e[(e.OnRefreshRewardView = 1195)] = "OnRefreshRewardView"),
      (e[(e.OnRefreshSpecialItemAllowReqUse = 1196)] =
        "OnRefreshSpecialItemAllowReqUse"),
      (e[(e.OnQueryProductInfo = 1197)] = "OnQueryProductInfo"),
      (e[(e.OnSdkFocusStateChange = 1198)] = "OnSdkFocusStateChange"),
      (e[(e.ReconnectClearData = 1199)] = "ReconnectClearData"),
      (e[(e.OnPreEndPIE = 1200)] = "OnPreEndPIE"),
      (e[(e.NoticeJourneyReceive = 1201)] = "NoticeJourneyReceive"),
      (e[(e.OnEntityInOutRangeLocal = 1202)] = "OnEntityInOutRangeLocal"),
      (e[(e.OnMyPlayerInOutRangeLocal = 1203)] = "OnMyPlayerInOutRangeLocal"),
      (e[(e.OnActorInOutRangeLocal = 1204)] = "OnActorInOutRangeLocal"),
      (e[(e.OnEntityInOutRangeOnline = 1205)] = "OnEntityInOutRangeOnline"),
      (e[(e.OnPlayerInOutRangeOnline = 1206)] = "OnPlayerInOutRangeOnline"),
      (e[(e.OnSetLoginServerId = 1207)] = "OnSetLoginServerId"),
      (e[(e.SetDecalShadowEnabled = 1208)] = "SetDecalShadowEnabled"),
      (e[(e.OnSelectTimePreset = 1209)] = "OnSelectTimePreset"),
      (e[(e.OnActionKeyChanged = 1210)] = "OnActionKeyChanged"),
      (e[(e.OnAxisKeyChanged = 1211)] = "OnAxisKeyChanged"),
      (e[(e.BeamCastStart = 1212)] = "BeamCastStart"),
      (e[(e.BeamCastStop = 1213)] = "BeamCastStop"),
      (e[(e.OnResetPhotographCamera = 1214)] = "OnResetPhotographCamera"),
      (e[(e.OnSpecialItemNotAllow = 1215)] = "OnSpecialItemNotAllow"),
      (e[(e.OnMarkItemShowStateChange = 1216)] = "OnMarkItemShowStateChange"),
      (e[(e.OnAbsoluteTimeStop = 1217)] = "OnAbsoluteTimeStop"),
      (e[(e.OnFightTestEnd = 1218)] = "OnFightTestEnd"),
      (e[(e.OnManipulateShowLandTips = 1219)] = "OnManipulateShowLandTips"),
      (e[(e.BeforeUiModelLoadStart = 1220)] = "BeforeUiModelLoadStart"),
      (e[(e.OnUiModelRoleConfigIdChange = 1221)] =
        "OnUiModelRoleConfigIdChange"),
      (e[(e.OnUiModelRoleDataIdChange = 1222)] = "OnUiModelRoleDataIdChange"),
      (e[(e.OnUiModelLoadComplete = 1223)] = "OnUiModelLoadComplete"),
      (e[(e.OnUiModelVisibleChange = 1224)] = "OnUiModelVisibleChange"),
      (e[(e.OnUiModelSetDitherEffect = 1225)] = "OnUiModelSetDitherEffect"),
      (e[(e.WorldMapSubMapChanged = 1226)] = "WorldMapSubMapChanged"),
      (e[(e.WorldMapSelectMultiMap = 1227)] = "WorldMapSelectMultiMap"),
      (e[(e.RoguelikePopularEntriesChange = 1228)] =
        "RoguelikePopularEntriesChange"),
      (e[(e.OnSceneItemMoveEventBroken = 1229)] = "OnSceneItemMoveEventBroken"),
      (e[(e.OnFragmentMemoryDataUpdate = 1230)] = "OnFragmentMemoryDataUpdate"),
      (e[(e.OnFragmentMemoryCollectUpdate = 1231)] =
        "OnFragmentMemoryCollectUpdate"),
      (e[(e.OnFragmentTopicSelect = 1232)] = "OnFragmentTopicSelect"),
      (e[(e.OnFragmentTopicClick = 1233)] = "OnFragmentTopicClick"),
      (e[(e.FragmentRewardRedDot = 1234)] = "FragmentRewardRedDot"),
      (e[(e.FragmentRewardTopicRedDot = 1235)] = "FragmentRewardTopicRedDot"),
      (e[(e.FragmentRewardEntranceRedDot = 1236)] =
        "FragmentRewardEntranceRedDot"),
      (e[(e.OnChangeBossRushBuff = 1237)] = "OnChangeBossRushBuff"),
      (e[(e.RequestChangeBossRushView = 1238)] = "RequestChangeBossRushView"),
      (e[(e.BossRushDataUpdate = 1239)] = "BossRushDataUpdate"),
      (e[(e.BossRefreshBossRushRewardRedDot = 1240)] =
        "BossRefreshBossRushRewardRedDot"),
      (e[(e.TowerDefenseOnOpenPhantomView = 1241)] =
        "TowerDefenseOnOpenPhantomView"),
      (e[(e.TowerDefenseOnClickOnePhantom = 1242)] =
        "TowerDefenseOnClickOnePhantom"),
      (e[(e.TowerDefenseSelfPhantomConfirm = 1243)] =
        "TowerDefenseSelfPhantomConfirm"),
      (e[(e.TowerDefensePhantomChanged = 1244)] = "TowerDefensePhantomChanged"),
      (e[(e.TowerDefenseBeforeConfirmQuickRoleSelect = 1245)] =
        "TowerDefenseBeforeConfirmQuickRoleSelect"),
      (e[(e.TowerDefenseOnWaveChanged = 1246)] = "TowerDefenseOnWaveChanged"),
      (e[(e.TowerDefenseOnActivityInfoUpdateNotify = 1247)] =
        "TowerDefenseOnActivityInfoUpdateNotify"),
      (e[(e.TowerDefenseOnInstanceInfoUpdateNotify = 1248)] =
        "TowerDefenseOnInstanceInfoUpdateNotify"),
      (e[(e.TowerDefenseOnPhantomInfoUpdateNotify = 1249)] =
        "TowerDefenseOnPhantomInfoUpdateNotify"),
      (e[(e.TowerDefenseShowInBattleView = 1250)] =
        "TowerDefenseShowInBattleView"),
      (e[(e.TowerDefenseOnShowPhantomInFormation = 1251)] =
        "TowerDefenseOnShowPhantomInFormation"),
      (e[(e.TowerDefenseOnTowerDefenseBattleEndNotify = 1252)] =
        "TowerDefenseOnTowerDefenseBattleEndNotify"),
      (e[(e.OnBeforeDestroyInstanceDungeonEntranceView = 1253)] =
        "OnBeforeDestroyInstanceDungeonEntranceView"),
      (e[(e.OnSetGameModeDataDone = 1254)] = "OnSetGameModeDataDone"),
      (e[(e.OnBossRushBuffViewOpened = 1255)] = "OnBossRushBuffViewOpened"),
      (e[(e.OnTutorialTipExistChanged = 1256)] = "OnTutorialTipExistChanged"),
      (e[(e.OnTutorialUpdate = 1257)] = "OnTutorialUpdate"),
      (e[(e.LevelLoadingLockTimeDilation = 1258)] =
        "LevelLoadingLockTimeDilation"),
      (e[(e.LevelLoadingUnlockDilation = 1259)] = "LevelLoadingUnlockDilation"),
      (e[(e.BusinessInvestResult = 1260)] = "BusinessInvestResult"),
      (e[(e.SetDelegationResultData = 1261)] = "SetDelegationResultData"),
      (e[(e.PopularityChange = 1262)] = "PopularityChange"),
      (e[(e.OpenTipsTravelView = 1263)] = "OpenTipsTravelView"),
      (e[(e.OpenTipsShopView = 1264)] = "OpenTipsShopView"),
      (e[(e.UnlockMoonChasingData = 1265)] = "UnlockMoonChasingData"),
      (e[(e.OnPlayerFollowerCreate = 1266)] = "OnPlayerFollowerCreate"),
      (e[(e.OnPlayerFollowerDestroy = 1267)] = "OnPlayerFollowerDestroy"),
      (e[(e.BuildAnimFinish = 1268)] = "BuildAnimFinish"),
      (e[(e.ConditionUnlockRole = 1269)] = "ConditionUnlockRole"),
      (e[(e.TakenRewardTargetData = 1270)] = "TakenRewardTargetData"),
      (e[(e.RefreshRewardTargetData = 1271)] = "RefreshRewardTargetData"),
      (e[(e.RefreshDelegate = 1272)] = "RefreshDelegate"),
      (e[(e.ElevatorMove = 1273)] = "ElevatorMove"),
      (e[(e.OnHighSpeedModeChanged = 1274)] = "OnHighSpeedModeChanged");
  })((EEventName = exports.EEventName || (exports.EEventName = {})));
//# sourceMappingURL=EventDefine.js.map
