"use strict";
var EEventName;
Object.defineProperty(exports, "__esModule", { value: !0 }),
  (exports.EEventName = void 0),
  (function (e) {
    (e[(e.SetEntityCreatureDataRelation = 0)] =
      "SetEntityCreatureDataRelation"),
      (e[(e.KeyClick = 1)] = "KeyClick"),
      (e[(e.UiSceneLoaded = 2)] = "UiSceneLoaded"),
      (e[(e.UiSceneStartLoad = 3)] = "UiSceneStartLoad"),
      (e[(e.OpenView = 4)] = "OpenView"),
      (e[(e.StackPreOpenView = 5)] = "StackPreOpenView"),
      (e[(e.StackOpenView = 6)] = "StackOpenView"),
      (e[(e.StackCloseView = 7)] = "StackCloseView"),
      (e[(e.OpenViewBegined = 8)] = "OpenViewBegined"),
      (e[(e.OpenViewFail = 9)] = "OpenViewFail"),
      (e[(e.CreateViewInstance = 10)] = "CreateViewInstance"),
      (e[(e.OnViewLoadCompleted = 11)] = "OnViewLoadCompleted"),
      (e[(e.OnViewDone = 12)] = "OnViewDone"),
      (e[(e.OnViewHidden = 13)] = "OnViewHidden"),
      (e[(e.CloseView = 14)] = "CloseView"),
      (e[(e.OpenTabView = 15)] = "OpenTabView"),
      (e[(e.TriggerUiTimeDilation = 16)] = "TriggerUiTimeDilation"),
      (e[(e.CloseTabView = 17)] = "CloseTabView"),
      (e[(e.ChangeChildView = 18)] = "ChangeChildView"),
      (e[(e.UiManagerInit = 19)] = "UiManagerInit"),
      (e[(e.UiManagerDestroy = 20)] = "UiManagerDestroy"),
      (e[(e.HotKeyInput = 21)] = "HotKeyInput"),
      (e[(e.ViewHotKeyInputPress = 22)] = "ViewHotKeyInputPress"),
      (e[(e.ViewHotKeyInputRelease = 23)] = "ViewHotKeyInputRelease"),
      (e[(e.ResetNormalAction = 24)] = "ResetNormalAction"),
      (e[(e.UnBlockCharacterAction = 25)] = "UnBlockCharacterAction"),
      (e[(e.ResetSystemAction = 26)] = "ResetSystemAction"),
      (e[(e.OnReduceDamageViewDepth = 27)] = "OnReduceDamageViewDepth"),
      (e[(e.LoginSuccess = 28)] = "LoginSuccess"),
      (e[(e.EnterGameSuccess = 29)] = "EnterGameSuccess"),
      (e[(e.LoginStatusChange = 30)] = "LoginStatusChange"),
      (e[(e.LoginRequestResult = 31)] = "LoginRequestResult"),
      (e[(e.SdkLoginResult = 32)] = "SdkLoginResult"),
      (e[(e.OnGetLoginPlayerInfo = 33)] = "OnGetLoginPlayerInfo"),
      (e[(e.OnSelectServerItem = 34)] = "OnSelectServerItem"),
      (e[(e.OnConfirmServerItem = 35)] = "OnConfirmServerItem"),
      (e[(e.SendHeartbeat = 36)] = "SendHeartbeat"),
      (e[(e.SdkInitDone = 37)] = "SdkInitDone"),
      (e[(e.SdkPayEnd = 38)] = "SdkPayEnd"),
      (e[(e.PlayStationJoinSessionEvent = 39)] = "PlayStationJoinSessionEvent"),
      (e[(e.CharQteActive = 40)] = "CharQteActive"),
      (e[(e.CharQteConsume = 41)] = "CharQteConsume"),
      (e[(e.CharInQteChanged = 42)] = "CharInQteChanged"),
      (e[(e.CharExecuteQte = 43)] = "CharExecuteQte"),
      (e[(e.CharExecuteMultiQte = 44)] = "CharExecuteMultiQte"),
      (e[(e.CharQteTagRowNameChanged = 45)] = "CharQteTagRowNameChanged"),
      (e[(e.CharHitLocal = 46)] = "CharHitLocal"),
      (e[(e.CharHitRemote = 47)] = "CharHitRemote"),
      (e[(e.CharBeHitLocal = 48)] = "CharBeHitLocal"),
      (e[(e.CharHitIncludingVision = 49)] = "CharHitIncludingVision"),
      (e[(e.CharBeHitRemote = 50)] = "CharBeHitRemote"),
      (e[(e.CharLimitDodge = 51)] = "CharLimitDodge"),
      (e[(e.CharBeHitAnim = 52)] = "CharBeHitAnim"),
      (e[(e.CharBeHitTimeScale = 53)] = "CharBeHitTimeScale"),
      (e[(e.CharShieldChange = 54)] = "CharShieldChange"),
      (e[(e.CharAnimBreakPoint = 55)] = "CharAnimBreakPoint"),
      (e[(e.CharBeforeSkillWithTarget = 56)] = "CharBeforeSkillWithTarget"),
      (e[(e.CharUseSkill = 57)] = "CharUseSkill"),
      (e[(e.CharUseSkillRemote = 58)] = "CharUseSkillRemote"),
      (e[(e.OnSkillEnd = 59)] = "OnSkillEnd"),
      (e[(e.OnMultiSkillIdChanged = 60)] = "OnMultiSkillIdChanged"),
      (e[(e.OnMultiSkillEnable = 61)] = "OnMultiSkillEnable"),
      (e[(e.CharSwitchControl = 62)] = "CharSwitchControl"),
      (e[(e.CharInputPress = 63)] = "CharInputPress"),
      (e[(e.CharInputHold = 64)] = "CharInputHold"),
      (e[(e.CharInputRelease = 65)] = "CharInputRelease"),
      (e[(e.CharSkillTargetChanged = 66)] = "CharSkillTargetChanged"),
      (e[(e.CharDeleteSkill = 67)] = "CharDeleteSkill"),
      (e[(e.CharResetSkill = 68)] = "CharResetSkill"),
      (e[(e.CharInterruptSkill = 69)] = "CharInterruptSkill"),
      (e[(e.CharSkillCountChanged = 70)] = "CharSkillCountChanged"),
      (e[(e.CharSkillRemainCdChanged = 71)] = "CharSkillRemainCdChanged"),
      (e[(e.CharSkillCdPauseStateChanged = 72)] =
        "CharSkillCdPauseStateChanged"),
      (e[(e.CharClearSkill = 73)] = "CharClearSkill"),
      (e[(e.CharDamage = 74)] = "CharDamage"),
      (e[(e.CharBeDamage = 75)] = "CharBeDamage"),
      (e[(e.GlobalCharDamage = 76)] = "GlobalCharDamage"),
      (e[(e.FormationPanelUIShowRoleHeal = 77)] =
        "FormationPanelUIShowRoleHeal"),
      (e[(e.CharPartDamage = 78)] = "CharPartDamage"),
      (e[(e.CharClimbStartExit = 79)] = "CharClimbStartExit"),
      (e[(e.CharActivateClimbInput = 80)] = "CharActivateClimbInput"),
      (e[(e.CharClimbJumpCheck = 81)] = "CharClimbJumpCheck"),
      (e[(e.CustomMoveSwim = 82)] = "CustomMoveSwim"),
      (e[(e.CustomMoveSlide = 83)] = "CustomMoveSlide"),
      (e[(e.CustomMoveSki = 84)] = "CustomMoveSki"),
      (e[(e.CustomMoveWalkOnWater = 85)] = "CustomMoveWalkOnWater"),
      (e[(e.CustomMoveClimb = 86)] = "CustomMoveClimb"),
      (e[(e.CustomMoveGlide = 87)] = "CustomMoveGlide"),
      (e[(e.CustomMovePendulum = 88)] = "CustomMovePendulum"),
      (e[(e.CustomMoveCatapult = 89)] = "CustomMoveCatapult"),
      (e[(e.CustomMoveSoar = 90)] = "CustomMoveSoar"),
      (e[(e.CustomMoveRoll = 91)] = "CustomMoveRoll"),
      (e[(e.CharTurnBegin = 92)] = "CharTurnBegin"),
      (e[(e.CharTurnEnd = 93)] = "CharTurnEnd"),
      (e[(e.CharMovementModeChanged = 94)] = "CharMovementModeChanged"),
      (e[(e.CharActivate = 95)] = "CharActivate"),
      (e[(e.CharOnAttrChanged = 96)] = "CharOnAttrChanged"),
      (e[(e.CharGravityDirectChanged = 97)] = "CharGravityDirectChanged"),
      (e[(e.CharOnRoleDrown = 98)] = "CharOnRoleDrown"),
      (e[(e.CharOnRoleDrownInjure = 99)] = "CharOnRoleDrownInjure"),
      (e[(e.CharOnEnergyChanged = 100)] = "CharOnEnergyChanged"),
      (e[(e.CharOnHealthChanged = 101)] = "CharOnHealthChanged"),
      (e[(e.CharOnHealthMaxChanged = 102)] = "CharOnHealthMaxChanged"),
      (e[(e.CharOnElementEnergyChanged = 103)] = "CharOnElementEnergyChanged"),
      (e[(e.CharOnUnifiedMoveStateChanged = 104)] =
        "CharOnUnifiedMoveStateChanged"),
      (e[(e.CharOnPositionStateChanged = 105)] = "CharOnPositionStateChanged"),
      (e[(e.CharOnDirectionStateChanged = 106)] =
        "CharOnDirectionStateChanged"),
      (e[(e.CharOnPositionSubStateChanged = 107)] =
        "CharOnPositionSubStateChanged"),
      (e[(e.CharSwimStrengthChanged = 108)] = "CharSwimStrengthChanged"),
      (e[(e.RoleOnStateInherit = 109)] = "RoleOnStateInherit"),
      (e[(e.CharOnEndPlay = 110)] = "CharOnEndPlay"),
      (e[(e.CharOnBuffAddUITexture = 111)] = "CharOnBuffAddUITexture"),
      (e[(e.CharOnBuffAddUIPrefab = 112)] = "CharOnBuffAddUIPrefab"),
      (e[(e.CharOnBuffAddUIDamage = 113)] = "CharOnBuffAddUIDamage"),
      (e[(e.CharOnAnimNotifyStateDurationChange = 114)] =
        "CharOnAnimNotifyStateDurationChange"),
      (e[(e.CharOnLand = 115)] = "CharOnLand"),
      (e[(e.CharPossessed = 116)] = "CharPossessed"),
      (e[(e.CharUnpossessed = 117)] = "CharUnpossessed"),
      (e[(e.CharChangeMeshAnim = 118)] = "CharChangeMeshAnim"),
      (e[(e.CharRecordOperate = 119)] = "CharRecordOperate"),
      (e[(e.CharOnRoleDead = 120)] = "CharOnRoleDead"),
      (e[(e.CharOnRoleDeadTargetSelf = 121)] = "CharOnRoleDeadTargetSelf"),
      (e[(e.OnRevive = 122)] = "OnRevive"),
      (e[(e.CharOnRevive = 123)] = "CharOnRevive"),
      (e[(e.OnTeamLivingStateChange = 124)] = "OnTeamLivingStateChange"),
      (e[(e.CharOnSetNewBeHit = 125)] = "CharOnSetNewBeHit"),
      (e[(e.OnBattleStateChanged = 126)] = "OnBattleStateChanged"),
      (e[(e.OnChangeWalkOrRun = 127)] = "OnChangeWalkOrRun"),
      (e[(e.CharOnFallInjure = 128)] = "CharOnFallInjure"),
      (e[(e.ChangeAiTeamLevel = 129)] = "ChangeAiTeamLevel"),
      (e[(e.AiHateAddOrRemove = 130)] = "AiHateAddOrRemove"),
      (e[(e.AiInFight = 131)] = "AiInFight"),
      (e[(e.AiHateTargetChanged = 132)] = "AiHateTargetChanged"),
      (e[(e.AiTauntAddOrRemove = 133)] = "AiTauntAddOrRemove"),
      (e[(e.AiTaskWanderForResetEnd = 134)] = "AiTaskWanderForResetEnd"),
      (e[(e.OnRunBehaviorTree = 135)] = "OnRunBehaviorTree"),
      (e[(e.OnAiEnable = 136)] = "OnAiEnable"),
      (e[(e.OnAiDisable = 137)] = "OnAiDisable"),
      (e[(e.CloseItemTips = 138)] = "CloseItemTips"),
      (e[(e.CreateRoleForwardAnimEnd = 139)] = "CreateRoleForwardAnimEnd"),
      (e[(e.CreateRoleShowInputName = 140)] = "CreateRoleShowInputName"),
      (e[(e.GuideFinish = 141)] = "GuideFinish"),
      (e[(e.GuideGroupOpening = 142)] = "GuideGroupOpening"),
      (e[(e.GuideGroupFinished = 143)] = "GuideGroupFinished"),
      (e[(e.GuideGroupBreak = 144)] = "GuideGroupBreak"),
      (e[(e.GuideGroupRest = 145)] = "GuideGroupRest"),
      (e[(e.GuideFocusNeedUiTabView = 146)] = "GuideFocusNeedUiTabView"),
      (e[(e.FinishGuideStepByEvent = 147)] = "FinishGuideStepByEvent"),
      (e[(e.GuideTouchIdInject = 148)] = "GuideTouchIdInject"),
      (e[(e.OnRefreshRoleHp = 149)] = "OnRefreshRoleHp"),
      (e[(e.BeforeLoadMap = 150)] = "BeforeLoadMap"),
      (e[(e.BeforeTravelMap = 151)] = "BeforeTravelMap"),
      (e[(e.EndTravelMap = 152)] = "EndTravelMap"),
      (e[(e.OnEnterTransitionMap = 153)] = "OnEnterTransitionMap"),
      (e[(e.SeamlessTravelFinishBeforeShowUI = 154)] =
        "SeamlessTravelFinishBeforeShowUI"),
      (e[(e.AfterLoadMap = 155)] = "AfterLoadMap"),
      (e[(e.ClearWorld = 156)] = "ClearWorld"),
      (e[(e.OnUiManagerClearAsync = 157)] = "OnUiManagerClearAsync"),
      (e[(e.WorldDone = 158)] = "WorldDone"),
      (e[(e.WorldDoneAndCloseLoading = 159)] = "WorldDoneAndCloseLoading"),
      (e[(e.ChangeMode = 160)] = "ChangeMode"),
      (e[(e.ChangeModeFinish = 161)] = "ChangeModeFinish"),
      (e[(e.ChangePerformanceLimitMode = 162)] = "ChangePerformanceLimitMode"),
      (e[(e.PauseGame = 163)] = "PauseGame"),
      (e[(e.OnChangeRole = 164)] = "OnChangeRole"),
      (e[(e.OnOtherChangeRole = 165)] = "OnOtherChangeRole"),
      (e[(e.OnChangeRoleCoolDownChanged = 166)] =
        "OnChangeRoleCoolDownChanged"),
      (e[(e.OnRoleGoDown = 167)] = "OnRoleGoDown"),
      (e[(e.OnRoleGoDownFinish = 168)] = "OnRoleGoDownFinish"),
      (e[(e.OnClearFollowData = 169)] = "OnClearFollowData"),
      (e[(e.InitArea = 170)] = "InitArea"),
      (e[(e.ChangeArea = 171)] = "ChangeArea"),
      (e[(e.UpdateAreaView = 172)] = "UpdateAreaView"),
      (e[(e.CreateEntity = 173)] = "CreateEntity"),
      (e[(e.CreateEntityFail = 174)] = "CreateEntityFail"),
      (e[(e.AddEntity = 175)] = "AddEntity"),
      (e[(e.FixBornLocation = 176)] = "FixBornLocation"),
      (e[(e.CharBornFinished = 177)] = "CharBornFinished"),
      (e[(e.PreloadEntityFinished = 178)] = "PreloadEntityFinished"),
      (e[(e.DelayRemoveEntityFinished = 179)] = "DelayRemoveEntityFinished"),
      (e[(e.RemoveEntity = 180)] = "RemoveEntity"),
      (e[(e.EntityOnLandedPush = 181)] = "EntityOnLandedPush"),
      (e[(e.EntityVarUpdate = 182)] = "EntityVarUpdate"),
      (e[(e.SpawnPlayer = 183)] = "SpawnPlayer"),
      (e[(e.SpawnBoss = 184)] = "SpawnBoss"),
      (e[(e.OnUpdateTeamGroupType = 185)] = "OnUpdateTeamGroupType"),
      (e[(e.OnUpdateSceneTeam = 186)] = "OnUpdateSceneTeam"),
      (e[(e.OnItemDecompose = 187)] = "OnItemDecompose"),
      (e[(e.OnItemLock = 188)] = "OnItemLock"),
      (e[(e.OnItemFuncValueChange = 189)] = "OnItemFuncValueChange"),
      (e[(e.OnGetReward = 190)] = "OnGetReward"),
      (e[(e.OnReceivePlayerVar = 191)] = "OnReceivePlayerVar"),
      (e[(e.OpenItemInfo = 192)] = "OpenItemInfo"),
      (e[(e.CloseItemInfo = 193)] = "CloseItemInfo"),
      (e[(e.BoughtItem = 194)] = "BoughtItem"),
      (e[(e.ShopUpdate = 195)] = "ShopUpdate"),
      (e[(e.OnShopInfoResponded = 196)] = "OnShopInfoResponded"),
      (e[(e.OnGoodUnlock = 197)] = "OnGoodUnlock"),
      (e[(e.SelectedMail = 198)] = "SelectedMail"),
      (e[(e.PickingAttachment = 199)] = "PickingAttachment"),
      (e[(e.DeletingMail = 200)] = "DeletingMail"),
      (e[(e.DeletingMailPassively = 201)] = "DeletingMailPassively"),
      (e[(e.AddingNewMail = 202)] = "AddingNewMail"),
      (e[(e.SwitchUnfinishedFlag = 203)] = "SwitchUnfinishedFlag"),
      (e[(e.CloseMailView = 204)] = "CloseMailView"),
      (e[(e.OnlyCloseMailContentView = 205)] = "OnlyCloseMailContentView"),
      (e[(e.SceneBulletOwnerCreated = 206)] = "SceneBulletOwnerCreated"),
      (e[(e.BulletCreate = 207)] = "BulletCreate"),
      (e[(e.BulletDestroy = 208)] = "BulletDestroy"),
      (e[(e.BulletHit = 209)] = "BulletHit"),
      (e[(e.BulletRebound = 210)] = "BulletRebound"),
      (e[(e.BulletHitSpecialCharacter = 211)] = "BulletHitSpecialCharacter"),
      (e[(e.BulletHitAirWall = 212)] = "BulletHitAirWall"),
      (e[(e.ScenePlayerChanged = 213)] = "ScenePlayerChanged"),
      (e[(e.ScenePlayerLocationChanged = 214)] = "ScenePlayerLocationChanged"),
      (e[(e.ScenePlayerLeaveScene = 215)] = "ScenePlayerLeaveScene"),
      (e[(e.ScenePlayerMarkItemStateChange = 216)] =
        "ScenePlayerMarkItemStateChange"),
      (e[(e.MatchTeamFlagChange = 217)] = "MatchTeamFlagChange"),
      (e[(e.LoadingViewProgressSequenceEnd = 218)] =
        "LoadingViewProgressSequenceEnd"),
      (e[(e.DestroyAllUiCameraAnimationHandles = 219)] =
        "DestroyAllUiCameraAnimationHandles"),
      (e[(e.RoleSelectionListUpdate = 220)] = "RoleSelectionListUpdate"),
      (e[(e.SelectRole = 221)] = "SelectRole"),
      (e[(e.SelectSkill = 222)] = "SelectSkill"),
      (e[(e.SelectLevelUpItemCount = 223)] = "SelectLevelUpItemCount"),
      (e[(e.SelectLevelUpItem = 224)] = "SelectLevelUpItem"),
      (e[(e.RoleInfoUpdate = 225)] = "RoleInfoUpdate"),
      (e[(e.RoleRefreshAttribute = 226)] = "RoleRefreshAttribute"),
      (e[(e.RoleSkillLevelUp = 227)] = "RoleSkillLevelUp"),
      (e[(e.RoleLevelUp = 228)] = "RoleLevelUp"),
      (e[(e.RoleLevelUpReceiveItem = 229)] = "RoleLevelUpReceiveItem"),
      (e[(e.RoleBreakUp = 230)] = "RoleBreakUp"),
      (e[(e.ActiveRole = 231)] = "ActiveRole"),
      (e[(e.RoleResonUplevel = 232)] = "RoleResonUplevel"),
      (e[(e.RoleResonActive = 233)] = "RoleResonActive"),
      (e[(e.RoleResonAnimationSuccess = 234)] = "RoleResonAnimationSuccess"),
      (e[(e.RoleResonPlayAnimation = 235)] = "RoleResonPlayAnimation"),
      (e[(e.CloseRoleView = 236)] = "CloseRoleView"),
      (e[(e.SelectedResonanceTab = 237)] = "SelectedResonanceTab"),
      (e[(e.UnSelectedResonanceTab = 238)] = "UnSelectedResonanceTab"),
      (e[(e.SwitchRootTabState = 239)] = "SwitchRootTabState"),
      (e[(e.RoleRefreshName = 240)] = "RoleRefreshName"),
      (e[(e.RoleSystemChangeRole = 241)] = "RoleSystemChangeRole"),
      (e[(e.RoleSystemDeleteRole = 242)] = "RoleSystemDeleteRole"),
      (e[(e.OnSelectedRoleChanged = 243)] = "OnSelectedRoleChanged"),
      (e[(e.ChangeResonance = 244)] = "ChangeResonance"),
      (e[(e.OnRoleInternalViewEnter = 245)] = "OnRoleInternalViewEnter"),
      (e[(e.OnRoleInternalViewQuit = 246)] = "OnRoleInternalViewQuit"),
      (e[(e.AttributeComponentEvent = 247)] = "AttributeComponentEvent"),
      (e[(e.UpdateRoleLevelUpViewData = 248)] = "UpdateRoleLevelUpViewData"),
      (e[(e.UpdateRoleResonanceDetailView = 249)] =
        "UpdateRoleResonanceDetailView"),
      (e[(e.UpdateRoleSkillView = 250)] = "UpdateRoleSkillView"),
      (e[(e.UpdateRoleSkillLevelUpView = 251)] = "UpdateRoleSkillLevelUpView"),
      (e[(e.RefreshSkillTreeInfoTabView = 252)] =
        "RefreshSkillTreeInfoTabView"),
      (e[(e.SkillTreeRefresh = 253)] = "SkillTreeRefresh"),
      (e[(e.RefreshSkillTreeLeftSkillPoint = 254)] =
        "RefreshSkillTreeLeftSkillPoint"),
      (e[(e.SkillTreeReset = 255)] = "SkillTreeReset"),
      (e[(e.SkillTreeClickEmpty = 256)] = "SkillTreeClickEmpty"),
      (e[(e.SkillTreeNodeActive = 257)] = "SkillTreeNodeActive"),
      (e[(e.SkillTreeNodeLevelUp = 258)] = "SkillTreeNodeLevelUp"),
      (e[(e.UpdateSkillTreeInfoView = 259)] = "UpdateSkillTreeInfoView"),
      (e[(e.OnSkillTreeNodeToggleClick = 260)] = "OnSkillTreeNodeToggleClick"),
      (e[(e.UpdateRoleFavorData = 261)] = "UpdateRoleFavorData"),
      (e[(e.UnLockRoleFavorItem = 262)] = "UnLockRoleFavorItem"),
      (e[(e.RoleFavorExpChange = 263)] = "RoleFavorExpChange"),
      (e[(e.UpdateRoleFavorHintView = 264)] = "UpdateRoleFavorHintView"),
      (e[(e.RefreshFunctionOpenView = 265)] = "RefreshFunctionOpenView"),
      (e[(e.RoleFindFixHook = 266)] = "RoleFindFixHook"),
      (e[(e.UpdateRoleBreachView = 267)] = "UpdateRoleBreachView"),
      (e[(e.OnClickSkillLevelUp = 268)] = "OnClickSkillLevelUp"),
      (e[(e.OnClickSkillActive = 269)] = "OnClickSkillActive"),
      (e[(e.OnEnterOrExitUltraSkill = 270)] = "OnEnterOrExitUltraSkill"),
      (e[(e.WeaponLevelUp = 271)] = "WeaponLevelUp"),
      (e[(e.WeaponLevelUpReceiveItem = 272)] = "WeaponLevelUpReceiveItem"),
      (e[(e.WeaponCanGoBreach = 273)] = "WeaponCanGoBreach"),
      (e[(e.WeaponItemClick = 274)] = "WeaponItemClick"),
      (e[(e.WeaponEmptyClick = 275)] = "WeaponEmptyClick"),
      (e[(e.WeaponSortClick = 276)] = "WeaponSortClick"),
      (e[(e.WeaponMaterialPropClick = 277)] = "WeaponMaterialPropClick"),
      (e[(e.EquipWeapon = 278)] = "EquipWeapon"),
      (e[(e.ContrastWeapon = 279)] = "ContrastWeapon"),
      (e[(e.WeaponResonanceSuccess = 280)] = "WeaponResonanceSuccess"),
      (e[(e.ReConnectBegin = 281)] = "ReConnectBegin"),
      (e[(e.ReConnectFail = 282)] = "ReConnectFail"),
      (e[(e.CanNotReConnect = 283)] = "CanNotReConnect"),
      (e[(e.ReConnectSuccess = 284)] = "ReConnectSuccess"),
      (e[(e.BackLoginView = 285)] = "BackLoginView"),
      (e[(e.LogOut = 286)] = "LogOut"),
      (e[(e.ExitGamePush = 287)] = "ExitGamePush"),
      (e[(e.NetWorkMaskRpcAdd = 288)] = "NetWorkMaskRpcAdd"),
      (e[(e.NetWorkMaskRpcRemove = 289)] = "NetWorkMaskRpcRemove"),
      (e[(e.OnAimStateChanged = 290)] = "OnAimStateChanged"),
      (e[(e.OnPhantomInputDataUpdate = 291)] = "OnPhantomInputDataUpdate"),
      (e[(e.OpenDragonPoolView = 292)] = "OpenDragonPoolView"),
      (e[(e.UpdateDragonPoolView = 293)] = "UpdateDragonPoolView"),
      (e[(e.LoadMapTileFinish = 294)] = "LoadMapTileFinish"),
      (e[(e.MapOpenAreaChange = 295)] = "MapOpenAreaChange"),
      (e[(e.MapOpenAreaFullUpdate = 296)] = "MapOpenAreaFullUpdate"),
      (e[(e.WorldMapSecondaryUiClosed = 297)] = "WorldMapSecondaryUiClosed"),
      (e[(e.WorldMapSecondaryUiOpened = 298)] = "WorldMapSecondaryUiOpened"),
      (e[(e.BlackScreenFadeOnPlotToWorldMap = 299)] =
        "BlackScreenFadeOnPlotToWorldMap"),
      (e[(e.MarkMenuClickItem = 300)] = "MarkMenuClickItem"),
      (e[(e.RefreshMenuSetting = 301)] = "RefreshMenuSetting"),
      (e[(e.OnGameplaySettingsSet = 302)] = "OnGameplaySettingsSet"),
      (e[(e.ModelReady = 303)] = "ModelReady"),
      (e[(e.MapReplaceMarkResponse = 304)] = "MapReplaceMarkResponse"),
      (e[(e.CreateMapMark = 305)] = "CreateMapMark"),
      (e[(e.RemoveMapMark = 306)] = "RemoveMapMark"),
      (e[(e.TrackMapMark = 307)] = "TrackMapMark"),
      (e[(e.UnlockTeleport = 308)] = "UnlockTeleport"),
      (e[(e.TrackMark = 309)] = "TrackMark"),
      (e[(e.UnTrackMark = 310)] = "UnTrackMark"),
      (e[(e.ClearTrackMark = 311)] = "ClearTrackMark"),
      (e[(e.MarkForceVisibleChanged = 312)] = "MarkForceVisibleChanged"),
      (e[(e.UpdateTrackTarget = 313)] = "UpdateTrackTarget"),
      (e[(e.SetTrackMarkOccupied = 314)] = "SetTrackMarkOccupied"),
      (e[(e.TeleportComplete = 315)] = "TeleportComplete"),
      (e[(e.TeleportStart = 316)] = "TeleportStart"),
      (e[(e.TeleportStartEntity = 317)] = "TeleportStartEntity"),
      (e[(e.OnEnterDailyQuestNotifyRange = 318)] =
        "OnEnterDailyQuestNotifyRange"),
      (e[(e.OnEnterNearbyTrackRange = 319)] = "OnEnterNearbyTrackRange"),
      (e[(e.OnLeaveNearbyTrackRange = 320)] = "OnLeaveNearbyTrackRange"),
      (e[(e.RemoveNearbyTrack = 321)] = "RemoveNearbyTrack"),
      (e[(e.UpdateNearbyTrackTag = 322)] = "UpdateNearbyTrackTag"),
      (e[(e.OnUpdateNearbyEnable = 323)] = "OnUpdateNearbyEnable"),
      (e[(e.WorldMapViewOpened = 324)] = "WorldMapViewOpened"),
      (e[(e.WorldMapPointerDown = 325)] = "WorldMapPointerDown"),
      (e[(e.WorldMapPointerDrag = 326)] = "WorldMapPointerDrag"),
      (e[(e.WorldMapJoystickMoveForward = 327)] =
        "WorldMapJoystickMoveForward"),
      (e[(e.WorldMapJoystickMoveRight = 328)] = "WorldMapJoystickMoveRight"),
      (e[(e.WorldMapJoystickFocusPlayer = 329)] =
        "WorldMapJoystickFocusPlayer"),
      (e[(e.WorldMapDragInertia = 330)] = "WorldMapDragInertia"),
      (e[(e.WorldMapPointerUp = 331)] = "WorldMapPointerUp"),
      (e[(e.WorldMapFingerExpandClose = 332)] = "WorldMapFingerExpandClose"),
      (e[(e.WorldMapWheelAxisInput = 333)] = "WorldMapWheelAxisInput"),
      (e[(e.WorldMapHandleTriggerAxisInput = 334)] =
        "WorldMapHandleTriggerAxisInput"),
      (e[(e.WorldMapPositionChanged = 335)] = "WorldMapPositionChanged"),
      (e[(e.TaskRangeTrackStateChange = 336)] = "TaskRangeTrackStateChange"),
      (e[(e.RangeTrackStateChanged = 337)] = "RangeTrackStateChanged"),
      (e[(e.GetAreaProgress = 338)] = "GetAreaProgress"),
      (e[(e.PlaySoundTrackEffect = 339)] = "PlaySoundTrackEffect"),
      (e[(e.WorldMapNavigate = 340)] = "WorldMapNavigate"),
      (e[(e.WorldMapFirstNavigateSelect = 341)] =
        "WorldMapFirstNavigateSelect"),
      (e[(e.WorldMapSecondNavigateSelect = 342)] =
        "WorldMapSecondNavigateSelect"),
      (e[(e.WorldMapFocalMarkItem = 343)] = "WorldMapFocalMarkItem"),
      (e[(e.WorldMapChangeMap = 344)] = "WorldMapChangeMap"),
      (e[(e.WorldMapBeforeChangeMap = 345)] = "WorldMapBeforeChangeMap"),
      (e[(e.WorldMapAfterChangeMap = 346)] = "WorldMapAfterChangeMap"),
      (e[(e.UpdatePlotSubtitle = 347)] = "UpdatePlotSubtitle"),
      (e[(e.ShowPlotSubtitleOptions = 348)] = "ShowPlotSubtitleOptions"),
      (e[(e.UpdatePlotCenterText = 349)] = "UpdatePlotCenterText"),
      (e[(e.UpdatePortraitVisible = 350)] = "UpdatePortraitVisible"),
      (e[(e.OnStartFlow = 351)] = "OnStartFlow"),
      (e[(e.PlotNetworkStart = 352)] = "PlotNetworkStart"),
      (e[(e.PlotNetworkEnd = 353)] = "PlotNetworkEnd"),
      (e[(e.PlotConfigChanged = 354)] = "PlotConfigChanged"),
      (e[(e.PlotDoingTextShow = 355)] = "PlotDoingTextShow"),
      (e[(e.ClearPlotSubtitle = 356)] = "ClearPlotSubtitle"),
      (e[(e.HidePlotUi = 357)] = "HidePlotUi"),
      (e[(e.PlotInteractViewOpen = 358)] = "PlotInteractViewOpen"),
      (e[(e.TriggerPlotInteraction = 359)] = "TriggerPlotInteraction"),
      (e[(e.TriggerBlackSequence = 360)] = "TriggerBlackSequence"),
      (e[(e.OnBlackFadeScreenStart = 361)] = "OnBlackFadeScreenStart"),
      (e[(e.OnBlackFadeScreenFinish = 362)] = "OnBlackFadeScreenFinish"),
      (e[(e.EnableSkipPlot = 363)] = "EnableSkipPlot"),
      (e[(e.PlotSequencePlay = 364)] = "PlotSequencePlay"),
      (e[(e.HangPlotViewHud = 365)] = "HangPlotViewHud"),
      (e[(e.UpdatePlotUiParam = 366)] = "UpdatePlotUiParam"),
      (e[(e.PlotViewChange = 367)] = "PlotViewChange"),
      (e[(e.PlotViewBgFadePhoto = 368)] = "PlotViewBgFadePhoto"),
      (e[(e.PlotViewBgFadeBlackScreen = 369)] = "PlotViewBgFadeBlackScreen"),
      (e[(e.PlotStartShowTalk = 370)] = "PlotStartShowTalk"),
      (e[(e.PlotEndShowTalk = 371)] = "PlotEndShowTalk"),
      (e[(e.PlotEnableControlView = 372)] = "PlotEnableControlView"),
      (e[(e.PrewarFormationChanged = 373)] = "PrewarFormationChanged"),
      (e[(e.PrewarReadyChanged = 374)] = "PrewarReadyChanged"),
      (e[(e.DissolvePrewar = 375)] = "DissolvePrewar"),
      (e[(e.SceneStepGroupChanged = 376)] = "SceneStepGroupChanged"),
      (e[(e.InstanceStepChanged = 377)] = "InstanceStepChanged"),
      (e[(e.InstanceEnterCountChanged = 378)] = "InstanceEnterCountChanged"),
      (e[(e.InstanceEntranceUnlock = 379)] = "InstanceEntranceUnlock"),
      (e[(e.EnterInstanceDungeon = 380)] = "EnterInstanceDungeon"),
      (e[(e.LeaveInstanceDungeon = 381)] = "LeaveInstanceDungeon"),
      (e[(e.DungeonGuideChange = 382)] = "DungeonGuideChange"),
      (e[(e.LeaveInstanceDungeonConfirm = 383)] =
        "LeaveInstanceDungeonConfirm"),
      (e[(e.OnDungeonFinish = 384)] = "OnDungeonFinish"),
      (e[(e.OnSelectInstance = 385)] = "OnSelectInstance"),
      (e[(e.OnRefreshEditBattleRoleSlotData = 386)] =
        "OnRefreshEditBattleRoleSlotData"),
      (e[(e.OnRefreshEditBattleRoleReady = 387)] =
        "OnRefreshEditBattleRoleReady"),
      (e[(e.EntityVisionSkillChanged = 388)] = "EntityVisionSkillChanged"),
      (e[(e.GetAllVisionSkill = 389)] = "GetAllVisionSkill"),
      (e[(e.VisionSkillUp = 390)] = "VisionSkillUp"),
      (e[(e.ExploreVisionSkill = 391)] = "ExploreVisionSkill"),
      (e[(e.VisionMorphBegin = 392)] = "VisionMorphBegin"),
      (e[(e.VisionMorphEnd = 393)] = "VisionMorphEnd"),
      (e[(e.VisionMorphInterrupt = 394)] = "VisionMorphInterrupt"),
      (e[(e.AddExploreVisionSkill = 395)] = "AddExploreVisionSkill"),
      (e[(e.ChangeVisionSkillByTab = 396)] = "ChangeVisionSkillByTab"),
      (e[(e.ChangeVisionSimplyState = 397)] = "ChangeVisionSimplyState"),
      (e[(e.VisionSkinViewClose = 398)] = "VisionSkinViewClose"),
      (e[(e.ChangeCalabashCollectSimplyState = 399)] =
        "ChangeCalabashCollectSimplyState"),
      (e[(e.SelectedPhantom = 400)] = "SelectedPhantom"),
      (e[(e.CheckNewUnlock = 401)] = "CheckNewUnlock"),
      (e[(e.PhantomEquip = 402)] = "PhantomEquip"),
      (e[(e.PhantomEquipError = 403)] = "PhantomEquipError"),
      (e[(e.VisionFilterMonster = 404)] = "VisionFilterMonster"),
      (e[(e.OnRolePropUpdate = 405)] = "OnRolePropUpdate"),
      (e[(e.RefreshVisionIntensifyViewBackBtnState = 406)] =
        "RefreshVisionIntensifyViewBackBtnState"),
      (e[(e.OnClickVisionIntensifyItemJump = 407)] =
        "OnClickVisionIntensifyItemJump"),
      (e[(e.VisionIntensifyTabOpen = 408)] = "VisionIntensifyTabOpen"),
      (e[(e.PhantomPersonalSkillActive = 409)] = "PhantomPersonalSkillActive"),
      (e[(e.PhantomEquipWithSourceAndTargetPos = 410)] =
        "PhantomEquipWithSourceAndTargetPos"),
      (e[(e.PhantomCostInsufficient = 411)] = "PhantomCostInsufficient"),
      (e[(e.PhantomExpPreviewChange = 412)] = "PhantomExpPreviewChange"),
      (e[(e.PhantomLevelUp = 413)] = "PhantomLevelUp"),
      (e[(e.PhantomLevelUpWithId = 414)] = "PhantomLevelUpWithId"),
      (e[(e.PhantomLevelUpReceiveItem = 415)] = "PhantomLevelUpReceiveItem"),
      (e[(e.CloseSubPhantomView = 416)] = "CloseSubPhantomView"),
      (e[(e.PhantomBreach = 417)] = "PhantomBreach"),
      (e[(e.PhantomBreachPreview = 418)] = "PhantomBreachPreview"),
      (e[(e.PhantomDecomposePreview = 419)] = "PhantomDecomposePreview"),
      (e[(e.PhantomDecompose = 420)] = "PhantomDecompose"),
      (e[(e.PhantomMaxLevelSkip = 421)] = "PhantomMaxLevelSkip"),
      (e[(e.HideDelFettersText = 422)] = "HideDelFettersText"),
      (e[(e.PhantomRecommendResponse = 423)] = "PhantomRecommendResponse"),
      (e[(e.ClosePhantomSkillTips = 424)] = "ClosePhantomSkillTips"),
      (e[(e.OnPhantomItemUpdate = 425)] = "OnPhantomItemUpdate"),
      (e[(e.OnPhantomSlotUpdate = 426)] = "OnPhantomSlotUpdate"),
      (e[(e.OnPhantomEnableStateChange = 427)] = "OnPhantomEnableStateChange"),
      (e[(e.OnVisionIdentify = 428)] = "OnVisionIdentify"),
      (e[(e.OnVisionIdentifyWithId = 429)] = "OnVisionIdentifyWithId"),
      (e[(e.OnVisionIdentifyDoAnimation = 430)] =
        "OnVisionIdentifyDoAnimation"),
      (e[(e.RefreshVisionIdentifyRedPoint = 431)] =
        "RefreshVisionIdentifyRedPoint"),
      (e[(e.RefreshVisionEquipRedPoint = 432)] = "RefreshVisionEquipRedPoint"),
      (e[(e.JumpToCalabashCollect = 433)] = "JumpToCalabashCollect"),
      (e[(e.JumpToPhantomBattleFettersTabView = 434)] =
        "JumpToPhantomBattleFettersTabView"),
      (e[(e.OnVisionSkinEquip = 435)] = "OnVisionSkinEquip"),
      (e[(e.RedDotRefreshCalabash = 436)] = "RedDotRefreshCalabash"),
      (e[(e.HasCalabashExp = 437)] = "HasCalabashExp"),
      (e[(e.CloseUpgradeCalabashView = 438)] = "CloseUpgradeCalabashView"),
      (e[(e.CloseCalabashExpAddView = 439)] = "CloseCalabashExpAddView"),
      (e[(e.ShowCalabashControllerView = 440)] = "ShowCalabashControllerView"),
      (e[(e.GetCalabashRewardSuccess = 441)] = "GetCalabashRewardSuccess"),
      (e[(e.ShowCalabashUnlockItemTips = 442)] = "ShowCalabashUnlockItemTips"),
      (e[(e.GetCalabashReward = 443)] = "GetCalabashReward"),
      (e[(e.CalabashLevelUpdate = 444)] = "CalabashLevelUpdate"),
      (e[(e.CalabashEnterInternalView = 445)] = "CalabashEnterInternalView"),
      (e[(e.CalabashQuitInternalView = 446)] = "CalabashQuitInternalView"),
      (e[(e.OnVisionRecoveryResult = 447)] = "OnVisionRecoveryResult"),
      (e[(e.OnVisionRecoveryBatchResult = 448)] =
        "OnVisionRecoveryBatchResult"),
      (e[(e.OnVisionRecoveryStorage = 449)] = "OnVisionRecoveryStorage"),
      (e[(e.OnRefreshCalabashTabShowState = 450)] =
        "OnRefreshCalabashTabShowState"),
      (e[(e.OnSetPartStateVisible = 451)] = "OnSetPartStateVisible"),
      (e[(e.ShowHUD = 452)] = "ShowHUD"),
      (e[(e.HideHUD = 453)] = "HideHUD"),
      (e[(e.OnGetPlayerBasicInfo = 454)] = "OnGetPlayerBasicInfo"),
      (e[(e.OnLoadedNewFlagConfig = 455)] = "OnLoadedNewFlagConfig"),
      (e[(e.OnPlayerLevelChanged = 456)] = "OnPlayerLevelChanged"),
      (e[(e.OnPlayerExpChanged = 457)] = "OnPlayerExpChanged"),
      (e[(e.OnLevelUpLevelRefresh = 458)] = "OnLevelUpLevelRefresh"),
      (e[(e.OnLevelUpExpRefresh = 459)] = "OnLevelUpExpRefresh"),
      (e[(e.OnLevelUpShowLevelOnly = 460)] = "OnLevelUpShowLevelOnly"),
      (e[(e.SelectFilterMultiple = 461)] = "SelectFilterMultiple"),
      (e[(e.SelectFilterSingle = 462)] = "SelectFilterSingle"),
      (e[(e.SelectSort = 463)] = "SelectSort"),
      (e[(e.OnSceneItemHit = 464)] = "OnSceneItemHit"),
      (e[(e.OnSceneItemHitByHitData = 465)] = "OnSceneItemHitByHitData"),
      (e[(e.OnSceneItemEntityHit = 466)] = "OnSceneItemEntityHit"),
      (e[(e.OnSceneItemEntityHitAlways = 467)] = "OnSceneItemEntityHitAlways"),
      (e[(e.OnAnySceneItemEntityHit = 468)] = "OnAnySceneItemEntityHit"),
      (e[(e.OnAnySceneItemDurabilityChange = 469)] =
        "OnAnySceneItemDurabilityChange"),
      (e[(e.OnSceneItemDurabilityChange = 470)] =
        "OnSceneItemDurabilityChange"),
      (e[(e.UpdateSceneItemState = 471)] = "UpdateSceneItemState"),
      (e[(e.OnSceneItemDestroy = 472)] = "OnSceneItemDestroy"),
      (e[(e.OnSceneItemStateChange = 473)] = "OnSceneItemStateChange"),
      (e[(e.OnSceneItemStatePreChange = 474)] = "OnSceneItemStatePreChange"),
      (e[(e.OnSceneItemStatePrechangeInSequence = 475)] =
        "OnSceneItemStatePrechangeInSequence"),
      (e[(e.OnEntityConcealedChange = 476)] = "OnEntityConcealedChange"),
      (e[(e.OnTimeTrackControlUpdate = 477)] = "OnTimeTrackControlUpdate"),
      (e[(e.OnSceneInteractionLoadCompleted = 478)] =
        "OnSceneInteractionLoadCompleted"),
      (e[(e.OnSceneItemVisionCaptureAdd = 479)] =
        "OnSceneItemVisionCaptureAdd"),
      (e[(e.OnSceneItemVisionCaptureRemove = 480)] =
        "OnSceneItemVisionCaptureRemove"),
      (e[(e.OnInputDistributeTagChanged = 481)] =
        "OnInputDistributeTagChanged"),
      (e[(e.OnDeviceLangChange = 482)] = "OnDeviceLangChange"),
      (e[(e.ForceReleaseInput = 483)] = "ForceReleaseInput"),
      (e[(e.OnFormationPlayLevelUp = 484)] = "OnFormationPlayLevelUp"),
      (e[(e.OnFormationPlayRevive = 485)] = "OnFormationPlayRevive"),
      (e[(e.OnItemUse = 486)] = "OnItemUse"),
      (e[(e.OnSpecialItemUse = 487)] = "OnSpecialItemUse"),
      (e[(e.OnGameplayTagChanged = 488)] = "OnGameplayTagChanged"),
      (e[(e.OnLevelTagChanged = 489)] = "OnLevelTagChanged"),
      (e[(e.OnGlobalGameplayTagChanged = 490)] = "OnGlobalGameplayTagChanged"),
      (e[(e.LevelEventTriggerExit = 491)] = "LevelEventTriggerExit"),
      (e[(e.OnLevelPlayStateChange = 492)] = "OnLevelPlayStateChange"),
      (e[(e.TodTimeChange = 493)] = "TodTimeChange"),
      (e[(e.DayStateChange = 494)] = "DayStateChange"),
      (e[(e.CrossDay = 495)] = "CrossDay"),
      (e[(e.ClickTimeItem = 496)] = "ClickTimeItem"),
      (e[(e.OnSelectTimeItem = 497)] = "OnSelectTimeItem"),
      (e[(e.AdjustTime = 498)] = "AdjustTime"),
      (e[(e.AdjustTimeInAnim = 499)] = "AdjustTimeInAnim"),
      (e[(e.PowerShopReady = 500)] = "PowerShopReady"),
      (e[(e.OnPowerChanged = 501)] = "OnPowerChanged"),
      (e[(e.OnPowerChangedWithId = 502)] = "OnPowerChangedWithId"),
      (e[(e.OnGamePlayCdChanged = 503)] = "OnGamePlayCdChanged"),
      (e[(e.InsertFloatTips = 504)] = "InsertFloatTips"),
      (e[(e.OriginWorldLevelUp = 505)] = "OriginWorldLevelUp"),
      (e[(e.CurWorldLevelChange = 506)] = "CurWorldLevelChange"),
      (e[(e.WorldLevelUpViewRefresh = 507)] = "WorldLevelUpViewRefresh"),
      (e[(e.OnShowMouseCursor = 508)] = "OnShowMouseCursor"),
      (e[(e.RefreshCursor = 509)] = "RefreshCursor"),
      (e[(e.InputDistribute = 510)] = "InputDistribute"),
      (e[(e.OnRefreshJoinTeamRole = 511)] = "OnRefreshJoinTeamRole"),
      (e[(e.LoadLguiEventSystemActor = 512)] = "LoadLguiEventSystemActor"),
      (e[(e.DestroyLguiEventSystemActor = 513)] =
        "DestroyLguiEventSystemActor"),
      (e[(e.OnUseBuffItem = 514)] = "OnUseBuffItem"),
      (e[(e.UpdateQuestDetails = 515)] = "UpdateQuestDetails"),
      (e[(e.UpdateRoleQuestDetails = 516)] = "UpdateRoleQuestDetails"),
      (e[(e.QuestUpdateInfoAdd = 517)] = "QuestUpdateInfoAdd"),
      (e[(e.AddInteractOptionByAction = 518)] = "AddInteractOptionByAction"),
      (e[(e.RemoveInteractOptionByAction = 519)] =
        "RemoveInteractOptionByAction"),
      (e[(e.OnQuestStateChange = 520)] = "OnQuestStateChange"),
      (e[(e.OnQuestFinishListNotify = 521)] = "OnQuestFinishListNotify"),
      (e[(e.OnQuestRedDotStateChange = 522)] = "OnQuestRedDotStateChange"),
      (e[(e.OnQuestFinishProtocolEnd = 523)] = "OnQuestFinishProtocolEnd"),
      (e[(e.OnRoleQuestAccept = 524)] = "OnRoleQuestAccept"),
      (e[(e.OnRoleQuestPointChange = 525)] = "OnRoleQuestPointChange"),
      (e[(e.OnRoleQuestNewUnlock = 526)] = "OnRoleQuestNewUnlock"),
      (e[(e.OnAddNewQuest = 527)] = "OnAddNewQuest"),
      (e[(e.OnNavigationQuest = 528)] = "OnNavigationQuest"),
      (e[(e.ActivityQuestCountdownEnd = 529)] = "ActivityQuestCountdownEnd"),
      (e[(e.OnQuestStageNameChange = 530)] = "OnQuestStageNameChange"),
      (e[(e.GeneralLogicTreeWakeUp = 531)] = "GeneralLogicTreeWakeUp"),
      (e[(e.OnLogicTreeNodeStatusChange = 532)] =
        "OnLogicTreeNodeStatusChange"),
      (e[(e.OnLogicTreeChildQuestNodeStatusChange = 533)] =
        "OnLogicTreeChildQuestNodeStatusChange"),
      (e[(e.OnLogicTreeNodeProgressChange = 534)] =
        "OnLogicTreeNodeProgressChange"),
      (e[(e.GeneralLogicTreeTimerInfoChanged = 535)] =
        "GeneralLogicTreeTimerInfoChanged"),
      (e[(e.OnLogicTreeTrackUpdate = 536)] = "OnLogicTreeTrackUpdate"),
      (e[(e.CurTrackQuestUnTrackedCheck = 537)] =
        "CurTrackQuestUnTrackedCheck"),
      (e[(e.OnLogicTreeTimerTick = 538)] = "OnLogicTreeTimerTick"),
      (e[(e.GeneralLogicTreeStartShowTrackText = 539)] =
        "GeneralLogicTreeStartShowTrackText"),
      (e[(e.GeneralLogicTreeUpdateShowTrackText = 540)] =
        "GeneralLogicTreeUpdateShowTrackText"),
      (e[(e.GeneralLogicTreeEndShowTrackText = 541)] =
        "GeneralLogicTreeEndShowTrackText"),
      (e[(e.GeneralLogicTreeRemove = 542)] = "GeneralLogicTreeRemove"),
      (e[(e.GeneralLogicTreeSuspend = 543)] = "GeneralLogicTreeSuspend"),
      (e[(e.GeneralLogicTreeCancelSuspend = 544)] =
        "GeneralLogicTreeCancelSuspend"),
      (e[(e.GeneralLogicTreePrepareRollback = 545)] =
        "GeneralLogicTreePrepareRollback"),
      (e[(e.GeneralLogicTreeRemovePrepareRollbackNode = 546)] =
        "GeneralLogicTreeRemovePrepareRollbackNode"),
      (e[(e.GeneralLogicTreeRollbackWaitingUpdate = 547)] =
        "GeneralLogicTreeRollbackWaitingUpdate"),
      (e[(e.GeneralLogicTreeEntityInteractFinished = 548)] =
        "GeneralLogicTreeEntityInteractFinished"),
      (e[(e.GeneralLogicTreeEntityKilled = 549)] =
        "GeneralLogicTreeEntityKilled"),
      (e[(e.GeneralLogicTreeAddTag = 550)] = "GeneralLogicTreeAddTag"),
      (e[(e.GeneralLogicTreeRemoveTag = 551)] = "GeneralLogicTreeRemoveTag"),
      (e[(e.GeneralLogicTreeViewForceRefresh = 552)] =
        "GeneralLogicTreeViewForceRefresh"),
      (e[(e.GeneralLogicTreeApplyExpressionOccupation = 553)] =
        "GeneralLogicTreeApplyExpressionOccupation"),
      (e[(e.GeneralLogicTreeReleaseExpressionOccupation = 554)] =
        "GeneralLogicTreeReleaseExpressionOccupation"),
      (e[(e.MissionPanelProcessEnd = 555)] = "MissionPanelProcessEnd"),
      (e[(e.QuestUpdateTipsClickTrack = 556)] = "QuestUpdateTipsClickTrack"),
      (e[(e.MissionPanelOut = 557)] = "MissionPanelOut"),
      (e[(e.MissionUpdate = 558)] = "MissionUpdate"),
      (e[(e.MissionUpdateAnimEnd = 559)] = "MissionUpdateAnimEnd"),
      (e[(e.MissionPanelStepTitleAnimStart = 560)] =
        "MissionPanelStepTitleAnimStart"),
      (e[(e.MissionPanelStepTitleAnimEnd = 561)] =
        "MissionPanelStepTitleAnimEnd"),
      (e[(e.FailRangeTimerStartShow = 562)] = "FailRangeTimerStartShow"),
      (e[(e.FailRangeTimerEndShow = 563)] = "FailRangeTimerEndShow"),
      (e[(e.ParkourFinished = 564)] = "ParkourFinished"),
      (e[(e.OnOpenDebugCommand = 565)] = "OnOpenDebugCommand"),
      (e[(e.ResetToBattleView = 566)] = "ResetToBattleView"),
      (e[(e.ResetModuleByResetToBattleView = 567)] =
        "ResetModuleByResetToBattleView"),
      (e[(e.ResetModuleAfterResetToBattleView = 568)] =
        "ResetModuleAfterResetToBattleView"),
      (e[(e.ExitNormalQueueState = 569)] = "ExitNormalQueueState"),
      (e[(e.OnStartLoadingState = 570)] = "OnStartLoadingState"),
      (e[(e.OnFinishLoadingState = 571)] = "OnFinishLoadingState"),
      (e[(e.OnOpenLoadingView = 572)] = "OnOpenLoadingView"),
      (e[(e.OnCloseLoadingView = 573)] = "OnCloseLoadingView"),
      (e[(e.OnLoadingNetDataDone = 574)] = "OnLoadingNetDataDone"),
      (e[(e.PlayUiComponentCloseTween = 575)] = "PlayUiComponentCloseTween"),
      (e[(e.ChangeUiComponentMarkId = 576)] = "ChangeUiComponentMarkId"),
      (e[(e.OnMenuDataEnableChanged = 577)] = "OnMenuDataEnableChanged"),
      (e[(e.OnSelectMenuMainType = 578)] = "OnSelectMenuMainType"),
      (e[(e.ChangeConfigValue = 579)] = "ChangeConfigValue"),
      (e[(e.RestartFlag = 580)] = "RestartFlag"),
      (e[(e.SettingFrameRateChanged = 581)] = "SettingFrameRateChanged"),
      (e[(e.TextLanguageChange = 582)] = "TextLanguageChange"),
      (e[(e.ConfigLoadChange = 583)] = "ConfigLoadChange"),
      (e[(e.SneakResult = 584)] = "SneakResult"),
      (e[(e.SneakMonsterStart = 585)] = "SneakMonsterStart"),
      (e[(e.SneakMonsterStop = 586)] = "SneakMonsterStop"),
      (e[(e.ChannelReset = 587)] = "ChannelReset"),
      (e[(e.OnShareResult = 588)] = "OnShareResult"),
      (e[(e.OnFirstShare = 589)] = "OnFirstShare"),
      (e[(e.ShowVideo = 590)] = "ShowVideo"),
      (e[(e.VideoStart = 591)] = "VideoStart"),
      (e[(e.PlayVideo = 592)] = "PlayVideo"),
      (e[(e.ScanTrackedStart = 593)] = "ScanTrackedStart"),
      (e[(e.ScanTrackedEnd = 594)] = "ScanTrackedEnd"),
      (e[(e.OnScanStart = 595)] = "OnScanStart"),
      (e[(e.RedDotStart = 596)] = "RedDotStart"),
      (e[(e.RedDotRefreshItemData = 597)] = "RedDotRefreshItemData"),
      (e[(e.RedDotRoleConfigList = 598)] = "RedDotRoleConfigList"),
      (e[(e.RedDotRefreshPhantomEquip = 599)] = "RedDotRefreshPhantomEquip"),
      (e[(e.RedDotRoleChange = 600)] = "RedDotRoleChange"),
      (e[(e.RedDotUnLockPhantom = 601)] = "RedDotUnLockPhantom"),
      (e[(e.RedDotNewTutorial = 602)] = "RedDotNewTutorial"),
      (e[(e.RedDotNewTutorialType = 603)] = "RedDotNewTutorialType"),
      (e[(e.RedDotAdventureManualUpdate = 604)] =
        "RedDotAdventureManualUpdate"),
      (e[(e.RedDotSilentFirstAward = 605)] = "RedDotSilentFirstAward"),
      (e[(e.RedDotSilentFirstAwardCategory = 606)] =
        "RedDotSilentFirstAwardCategory"),
      (e[(e.RedDotSilentFirstAwardResult = 607)] =
        "RedDotSilentFirstAwardResult"),
      (e[(e.RedDotCreateRole = 608)] = "RedDotCreateRole"),
      (e[(e.RouletteRefreshRedDot = 609)] = "RouletteRefreshRedDot"),
      (e[(e.SilentTipsRefresh = 610)] = "SilentTipsRefresh"),
      (e[(e.OnRefreshElementBallData = 611)] = "OnRefreshElementBallData"),
      (e[(e.ShootTargetStateChanged = 612)] = "ShootTargetStateChanged"),
      (e[(e.InteractNavigation = 613)] = "InteractNavigation"),
      (e[(e.InteractionViewUpdate = 614)] = "InteractionViewUpdate"),
      (e[(e.HideInteractView = 615)] = "HideInteractView"),
      (e[(e.SceneItemInteractionEvent = 616)] = "SceneItemInteractionEvent"),
      (e[(e.OnFunctionOpenSet = 617)] = "OnFunctionOpenSet"),
      (e[(e.OnFunctionOpenUpdate = 618)] = "OnFunctionOpenUpdate"),
      (e[(e.OnFunctionOpenUpdateNotify = 619)] = "OnFunctionOpenUpdateNotify"),
      (e[(e.OnConcertoResponseOpen = 620)] = "OnConcertoResponseOpen"),
      (e[(e.OnFirstOpenShopChanged = 621)] = "OnFirstOpenShopChanged"),
      (e[(e.OnSetHeadStateVisible = 622)] = "OnSetHeadStateVisible"),
      (e[(e.OnSetBossStateVisible = 623)] = "OnSetBossStateVisible"),
      (e[(e.SdkKick = 624)] = "SdkKick"),
      (e[(e.SdkPostWebViewRedPointRefresh = 625)] =
        "SdkPostWebViewRedPointRefresh"),
      (e[(e.SdkCustomerRedPointRefresh = 626)] = "SdkCustomerRedPointRefresh"),
      (e[(e.UpdateFriendViewShow = 627)] = "UpdateFriendViewShow"),
      (e[(e.UpdateRecentlyTeamDataEvent = 628)] =
        "UpdateRecentlyTeamDataEvent"),
      (e[(e.OnRemoveFriend = 629)] = "OnRemoveFriend"),
      (e[(e.FriendApplicationListUpdate = 630)] =
        "FriendApplicationListUpdate"),
      (e[(e.UpdateBlackListShow = 631)] = "UpdateBlackListShow"),
      (e[(e.SearchPlayerInfo = 632)] = "SearchPlayerInfo"),
      (e[(e.FriendRemarkLengthLimit = 633)] = "FriendRemarkLengthLimit"),
      (e[(e.FriendRemarkContainsDirtyWord = 634)] =
        "FriendRemarkContainsDirtyWord"),
      (e[(e.RefreshFriendApplicationRedDot = 635)] =
        "RefreshFriendApplicationRedDot"),
      (e[(e.FriendApplyReceived = 636)] = "FriendApplyReceived"),
      (e[(e.FriendAdded = 637)] = "FriendAdded"),
      (e[(e.LoadTestFriendsByGm = 638)] = "LoadTestFriendsByGm"),
      (e[(e.ApplicationHandled = 639)] = "ApplicationHandled"),
      (e[(e.ApplicationSent = 640)] = "ApplicationSent"),
      (e[(e.OnGetFriendInitData = 641)] = "OnGetFriendInitData"),
      (e[(e.FriendOnMultiItemAction = 642)] = "FriendOnMultiItemAction"),
      (e[(e.OnNavigationViewUiCreated = 643)] = "OnNavigationViewUiCreated"),
      (e[(e.OnUiNavigationViewSetActive = 644)] =
        "OnUiNavigationViewSetActive"),
      (e[(e.InputControllerChange = 645)] = "InputControllerChange"),
      (e[(e.InputControllerMainTypeChange = 646)] =
        "InputControllerMainTypeChange"),
      (e[(e.ShowTypeChange = 647)] = "ShowTypeChange"),
      (e[(e.PointerInputTypeChange = 648)] = "PointerInputTypeChange"),
      (e[(e.ControllerConnectChange = 649)] = "ControllerConnectChange"),
      (e[(e.ChangeScrollBarPosition = 650)] = "ChangeScrollBarPosition"),
      (e[(e.OnSelectChatFriend = 651)] = "OnSelectChatFriend"),
      (e[(e.OnCreatePrivateChatRoom = 652)] = "OnCreatePrivateChatRoom"),
      (e[(e.OnJoinChatRoom = 653)] = "OnJoinChatRoom"),
      (e[(e.OnAddChatContent = 654)] = "OnAddChatContent"),
      (e[(e.OnRefreshChatRedDot = 655)] = "OnRefreshChatRedDot"),
      (e[(e.OnRefreshChatRoomRedDot = 656)] = "OnRefreshChatRoomRedDot"),
      (e[(e.OnAddHistoryChatContentCompleted = 657)] =
        "OnAddHistoryChatContentCompleted"),
      (e[(e.OnPushChatRowData = 658)] = "OnPushChatRowData"),
      (e[(e.OnPopChatRowData = 659)] = "OnPopChatRowData"),
      (e[(e.OnRefreshChatRowData = 660)] = "OnRefreshChatRowData"),
      (e[(e.OnAddMutePlayer = 661)] = "OnAddMutePlayer"),
      (e[(e.OnRemoveMutePlayer = 662)] = "OnRemoveMutePlayer"),
      (e[(e.OnRemovePrivateChatRoom = 663)] = "OnRemovePrivateChatRoom"),
      (e[(e.OnClosePrivateChatRoom = 664)] = "OnClosePrivateChatRoom"),
      (e[(e.OnOpenChatRoom = 665)] = "OnOpenChatRoom"),
      (e[(e.OnSelectExpression = 666)] = "OnSelectExpression"),
      (e[(e.OnServerAttributeChange = 667)] = "OnServerAttributeChange"),
      (e[(e.OnPayItemSuccess = 668)] = "OnPayItemSuccess"),
      (e[(e.RefreshPayItemList = 669)] = "RefreshPayItemList"),
      (e[(e.RefreshPayGiftList = 670)] = "RefreshPayGiftList"),
      (e[(e.OnPlayerCurrencyChange = 671)] = "OnPlayerCurrencyChange"),
      (e[(e.OnRefreshPermissionsSetting = 672)] =
        "OnRefreshPermissionsSetting"),
      (e[(e.OnRefreshApply = 673)] = "OnRefreshApply"),
      (e[(e.OnSearchWorld = 674)] = "OnSearchWorld"),
      (e[(e.OnRefreshWorldList = 675)] = "OnRefreshWorldList"),
      (e[(e.OnRefreshOnlineTeamList = 676)] = "OnRefreshOnlineTeamList"),
      (e[(e.OnWorldTeamPlayerInfoChanged = 677)] =
        "OnWorldTeamPlayerInfoChanged"),
      (e[(e.OnRefreshPlayerPing = 678)] = "OnRefreshPlayerPing"),
      (e[(e.OnRefreshPlayerUiState = 679)] = "OnRefreshPlayerUiState"),
      (e[(e.OnRefreshOnlineChallengePlayer = 680)] =
        "OnRefreshOnlineChallengePlayer"),
      (e[(e.OnRefreshSuggestChallengePlayerInfo = 681)] =
        "OnRefreshSuggestChallengePlayerInfo"),
      (e[(e.SwitchPayShopTabItem = 682)] = "SwitchPayShopTabItem"),
      (e[(e.PayShopGoodsBuy = 683)] = "PayShopGoodsBuy"),
      (e[(e.GoodsRefreshDiscountTime = 684)] = "GoodsRefreshDiscountTime"),
      (e[(e.SwitchPayShopView = 685)] = "SwitchPayShopView"),
      (e[(e.RefreshPayShop = 686)] = "RefreshPayShop"),
      (e[(e.RefreshAllPayShop = 687)] = "RefreshAllPayShop"),
      (e[(e.RefreshGoods = 688)] = "RefreshGoods"),
      (e[(e.ShopVersionCodeChange = 689)] = "ShopVersionCodeChange"),
      (e[(e.GoodsSoldOut = 690)] = "GoodsSoldOut"),
      (e[(e.RefreshGoodsList = 691)] = "RefreshGoodsList"),
      (e[(e.UnLockGoods = 692)] = "UnLockGoods"),
      (e[(e.RefreshPayShopEntranceRedDot = 693)] =
        "RefreshPayShopEntranceRedDot"),
      (e[(e.RefreshPayShopInstanceRedDot = 694)] =
        "RefreshPayShopInstanceRedDot"),
      (e[(e.RefreshPayShopTabRedDot = 695)] = "RefreshPayShopTabRedDot"),
      (e[(e.DiscountShopTimerRefresh = 696)] = "DiscountShopTimerRefresh"),
      (e[(e.OnOpenGachaChanged = 697)] = "OnOpenGachaChanged"),
      (e[(e.RefreshGachaMainView = 698)] = "RefreshGachaMainView"),
      (e[(e.GachaPoolSelectResponse = 699)] = "GachaPoolSelectResponse"),
      (e[(e.GachaResponse = 700)] = "GachaResponse"),
      (e[(e.GachaHistoryResponse = 701)] = "GachaHistoryResponse"),
      (e[(e.CloseGachaSceneView = 702)] = "CloseGachaSceneView"),
      (e[(e.EndGachaScene = 703)] = "EndGachaScene"),
      (e[(e.GachaClick = 704)] = "GachaClick"),
      (e[(e.GachaSelectionViewRefresh = 705)] = "GachaSelectionViewRefresh"),
      (e[(e.AfterCloseGachaScene = 706)] = "AfterCloseGachaScene"),
      (e[(e.PlaySequenceEventByStringParam = 707)] =
        "PlaySequenceEventByStringParam"),
      (e[(e.GachaInteractFinish = 708)] = "GachaInteractFinish"),
      (e[(e.ItemExChangeResponse = 709)] = "ItemExChangeResponse"),
      (e[(e.ItemHintVisibilityChange = 710)] = "ItemHintVisibilityChange"),
      (e[(e.ShowAnimalsHeadInfo = 711)] = "ShowAnimalsHeadInfo"),
      (e[(e.OnAnimalDying = 712)] = "OnAnimalDying"),
      (e[(e.OnSkillButtonDataRefresh = 713)] = "OnSkillButtonDataRefresh"),
      (e[(e.OnSkillButtonDataClear = 714)] = "OnSkillButtonDataClear"),
      (e[(e.OnSkillButtonIndexRefresh = 715)] = "OnSkillButtonIndexRefresh"),
      (e[(e.OnSkillButtonEnableRefresh = 716)] = "OnSkillButtonEnableRefresh"),
      (e[(e.OnSkillButtonVisibleRefresh = 717)] =
        "OnSkillButtonVisibleRefresh"),
      (e[(e.OnSkillButtonSkillIdRefresh = 718)] =
        "OnSkillButtonSkillIdRefresh"),
      (e[(e.OnSkillButtonDynamicEffectRefresh = 719)] =
        "OnSkillButtonDynamicEffectRefresh"),
      (e[(e.OnSkillButtonCdRefresh = 720)] = "OnSkillButtonCdRefresh"),
      (e[(e.OnSkillButtonAttributeRefresh = 721)] =
        "OnSkillButtonAttributeRefresh"),
      (e[(e.OnSkillButtonIconPathRefresh = 722)] =
        "OnSkillButtonIconPathRefresh"),
      (e[(e.OnBehaviorButtonVisibleRefresh = 723)] =
        "OnBehaviorButtonVisibleRefresh"),
      (e[(e.OnInputChangeForCond = 724)] = "OnInputChangeForCond"),
      (e[(e.OnGetNewItem = 725)] = "OnGetNewItem"),
      (e[(e.OnElementFusion = 726)] = "OnElementFusion"),
      (e[(e.OnChangeSelectedExploreId = 727)] = "OnChangeSelectedExploreId"),
      (e[(e.OnRouletteViewVisibleChanged = 728)] =
        "OnRouletteViewVisibleChanged"),
      (e[(e.OnRouletteItemSelect = 729)] = "OnRouletteItemSelect"),
      (e[(e.OnRouletteItemUnlock = 730)] = "OnRouletteItemUnlock"),
      (e[(e.OnRouletteSaveDataChange = 731)] = "OnRouletteSaveDataChange"),
      (e[(e.OpenRouletteSetView = 732)] = "OpenRouletteSetView"),
      (e[(e.OnAggroAdd = 733)] = "OnAggroAdd"),
      (e[(e.OnAggroRemoved = 734)] = "OnAggroRemoved"),
      (e[(e.OnBossFight = 735)] = "OnBossFight"),
      (e[(e.OnSkillTagChanged = 736)] = "OnSkillTagChanged"),
      (e[(e.OnMatchingChange = 737)] = "OnMatchingChange"),
      (e[(e.OnMatchingBegin = 738)] = "OnMatchingBegin"),
      (e[(e.OnEnterTeam = 739)] = "OnEnterTeam"),
      (e[(e.OnLeaveTeam = 740)] = "OnLeaveTeam"),
      (e[(e.OnEnterOnlineWorld = 741)] = "OnEnterOnlineWorld"),
      (e[(e.OnLeaveOnlineWorld = 742)] = "OnLeaveOnlineWorld"),
      (e[(e.OnlineDisableStateChange = 743)] = "OnlineDisableStateChange"),
      (e[(e.PlayerChallengeStateChange = 744)] = "PlayerChallengeStateChange"),
      (e[(e.OnTriggerVolumeExit = 745)] = "OnTriggerVolumeExit"),
      (e[(e.RefreshAcquireView = 746)] = "RefreshAcquireView"),
      (e[(e.OnResonanceMaterialChange = 747)] = "OnResonanceMaterialChange"),
      (e[(e.OnAddMaterialController = 748)] = "OnAddMaterialController"),
      (e[(e.OnRemoveMaterialController = 749)] = "OnRemoveMaterialController"),
      (e[(e.OnAddMaterialControllerGroup = 750)] =
        "OnAddMaterialControllerGroup"),
      (e[(e.OnRemoveMaterialControllerGroup = 751)] =
        "OnRemoveMaterialControllerGroup"),
      (e[(e.WeatherChange = 752)] = "WeatherChange"),
      (e[(e.OnManipulateSwitchToNewTarget = 753)] =
        "OnManipulateSwitchToNewTarget"),
      (e[(e.OnManipulateStartChanting = 754)] = "OnManipulateStartChanting"),
      (e[(e.OnManipulateCancelChanting = 755)] = "OnManipulateCancelChanting"),
      (e[(e.OnManipulateCompleteChanting = 756)] =
        "OnManipulateCompleteChanting"),
      (e[(e.HiddenManipulateUI = 757)] = "HiddenManipulateUI"),
      (e[(e.ManipulateStartLockCastTarget = 758)] =
        "ManipulateStartLockCastTarget"),
      (e[(e.ManipulateEndLockCastTarget = 759)] =
        "ManipulateEndLockCastTarget"),
      (e[(e.OnManipulatableSceneItemPosInFoundation = 760)] =
        "OnManipulatableSceneItemPosInFoundation"),
      (e[(e.AddSubCameraTag = 761)] = "AddSubCameraTag"),
      (e[(e.RemoveSubCameraTag = 762)] = "RemoveSubCameraTag"),
      (e[(e.AddExtraHoldingTags = 763)] = "AddExtraHoldingTags"),
      (e[(e.RemoveExtraHoldingTags = 764)] = "RemoveExtraHoldingTags"),
      (e[(e.HideJigsawBaseHint = 765)] = "HideJigsawBaseHint"),
      (e[(e.OnModifyJigsawItemPutIndex = 766)] = "OnModifyJigsawItemPutIndex"),
      (e[(e.OnManipulatableItemStateModified = 767)] =
        "OnManipulatableItemStateModified"),
      (e[(e.OnManipulatedItemPosReset = 768)] = "OnManipulatedItemPosReset"),
      (e[(e.SetCameraAimVisible = 769)] = "SetCameraAimVisible"),
      (e[(e.SetFollowShootAimVisible = 770)] = "SetFollowShootAimVisible"),
      (e[(e.ClickDisplayItem = 771)] = "ClickDisplayItem"),
      (e[(e.OnSelectItemAdd = 772)] = "OnSelectItemAdd"),
      (e[(e.DetectSuccess = 773)] = "DetectSuccess"),
      (e[(e.AdventureTaskStateChange = 774)] = "AdventureTaskStateChange"),
      (e[(e.ChapterRewardReceived = 775)] = "ChapterRewardReceived"),
      (e[(e.SilentRewardReceived = 776)] = "SilentRewardReceived"),
      (e[(e.AdventureHelpBtn = 777)] = "AdventureHelpBtn"),
      (e[(e.NewSoundAreaRefreshReward = 778)] = "NewSoundAreaRefreshReward"),
      (e[(e.DailyActivityTaskUpdate = 779)] = "DailyActivityTaskUpdate"),
      (e[(e.DailyActivityRefresh = 780)] = "DailyActivityRefresh"),
      (e[(e.DailyActivityValueChange = 781)] = "DailyActivityValueChange"),
      (e[(e.DailyActivityRewardTake = 782)] = "DailyActivityRewardTake"),
      (e[(e.RefreshActivityRewardPopUp = 783)] = "RefreshActivityRewardPopUp"),
      (e[(e.DailyActivityCountDownUpdate = 784)] =
        "DailyActivityCountDownUpdate"),
      (e[(e.DailyUpdateNotify = 785)] = "DailyUpdateNotify"),
      (e[(e.DailyActivityStateNotify = 786)] = "DailyActivityStateNotify"),
      (e[(e.DailyTaskAreaItemClick = 787)] = "DailyTaskAreaItemClick"),
      (e[(e.DailyTaskInfluenceItemClick = 788)] =
        "DailyTaskInfluenceItemClick"),
      (e[(e.DailyTaskUnlockAreaChange = 789)] = "DailyTaskUnlockAreaChange"),
      (e[(e.DailyTaskStateChange = 790)] = "DailyTaskStateChange"),
      (e[(e.DailyTaskChange = 791)] = "DailyTaskChange"),
      (e[(e.DailyTaskTendencyChange = 792)] = "DailyTaskTendencyChange"),
      (e[(e.OnAddCommonItem = 793)] = "OnAddCommonItem"),
      (e[(e.OnAddCommonItemList = 794)] = "OnAddCommonItemList"),
      (e[(e.OnAddCommonItemNotify = 795)] = "OnAddCommonItemNotify"),
      (e[(e.OnResponseCommonItem = 796)] = "OnResponseCommonItem"),
      (e[(e.OnResponseCommonItemFinished = 797)] =
        "OnResponseCommonItemFinished"),
      (e[(e.OnRemoveCommonItem = 798)] = "OnRemoveCommonItem"),
      (e[(e.OnCommonItemCountRefresh = 799)] = "OnCommonItemCountRefresh");
    (e[(e.OnCommonItemCountAnyChange = 800)] = "OnCommonItemCountAnyChange"),
      (e[(e.OnAddWeaponItem = 801)] = "OnAddWeaponItem"),
      (e[(e.OnAddWeaponItemList = 802)] = "OnAddWeaponItemList"),
      (e[(e.OnResponseWeaponItem = 803)] = "OnResponseWeaponItem"),
      (e[(e.OnResponseWeaponAll = 804)] = "OnResponseWeaponAll"),
      (e[(e.OnRemoveWeaponItem = 805)] = "OnRemoveWeaponItem"),
      (e[(e.OnWeaponFunctionValueRefresh = 806)] =
        "OnWeaponFunctionValueRefresh"),
      (e[(e.OnAddPhantomItem = 807)] = "OnAddPhantomItem"),
      (e[(e.OnAddPhantomItemList = 808)] = "OnAddPhantomItemList"),
      (e[(e.OnResponsePhantomItem = 809)] = "OnResponsePhantomItem"),
      (e[(e.OnEquipPhantomItem = 810)] = "OnEquipPhantomItem"),
      (e[(e.OnRemovePhantomItem = 811)] = "OnRemovePhantomItem"),
      (e[(e.OnPhantomFunctionValueRefresh = 812)] =
        "OnPhantomFunctionValueRefresh"),
      (e[(e.OnAddFavorItem = 813)] = "OnAddFavorItem"),
      (e[(e.NotifyInvalidItem = 814)] = "NotifyInvalidItem"),
      (e[(e.EnterPresentationInitRange = 815)] = "EnterPresentationInitRange"),
      (e[(e.EnterLogicRange = 816)] = "EnterLogicRange"),
      (e[(e.LeaveLogicRange = 817)] = "LeaveLogicRange"),
      (e[(e.PlayerSenseTargetEnter = 818)] = "PlayerSenseTargetEnter"),
      (e[(e.PlayerSenseTargetLeave = 819)] = "PlayerSenseTargetLeave"),
      (e[(e.OnAiSenseEntityEnter = 820)] = "OnAiSenseEntityEnter"),
      (e[(e.OnAiSenseEntityLeave = 821)] = "OnAiSenseEntityLeave"),
      (e[(e.OnInteractStateChange = 822)] = "OnInteractStateChange"),
      (e[(e.OnGuideRangeEnter = 823)] = "OnGuideRangeEnter"),
      (e[(e.SwitchCookType = 824)] = "SwitchCookType"),
      (e[(e.UpdateFormula = 825)] = "UpdateFormula"),
      (e[(e.UpdateCookerInfo = 826)] = "UpdateCookerInfo"),
      (e[(e.UpgradeCookerLevel = 827)] = "UpgradeCookerLevel"),
      (e[(e.GetCookData = 828)] = "GetCookData"),
      (e[(e.OpenProcessedStudy = 829)] = "OpenProcessedStudy"),
      (e[(e.CloseProcessedStudy = 830)] = "CloseProcessedStudy"),
      (e[(e.OpenCook = 831)] = "OpenCook"),
      (e[(e.OpenCookLevel = 832)] = "OpenCookLevel"),
      (e[(e.OpenCookRole = 833)] = "OpenCookRole"),
      (e[(e.CloseCookRole = 834)] = "CloseCookRole"),
      (e[(e.CookSuccess = 835)] = "CookSuccess"),
      (e[(e.CookFail = 836)] = "CookFail"),
      (e[(e.MachiningSuccess = 837)] = "MachiningSuccess"),
      (e[(e.MachiningStudyFail = 838)] = "MachiningStudyFail"),
      (e[(e.FixSuccess = 839)] = "FixSuccess"),
      (e[(e.OpenSelected = 840)] = "OpenSelected"),
      (e[(e.CloseSelected = 841)] = "CloseSelected"),
      (e[(e.OnAddCommonEffect = 842)] = "OnAddCommonEffect"),
      (e[(e.RefreshRewardPopUp = 843)] = "RefreshRewardPopUp"),
      (e[(e.ReceiveMonthCardDataEvent = 844)] = "ReceiveMonthCardDataEvent"),
      (e[(e.OnClickSingleTimeTowerStageBtn = 845)] =
        "OnClickSingleTimeTowerStageBtn"),
      (e[(e.OnClickSingleTimeTowerTeamBtn = 846)] =
        "OnClickSingleTimeTowerTeamBtn"),
      (e[(e.OnClickSingleTimeTowerTeamRoleBtn = 847)] =
        "OnClickSingleTimeTowerTeamRoleBtn"),
      (e[(e.OnClickSingleTimeTowerStageDetailBtn = 848)] =
        "OnClickSingleTimeTowerStageDetailBtn"),
      (e[(e.OnClickSingleTimeTowerMonsterBtn = 849)] =
        "OnClickSingleTimeTowerMonsterBtn"),
      (e[(e.OnClickSingleTimeTowerDetailSwitchBtn = 850)] =
        "OnClickSingleTimeTowerDetailSwitchBtn"),
      (e[(e.OnInstResultNotify = 851)] = "OnInstResultNotify"),
      (e[(e.OnTowerChallengeChangeTeamNotify = 852)] =
        "OnTowerChallengeChangeTeamNotify"),
      (e[(e.OnTowerRewardReceived = 853)] = "OnTowerRewardReceived"),
      (e[(e.RedDotTowerReward = 854)] = "RedDotTowerReward"),
      (e[(e.RedDotTowerRewardByDifficulties = 855)] =
        "RedDotTowerRewardByDifficulties"),
      (e[(e.OnTowerRefresh = 856)] = "OnTowerRefresh"),
      (e[(e.OnTowerRecordUpdate = 857)] = "OnTowerRecordUpdate"),
      (e[(e.OnShowTowerGuideButton = 858)] = "OnShowTowerGuideButton"),
      (e[(e.OnClickCycleTowerAreaBtn = 859)] = "OnClickCycleTowerAreaBtn"),
      (e[(e.OnResetCycleTowerArea = 860)] = "OnResetCycleTowerArea"),
      (e[(e.OnClickCycleTowerRoleBtn = 861)] = "OnClickCycleTowerRoleBtn"),
      (e[(e.OnClickCycleTowerDetailSwitchBtn = 862)] =
        "OnClickCycleTowerDetailSwitchBtn"),
      (e[(e.OnCycleTowerUpdateSeason = 863)] = "OnCycleTowerUpdateSeason"),
      (e[(e.OnCycleTowerUpdateSeasonNotify = 864)] =
        "OnCycleTowerUpdateSeasonNotify"),
      (e[(e.OnCycleTowerScoreChange = 865)] = "OnCycleTowerScoreChange"),
      (e[(e.OnTowerGuideClose = 866)] = "OnTowerGuideClose"),
      (e[(e.OnTowerRefreshStars = 867)] = "OnTowerRefreshStars"),
      (e[(e.OnReceiveAdviceData = 868)] = "OnReceiveAdviceData"),
      (e[(e.OnCreateAdviceSuccess = 869)] = "OnCreateAdviceSuccess"),
      (e[(e.OnModifyAdviceSuccess = 870)] = "OnModifyAdviceSuccess"),
      (e[(e.OnDeleteAdviceSuccess = 871)] = "OnDeleteAdviceSuccess"),
      (e[(e.OnClickAdviceExpression = 872)] = "OnClickAdviceExpression"),
      (e[(e.OnClickAdviceWord = 873)] = "OnClickAdviceWord"),
      (e[(e.OnChangeAdviceWord = 874)] = "OnChangeAdviceWord"),
      (e[(e.OnClickAdviceSort = 875)] = "OnClickAdviceSort"),
      (e[(e.OnClickAdviceSortWord = 876)] = "OnClickAdviceSortWord"),
      (e[(e.OnClickAdviceMotion = 877)] = "OnClickAdviceMotion"),
      (e[(e.OnChangeAdviceRole = 878)] = "OnChangeAdviceRole"),
      (e[(e.OnClickAdviceSelectItem = 879)] = "OnClickAdviceSelectItem"),
      (e[(e.OnSelectAdviceWord = 880)] = "OnSelectAdviceWord"),
      (e[(e.OnSelectAdviceExpression = 881)] = "OnSelectAdviceExpression"),
      (e[(e.OnAdviceEntityNotify = 882)] = "OnAdviceEntityNotify"),
      (e[(e.OnAdviceVoteNotify = 883)] = "OnAdviceVoteNotify"),
      (e[(e.RefreshAdviceInfoView = 884)] = "RefreshAdviceInfoView"),
      (e[(e.SneakStart = 885)] = "SneakStart"),
      (e[(e.SneakEnd = 886)] = "SneakEnd"),
      (e[(e.AddAlterMark = 887)] = "AddAlterMark"),
      (e[(e.RemoveAlterMark = 888)] = "RemoveAlterMark"),
      (e[(e.OnSneakFoundChange = 889)] = "OnSneakFoundChange"),
      (e[(e.OnChildQuestNodeFinish = 890)] = "OnChildQuestNodeFinish"),
      (e[(e.AddStalkAlertMark = 891)] = "AddStalkAlertMark"),
      (e[(e.RemoveStalkAlertMark = 892)] = "RemoveStalkAlertMark"),
      (e[(e.OnStalkAlert = 893)] = "OnStalkAlert"),
      (e[(e.OnStalkAlertLifted = 894)] = "OnStalkAlertLifted"),
      (e[(e.OnStalkFound = 895)] = "OnStalkFound"),
      (e[(e.OnStalkFailed = 896)] = "OnStalkFailed"),
      (e[(e.AddEavesdropMark = 897)] = "AddEavesdropMark"),
      (e[(e.RemoveEavesdropMark = 898)] = "RemoveEavesdropMark"),
      (e[(e.OnEavesdropFound = 899)] = "OnEavesdropFound"),
      (e[(e.OnAddFullScreenEffect = 900)] = "OnAddFullScreenEffect"),
      (e[(e.OnRemoveFullScreenEffect = 901)] = "OnRemoveFullScreenEffect"),
      (e[(e.OnClearFullScreenEffect = 902)] = "OnClearFullScreenEffect"),
      (e[(e.OnChangeFullScreenNiagaraFloatParameter = 903)] =
        "OnChangeFullScreenNiagaraFloatParameter"),
      (e[(e.OnSceneItemBuffConsumed = 904)] = "OnSceneItemBuffConsumed"),
      (e[(e.OnSceneItemBuffRemoved = 905)] = "OnSceneItemBuffRemoved"),
      (e[(e.OnSceneItemBuffTimeout = 906)] = "OnSceneItemBuffTimeout"),
      (e[(e.OnSceneItemBuffTargetRemoved = 907)] =
        "OnSceneItemBuffTargetRemoved"),
      (e[(e.OnSceneItemBuffConsumerPerformanceComplete = 908)] =
        "OnSceneItemBuffConsumerPerformanceComplete"),
      (e[(e.OnExecuteServerGm = 909)] = "OnExecuteServerGm"),
      (e[(e.ActiveBattleView = 910)] = "ActiveBattleView"),
      (e[(e.DisActiveBattleView = 911)] = "DisActiveBattleView"),
      (e[(e.BattleUiCurRoleDataChanged = 912)] = "BattleUiCurRoleDataChanged"),
      (e[(e.BattleUiCurRoleDataChangedNextTick = 913)] =
        "BattleUiCurRoleDataChangedNextTick"),
      (e[(e.BattleUiAllRoleDataChanged = 914)] = "BattleUiAllRoleDataChanged"),
      (e[(e.BattleUiRemoveRoleData = 915)] = "BattleUiRemoveRoleData"),
      (e[(e.BattleUiElementEnergyChanged = 916)] =
        "BattleUiElementEnergyChanged"),
      (e[(e.BattleUiElementHideTagChanged = 917)] =
        "BattleUiElementHideTagChanged"),
      (e[(e.BattleUiDeadTagChanged = 918)] = "BattleUiDeadTagChanged"),
      (e[(e.BattleUiQteEnableTagChanged = 919)] =
        "BattleUiQteEnableTagChanged"),
      (e[(e.BattleUiQteCdTagChanged = 920)] = "BattleUiQteCdTagChanged"),
      (e[(e.BattleUiUseQteTagChanged = 921)] = "BattleUiUseQteTagChanged"),
      (e[(e.BattleUiConcertoEnableTagChanged = 922)] =
        "BattleUiConcertoEnableTagChanged"),
      (e[(e.BattleUiPoisonChanged = 923)] = "BattleUiPoisonChanged"),
      (e[(e.BattleUiHealthChanged = 924)] = "BattleUiHealthChanged"),
      (e[(e.BattleUiShieldChanged = 925)] = "BattleUiShieldChanged"),
      (e[(e.BattleUiLevelChanged = 926)] = "BattleUiLevelChanged"),
      (e[(e.BattleUiFloatTipUpdate = 927)] = "BattleUiFloatTipUpdate"),
      (e[(e.BattleUiPlayAudio = 928)] = "BattleUiPlayAudio"),
      (e[(e.BattleUiExploreModeChanged = 929)] = "BattleUiExploreModeChanged"),
      (e[(e.BattleUiMergeHeadStateVisibleChanged = 930)] =
        "BattleUiMergeHeadStateVisibleChanged"),
      (e[(e.BattleUiMergeHeadStateHealthChanged = 931)] =
        "BattleUiMergeHeadStateHealthChanged"),
      (e[(e.BattleUiEnvironmentKeyChanged = 932)] =
        "BattleUiEnvironmentKeyChanged"),
      (e[(e.BattleUiPressCombineButtonChanged = 933)] =
        "BattleUiPressCombineButtonChanged"),
      (e[(e.BattleUiToggleSilentAreaInfoView = 934)] =
        "BattleUiToggleSilentAreaInfoView"),
      (e[(e.BattleInputEnableChanged = 935)] = "BattleInputEnableChanged"),
      (e[(e.BattleInputVisibleChanged = 936)] = "BattleInputVisibleChanged"),
      (e[(e.BattleUiFollowerAimStateChanged = 937)] =
        "BattleUiFollowerAimStateChanged"),
      (e[(e.BattleUiChatScrollViewVisibleChanged = 938)] =
        "BattleUiChatScrollViewVisibleChanged"),
      (e[(e.BattleUiToggleTowerDefenseInfoView = 939)] =
        "BattleUiToggleTowerDefenseInfoView"),
      (e[(e.BattleSettlementStateChanged = 940)] =
        "BattleSettlementStateChanged"),
      (e[(e.BattleScoreChanged = 941)] = "BattleScoreChanged"),
      (e[(e.OnRefreshFormationCooldownExternalInBattleView = 942)] =
        "OnRefreshFormationCooldownExternalInBattleView"),
      (e[(e.RefreshInfluencePanel = 943)] = "RefreshInfluencePanel"),
      (e[(e.ReceiveReputationReward = 944)] = "ReceiveReputationReward"),
      (e[(e.SearchInfluence = 945)] = "SearchInfluence"),
      (e[(e.RedDotInfluence = 946)] = "RedDotInfluence"),
      (e[(e.BehaviorTreeStartActionSession = 947)] =
        "BehaviorTreeStartActionSession"),
      (e[(e.UiPlayCloseAudio = 948)] = "UiPlayCloseAudio"),
      (e[(e.OnSceneItemLockPropChange = 949)] = "OnSceneItemLockPropChange"),
      (e[(e.OnSpecialItemUpdate = 950)] = "OnSpecialItemUpdate"),
      (e[(e.EquipAndSwitchSpecialItem = 951)] = "EquipAndSwitchSpecialItem"),
      (e[(e.UnEquipSpecialItem = 952)] = "UnEquipSpecialItem"),
      (e[(e.ShowPlayerPosition = 953)] = "ShowPlayerPosition"),
      (e[(e.BattlePassHadEnterUpdate = 954)] = "BattlePassHadEnterUpdate"),
      (e[(e.GetBattlePassRewardEvent = 955)] = "GetBattlePassRewardEvent"),
      (e[(e.ReceiveBattlePassDataEvent = 956)] = "ReceiveBattlePassDataEvent"),
      (e[(e.BattlePassFirstUnlockAnime = 957)] = "BattlePassFirstUnlockAnime"),
      (e[(e.ReceiveBattlePassTaskEvent = 958)] = "ReceiveBattlePassTaskEvent"),
      (e[(e.OnChoseLevelItemEvent = 959)] = "OnChoseLevelItemEvent"),
      (e[(e.OnClickLevelItemEvent = 960)] = "OnClickLevelItemEvent"),
      (e[(e.UpdateBattlePassTaskEvent = 961)] = "UpdateBattlePassTaskEvent"),
      (e[(e.OnBattlePassLevelUpEvent = 962)] = "OnBattlePassLevelUpEvent"),
      (e[(e.OnBattlePassExpireEvent = 963)] = "OnBattlePassExpireEvent"),
      (e[(e.BattlePassMainViewHide = 964)] = "BattlePassMainViewHide"),
      (e[(e.SwitchViewType = 965)] = "SwitchViewType"),
      (e[(e.SwitchComposeType = 966)] = "SwitchComposeType"),
      (e[(e.GetComposeData = 967)] = "GetComposeData"),
      (e[(e.UpgradeComposeLevel = 968)] = "UpgradeComposeLevel"),
      (e[(e.OpenComposeLevel = 969)] = "OpenComposeLevel"),
      (e[(e.OpenCompose = 970)] = "OpenCompose"),
      (e[(e.ComposeSuccess = 971)] = "ComposeSuccess"),
      (e[(e.ComposeFail = 972)] = "ComposeFail"),
      (e[(e.OpenHelpRole = 973)] = "OpenHelpRole"),
      (e[(e.CloseHelpRole = 974)] = "CloseHelpRole"),
      (e[(e.UpdateComposeFormula = 975)] = "UpdateComposeFormula"),
      (e[(e.UpdateComposeInfo = 976)] = "UpdateComposeInfo"),
      (e[(e.UpdateForgingFormula = 977)] = "UpdateForgingFormula"),
      (e[(e.OpenForging = 978)] = "OpenForging"),
      (e[(e.GetForgingData = 979)] = "GetForgingData"),
      (e[(e.ForgingSuccess = 980)] = "ForgingSuccess"),
      (e[(e.ForgingFail = 981)] = "ForgingFail"),
      (e[(e.ChangePlayerInfoId = 982)] = "ChangePlayerInfoId"),
      (e[(e.OnShowGridAnimation = 983)] = "OnShowGridAnimation"),
      (e[(e.OnActivateUiCameraAnimationHandle = 984)] =
        "OnActivateUiCameraAnimationHandle"),
      (e[(e.OnActivateUiCameraAnimationHandleFail = 985)] =
        "OnActivateUiCameraAnimationHandleFail"),
      (e[(e.OnUiBlendInCameraSequenceFinished = 986)] =
        "OnUiBlendInCameraSequenceFinished"),
      (e[(e.RoleHandBookActive = 987)] = "RoleHandBookActive"),
      (e[(e.OnSequenceCameraStatus = 988)] = "OnSequenceCameraStatus"),
      (e[(e.LocalStorageInitPlayerId = 989)] = "LocalStorageInitPlayerId"),
      (e[(e.DynamicInteractServerResponse = 990)] =
        "DynamicInteractServerResponse"),
      (e[(e.UpdateCameraInfo = 991)] = "UpdateCameraInfo"),
      (e[(e.PlayCameraLevelSequence = 992)] = "PlayCameraLevelSequence"),
      (e[(e.CameraModeChanged = 993)] = "CameraModeChanged"),
      (e[(e.CameraViewTargetChanged = 994)] = "CameraViewTargetChanged"),
      (e[(e.FixedCameraRestored = 995)] = "FixedCameraRestored"),
      (e[(e.CameraCharacterChanged = 996)] = "CameraCharacterChanged"),
      (e[(e.OpenTreasureBox = 997)] = "OpenTreasureBox"),
      (e[(e.OnHandBookDataInit = 998)] = "OnHandBookDataInit"),
      (e[(e.OnHandBookDataUpdate = 999)] = "OnHandBookDataUpdate"),
      (e[(e.OnHandBookRedDotUpdate = 1e3)] = "OnHandBookRedDotUpdate"),
      (e[(e.OnHandBookRead = 1001)] = "OnHandBookRead"),
      (e[(e.OnPhantomReadRedDotUpdate = 1002)] = "OnPhantomReadRedDotUpdate"),
      (e[(e.OnItemReadRedDotUpdate = 1003)] = "OnItemReadRedDotUpdate"),
      (e[(e.OnPhotoSelect = 1004)] = "OnPhotoSelect"),
      (e[(e.OnGeographyPhotoSelect = 1005)] = "OnGeographyPhotoSelect"),
      (e[(e.OnHandBookPlotNodeRefresh = 1006)] = "OnHandBookPlotNodeRefresh"),
      (e[(e.RemoveCreatureDataComponentCache = 1007)] =
        "RemoveCreatureDataComponentCache"),
      (e[(e.TravelClearView = 1008)] = "TravelClearView"),
      (e[(e.OnPressOrReleaseBehaviorButton = 1009)] =
        "OnPressOrReleaseBehaviorButton"),
      (e[(e.SetImageQuality = 1010)] = "SetImageQuality"),
      (e[(e.SetDisplayMode = 1011)] = "SetDisplayMode"),
      (e[(e.SetResolution = 1012)] = "SetResolution"),
      (e[(e.SetNiagaraQuality = 1013)] = "SetNiagaraQuality"),
      (e[(e.AfterGameQualitySettingsManagerInitialize = 1014)] =
        "AfterGameQualitySettingsManagerInitialize"),
      (e[(e.SetGmIsOpen = 1015)] = "SetGmIsOpen"),
      (e[(e.AddToTickList = 1016)] = "AddToTickList"),
      (e[(e.HandleNextAction = 1017)] = "HandleNextAction"),
      (e[(e.HandleActionFailure = 1018)] = "HandleActionFailure"),
      (e[(e.AddGuaranteeAction = 1019)] = "AddGuaranteeAction"),
      (e[(e.RemGuaranteeAction = 1020)] = "RemGuaranteeAction"),
      (e[(e.ShareGroupCd = 1021)] = "ShareGroupCd"),
      (e[(e.AddShareGroupLimitCount = 1022)] = "AddShareGroupLimitCount"),
      (e[(e.OnInteractPlotStart = 1023)] = "OnInteractPlotStart"),
      (e[(e.OnInteractPlotEnd = 1024)] = "OnInteractPlotEnd"),
      (e[(e.OnAchievementDataNotify = 1025)] = "OnAchievementDataNotify"),
      (e[(e.OnAchievementDataWithIdNotify = 1026)] =
        "OnAchievementDataWithIdNotify"),
      (e[(e.OnAchievementGroupDataNotify = 1027)] =
        "OnAchievementGroupDataNotify"),
      (e[(e.OnGetAchievementBaseData = 1028)] = "OnGetAchievementBaseData"),
      (e[(e.OnGetAchievementSearchTextChange = 1029)] =
        "OnGetAchievementSearchTextChange"),
      (e[(e.OnAchievementGroupChange = 1030)] = "OnAchievementGroupChange"),
      (e[(e.RefreshAchievementRedPoint = 1031)] = "RefreshAchievementRedPoint"),
      (e[(e.OnActivityUpdate = 1032)] = "OnActivityUpdate"),
      (e[(e.OnSelectActivity = 1033)] = "OnSelectActivity"),
      (e[(e.OnSelectActivityAndSubViewReady = 1034)] =
        "OnSelectActivityAndSubViewReady"),
      (e[(e.RefreshActivityTab = 1035)] = "RefreshActivityTab"),
      (e[(e.OnReceiveActivityData = 1036)] = "OnReceiveActivityData"),
      (e[(e.SetActivityViewState = 1037)] = "SetActivityViewState"),
      (e[(e.SetActivityViewCurrency = 1038)] = "SetActivityViewCurrency"),
      (e[(e.OnClickActivityRunChallenge = 1039)] =
        "OnClickActivityRunChallenge"),
      (e[(e.OnSelectActivityRunChallengeItem = 1040)] =
        "OnSelectActivityRunChallengeItem"),
      (e[(e.RefreshCommonActivityRedDot = 1041)] =
        "RefreshCommonActivityRedDot"),
      (e[(e.RefreshRunActivityRedDot = 1042)] = "RefreshRunActivityRedDot"),
      (e[(e.OnGetRunActivityReward = 1043)] = "OnGetRunActivityReward"),
      (e[(e.ActivityCrossDayRefresh = 1044)] = "ActivityCrossDayRefresh"),
      (e[(e.OnActivityClose = 1045)] = "OnActivityClose"),
      (e[(e.OnActivityOpen = 1046)] = "OnActivityOpen"),
      (e[(e.OnActivitySequenceEmitEvent = 1047)] =
        "OnActivitySequenceEmitEvent"),
      (e[(e.RefreshCommonActivityRewardPopUpView = 1048)] =
        "RefreshCommonActivityRewardPopUpView"),
      (e[(e.ActivityViewChange = 1049)] = "ActivityViewChange"),
      (e[(e.ActivityViewRefreshCurrent = 1050)] = "ActivityViewRefreshCurrent"),
      (e[(e.LongShanUpdate = 1051)] = "LongShanUpdate"),
      (e[(e.OnPhantomCollectUpdate = 1052)] = "OnPhantomCollectUpdate"),
      (e[(e.TurntableStartRun = 1053)] = "TurntableStartRun"),
      (e[(e.TrackMoonHandbookUpdate = 1054)] = "TrackMoonHandbookUpdate"),
      (e[(e.MoonChasingRefreshBuildingRedDot = 1055)] =
        "MoonChasingRefreshBuildingRedDot"),
      (e[(e.MoonChasingRefreshRewardRedDot = 1056)] =
        "MoonChasingRefreshRewardRedDot"),
      (e[(e.MoonChasingRefreshDelegationRedDot = 1057)] =
        "MoonChasingRefreshDelegationRedDot"),
      (e[(e.MoonChasingRefreshRoleRedDot = 1058)] =
        "MoonChasingRefreshRoleRedDot"),
      (e[(e.MoonChasingRefreshQuestRedDot = 1059)] =
        "MoonChasingRefreshQuestRedDot"),
      (e[(e.MoonChasingOnOpenInteractive = 1060)] =
        "MoonChasingOnOpenInteractive"),
      (e[(e.GmAutoModeChange = 1061)] = "GmAutoModeChange"),
      (e[(e.OnAddNotAllowFightInputViewName = 1062)] =
        "OnAddNotAllowFightInputViewName"),
      (e[(e.OnRemoveNotAllowFightInputViewName = 1063)] =
        "OnRemoveNotAllowFightInputViewName"),
      (e[(e.OnClearNotAllowFightInputViewName = 1064)] =
        "OnClearNotAllowFightInputViewName"),
      (e[(e.OnSelectedEditPanelItem = 1065)] = "OnSelectedEditPanelItem"),
      (e[(e.UiRoleSequenceEndKeyFrame = 1066)] = "UiRoleSequenceEndKeyFrame"),
      (e[(e.DropItemStarted = 1067)] = "DropItemStarted"),
      (e[(e.OnRoleChangeEnd = 1068)] = "OnRoleChangeEnd"),
      (e[(e.ComboTeachingPress = 1069)] = "ComboTeachingPress"),
      (e[(e.ComboTeachingRelease = 1070)] = "ComboTeachingRelease"),
      (e[(e.ComboTeachingHold = 1071)] = "ComboTeachingHold"),
      (e[(e.ComboTeachingNodeEnd = 1072)] = "ComboTeachingNodeEnd"),
      (e[(e.ComboTeachingViewOpen = 1073)] = "ComboTeachingViewOpen"),
      (e[(e.SkillAcceptChanged = 1074)] = "SkillAcceptChanged"),
      (e[(e.ComboTeachingFinish = 1075)] = "ComboTeachingFinish"),
      (e[(e.ComboTeachingCloseGuide = 1076)] = "ComboTeachingCloseGuide"),
      (e[(e.RoleIntroductionViewHide = 1077)] = "RoleIntroductionViewHide"),
      (e[(e.RequestClearMeshRotationBuffer = 1078)] =
        "RequestClearMeshRotationBuffer"),
      (e[(e.NavigationViewCreate = 1079)] = "NavigationViewCreate"),
      (e[(e.NavigationViewDestroy = 1080)] = "NavigationViewDestroy"),
      (e[(e.ResetNavigationListener = 1081)] = "ResetNavigationListener"),
      (e[(e.NavigationTriggerMapForward = 1082)] =
        "NavigationTriggerMapForward"),
      (e[(e.NavigationTriggerMapRight = 1083)] = "NavigationTriggerMapRight"),
      (e[(e.NavigationTriggerMapZoom = 1084)] = "NavigationTriggerMapZoom"),
      (e[(e.NavigationTriggerRoleLookUp = 1085)] =
        "NavigationTriggerRoleLookUp"),
      (e[(e.NavigationTriggerRoleTurn = 1086)] = "NavigationTriggerRoleTurn"),
      (e[(e.NavigationTriggerRoleZoom = 1087)] = "NavigationTriggerRoleZoom"),
      (e[(e.NavigationTriggerRoleReset = 1088)] = "NavigationTriggerRoleReset"),
      (e[(e.GamepadMoveOverScreen = 1089)] = "GamepadMoveOverScreen"),
      (e[(e.NavigationTriggerPlotForward = 1090)] =
        "NavigationTriggerPlotForward"),
      (e[(e.NavigationTriggerPlotRight = 1091)] = "NavigationTriggerPlotRight"),
      (e[(e.NavigationTriggerPlotZoom = 1092)] = "NavigationTriggerPlotZoom"),
      (e[(e.NavigationRefreshPlotNextPage = 1093)] =
        "NavigationRefreshPlotNextPage"),
      (e[(e.FunctionGridSelected = 1094)] = "FunctionGridSelected"),
      (e[(e.OnPersonalCardRead = 1095)] = "OnPersonalCardRead"),
      (e[(e.OnPersonalCardRefreshRedDot = 1096)] =
        "OnPersonalCardRefreshRedDot"),
      (e[(e.OnHeadIconChange = 1097)] = "OnHeadIconChange"),
      (e[(e.OnSignChange = 1098)] = "OnSignChange"),
      (e[(e.OnNameChange = 1099)] = "OnNameChange"),
      (e[(e.OnModifyNameStateChange = 1100)] = "OnModifyNameStateChange"),
      (e[(e.OnBirthChange = 1101)] = "OnBirthChange"),
      (e[(e.OnBirthDisplayChange = 1102)] = "OnBirthDisplayChange"),
      (e[(e.OnCardChange = 1103)] = "OnCardChange"),
      (e[(e.ResetRoleFlag = 1104)] = "ResetRoleFlag"),
      (e[(e.OnRoleShowListChange = 1105)] = "OnRoleShowListChange"),
      (e[(e.OnRoleElementChange = 1106)] = "OnRoleElementChange"),
      (e[(e.ShowRoleElementChangePreviewEffect = 1107)] =
        "ShowRoleElementChangePreviewEffect"),
      (e[(e.OnChangedActionKeys = 1108)] = "OnChangedActionKeys"),
      (e[(e.OnChangedAxisKeys = 1109)] = "OnChangedAxisKeys"),
      (e[(e.SelectRoleTab = 1110)] = "SelectRoleTab"),
      (e[(e.SelectRoleTabOutside = 1111)] = "SelectRoleTabOutside"),
      (e[(e.OnFunctionViewShow = 1112)] = "OnFunctionViewShow"),
      (e[(e.UpdatePanelQteWorldTimeDilation = 1113)] =
        "UpdatePanelQteWorldTimeDilation"),
      (e[(e.PanelQteStart = 1114)] = "PanelQteStart"),
      (e[(e.PanelQteEnd = 1115)] = "PanelQteEnd"),
      (e[(e.StartHeartBeat = 1116)] = "StartHeartBeat"),
      (e[(e.StopHeartBeat = 1117)] = "StopHeartBeat"),
      (e[(e.CreateEffectHandle = 1118)] = "CreateEffectHandle"),
      (e[(e.RemoveEffectHandle = 1119)] = "RemoveEffectHandle"),
      (e[(e.LoadEffect = 1120)] = "LoadEffect"),
      (e[(e.BeforePlayEffect = 1121)] = "BeforePlayEffect"),
      (e[(e.AfterPlayEffect = 1122)] = "AfterPlayEffect"),
      (e[(e.FinishEffect = 1123)] = "FinishEffect"),
      (e[(e.TestQuestAutoPilotFinish = 1124)] = "TestQuestAutoPilotFinish"),
      (e[(e.TestQuestFunctionFinish = 1125)] = "TestQuestFunctionFinish"),
      (e[(e.OnRefreshRewardViewItemList = 1126)] =
        "OnRefreshRewardViewItemList"),
      (e[(e.OnRefreshRewardProgressBar = 1127)] = "OnRefreshRewardProgressBar"),
      (e[(e.OnRefreshRewardButton = 1128)] = "OnRefreshRewardButton"),
      (e[(e.OnItemRewardNotify = 1129)] = "OnItemRewardNotify"),
      (e[(e.OnShowRewardView = 1130)] = "OnShowRewardView"),
      (e[(e.OnCloseRewardView = 1131)] = "OnCloseRewardView"),
      (e[(e.OnPlotWaitViewDone = 1132)] = "OnPlotWaitViewDone"),
      (e[(e.OnPlayCameraAnimationStart = 1133)] = "OnPlayCameraAnimationStart"),
      (e[(e.OnPlayCameraAnimationFinish = 1134)] =
        "OnPlayCameraAnimationFinish"),
      (e[(e.CommunicateFinished = 1135)] = "CommunicateFinished"),
      (e[(e.CommunicateAgain = 1136)] = "CommunicateAgain"),
      (e[(e.ChallengeAgain = 1137)] = "ChallengeAgain"),
      (e[(e.OnPhotographSetUpViewVisibleChanged = 1138)] =
        "OnPhotographSetUpViewVisibleChanged"),
      (e[(e.OnEntityCameraOneSituationChanged = 1139)] =
        "OnEntityCameraOneSituationChanged"),
      (e[(e.OnEntityCameraSearchGreat = 1140)] = "OnEntityCameraSearchGreat"),
      (e[(e.OnEntityCameraFinished = 1141)] = "OnEntityCameraFinished"),
      (e[(e.OnScreenShotDone = 1142)] = "OnScreenShotDone"),
      (e[(e.OnSubmitItemSuccess = 1143)] = "OnSubmitItemSuccess"),
      (e[(e.OnSubmitItemFail = 1144)] = "OnSubmitItemFail"),
      (e[(e.OnSubmitItemLevelUp = 1145)] = "OnSubmitItemLevelUp"),
      (e[(e.OnSubmitItemLevelMax = 1146)] = "OnSubmitItemLevelMax"),
      (e[(e.OnCameraSequenceSetUiVisible = 1147)] =
        "OnCameraSequenceSetUiVisible"),
      (e[(e.OnUiScreenRootVisibleChange = 1148)] =
        "OnUiScreenRootVisibleChange"),
      (e[(e.OnTurntableControllerBusyStateChange = 1149)] =
        "OnTurntableControllerBusyStateChange"),
      (e[(e.OnAnyProgressControlEnableStateChange = 1150)] =
        "OnAnyProgressControlEnableStateChange"),
      (e[(e.OnDropItemSuccess = 1151)] = "OnDropItemSuccess"),
      (e[(e.OnInteractDropItemSuccess = 1152)] = "OnInteractDropItemSuccess"),
      (e[(e.OnExecuteUiCameraSequenceEvent = 1153)] =
        "OnExecuteUiCameraSequenceEvent"),
      (e[(e.OnInputAnyKey = 1154)] = "OnInputAnyKey"),
      (e[(e.OnAddDynamicOption = 1155)] = "OnAddDynamicOption"),
      (e[(e.OnRemoveDynamicOption = 1156)] = "OnRemoveDynamicOption"),
      (e[(e.OnFilterDataUpdate = 1157)] = "OnFilterDataUpdate"),
      (e[(e.OnPlayNpcPerformSequence = 1158)] = "OnPlayNpcPerformSequence"),
      (e[(e.OnNpcPerformSequenceFinished = 1159)] =
        "OnNpcPerformSequenceFinished"),
      (e[(e.OnAntiqueShopUpgradeSequenceFinished = 1160)] =
        "OnAntiqueShopUpgradeSequenceFinished"),
      (e[(e.OnAntiqueShopLevelMaxSequenceFinished = 1161)] =
        "OnAntiqueShopLevelMaxSequenceFinished"),
      (e[(e.OnAntiqueShopUpgradeSequencePlayFail = 1162)] =
        "OnAntiqueShopUpgradeSequencePlayFail"),
      (e[(e.OnCookSuccessSequenceFinished = 1163)] =
        "OnCookSuccessSequenceFinished"),
      (e[(e.OnBeginPlayCookSuccessDisplay = 1164)] =
        "OnBeginPlayCookSuccessDisplay"),
      (e[(e.OnPlayCookSuccessDisplayFinished = 1165)] =
        "OnPlayCookSuccessDisplayFinished"),
      (e[(e.OnBeginPlayCookFailDisplay = 1166)] = "OnBeginPlayCookFailDisplay"),
      (e[(e.OnPlayCookFailDisplayFinished = 1167)] =
        "OnPlayCookFailDisplayFinished"),
      (e[(e.OnBeginPlayCompositeWorkingDisplay = 1168)] =
        "OnBeginPlayCompositeWorkingDisplay"),
      (e[(e.OnPlayCompositeWorkingDisplayFinished = 1169)] =
        "OnPlayCompositeWorkingDisplayFinished"),
      (e[(e.OnBeginPlayForgingWorkingDisplay = 1170)] =
        "OnBeginPlayForgingWorkingDisplay"),
      (e[(e.OnPlayForgingWorkingDisplayFinished = 1171)] =
        "OnPlayForgingWorkingDisplayFinished"),
      (e[(e.OnCharFootOnTheGround = 1172)] = "OnCharFootOnTheGround"),
      (e[(e.BattleViewActiveSequenceFinish = 1173)] =
        "BattleViewActiveSequenceFinish"),
      (e[(e.SmartObjectAiAlterNotify = 1174)] = "SmartObjectAiAlterNotify"),
      (e[(e.OnSetActorHidden = 1175)] = "OnSetActorHidden"),
      (e[(e.OnCheckGamePing = 1176)] = "OnCheckGamePing"),
      (e[(e.OnRemoveItemRedDot = 1177)] = "OnRemoveItemRedDot"),
      (e[(e.RunGm = 1178)] = "RunGm"),
      (e[(e.GmHandleActionFailed = 1179)] = "GmHandleActionFailed"),
      (e[(e.TestEffectAddDaRec = 1180)] = "TestEffectAddDaRec"),
      (e[(e.TestEffectAddEffectRec = 1181)] = "TestEffectAddEffectRec"),
      (e[(e.TestManuallyGarbageCollection = 1182)] =
        "TestManuallyGarbageCollection"),
      (e[(e.GmEntityPerformanceTestFinish = 1183)] =
        "GmEntityPerformanceTestFinish"),
      (e[(e.GmOnlyShowMiniMap = 1184)] = "GmOnlyShowMiniMap"),
      (e[(e.GmOnlyShowJoyStick = 1185)] = "GmOnlyShowJoyStick"),
      (e[(e.RoguelikeCloseGainSelectView = 1186)] =
        "RoguelikeCloseGainSelectView"),
      (e[(e.RoguelikeDataUpdate = 1187)] = "RoguelikeDataUpdate"),
      (e[(e.RoguelikeChooseDataResult = 1188)] = "RoguelikeChooseDataResult"),
      (e[(e.RoguelikeChooseDataNotify = 1189)] = "RoguelikeChooseDataNotify"),
      (e[(e.RoguelikeInfoSelectedToken = 1190)] = "RoguelikeInfoSelectedToken"),
      (e[(e.RoguelikeRefreshGain = 1191)] = "RoguelikeRefreshGain"),
      (e[(e.RoguelikeSelectSkill = 1192)] = "RoguelikeSelectSkill"),
      (e[(e.RoguelikeTalentLevelUp = 1193)] = "RoguelikeTalentLevelUp"),
      (e[(e.RoguelikeCurrencyUpdate = 1194)] = "RoguelikeCurrencyUpdate"),
      (e[(e.RoguelikeSelectToken = 1195)] = "RoguelikeSelectToken"),
      (e[(e.RoguelikeSelectSeason = 1196)] = "RoguelikeSelectSeason"),
      (e[(e.RoguelikeGetTokenReward = 1197)] = "RoguelikeGetTokenReward"),
      (e[(e.RogueTermUnlock = 1198)] = "RogueTermUnlock"),
      (e[(e.OnMarkItemViewCreate = 1199)] = "OnMarkItemViewCreate"),
      (e[(e.OnMarkItemViewDestroy = 1200)] = "OnMarkItemViewDestroy"),
      (e[(e.OnMarkItemViewEnter = 1201)] = "OnMarkItemViewEnter"),
      (e[(e.OnMarkItemViewExit = 1202)] = "OnMarkItemViewExit"),
      (e[(e.LogCustomMarkInfo = 1203)] = "LogCustomMarkInfo"),
      (e[(e.OnOpenSystemFeed = 1204)] = "OnOpenSystemFeed"),
      (e[(e.OnCloseSystemFeed = 1205)] = "OnCloseSystemFeed"),
      (e[(e.OnDeliveryProps = 1206)] = "OnDeliveryProps"),
      (e[(e.OnWorldMapTrackMarkItem = 1207)] = "OnWorldMapTrackMarkItem"),
      (e[(e.OnSundialRingChangeShine = 1208)] = "OnSundialRingChangeShine"),
      (e[(e.OnSundialRingSwitch = 1209)] = "OnSundialRingSwitch"),
      (e[(e.OnNeedUpdateSundialTips = 1210)] = "OnNeedUpdateSundialTips"),
      (e[(e.OnSignalDeviceLinkingCheck = 1211)] = "OnSignalDeviceLinkingCheck"),
      (e[(e.OnSignalDeviceReset = 1212)] = "OnSignalDeviceReset"),
      (e[(e.OnSignalDeviceLinking = 1213)] = "OnSignalDeviceLinking"),
      (e[(e.OnSignalDeviceFinish = 1214)] = "OnSignalDeviceFinish"),
      (e[(e.OnOverlapSceneItemExploreInteractRange = 1215)] =
        "OnOverlapSceneItemExploreInteractRange"),
      (e[(e.OnUseMapExploreToolSuccess = 1216)] = "OnUseMapExploreToolSuccess"),
      (e[(e.OnMapExploreToolPlaceNumUpdated = 1217)] =
        "OnMapExploreToolPlaceNumUpdated"),
      (e[(e.DoLeaveLevel = 1218)] = "DoLeaveLevel"),
      (e[(e.ClearSceneBegin = 1219)] = "ClearSceneBegin"),
      (e[(e.OnExploreProgressResponse = 1220)] = "OnExploreProgressResponse"),
      (e[(e.OnExploreScoreRewardResponse = 1221)] =
        "OnExploreScoreRewardResponse"),
      (e[(e.OnCountryExploreScoreInfoResponse = 1222)] =
        "OnCountryExploreScoreInfoResponse"),
      (e[(e.OnExploreLevelNotify = 1223)] = "OnExploreLevelNotify"),
      (e[(e.OnSignalCatchSuccess = 1224)] = "OnSignalCatchSuccess"),
      (e[(e.OnSignalCatchFailed = 1225)] = "OnSignalCatchFailed"),
      (e[(e.OnSignalCatchStart = 1226)] = "OnSignalCatchStart"),
      (e[(e.OnSignalCatchContinue = 1227)] = "OnSignalCatchContinue"),
      (e[(e.OnSignalCatchStartAgain = 1228)] = "OnSignalCatchStartAgain"),
      (e[(e.RefreshMonthCardRedDot = 1229)] = "RefreshMonthCardRedDot"),
      (e[(e.OnSetJoystickMode = 1230)] = "OnSetJoystickMode"),
      (e[(e.OnOverlapEncloseSpace = 1231)] = "OnOverlapEncloseSpace"),
      (e[(e.OnEncloseSpaceTypeChange = 1232)] = "OnEncloseSpaceTypeChange"),
      (e[(e.OnSubLevelAdded = 1233)] = "OnSubLevelAdded"),
      (e[(e.OnAndroidConfigurationChange = 1234)] =
        "OnAndroidConfigurationChange"),
      (e[(e.OnChatPlayerInfoChanged = 1235)] = "OnChatPlayerInfoChanged"),
      (e[(e.OnPlotTransitionRemoveCallback = 1236)] =
        "OnPlotTransitionRemoveCallback"),
      (e[(e.OnEnterOrExitExecutionRange = 1237)] =
        "OnEnterOrExitExecutionRange"),
      (e[(e.OnExecutionOptionChange = 1238)] = "OnExecutionOptionChange"),
      (e[(e.OnInteractActionEnd = 1239)] = "OnInteractActionEnd"),
      (e[(e.OnLevelFuncFlagSet = 1240)] = "OnLevelFuncFlagSet"),
      (e[(e.OnLevelFuncFlagChanged = 1241)] = "OnLevelFuncFlagChanged"),
      (e[(e.OnRefreshRewardView = 1242)] = "OnRefreshRewardView"),
      (e[(e.OnRefreshSpecialItemAllowReqUse = 1243)] =
        "OnRefreshSpecialItemAllowReqUse"),
      (e[(e.OnQueryProductInfo = 1244)] = "OnQueryProductInfo"),
      (e[(e.OnSdkFocusStateChange = 1245)] = "OnSdkFocusStateChange"),
      (e[(e.ReconnectClearData = 1246)] = "ReconnectClearData"),
      (e[(e.OnPreEndPIE = 1247)] = "OnPreEndPIE"),
      (e[(e.NoticeJourneyReceive = 1248)] = "NoticeJourneyReceive"),
      (e[(e.OnEntityInOutRangeLocal = 1249)] = "OnEntityInOutRangeLocal"),
      (e[(e.OnMyPlayerInOutRangeLocal = 1250)] = "OnMyPlayerInOutRangeLocal"),
      (e[(e.OnActorInOutRangeLocal = 1251)] = "OnActorInOutRangeLocal"),
      (e[(e.OnEntityInOutRangeOnline = 1252)] = "OnEntityInOutRangeOnline"),
      (e[(e.OnPlayerInOutRangeOnline = 1253)] = "OnPlayerInOutRangeOnline"),
      (e[(e.RoleTriggerInit = 1254)] = "RoleTriggerInit"),
      (e[(e.OnSetLoginServerId = 1255)] = "OnSetLoginServerId"),
      (e[(e.SetDecalShadowEnabled = 1256)] = "SetDecalShadowEnabled"),
      (e[(e.OnSelectTimePreset = 1257)] = "OnSelectTimePreset"),
      (e[(e.OnActionKeyChanged = 1258)] = "OnActionKeyChanged"),
      (e[(e.OnAxisKeyChanged = 1259)] = "OnAxisKeyChanged"),
      (e[(e.BeamCastStart = 1260)] = "BeamCastStart"),
      (e[(e.BeamCastStop = 1261)] = "BeamCastStop"),
      (e[(e.OnResetPhotographCamera = 1262)] = "OnResetPhotographCamera"),
      (e[(e.OnSpecialItemNotAllow = 1263)] = "OnSpecialItemNotAllow"),
      (e[(e.OnMarkItemShowStateChange = 1264)] = "OnMarkItemShowStateChange"),
      (e[(e.OnAbsoluteTimeStop = 1265)] = "OnAbsoluteTimeStop"),
      (e[(e.OnFightTestEnd = 1266)] = "OnFightTestEnd"),
      (e[(e.OnManipulateShowLandTips = 1267)] = "OnManipulateShowLandTips"),
      (e[(e.BeforeUiModelLoadStart = 1268)] = "BeforeUiModelLoadStart"),
      (e[(e.OnUiModelRoleConfigIdChange = 1269)] =
        "OnUiModelRoleConfigIdChange"),
      (e[(e.OnUiModelRoleDataIdChange = 1270)] = "OnUiModelRoleDataIdChange"),
      (e[(e.OnUiModelLoadComplete = 1271)] = "OnUiModelLoadComplete"),
      (e[(e.OnUiModelVisibleChange = 1272)] = "OnUiModelVisibleChange"),
      (e[(e.OnUiModelSetDitherEffect = 1273)] = "OnUiModelSetDitherEffect"),
      (e[(e.WorldMapSubMapChanged = 1274)] = "WorldMapSubMapChanged"),
      (e[(e.WorldMapSelectMultiMap = 1275)] = "WorldMapSelectMultiMap"),
      (e[(e.RoguelikePopularEntriesChange = 1276)] =
        "RoguelikePopularEntriesChange"),
      (e[(e.OnSceneItemMoveEventBroken = 1277)] = "OnSceneItemMoveEventBroken"),
      (e[(e.OnFragmentMemoryDataUpdate = 1278)] = "OnFragmentMemoryDataUpdate"),
      (e[(e.OnFragmentMemoryCollectUpdate = 1279)] =
        "OnFragmentMemoryCollectUpdate"),
      (e[(e.OnFragmentTopicSelect = 1280)] = "OnFragmentTopicSelect"),
      (e[(e.OnFragmentTopicClick = 1281)] = "OnFragmentTopicClick"),
      (e[(e.FragmentRewardRedDot = 1282)] = "FragmentRewardRedDot"),
      (e[(e.FragmentRewardTopicRedDot = 1283)] = "FragmentRewardTopicRedDot"),
      (e[(e.FragmentRewardEntranceRedDot = 1284)] =
        "FragmentRewardEntranceRedDot"),
      (e[(e.OnChangeBossRushBuff = 1285)] = "OnChangeBossRushBuff"),
      (e[(e.RequestChangeBossRushView = 1286)] = "RequestChangeBossRushView"),
      (e[(e.BossRushDataUpdate = 1287)] = "BossRushDataUpdate"),
      (e[(e.BossRefreshBossRushRewardRedDot = 1288)] =
        "BossRefreshBossRushRewardRedDot"),
      (e[(e.TowerDefenseOnOpenPhantomView = 1289)] =
        "TowerDefenseOnOpenPhantomView"),
      (e[(e.TowerDefenseOnClickOnePhantom = 1290)] =
        "TowerDefenseOnClickOnePhantom"),
      (e[(e.TowerDefenseSelfPhantomConfirm = 1291)] =
        "TowerDefenseSelfPhantomConfirm"),
      (e[(e.TowerDefensePhantomChanged = 1292)] = "TowerDefensePhantomChanged"),
      (e[(e.TowerDefenseBeforeConfirmQuickRoleSelect = 1293)] =
        "TowerDefenseBeforeConfirmQuickRoleSelect"),
      (e[(e.TowerDefenseOnWaveChanged = 1294)] = "TowerDefenseOnWaveChanged"),
      (e[(e.TowerDefenseOnActivityInfoUpdateNotify = 1295)] =
        "TowerDefenseOnActivityInfoUpdateNotify"),
      (e[(e.TowerDefenseOnInstanceInfoUpdateNotify = 1296)] =
        "TowerDefenseOnInstanceInfoUpdateNotify"),
      (e[(e.TowerDefenseOnPhantomInfoUpdateNotify = 1297)] =
        "TowerDefenseOnPhantomInfoUpdateNotify"),
      (e[(e.TowerDefenseShowInBattleView = 1298)] =
        "TowerDefenseShowInBattleView"),
      (e[(e.TowerDefenseOnShowPhantomInFormation = 1299)] =
        "TowerDefenseOnShowPhantomInFormation"),
      (e[(e.TowerDefenseOnTowerDefenseBattleEndNotify = 1300)] =
        "TowerDefenseOnTowerDefenseBattleEndNotify"),
      (e[(e.OnBeforeDestroyInstanceDungeonEntranceView = 1301)] =
        "OnBeforeDestroyInstanceDungeonEntranceView"),
      (e[(e.OnClickEnterInstanceSingle = 1302)] = "OnClickEnterInstanceSingle"),
      (e[(e.MowingBasicBuffGridItemClick = 1303)] =
        "MowingBasicBuffGridItemClick"),
      (e[(e.MowingSuperBuffGridItemClick = 1304)] =
        "MowingSuperBuffGridItemClick"),
      (e[(e.MowingRiskInBattleViewSetActive = 1305)] =
        "MowingRiskInBattleViewSetActive"),
      (e[(e.MowingRiskInBattleRootUpdate = 1306)] =
        "MowingRiskInBattleRootUpdate"),
      (e[(e.MowingRiskOnInstanceClearRewardResponse = 1307)] =
        "MowingRiskOnInstanceClearRewardResponse"),
      (e[(e.MowingRiskOnScoreRewardResponse = 1308)] =
        "MowingRiskOnScoreRewardResponse"),
      (e[(e.MowingRiskOnBuffCountRewardResponse = 1309)] =
        "MowingRiskOnBuffCountRewardResponse"),
      (e[(e.MowingRiskOnRefreshRewardRedDot = 1310)] =
        "MowingRiskOnRefreshRewardRedDot"),
      (e[(e.MowingRiskOnRefreshBuffAllRedDot = 1311)] =
        "MowingRiskOnRefreshBuffAllRedDot"),
      (e[(e.MowingRiskOnBuffTipsAfterDestroy = 1312)] =
        "MowingRiskOnBuffTipsAfterDestroy"),
      (e[(e.MowingRiskOnNeedPlayLevelUpSequence = 1313)] =
        "MowingRiskOnNeedPlayLevelUpSequence"),
      (e[(e.OnSetGameModeDataDone = 1314)] = "OnSetGameModeDataDone"),
      (e[(e.OnBossRushBuffViewOpened = 1315)] = "OnBossRushBuffViewOpened"),
      (e[(e.OnTutorialTipExistChanged = 1316)] = "OnTutorialTipExistChanged"),
      (e[(e.OnTutorialUpdate = 1317)] = "OnTutorialUpdate"),
      (e[(e.LevelLoadingLockTimeDilation = 1318)] =
        "LevelLoadingLockTimeDilation"),
      (e[(e.LevelLoadingUnlockDilation = 1319)] = "LevelLoadingUnlockDilation"),
      (e[(e.BusinessInvestResult = 1320)] = "BusinessInvestResult"),
      (e[(e.SetDelegationResultData = 1321)] = "SetDelegationResultData"),
      (e[(e.PopularityChange = 1322)] = "PopularityChange"),
      (e[(e.OpenTipsTravelView = 1323)] = "OpenTipsTravelView"),
      (e[(e.OpenTipsShopView = 1324)] = "OpenTipsShopView"),
      (e[(e.UnlockMoonChasingData = 1325)] = "UnlockMoonChasingData"),
      (e[(e.RefreshCorniceMeetingRedDot = 1326)] =
        "RefreshCorniceMeetingRedDot"),
      (e[(e.OnClickActivityCorniceMeetingTab = 1327)] =
        "OnClickActivityCorniceMeetingTab"),
      (e[(e.OnPlayerFollowerCreate = 1328)] = "OnPlayerFollowerCreate"),
      (e[(e.OnPlayerFollowerDestroy = 1329)] = "OnPlayerFollowerDestroy"),
      (e[(e.OnPlayerFollowerEnableChange = 1330)] =
        "OnPlayerFollowerEnableChange"),
      (e[(e.BuildAnimFinish = 1331)] = "BuildAnimFinish"),
      (e[(e.ConditionUnlockRole = 1332)] = "ConditionUnlockRole"),
      (e[(e.TakenRewardTargetData = 1333)] = "TakenRewardTargetData"),
      (e[(e.RefreshRewardTargetData = 1334)] = "RefreshRewardTargetData"),
      (e[(e.RefreshDelegate = 1335)] = "RefreshDelegate"),
      (e[(e.ElevatorMove = 1336)] = "ElevatorMove"),
      (e[(e.OnHighSpeedModeChanged = 1337)] = "OnHighSpeedModeChanged"),
      (e[(e.OnDropDownListVisibleChanged = 1338)] =
        "OnDropDownListVisibleChanged"),
      (e[(e.OnGlobalFootstepMaterialChange = 1339)] =
        "OnGlobalFootstepMaterialChange"),
      (e[(e.OnPortalRegister = 1340)] = "OnPortalRegister"),
      (e[(e.OnPortalUnRegister = 1341)] = "OnPortalUnRegister"),
      (e[(e.OnChangeModuleDebugLevel = 1342)] = "OnChangeModuleDebugLevel"),
      (e[(e.OnMarkActorInFighting = 1343)] = "OnMarkActorInFighting"),
      (e[(e.OnPunishMarkStateChanged = 1344)] = "OnPunishMarkStateChanged"),
      (e[(e.OnInputSettingResponse = 1345)] = "OnInputSettingResponse"),
      (e[(e.OnInputSettingUpdateNotify = 1346)] = "OnInputSettingUpdateNotify");
  })((EEventName = exports.EEventName || (exports.EEventName = {})));
//# sourceMappingURL=EventDefine.js.map
