"use strict";
Object.defineProperty(exports, "__esModule", { value: !0 }),
  (exports.mapComponentRegisterInfo = exports.MAP_VERSION = void 0);
const WorldMapStreamingComponent_1 = require("../../WorldMap/ViewComponent/SteamingLoad/WorldMapStreamingComponent"),
  WorldMapAlterMapComponent_1 = require("../../WorldMap/ViewComponent/WorldMapAlterMapComponent"),
  WorldMapInteractComponent_1 = require("../../WorldMap/ViewComponent/WorldMapInteractComponent"),
  WorldMapMoveComponent_1 = require("../../WorldMap/ViewComponent/WorldMapMoveComponent"),
  WorldMapMultiFloorComponent_1 = require("../../WorldMap/ViewComponent/WorldMapMultiFloorComponent"),
  WorldMapPlayerComponent_1 = require("../../WorldMap/ViewComponent/WorldMapPlayerComponent"),
  WorldMapQuickNavigateComponent_1 = require("../../WorldMap/ViewComponent/WorldMapQuickNavigateComponent"),
  WorldMapScaleComponent_1 = require("../../WorldMap/ViewComponent/WorldMapScaleComponent"),
  WorldMapSecondaryUiComponent_1 = require("../../WorldMap/ViewComponent/WorldMapSecondaryUiComponent"),
  MarkCommonGamePlayStateComponent_1 = require("../Mark/Component/MarkCommonGamePlayStateComponent"),
  MarkConfigComponent_1 = require("../Mark/Component/MarkConfigComponent"),
  MarkEntityComponent_1 = require("../Mark/Component/MarkEntityComponent"),
  MarkFishingPointComponent_1 = require("../Mark/Component/MarkFishingPointComponent"),
  MarkGamePlayComponent_1 = require("../Mark/Component/MarkGamePlayComponent"),
  MarkGamePlayStateComponent_1 = require("../Mark/Component/MarkGamePlayStateComponent"),
  MarkMultiFloorComponent_1 = require("../Mark/Component/MarkMultiFloorComponent"),
  MarkResourceComponent_1 = require("../Mark/Component/MarkResourceComponent"),
  MarkViewLifeCircleComponent_1 = require("../Mark/Component/MarkViewLifeCircleComponent"),
  MapLoggerComponent_1 = require("./MapLoggerComponent");
(exports.MAP_VERSION = "1"),
  (exports.mapComponentRegisterInfo = new Map([
    [0, MapLoggerComponent_1.MapLoggerComponent],
    [1, WorldMapSecondaryUiComponent_1.WorldMapSecondaryUiComponent],
    [2, WorldMapInteractComponent_1.WorldMapInteractComponent],
    [3, WorldMapMoveComponent_1.WorldMapMoveComponent],
    [4, WorldMapScaleComponent_1.WorldMapScaleComponent],
    [5, WorldMapPlayerComponent_1.WorldMapPlayerComponent],
    [6, WorldMapMultiFloorComponent_1.WorldMapMultiFloorComponent],
    [7, WorldMapQuickNavigateComponent_1.WorldMapQuickNavigateComponent],
    [8, WorldMapStreamingComponent_1.WorldMapStreamingComponent],
    [9, WorldMapAlterMapComponent_1.WorldMapAlterMapComponent],
    [10, MarkGamePlayComponent_1.MarkGamePlayComponent],
    [11, MarkResourceComponent_1.MarkResourceComponent],
    [12, MarkViewLifeCircleComponent_1.MarkViewLifeCircleComponent],
    [13, MarkGamePlayStateComponent_1.MarkGamePlayStateComponent],
    [14, MarkCommonGamePlayStateComponent_1.MarkCommonGamePlayStateComponent],
    [15, MarkConfigComponent_1.MarkConfigComponent],
    [16, MarkFishingPointComponent_1.MarkFishingPointComponent],
    [17, MarkMultiFloorComponent_1.MarkMultiFloorComponent],
    [18, MarkEntityComponent_1.MarkEntityComponent],
  ]));
//# sourceMappingURL=MapBaseDefine.js.map
