"use strict";
Object.defineProperty(exports, "__esModule", { value: !0 }),
  (exports.qteInputActions = void 0),
  (exports.qteInputActions = [
    "无",
    "跳跃",
    "攀爬",
    "走跑切换",
    "攻击",
    "闪避",
    "技能1",
    "幻象1",
    "大招",
    "幻象2",
    "切换角色1",
    "切换角色2",
    "切换角色3",
    "锁定目标",
    "瞄准",
    "通用交互",
    "向前移动",
    "向后移动",
    "向左移动",
    "向右移动",
  ]);
//# sourceMappingURL=QteDefine.js.map
